### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by Kazamiaep** [agalwood/Motrix#1000]
**Describe the bug**
Downloads absolutely nothing.

**Expected behavior**
Added a new torrent file and clicked confirm

**Screenshots**
![01](https://user-images.githubusercontent.com/87103995/124848717-5bbd6180-dfd8-11eb-9aa9-27293da7d07b.png)

**Environment:**
 - OS & Version: [Windows]
 - Version: [Windows 10]
 - Motrix Version: [e.g. v1.6.11]
 - Installation package type: [Motrix-1.6.11-win.zip]

**Comment by lordcyb3r** [comment]
not sure if this will fix it but here are a few possible solutions:
1. portforward the listening port under advanced settings
2. set a proxy under advanced settings
3. use a vpn (maybe one that supports port forwarding)

might be a restrictive network but also might be a motrix issue. who knows

**Comment by Kazamiaep** [comment]
It works with VPN, but why do I need it? If my other torrent client works without vpn. Disappointed... not in the program, but in the country where I live.
