### ISSUE TITLE
1.6.11依旧不是Apple Silicon M1 特性

### ISSUE THREAD

**Issue by Silentely** [agalwood/Motrix#1004]
查询依旧还是intel

![07136CTs0b](http://tc.aeyo.xyz/uPic/07136CTs0b.png)

**Comment by Silentely** [comment]
![0713wWgBsh](http://tc.aeyo.xyz/uPic/0713wWgBsh.png)

**Comment by shatyuka** [comment]
Invalid issue.
https://github.com/agalwood/Motrix/releases/download/v1.6.11/Motrix-1.6.11-arm64.dmg
