### ISSUE TITLE
Error updating Motrix

### ISSUE THREAD

**Issue by jotana240** [agalwood/Motrix#1006]
**Before feedback**
Before you feedback, please search for the issues to see if there are similar problems that can solve your problem.

**Please delete the above and the contents of this line, then fill in the feedback form in the following format, Thanks.**

**Describe the bug**
at the moment of giving it update I get an error and it does not verify or update me

**To Reproduce**
1. Go to 'in the Advanced module, when you click on the "Check now" button'
2. Click on 'on the update button'

**Expected behavior**
I was hoping that it would verify if it already had the last update of the application and if the example did not have the last version, I would like the button to verify the version to work

**Screenshots**
![Captura de pantalla de 2021-07-13 23-45-16](https://user-images.githubusercontent.com/36685880/125557858-df1ff7d7-0c7b-4ccc-b08c-5c6a0b881d98.png)
![Captura de pantalla de 2021-07-13 23-29-06](https://user-images.githubusercontent.com/36685880/125557268-9e6c649a-db96-406f-bf95-3b7a7ffe91d6.png)
![Captura de pantalla de 2021-07-13 23-34-27](https://user-images.githubusercontent.com/36685880/125557275-9e79ee33-8bcb-4399-89c4-a24797f91eb9.png)

**Environment (please complete the following information):**
 - OS Linux Ubuntu LTS 64 bits
 - Version: [Ubuntu 20.04.2 LTS]
 - Motrix Version: [Version 1.6.11]
 - Installation package type: [Motrix_1.6.11_amd64.deb]

**Additional context**
I know that I already have the latest version but then my question is why it does not verify the update?.

It should be noted that when I run it through the terminal with "Motrix-1.6.11.AppImage", the update verification works.

**Comment by Fish-Who** [comment]
It seems that installation on ubuntu 21.04 through deb(1.6.11 amd64) would result in lack of this file as well

**Comment by agalwood** [comment]
Only AppImage format supports AutoUpdate. Since it is difficult to judge the Linux distribution version to hide the automatically updated menu item, it is left.

https://www.electron.build/auto-update.html
