### ISSUE TITLE
Minimized Window Problem.

### ISSUE THREAD

**Issue by jytan9898u** [agalwood/Motrix#1011]
**Describe the bug**
This problem only occurs when Motrix window is minimized.
If I execute right-click action on the notification icon (for example New BT Task), it does change its state to my desire but won't bring the window back to the front. 

**To Reproduce**
1. Minimized Motrix window.
2. Right-click on Motrix notification icon.
3. Select the action.
4. Motrix window did change state on behind but not bring back to front.

**Expected behavior**
When execute right-click action on the notification icon, it should bring the window back to the front and change its state as desire.

**Environment**
 - OS & Version: Windows 10
 - Version: 21H1 (OS Build 19043.1110)
 - Motrix Version: 1.6.11
 - Installation package type: EXE

**Comment by shatyuka** [comment]
Bug confirmed.
