### ISSUE TITLE
菜单里关于“隐藏窗口”的几个按钮都不管用

### ISSUE THREAD

**Issue by kerhbal** [agalwood/Motrix#102]
**Bug 描述**
菜单里关于“隐藏窗口”的几个按钮都不管用，因为我不知道具体成功效果所以在此猜测一下，是最小化到右下角？因为现在的最小化在任务栏还有图标。

**如何重现**
![pn-2019-02-27_20-27-40](https://user-images.githubusercontent.com/11629684/53534902-b3756500-3ace-11e9-945f-e31a510f2517.gif)

**预期的行为**
最小化到右下角？

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： Windows 10
 - Motrix 版本： v1.1.3

**Comment by agalwood** [comment]
看来这部分功能在 Windows 上无效呀，macOS 的逻辑是正常的

**Comment by kerhbal** [comment]
@agalwood 嗯不知道是不是只有我有这个问题...

**Comment by DonkeyTao** [comment]
win10下我也是 还有双标题栏 选了隐藏没变化

**Comment by agalwood** [comment]
@kerhbal 菜单项开发时用了 macOS 特有的 API 「hide, hideOthers」没注意到
https://electronjs.org/docs/api/menu-item#roles

@DonkeyTao 已知 bug，https://github.com/agalwood/Motrix/issues/54

**Comment by agalwood** [comment]
@DonkeyTao 已发布，请更新
https://github.com/agalwood/Motrix/releases/tag/v1.2.2
