### ISSUE TITLE
使用Motrix和迅雷下载磁力链接的区别是什么？为什么Motrix一点速度都没有而迅雷几乎是导入就满速？

### ISSUE THREAD

**Issue by AigeStudio** [agalwood/Motrix#1036]
**错误描述**
RT，先给个示例链接吧：
> magnet:?xt=urn:btih:669B2A1E8083BDBC9B909DD03B3E47AC7E159264&dn=syqy&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce

上述链接使用迅雷添加就可以满速（非会员，我觉得会不会员也没啥影响），但是用Motrix挂一天都不会有速度，是因为迅雷有做类似CDN之类的优化吗？下载资源的时候从它的CDN服务器下载？

**运行环境**
 - 操作系统类型：MacOS
 - 具体版本：10.15
 - Motrix 版本：1.6.11
 - 安装包类型：dmg

**Comment by xinghui233** [comment]
Motrix 是调用aria2下载的磁力链接 虽然motrix提供了自动更新tracker服务器列表来发现正在下载同一资源的用户
但对于磁力链接来说 寻找资源更多的是依靠与dht文件 

迅雷则有着自己的服务器来提供下载，保存资源，正在下载的用户
并且迅雷只会向使用迅雷下载的用户上传数据 
因此对于国内环境 迅雷确实有着更好的下载速度 冷门资源还是建议使用迅雷下载

**Comment by heapmotion** [comment]
Works for me. Have not succeeded in downloading even one magnet in years.
