### ISSUE TITLE
下载自动停止后无法继续下载

### ISSUE THREAD

**Issue by FhyTan** [agalwood/Motrix#104]
在下载大文件（我在下一个win10的iso镜像）下了大部分后进入已停止状态，无法继续下载，重启软件也没用

截图：
![image](https://user-images.githubusercontent.com/16273230/53555199-68199000-3b7c-11e9-9c1e-e5a2dff538dc.png)

download.session信息：
https://software-download.microsoft.com/sg/Win10_1809Oct_Chinese(Simplified)_x64.iso?t=b55a40b8-4230-49e5-b1aa-127c871b88cf&e=1551342666&h=040fc4890dce36a060dcc124b138b79f	
 gid=6c95b37d01ef244e
 dir=/Users/fhytan/Downloads
 split=16
 max-download-limit=0
 allow-overwrite=true
 continue=true
 auto-file-renaming=true
 max-connection-per-server=64
 min-split-size=1048576
 user-agent=Transmission/2.94

**运行环境**
 - 操作系统：macOS 10.14.3
 - Motrix 版本： v1.1.3
 - 安装包类型：dmg

**Comment by agalwood** [comment]
> https://software-download.microsoft.com/sg/Win10_1809Oct_Chinese(Simplified)_x64.iso?t=b55a40b8-4230-49e5-b1aa-127c871b88cf&e=1551342666&h=040fc4890dce36a060dcc124b138b79f

你的下载地址已经失效了，当然下不动了，你可以试下去微软那里重新生成出一个链接，然后替换到 `download.session` 里试试

**Comment by E-mouse** [comment]
你好，我使用VirusTotal（https://www.virustotal.com/en/）在线检测Windows版安装包，提示两个威胁：

Bkav | HW32.Packed.
-- | --

Trapmine | malicious.moderate.ml.score
-- | --

不知道这是什么情况，如果能抽时间解释一下最好不过了，提前谢谢你。

**Comment by agalwood** [comment]
@E-mouse 请确认是从官网或 GitHub 下载的安装包，其他途径下载的安装包可能被人加马之类的概不负责，
如果觉得信不过安装包，你可以自行下载源码编译

**Comment by FhyTan** [comment]
十分感谢，我没想过连接会失效所以也没点进去看一眼😂

**Comment by E-mouse** [comment]
> @E-mouse 请确认是从官网或 GitHub 下载的安装包，其他途径下载的安装包可能被人加马之类的概不负责，
> 如果觉得信不过安装包，你可以自行下载源码编译

感谢及时回复。我确认是从官网下载的。不会编译诶，暂时就先不尝试了吧，等哪天有缘再过来看看。
