### ISSUE TITLE
无法批量删除任务,有200多个错误任务.我卸载后重装任务列表还在,任务的文件请问在哪?

### ISSUE THREAD

**Issue by xysemies** [agalwood/Motrix#106]
无法批量删除任务,有200多个错误任务.我卸载后重装任务列表还在,
任务的文件请问在哪?

请问 可以手动挡清空吗?

**Comment by agalwood** [comment]
偏好设置-进阶设置，可以看到有一个 `download.session` 的地址，点击右边的文件夹按钮，去把它清空一下或者直接删掉
