### ISSUE TITLE
win10 更改默认下载地址无效

### ISSUE THREAD

**Issue by hktkzyx** [agalwood/Motrix#107]
win10 在系统设置里更改了默认下载地址，但是每次下载之后都不是自己更改之后的下载地址。修改的没用。
另外，win10 也不能隐藏到任务栏。
另外，能不能支持浏览器点击下载链接直接启动motrix下载

**Comment by agalwood** [comment]
1、老铁，能按照问题反馈模版提 issue 把问题描述清楚么？
https://github.com/agalwood/Motrix/issues/new?assignees=&labels=&template=bug_report_cn.md
2、3 两条其他 issue 都有说明，请自行搜索
