### ISSUE TITLE
通过命令行添加下载任务

### ISSUE THREAD

**Issue by gogogosco** [agalwood/Motrix#1089]
**请描述一下你的新功能请求是否与已知问题有关？**
目前没有合适的稳定下载SDK，希望可以支持通过cmd  exe路径 + 参数的形式进行创建任务。

**描述你想要的解决方案**
目前没有合适的稳定下载SDK，希望可以支持通过cmd  exe路径 + 参数的形式进行创建任务。

**描述你考虑过的替代方案**
无

**更多信息**
补充有关该新功能的其他信息。

**Comment by shatyuka** [comment]
搜索 aria2 RPC
