### ISSUE TITLE
挂代理设置全局模式的时候motrix界面不显示任务

### ISSUE THREAD

**Issue by nilday** [agalwood/Motrix#109]
**反馈之前**
反馈之前请搜索一下已有 issues 和 帮助文档，看是否有类似问题可以解决你的问题
https://github.com/agalwood/Motrix/issues
http://motrix.app/support

**请删除上面和本行的内容，然后按以下格式填写反馈信息，谢谢**

**Bug 描述**
mac系统
挂v2rayx作为代理翻墙，设置全局模式的时候motrix界面不显示任务，实际上任务应该添加成功的。

**如何重现**
重现步骤，如：
1. 代理设置成global mode
2. 添加下载任务，无论是yaaw添加还是手动添加
3. 下载、等待、和停止界面没有任何显示
4. Yet Another Aria2 Web Frontend正常显示下载内容
**预期的行为**
清楚简洁地描述您期望发生的事情。

**截图**
请添加屏幕截图以帮助解释您的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

**运行环境**
 - 操作系统类型： MAC
 - 具体版本： 
 - Motrix 版本： v1.1.3
 - 安装包类型：dmg

**更多信息**
添加有关此问题的任何其他上下文信息。

**Comment by agalwood** [comment]
Motrix 与内置的 aria2 通信走的 WebSocket，全局代理会无法建立连接

你打开 macOS 的系统偏好设置—网络设置—WiFi—代理—忽略这些主机与域的代理设置：
在输入框里加上
`localhost`
Motrix 就不会受全局代理影响了
