### ISSUE TITLE
请问有TG群或者直面沟通开发者的渠道么？

### ISSUE THREAD

**Issue by zealson** [agalwood/Motrix#11]
我是今天无意才知道Mac上还有这么优秀且全能的下载工具，真的好自责，用了Mac这么久，今天才发现，而且按照教程一步步操作，功能和视觉体验都非常棒，之前一直用的Proxyee，每次启动都很慢（貌似是Java编译的吧），现在发现Motrix感觉太幸福了，希望开发者能建立一个高效沟通渠道（推荐TG群组），能够让这个项目有更好的持续性：），再次感谢🙏

**Comment by agalwood** [comment]
有建了个Motrix 使用交流的QQ群，可是怕老司机们在里面发车（TG似乎更那啥），所以没有放到 README 上🤔

**Comment by zealson** [comment]
> 有建了个Motrix 使用交流的QQ群，可是怕老司机们在里面发车（TG似乎更那啥），所以没有放到 README 上🤔

其实TG群组还是蛮自由的啊很多macOS app独立项目都有在TG开群组,QQ群不好监管,希望开发者大大搞个TG群组吧🤗
