### ISSUE TITLE
对于zh-TW版本的一些说明

### ISSUE THREAD

**Issue by agalwood** [agalwood/Motrix#110]
无意引发某些问题，统一去除了语言下拉选框里的emoji ：I
将“正體中文”修改为“繁體中文” ，「参考了微软官网（tw），苹果系统的语言和地区」。
试用了几个知名的下载软件（有繁體中文的）如 BitComet、EagleGet，对于 “task” 通常翻译为 “任務”，所以一并进行了修改替换。望周知 @Yukaii 
https://github.com/agalwood/Motrix/commit/e7ed58e39489ed6c23683c4797fe0e3041755e0e

**Comment by Yukaii** [comment]
OK 👍
