### ISSUE TITLE
这个下载软件的目录下怎么还有一堆d3d、vulkcan、ffmpeg的东西？

### ISSUE THREAD

**Issue by m666m** [agalwood/Motrix#1110]
前端不是用的js的吗？ 有啥功能需要弄得跟3d游戏似的，是不是方向跑偏了？挺好用的软件，千万别跟迅雷学阿

**Comment by m666m** [comment]
Motrix目录已经200MB了，aria2套壳不可能这么大阿，作者能否做个说明？

**Comment by troyeguo** [comment]
Electron应用都是这么大，这些dll库也都是Electron应用本身就有的

**Comment by m666m** [comment]
> Electron应用都是这么大，这些dll库也都是Electron应用本身就有的

多谢指教
