### ISSUE TITLE
关于arm64平台下编译的问题，主要是aria2c无法调用

### ISSUE THREAD

**Issue by kero990** [agalwood/Motrix#1143]
motrix没有arm64架构的linux运行包，然而当我自行编译的时候，motrix可以正确的编译为arm64可执行文件，但其中的aria2c并不是，它依然是x64的。
而且，我将arm64能用的aria2c可执行文件替换掉内置的x64版本，仍然无法运行，添加下载任务会报failed to fetch。进程里没有aria2c，端口也并未开放6800或16800。可以确认是无法调用aria
而且自带的aria2c有10M大小，我替换过来的aria只有区区10kb
请问我该怎么修正这个问题，直接替换aria2c到底是否可行？10M大小的ariac到底包含了些什么，我去哪找一个arm64能用的，motrix也能用的aria2c呢？

**Comment by shatyuka** [comment]
https://github.com/agalwood/aria2

**Comment by kero990** [comment]
> https://github.com/agalwood/aria2

我当然找得到aria2的项目地址，我的系统里也安装有aria2，但是我把我的aria2复制过来是不能调用的，而且两者文件大小差距巨大。我不认为我自行编译一个aria2，就会比系统安装的那个更有效，我想搞清楚为什么你的aria2有10m而我的只有10k，而且我复制过去的10k的aria2在终端运行没有任何问题，他又为什么不能被motrix调用呢

**Comment by Gruood** [comment]
是的, 我也有同样的疑惑, 请求构建文档. There is any doc about build?

**Comment by kero990** [comment]
上面的回复我没有仔细看，以至于没发现那个aria2不是官方而是Motrix作者fork的，使用这个fork的aria静态编译即可正常调用内核。Motrix本身的编译没啥，就是正常的electron，甚至直接替换resources文件夹就能用。
我编译了基于arm64的包，有需要的自用。
https://kero990.lanzoum.com/iHUZN0ot60kf
