### ISSUE TITLE
可不可以把release放到gitee上

### ISSUE THREAD

**Issue by wszqkzqk** [agalwood/Motrix#115]
如题，github在国内速度太慢了

**Comment by agalwood** [comment]
gitee 上建了个同名项目，强制同步 GitHub 了几次都没成功。。。

**Comment by agalwood** [comment]
官网下载地址不会考虑用 gitee 的 release，因为要登录 gitee 之后才能下载
https://github.com/agalwood/Motrix/issues/89#issuecomment-469159847
