### ISSUE TITLE
Crash on launching appimage (v 1.6.11)

### ISSUE THREAD

**Issue by RafaelLinux** [agalwood/Motrix#1158]
**Describe the bug**
When I launch AppImage in Linux (from console) I got this output:
`/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
11:59:00.465 › [Motrix] Logger init
11:59:00.468 › [Motrix] Logger init
11:59:00.722 › [Motrix] openedAtLogin: false
11:59:00.856 › [Motrix] UPnPManager port mapping:  21301
11:59:00.857 › [Motrix] UPnPManager port mapping:  26701
11:59:00.857 › [Motrix] Engie pid path: /home/usuario/.config/Motrix/engine.pid
extraConfig===> {
  'all-proxy': 'file:///home/usuario/proxy_PAC_configuracion.pac',
  'allow-overwrite': true,
  'auto-file-renaming': true,
  'bt-exclude-tracker': '',
  'bt-load-saved-metadata': true,
  'bt-save-metadata': true,
  'bt-tracker': '',
  continue: true,
  'dht-file-path': '/home/usuario/.config/Motrix/dht.dat',
  'dht-file-path6': '/home/usuario/.config/Motrix/dht6.dat',
  'dht-listen-port': 26701,
  dir: '/home/usuario/Descargas',
  'listen-port': 21301,
  'max-concurrent-downloads': 5,
  'max-connection-per-server': 16,
  'max-download-limit': 0,
  'max-overall-download-limit': 0,
  'max-overall-upload-limit': 0,
  'min-split-size': '1M',
  'no-proxy': '',
  pause: true,
  'rpc-listen-port': 16800,
  'rpc-secret': '',
  'seed-ratio': 1,
  'seed-time': 60,
  split: 16,
  'user-agent': 'Transmission/2.94'
}
11:59:00.864 › [Motrix] main engine client connect { host: '127.0.0.1', port: 16800, secret: '' }
11:59:03.910 › [Motrix] auto sync tracker checkIsNeedRun: true
11:59:04.010 › [Motrix] UPnPManager map 21301 failed, error:  Error: UPnP port mapping failed
    at /tmp/.mount_MotrixKzo9KN/resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
    at /tmp/.mount_MotrixKzo9KN/resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
    at /tmp/.mount_MotrixKzo9KN/resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:24:23
    at Timeout._onTimeout (/tmp/.mount_MotrixKzo9KN/resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:193:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
11:59:04.011 › [Motrix] UPnPManager map 26701 failed, error:  Error: UPnP port mapping failed
    at /tmp/.mount_MotrixKzo9KN/resources/app.asar/node_modules/@motrix/nat-api/index.js:226:25
    at /tmp/.mount_MotrixKzo9KN/resources/app.asar/node_modules/@motrix/nat-api/index.js:327:16
    at /tmp/.mount_MotrixKzo9KN/resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:24:23
    at Timeout._onTimeout (/tmp/.mount_MotrixKzo9KN/resources/app.asar/node_modules/@motrix/nat-api/lib/upnp/index.js:193:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[16716:0215/115904.246633:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.`

**To Reproduce**
1. Click on Motrix appimage file (nothing happens)
2. Launch Motrix appimage file from console (crash and output errors)

**Expected behavior**
To open Motrix window

**Environment (please complete the following information):**
- Operating System: openSUSE Tumbleweed 20220205
- KDE Plasma Version: 5.23.5
- KDE Frameworks Version: 5.90.0
- Qt Version: 5.15.2
- Kernel Version: 5.16.4-1-default (64-bit)
- Graphics Platform: X11
- Processors: 8 × Intel® Core™ i7-9700K CPU @ 3.60GHz
- Memory: 15.4 GiB of RAM
- Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2
- Motrix v 1.6.11

**Additional context**
Version 1.2 AppImage at least didn't crash, but didn't work (possible cause: Using proxy with user/password required)

**Comment by flwwater** [comment]
Electron-libs don't match your system,wait for motrix 1.6.12 out,it will be update electron-libs

**Comment by Flashwalker** [comment]
try with `--in-process-gpu` option

**Comment by RafaelLinux** [comment]
It works with that workaround. Anyway, I see no updates from 2021 to Motrix ... it seems abandonware :(
