### ISSUE TITLE
动态客户端伪装，切入迅雷庞大的私有种群

### ISSUE THREAD

**Issue by CalunVier** [agalwood/Motrix#1159]
我多次遇到其他BT下载器没有速度而迅雷可以满速下载的情况。这令我十分懊恼，迅雷用户有庞大的种群却不愿意分享，仅仅因为我拒绝使用迅雷那恶心的客户端下载BT（或许它还能被称为BT客户端的话）。

或许我们可以伪装Motrix让我们看起来像迅雷。这不是一股脑的伪装，我是说，Mortrix还是Mortrix，尤其是当我们遇到正常的BT客户端时。而当我遇到迅雷客户端（或者其他可选的客户端）时，将自己伪装为迅雷客户端以建立对等连接。此时Mortrix将成为迅雷种群和BT种群的桥梁

**Comment by lovecg1314** [comment]
《刑法》第二百八十五条第二款：违反国家规定，侵入前款规定以外的计算机信息系统或者采用其他技术手段，获取该计算机信息系统中存储、处理或者传输的数据，或者对该计算机信息系统实施非法控制，情节严重的，处三年以下有期徒刑或者拘役，并处或者单处罚金；情节特别严重的，处三年以上七年以下有期徒刑，并处罚金。

**Comment by CalunVier** [comment]
> 《刑法》第二百八十五条第二款：违反国家规定，侵入前款规定以外的计算机信息系统或者采用其他技术手段，获取该计算机信息系统中存储、处理或者传输的数据，或者对该计算机信息系统实施非法控制，情节严重的，处三年以下有期徒刑或者拘役，并处或者单处罚金；情节特别严重的，处三年以上七年以下有期徒刑，并处罚金。

这波算是紧跟时事了😅

**Comment by hjkl950217** [comment]
这个不算侵入阿。。只是加入分享网络

**Comment by CalunVier** [comment]
> 这个不算侵入阿。。只是加入分享网络。
> 
> 但是从技术上来说，下载内核是aria2，不是motrix做的，这个需求可能不好实现。BT/QT网络的话，最好能挂机下载。。慢慢下总能下到的

主要是会有死种

**Comment by hjkl950217** [comment]
> > 这个不算侵入阿。。只是加入分享网络。
> > 但是从技术上来说，下载内核是aria2，不是motrix做的，这个需求可能不好实现。BT/QT网络的话，最好能挂机下载。。慢慢下总能下到的
> 
> 主要是会有死种

恩 我也经常遇到死种的。。但确实整体BT/QT网络不想和迅雷为伍。。

**Comment by FinnRaze** [comment]
我曾经想过从迅雷那下载了再做种，然而迅雷一样没速度，笑死

**Comment by WnisWn** [comment]
> > 这个不算侵入阿。。只是加入分享网络。
> > 但是从技术上来说，下载内核是aria2，不是motrix做的，这个需求可能不好实现。BT/QT网络的话，最好能挂机下载。。慢慢下总能下到的
> 
> 主要是会有死种

你想多了，BT从服务器拿到资源名单，你的BT客户端根据这份名单去连接其它的人，迅雷同理，从迅雷服务器拿迅雷用户的名单，除非破解迅雷的协议黑进迅雷服务器里，不然单纯的伪装没人鸟你。

**Comment by CalunVier** [comment]
> > > 这个不算侵入阿。。只是加入分享网络。
> > > 但是从技术上来说，下载内核是aria2，不是motrix做的，这个需求可能不好实现。BT/QT网络的话，最好能挂机下载。。慢慢下总能下到的
> > 
> > 
> > 主要是会有死种
> 
> 你想多了，BT从服务器拿到资源名单，你的BT客户端根据这份名单去连接其它的人，迅雷同理，从迅雷服务器拿迅雷用户的名单，除非破解迅雷的协议黑进迅雷服务器里，不然单纯的伪装没人鸟你。

似乎不必要。普通BT下载器在日常也会遇到迅雷客户端的。只需要与迅雷客户端交换数据就可以了。
