### ISSUE TITLE
Application accessing the internet after being closed

### ISSUE THREAD

**Issue by alexwender1** [agalwood/Motrix#116]
**Describe the bug**
When closing Motrix, with downloads happening, the speed of internet browsing (in other applications - browser, for example) stays slow - as if Motrix was running.

I have identified that there are 2 processes running (even after the application is closed) with the name Motrix ... and a third process, under the name "aria2c" accessing the entire Internet band. By forcing the aria2c to close, everything returns to normal.

If you pause downloads before closing Motrix; the problem does not occur ... although the processes are running; with the application closed.

**Screenshots**
The aria2c process has binding to the Motrix, according to the capture.

![captura de tela_selecionar area_20190302141314](https://user-images.githubusercontent.com/45263160/53687918-f1b29480-3d19-11e9-8341-113f0765e46f.png)

**Environment (please complete the following information):**
 - OS & Version: Deepin 15.9.1
 - Motrix Version: 1.1.3
 - Installation package type: AppImage

**Comment by agalwood** [comment]
Under normal circumstances, the motrix will manage the aria2c process as a child process when it starts, and will automatically exit the aria2c process after exiting the software. Your situation estimates an abnormal situation and did not successfully exit the aria2c process.
