### ISSUE TITLE
请求和建议

### ISSUE THREAD

**Issue by WanYanYueCong** [agalwood/Motrix#118]
明明是中文软件，官网的默认语言为什么是英语。还有bug反馈和建议为什么不放到软件内或者官网，还要跳转到GitHUb（不利于普通用户）。移动版app打算什么时候开始做（收费也没有问题）。

**Comment by agalwood** [comment]
1. 对于软件打开是中文的，那是因为你的系统环境是中文的，Motrix 初次启动之后做了语言识别，官网没做罢了
https://github.com/agalwood/Motrix/blob/64cda63587219c1536085e4a69dea34867f99ef1/src/main/core/ConfigManager.js#L63
2. 作为一个开源软件，没有精力去维护一套 bug 和 feature request 跟踪管理系统。曾经语雀那边也开着评论，然而留言提问题乱七八糟，东一句西一句，根本无法追踪解决。
3. iOS版开发出来也基本不可能上得了架，Motrix 本来是要上 Mac App Store 的，审核被拒绝，苹果让我移除下载功能，所以才有了后来的 Motrix 开源。安卓版本身就支持下载文件，而且目前已经有多个 aria2 的管理工具。所以移动版，暂无计划吧
