### ISSUE TITLE
spawn ENAMETOOLONG 程序崩溃

### ISSUE THREAD

**Issue by Aloento** [agalwood/Motrix#1184]
**错误描述**
不知道如何发生，只是打开应用程序后弹出，随后程序崩溃

**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接（如链接不涉及到隐私和版权问题，请顺便提供）
3. 点击提交
4. 发现报错

**预期的行为**
清楚简洁地描述你期望发生的事情。

**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

![image](https://user-images.githubusercontent.com/11802769/159178056-dc456555-5064-4779-af03-92482f71e70f.png)

**运行环境**
 - 操作系统类型：Windows
 - 具体版本： Windows 11
 - Motrix 版本： 最新
 - 安装包类型：exe

**更多信息**
补充有关该问题的其他信息。

**Comment by Andy0evil** [comment]
删除C:\Users\用户名\AppData\Roaming里的motrix文件夹，再重开应该就好了

**Comment by JOYACEpoor** [comment]
> 
useful
