### ISSUE TITLE
closing after saving the parameters

### ISSUE THREAD

**Issue by franco27** [agalwood/Motrix#119]
**Describe the bug**
after a modification of the parameters and a click on the button, the application is immediately closed with deletion of the download list  

**To Reproduce**
1. completed tasks are present in the list
2. I modify a parameter to File/Preference
3. I click on:
![2019-03-03_16-37-14](https://user-images.githubusercontent.com/31793920/53697688-40bd0000-3dd4-11e9-9037-c6e3519235f6.png)

4. then close the download manager, forced to reopen the application and I see that the tasks have been deleted

**Environment (please complete the following information):**
 - OS & Version: Windows 10 x64 
 - Motrix Version: current version 1.1.3
 - Installation package type: Motrix-Setup-1.1.3.exe

**Comment by alexwender1** [comment]
It also occurs in the AppImage version (for Linux).

**Comment by agalwood** [comment]
Motrix's built-in download engine is aria2 (it cleans up the completed downloads regularly), and the aria2 process is restarted after saving the settings, so the record is gone. It would be a bit cumbersome if Motrix itself maintains a list of completed tasks.

**Comment by agalwood** [comment]
The new version of v1.4.x configuring preferences no longer needs to restart the app, you can update to the latest version.

https://github.com/agalwood/Motrix/releases
