### ISSUE TITLE
chrome baidu pan plugin bug

### ISSUE THREAD

**Issue by zack7wong** [agalwood/Motrix#12]
system:
- win10 x64
- chrome 71.0.3578.98

无法下载百度网盘资源，插件异常如：

> 无法访问 http://pan.baidu.com 和 https://pcs.baidu.com 的cookie

**Comment by agalwood** [comment]
请提供更详细的信息，如：截图，chrome 扩展错误日志

**Comment by zealson** [comment]
希望能够生成一个crx文件吧，加载扩展文件夹，总是会误删文件夹导致插件丢失，CRX会稳定点
