### ISSUE TITLE
language CN for update in US

### ISSUE THREAD

**Issue by franco27** [agalwood/Motrix#120]
1/ the English language is selected
2/ I click on "Check for updates ... "

3/ see the screenshot
![2019-03-03_17-04-15](https://user-images.githubusercontent.com/31793920/53697911-79f66f80-3dd6-11e9-9f04-65d652be5bc0.png)

Environment (please complete the following information):

OS & Version: Windows 10 x64
Motrix Version: current version 1.1.3
Installation package type: Motrix-Setup-1.1.3.exe

**Comment by agalwood** [comment]
Thanks report
