### ISSUE TITLE
内置的 TrackersList CDN 地址 `cdn.jsdelivr.net` 已经被 DNS 污染，建议及时更换

### ISSUE THREAD

**Issue by XIU2** [agalwood/Motrix#1215]
**错误描述**
内置的 TrackersList CDN 地址 `cdn.jsdelivr.net` 已经被 DNS 污染
https://github.com/jsdelivr/jsdelivr/issues/18392

**如何重现**
在任意在线全国 Ping 的网站上测试一下就能确认这点。

**预期的行为**
更换其他可用的 Github Raw 镜像，例如 ` fastly.jsdelivr.net `（目前只有 `cdn.jsdelivr.net` 子域名被 DNS 污染）

**截图**
https://github.com/agalwood/Motrix/blob/4c5bba89ef7ed9175071767fd4f30fee890a8653/src/shared/constants.js#L40-L62

**运行环境**
 - 操作系统类型： [如 macOS, Windows, Linux]
 - 具体版本： [如 macOS 10.14.2, Windows 10, Ubuntu 18.04]
 - Motrix 版本： [如 v1.1.3, v1.1.0]
 - 安装包类型：[如 dmg, AppImage]

**更多信息**
补充有关该问题的其他信息。

**Comment by XIU2** [comment]
@yaotthaha 确实，几个小时前就发现了，虽然比较离奇，但建议再多观察几天。
而且，经历这几次事情，怕是很多人不会再将 `cdn.jsdelivr.net` 用于生产环境（项目）中了。。。

**Comment by XIU2** [comment]
好像没有再复发了，那我就先关了~

**Comment by yaotthaha** [comment]
其实可以添加多个CDN地址作为备用，谁也不知道未来又会发生什么

**Comment by XIU2** [comment]
@yaotthaha 刚刚发现又被 DNS 污染了。
