### ISSUE TITLE
下载过大文件卡死

### ISSUE THREAD

**Issue by Kimaru-bili** [agalwood/Motrix#1226]
**错误描述**
清楚简洁地描述错误，方便我们复现之后处理。
下载文件过大会卡死

**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接（如链接不涉及到隐私和版权问题，请顺便提供）
3. 点击提交
4. 开始下载 然后卡死

**预期的行为**
清楚简洁地描述你期望发生的事情。
正常下载

**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

![image](https://user-images.githubusercontent.com/40233772/169635445-147d17fc-7d2d-499b-b1be-fbbf0524181f.png)

**运行环境**
 - 操作系统类型： windows
 - 具体版本： windows11
 - Motrix 版本： 1.6.11
 - 安装包类型：exe

**更多信息**
补充有关该问题的其他信息。

**Comment by 7est** [comment]
因为Motrix用的是aria2，机制就是先给你硬盘里写入同样大小的文件，再慢慢填入数据，硬盘不够快就会发生卡死的情况，等待的时间随硬盘速度而定

**Comment by Kimaru-bili** [comment]
以前不会这样的 以前下6-7G的东西都不会卡死 现在下照样卡死 不理解 我的是NVME的固态应该不会出现不够快的情况吧
现在就是这样 卡在这里半天都不下载
![image](https://user-images.githubusercontent.com/40233772/170238823-e11b6f0f-6717-4b66-a08b-2fcea65ddc65.png)
还会爆这样的错误 
![image](https://user-images.githubusercontent.com/40233772/170238895-5d3974a6-9f83-4705-8f53-127503486bf5.png)

**Comment by Kimaru-bili** [comment]
有的时候卡了连正在下载的东西都删不掉 必须强制关闭下载器重启才能删除

**Comment by 7est** [comment]
> 以前不会这样的 以前下6-7G的东西都不会卡死 现在下照样卡死 不理解 我的是NVME的固态应该不会出现不够快的情况吧 现在就是这样 卡在这里半天都不下载 ![image](https://user-images.githubusercontent.com/40233772/170238823-e11b6f0f-6717-4b66-a08b-2fcea65ddc65.png) 还会爆这样的错误 ![image](https://user-images.githubusercontent.com/40233772/170238895-5d3974a6-9f83-4705-8f53-127503486bf5.png)

看看任务管理器硬盘是否占用100%，另外看样子Motrix已经不维护的，官网也挂了，所以会有检查升级失败的错误，关闭自动检查升级就好

**Comment by Kimaru-bili** [comment]
感谢 原来是检查更新出错了 我没仔细看以为是下载文件出错了
