### ISSUE TITLE
Windows不能跟随系统主题切换深色浅色模式

### ISSUE THREAD

**Issue by mendax1234** [agalwood/Motrix#1232]
**Before feedback**
Before you feedback, please search for the issues to see if there are similar problems that can solve your problem.

**Please delete the above and the contents of this line, then fill in the feedback form in the following format, Thanks.**

Windows10 21H2 Motrix1.6.11

**Describe the bug**

The question is the same as the title.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & Version: [e.g. macOS, Windows, Linux]
 - Version: [e.g. macOS 10.14.2, Windows 10, Ubuntu 18.04]
 - Motrix Version: [e.g. v1.1.3, v1.1.0]
 - Installation package type: [e.g. dmg, AppImage]

**Additional context**

**Comment by agalwood** [comment]
更新 Motrix 版本到 1.8.19+
