### ISSUE TITLE
Browser integration 

### ISSUE THREAD

**Issue by codefreak558** [agalwood/Motrix#1242]
#Basic idea
Like IDM(Internet Download Manger) I would like to see an integration between the browser and the download manager.
So when a download is requested by the browser it redirects the download over to Mortrix.

**Comment by codefreak558** [comment]
Ah that's great I didn't check the lab.

**Comment by Kritiqual** [comment]
Well, it does not work on firefox

**Comment by Katzenwerfer** [comment]
> Well, it does not work on firefox

I think there was one extension specifically listed for Firefox

**Comment by NebulaTechs** [comment]
的确是个好主意。

**Comment by shuvashish76** [comment]
The above mentioned one by @Katzenwerfer changed to [Motrix WebExtension](https://github.com/gautamkrishnar/motrix-webextension) that supports [FF](https://addons.mozilla.org/en-US/firefox/addon/motrixwebextension/)
