### ISSUE TITLE
[Feature] Add support for HTTP Authorization

### ISSUE THREAD

**Issue by RaymondSalim** [agalwood/Motrix#1262]
**Is your feature request related to a problem? Please describe.**
Motrix is unable to download files from some sites that requires authentication

**Describe the solution you'd like**
Adding a field  `Authorization` which will be added to the HTTP Header

**Describe alternatives you've considered**
- Using cookies is much harder and does not always work.

**Additional context**

**Comment by MMaksim1234** [comment]
На тепловизор зсу

**Comment by MMaksim1234** [comment]
4441114417342316

**Comment by AxoCode** [comment]
Or also support `Cookie` header? Site like google drive need it

**Comment by RaymondSalim** [comment]
Merged in #1263

**Comment by RaymondSalim** [comment]
Merged in #1263
