### ISSUE TITLE
WIN11下载问题

### ISSUE THREAD

**Issue by Wuoy** [agalwood/Motrix#1268]
进入网页，下载按钮左端有一个苹果logo，
向下箭头不可用，
无法选择其他版本
点击会下载一个dmg文件，而非安装程序

**Comment by jyeric** [comment]
https://dl.motrix.app/release/Motrix-Setup-1.6.11.exe

https://motrix.app/ 英文版界面正常 中文版好像确实不行

**Comment by agalwood** [comment]
官网下载页面调整了
https://motrix.app/download
