### ISSUE TITLE
默认下载路径修改后无效

### ISSUE THREAD

**Issue by hktkzyx** [agalwood/Motrix#128]
**错误描述**
自定义默认下载地址，再次下载时默认地址又变成了系统默认
**如何重现**
重现步骤，如：
1. 点击偏好设置
2. 修改默认下载路径
3. 点击保存并应用
4. 随便下载一个文件，再次查看偏好设置，默认下载路径又变成修改前的路径

**预期的行为**
路径设置后不变

**截图**

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： Windows 10
 - Motrix 版本： v1.1.3
 - 安装包类型：exe

**更多信息**

**Comment by agalwood** [comment]
同样运行环境下测试没复现，你是不是指下载du盘的资源没有按照 Motrix 偏好设置里的“默认下载路径”保存？那个下载路径是在浏览器扩展里设置的，优先级比 Motrix 偏好设置高。

**Comment by yiplee** [comment]
我也是 win10，设置更改之后点了保存并应用，下次启动之前改了的设置又复原变成默认的了，包括自动检查更新选项，下载路径等。版本是在官网上下载的最新的 1.3.7 版本。

**Comment by agalwood** [comment]
@yiplee 修复 v1.3.8 已经发布了，你升级一下
https://github.com/agalwood/Motrix/releases

不过，你俩的 bug 不是同一个问题引起的 : (
