### ISSUE TITLE
发现问题&建议

### ISSUE THREAD

**Issue by ghost** [agalwood/Motrix#1281]
便携版Motrix，就是下载区win.zip格式的，非绝对便携，发现C:\Users\User\AppData\Roaming\Motrix有大量文件，虽然总体积只有7Ｍ，但下一个版本可否写个动态指令，把Ｍotrix有关的appdata目录迁移到Motrix软件主体文件夹下，就是与locales，resources，swiftshader文件夹并列

**Comment by kaseeen** [comment]
同问 2024了还没解决
