### ISSUE TITLE
无法下载任务，程序内无限报错

### ISSUE THREAD

**Issue by Mtatacre** [agalwood/Motrix#129]
**错误描述**
无法下载任务，程序内无限报错

**如何重现**
在百度网盘下载文件，网页出现“下载成功”，但是打开Motrix却提示我下载失败。

**截图**
请添加屏幕截图以帮助解释您的问题：
![image](https://user-images.githubusercontent.com/48311357/53939622-9d7b2c00-40ee-11e9-944f-6f735a77b96f.png)
![image](https://user-images.githubusercontent.com/48311357/53939636-a966ee00-40ee-11e9-9df0-779ed89696ba.png)

打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图
![image](https://user-images.githubusercontent.com/48311357/53939716-d9ae8c80-40ee-11e9-9f39-c58c51efb26e.png)
![image](https://user-images.githubusercontent.com/48311357/53939722-dca97d00-40ee-11e9-9515-951e8baa9d2f.png)
![image](https://user-images.githubusercontent.com/48311357/53939724-df0bd700-40ee-11e9-9413-e113995097f8.png)
无报错

**运行环境**
 - 操作系统类型：Mac
 - 具体版本： macOS 10.14.2
 - Motrix 版本：  v1.33.1
 - 安装包类型：dmg

**Comment by agalwood** [comment]
被du封了吧，晾账号一段时间吧
https://www.yuque.com/moapp/help/extensions#evqwnu
