### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by LeoMartinDev** [agalwood/Motrix#130]
Have you considered developping a browser extension allowing in-browser downloads to open up in Motrix ? 
This would be a great feature !

**Comment by agalwood** [comment]
There is an extension in the Google Chrome Webstore that is now supported, but it is only available in Chinese. You can try it out with Google Translate.
https://chrome.google.com/webstore/detail/yaaw-for-chrome/dennnbdlpgjgbcjfgaohdahloollfgoc
https://www.yuque.com/moapp/help/extensions#22993f87
