### ISSUE TITLE
关闭按钮建议

### ISSUE THREAD

**Issue by guoqianc** [agalwood/Motrix#131]
1. 这两层按钮作用一样，建议合并；
![image](https://user-images.githubusercontent.com/45277775/54012016-8cdeba80-41af-11e9-821d-a5cc429646b8.png)
2. 建议在用户点击关闭按钮有提示；
3. 可以设置关闭按钮类似如下功能。
![image](https://user-images.githubusercontent.com/45277775/54012330-b2b88f00-41b0-11e9-9925-19ada524aec3.png)

**Comment by agalwood** [comment]
1. 是 bug，已修复待发布
2. 3. 会开发，最近比较忙，进度比较慢

**Comment by agalwood** [comment]
1、两层按钮的 bug 修复已发布，请更新
https://github.com/agalwood/Motrix/releases/tag/v1.2.2
2、3 目前是默认显示系统托盘图标，暂不支持设置
