### ISSUE TITLE
无法正常打开软件，报错spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by hyb-oyqq** [agalwood/Motrix#1312]
**错误描述**
无法正常打开软件，报错spawn ENAMETOOLONG

**如何重现**
每当启动软件时

**预期的行为**
无报错，正常运行

**截图**
![TMLIE45@6DPC%H@L`}W`_9B](https://user-images.githubusercontent.com/35864297/194734553-bf9c8ef6-10ad-4e94-bd32-a3babdbb48ab.png)

**运行环境**
 - 操作系统类型： Windows 11 
 - 具体版本：21H2
 - Motrix 版本：1.6.11
 - 安装包类型：exe

**更多信息**
尝试过重装软件和给予管理员权限启动均无效。
报错的同时软件窗口会正常弹出，此时部分功能可正常使用，当报错窗口关闭时软件闪退关闭

**Comment by fxjy15550** [comment]
删除C:\Users\用户名\AppData\Roaming里的motrix文件夹，再重开应该就好了

_Originally posted by @Andy0evil in https://github.com/agalwood/Motrix/issues/1184#issuecomment-1077710995_

**Comment by hyb-oyqq** [comment]
> ```
>     删除C:\Users\用户名\AppData\Roaming里的motrix文件夹，再重开应该就好了
> ```
> 
> _最初由 发布@Andy0evil在[#1184（评论）](https://github.com/agalwood/Motrix/issues/1184#issuecomment-1077710995)_

谢谢，已经可以打开了
