### ISSUE TITLE
p2p下载时建议增加“下载完后再开一会”的提示

### ISSUE THREAD

**Issue by czccycgj** [agalwood/Motrix#134]
温和地提示下p2p下载的的规则，可以方便更多人下载。
虽然这样可能不太【美】，但我认为好处更大些。

**Comment by agalwood** [comment]
感谢你的建议，规则已经被 ⚡️🔫玩坏了: |

**Comment by agalwood** [comment]
v1.3.x 版本加了 BT 任务完成之后做种中的提示，分享只能看自觉了
