### ISSUE TITLE
Dock栏上的图标右键菜单中的最近下载记录无法清除，一直存在。

### ISSUE THREAD

**Issue by maplejaw** [agalwood/Motrix#135]
**错误描述**
 Dock栏上的图标右键菜单中的最近下载记录无法清除，一直存在。

**运行环境**
 - 操作系统类型： macOS
 - 具体版本： macOS 10.14.2
 - Motrix 版本： v1.1.3
 - 安装包类型：dmg

**Comment by agalwood** [comment]
已修正，待发布 https://github.com/agalwood/Motrix/commit/324347e5915cb07481b1d72f71e1d113c510fb97
