### ISSUE TITLE
请问该项目目前还在维护更新吗

### ISSUE THREAD

**Issue by Wanguy** [agalwood/Motrix#1355]
请问该项目还在维护更新吗？看到上一次release已经是2021年5月的事了，新系统更新后有许多bug。

**Comment by huanghaobaobao** [comment]
同问

**Comment by BiuZero** [comment]
好像弃坑了吧， 一年半没更新了，win11下貌似退出都无效，只能用任务管理器🤦‍♂️

**Comment by SuSWhW** [comment]
> 好像弃坑了吧， 一年半没更新了，win11下貌似退出都无效，只能用任务管理器🤦‍♂️

俺也win11，一切正常，但是看着作者好久没更新我也急

**Comment by falseUtopia** [comment]
#1396
