### ISSUE TITLE
p2p上传不能限速

### ISSUE THREAD

**Issue by mountainguan** [agalwood/Motrix#136]
下载完资源后，整个上传的带宽都被拿去p2p分享了…分享是应该的，但是能不能不要把整个上传都用完，都影响到正常上网的体验了

**Comment by agalwood** [comment]
Motrix 偏好设置暂时没有开放这个编辑，不过可以暂时通过修改 aria2.conf 来解决

找到 Motrix 内置的 `aria2.conf` 文件
macOS:
```
/Applications/Motrix.app/Contents/Resources/engine/aria2.conf
```

Windows:
```
你的Motrix安装路径\resources\engine\aria2.conf
```

```
Linux:
手头暂时没 Linux 系统，自己找一下吧 : P
```

用文本编辑工具打开 `aria2.conf`，找到 `#@max-overall-upload-limit=0`，删除该行最前面的注释 `#@`，然后将 `0` 修改为你想要的限速，如 `512K`，限速值的详细说明请参考以下文档：
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-max-overall-upload-limit

**Comment by Raistlin916** [comment]
可以考虑把默认上传限速改成比如 50k ？
