### ISSUE TITLE
More config options for BitTorrent?

### ISSUE THREAD

**Issue by LBYPatrick** [agalwood/Motrix#1363]
**Is your feature request related to a problem? Please describe.**

Support for aria2 flags such as ``bt-force-encryption``, ``enable-dht``, and ``bt-enable-pld``. See [aria2 documentation](http://aria2.github.io/manual/en/html/aria2c.html)
添加更多aria2的BT/DHT配置选项（见上，有一些可以防止吸血和支持DHT）。

**Describe the solution you'd like**

See above. 见上。

**Describe alternatives you've considered**

...没，因为不然就得换aria2了

**Additional context**

Not Applicable. 不适用

**Comment by agalwood** [comment]
#1425
