### ISSUE TITLE
在长时间下载速率为0m/s时自动重新获取下载链接

### ISSUE THREAD

**Issue by SuSWhW** [agalwood/Motrix#1365]
motrix在下载文件时会出现下着下着就变成0m/s的情况，希望可以添加一个自动重新获取下载链接的功能

**Comment by ImBIOS** [comment]
能否帮我们复现一下或者了解更多，比如可以帮我们做一个关于这个bug的窗口记录？

**Comment by SuSWhW** [comment]
> 能否帮我们复现一下或者了解更多，比如可以帮我们做一个关于这个bug的窗口记录？

大抵是不能的，这是个概率问题
