### ISSUE TITLE
Flatpak version of motrix not working

### ISSUE THREAD

**Issue by wowoyoho** [agalwood/Motrix#1370]
**Describe the bug**
Flatpak version of motrix not working

**To Reproduce**
1. Run 'flatpak run net.agalwood.Motrix' in terminal
2. See error

**Expected behavior**
Motrix running

**Screenshots**

**Environment (please complete the following information):**
 - OS & Version: steamos
 - Version: steamos 3.4.4
 - Motrix Version: 1.6.11
 - Installation package type: flatpak

**Additional context**
Detailed error: 
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'fs/promises'
Require stack:
- /app/motrix/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js
- /app/motrix/resources/app.asar/node_modules/electron-updater/out/main.js
- /app/motrix/resources/app.asar/dist/electron/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:249:921)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/motrix/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
Gtk-Message: 22:24:58.276: Failed to load module "canberra-gtk-module"
```

**Comment by AyoungDukie** [comment]
Just encountered this myself on Fedora 37; not sure if this could be a problem from the flatpak build due to Flathub's data outage?

If it is related, I have linked to that issue on the Flathub builder repo:

https://github.com/flathub/net.agalwood.Motrix/issues/11

**Comment by AyoungDukie** [comment]
This may be related to an electron/node problem [based on this thread](https://stackoverflow.com/questions/68085375/cannot-find-module-fs-promises-electron-js), which might be introduced by the rebuilding needed for making the flatpak. I will test with the app-image to see, but may be the case that the last static builds of Motrix from 2021 may not have encountered this problem.

**Comment by cedarice** [comment]
same issue on Kubuntu 22.04 recent days

**Comment by AyoungDukie** [comment]
Just got an updated flatpak release, and now seems to launch/run fine!

**Comment by m110s** [comment]
Looks like previous bug is solved, but I got new error:
`[3:0122/091159.827872:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
/app/bin/start-motrix: line 3:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper /app/motrix/motrix "$@"
`
It starts and works fine with option:   --in-process-gpu
`flatpak run net.agalwood.Motrix --in-process-gpu`

**Comment by SpamixOfficial** [comment]
@m110s Getting the same error. Im currently on EndeavourOS

**Comment by m110s** [comment]
> @m110s Getting the same error. Im currently on EndeavourOS

I'm on ReborneOS, same Arch base.
Just installed new update but situation is the same.

**Comment by SpamixOfficial** [comment]
@m110s Yea, but using that tag makes it at least usable. Might have to use another manager while this is an issue!
