### ISSUE TITLE
这个项目还有人维护吗

### ISSUE THREAD

**Issue by youtehub** [agalwood/Motrix#1379]
![image](https://user-images.githubusercontent.com/18629921/215465894-e04a5aca-d3d7-438a-986b-6365796be1cc.png)
ru如图，最后一个维护还是去年2022年4月份的事情了，现在还有人维护这个项目吗，这么好用的项目停掉了怪可惜的唉，希望有能力的开发者能够加入进来帮忙维护这个开源项目，因为这个项目真心非常方便

**Comment by Dragon1573** [comment]
原作 `agalwood` 大概率已经弃坑了。

Motrix 使用的 Aria2 来源于他自己的专用 Fork 而非官方发行的预编译包，单纯替换 Aria2 内核是没有用的，从这一点上就导致转移仓库所有权，让社区接手后续维护变得很困难。

Motrix 是使用 Electron 生成构建的，我试过使用 Electron 官方提供的 Docker 镜像自行编译构建 Motrix 也无济于事。Motrix 应该是永远停留在 `v1.6.11` 了，其 Aria2 内核也永远停留在 `v1.35.0` 了。

**Comment by youtehub** [comment]
那太可惜了，这么好的项目无法维护了，现在感觉才是最好用，普及率也越来越好，

**Comment by Dragon1573** [comment]
> 那太可惜了，这么好的项目无法维护了。

不仅是 Motrix ，Aria2 自身貌似也停更了，当前最新版本是 `v1.36.0` ，也是接近2年前发布的 GitHub Release 。

> 现在感觉才是最好用，普及率也越来越好。

个人猜测 Motrix 安装率应该不低，直接提供 GUI 交互＋内置开机自启功能挺方便的，但弃坑了确实可惜。

我目前使用官方 Aria2 `v1.36.0` ，配置文件原样复用 Motrix 的 `aria2.conf` ，使用了 WinSW 将 Aria2 安装成用户服务来开机自启，配合 Aria2 for Edge 插件拦截浏览器下载，使用插件附带 AirNG 进行图形化交互。

**Comment by zkwolf** [comment]
就Aria2的更新日志看来v1.36.0升级也没啥大变动本质上应该也不会有啥体验的提升吧

**Comment by Dragon1573** [comment]
个人认为第6~8项相对重要一点：

- 新版本 Aria2 可以防止软件/系统崩溃时造成下载损坏
- 在下载过程启动时重置 `sessionDownloadLength` 和 `sessionUploadLength`（猜测是下载过程中需要的两个参数值）
- 添加 TLS v1.3 支持

在使用上暂时没感受出有什么变化，我目前也只用 Aria2 下载过 HTTP(s) 资源，Torrent/Magnet/FTP 资源还没见过。

**Comment by Jerry23011** [comment]
aria2仓库还是在积极开发的，只不过没新的release，Motrix现在和public archive没什么区别了

**Comment by Dragon1573** [comment]
> Aria2 仓库还是在积极开发的，只不过没新的 Release 。

但也挺奇怪的，都快2年了也不出 Release 。这是在憋哪吒，准备发明「次时代多线程下载器」，直接上 `v2.0.0` 然后改叫 Aria3 么？

![滑稽](https://user-images.githubusercontent.com/49941141/217287874-996efbc6-f3d5-4d43-9cab-fb9ac1161288.jpg)

**Comment by Jerry23011** [comment]
> > Aria2 仓库还是在积极开发的，只不过没新的 Release 。
> 
> 但也挺奇怪的，都快2年了也不出 Release 。这是在憋哪吒，准备发明「次时代多线程下载器」，直接上 `v2.0.0` 然后改叫 Aria3 么？
> 
> ![滑稽](https://user-images.githubusercontent.com/49941141/217287874-996efbc6-f3d5-4d43-9cab-fb9ac1161288.jpg)

不知道啊，也没看出来有什么重磅的啊😄

**Comment by Dragon1573** [comment]
> Motrix 现在和 `Public Archived` 没什么区别了

雀食。在 GitHub 也有大量或优质或辣鸡的项目，虽然没有加 `Archived` 标记但作者已事实弃坑。不论这些是传世珍宝还是依托答辩，原作弃坑一下坟头一片杂草也挺可惜的……

**Comment by Jerry23011** [comment]
要我说作者要是因为什么原因不维护了就把状态改了，目前这样的我个人是不怎么喜欢 :)在 2023年2月7日，23:33，べ断桥烟雨ミ ***@***.***> 写道：﻿

Motrix 现在和 Public Archived 没什么区别了

雀食。在 GitHub 也有大量或优质或辣鸡的项目，虽然没有加 Archived 标记但作者已事实弃坑。不论这些是传世珍宝还是依托答辩，原作弃坑一下坟头一片杂草也挺可惜的……

**Comment by zkwolf** [comment]
看了看感觉接手也挺难的，打包dmg还需要apple的开发者账号，要不然就得用xattr手动处理一下

**Comment by Dragon1573** [comment]
> 看了看感觉接手也挺难的，打包 `*.dmg` 还需要 Apple 的开发者账号，要不然就得用 `xattr` 手动处理一下。

其实也不一定要打成 `*.dmg` 格式的，封装成 `*.tar.gz` 或者 `*.zip` 也行，印象中 Electron 有提供 Docker 镜像来实现跨平台构建。

主要是如何解决 Aria2 内核的升级问题，这个项目按照 `README.md` 里提供的构建方法是可以把当前的 `v1.6.11＋v1.35.0` 构建出来并正常使用的。

只要新版本能编译出来，分发形式应该是小事。

**Comment by Jerry23011** [comment]
> 其实也不一定要打成 *.dmg 格式的，封装成 *.tar.gz 或者 *.zip 也行，印象中 Electron 有提供 Docker 镜像来实现跨平台构建。

主要是考虑大部分用户嘛，还是有签名的dmg更方便
我还觉得需要升级一下electron版本，因为最新macOS系统下有一个动画掉帧的bug需要electron新版本解决

**Comment by Jerry23011** [comment]
从 #1300 这个 Discussion 能看出大家的担忧😄

**Comment by zkwolf** [comment]
> > 其实也不一定要打成 *.dmg 格式的，封装成 *.tar.gz 或者 *.zip 也行，印象中 Electron 有提供 Docker 镜像来实现跨平台构建。
> 
> 主要是考虑大部分用户嘛，还是有签名的dmg更方便 我还觉得需要升级一下electron版本，因为最新macOS系统下有一个动画掉帧的bug需要electron新版本解决

拉了一下electron的版本，可以试试有没有问题，dmg没签名自己处理一下https://github.com/zkwolf/Motrix/releases/tag/v1.7.0

**Comment by Jerry23011** [comment]
OK 我看了一下，macOS好像没打包universal的，x86运行导致在Apple silicon上速度有点慢，然后动画掉帧bug还在，不知道为什么，看来是我误判了，还是需要再研究一下，目前观察只会出现在低版本electron app上，但是可能有其他触发原因，辛苦了

**Comment by zkwolf** [comment]
Silicon的话用那个arm64.dmg

**Comment by Jerry23011** [comment]
收到，简单看了一下，是没有问题的，就是设置界面点“保存并应用”会报错，但是我看设置实际上是保存成功的
<img width="1019" alt="截屏2023-02-08 19 25 23" src="https://user-images.githubusercontent.com/89069957/217517781-e72589d7-bade-4f49-935e-faa3d86325f5.png">

- macOS 13.2
- MacBook Pro 14‘

**Comment by Jerry23011** [comment]
动画卡顿的问题找到了，是 electron 的半透明效果，不知道能不能加上一个设置让用户选择启动app的时候禁用electron的半透明效果

**Comment by zkwolf** [comment]
上个视频来看看？我感觉我这没感受到有啥卡顿的

**Comment by Jerry23011** [comment]
https://user-images.githubusercontent.com/89069957/218104405-b9385e0f-3423-4073-84ae-682df6e601c3.mov

录屏只有不到60帧/秒，120Hz的屏上感觉更明显

**Comment by jyeric** [comment]
新版本编译直接用GitHub Actions就行了。我去年本来想把64线程加到256线程的时候搞了一个 https://github.com/jyeric/Motrix-256threads 。但实际上只加到了128线程（具体aria2替换我都忘了是不是在这个上面了）

现在我基本上用bitcomet了。多线程最高支持200线程，而且没有等待时间

**Comment by Jerry23011** [comment]
> 新版本编译直接用GitHub Actions就行了。我去年本来想把64线程加到256线程的时候搞了一个 https://github.com/jyeric/Motrix-256threads 。但实际上只加到了128线程（具体aria2替换我都忘了是不是在这个上面了）
> 
> 
> 
> 现在我基本上用bitcomet了。多线程最高支持200线程，而且没有等待时间

Bitcomit 支持 http 下载吗？

**Comment by jyeric** [comment]
支持，最大200线程。大文件无需等待







在 2023-02-11 23:56:26，Jerry ***@***.***> 写道：


新版本编译直接用GitHub Actions就行了。我去年本来想把64线程加到256线程的时候搞了一个 https://github.com/jyeric/Motrix-256threads 。但实际上只加到了128线程（具体aria2替换我都忘了是不是在这个上面了）

现在我基本上用bitcomet了。多线程最高支持200线程，而且没有等待时间

Bitcomit 支持 http 下载吗？

**Comment by Jerry23011** [comment]
看了一下，bitcomet 好像不开源也没原生 Apple silicon，而且官网被腾讯列为欺骗性网站，种子下载我一般用 Transmission，Motrix 主要是 http 比较方便

**Comment by jyeric** [comment]
确实如此并非开源软件。欺骗性网站嘛，毕竟是以前较火的bt下载软件，很有可能被封杀。这个主要支持内网打洞、大文件无需预留空间、大量dht节点，目前也没看到替代品
















在 2023-02-12 12:20:39，"Jerry" ***@***.***> 写道：

看了一下，bitcomet 好像不开源也没原生 Apple silicon，而且官网被腾讯列为欺骗性网站，种子下载我一般用 Transmission，Motrix 主要是 http 比较方便

**Comment by SuSWhW** [comment]
> > > Aria2 仓库还是在积极开发的，只不过没新的 Release 。
> > 
> > 
> > 但也挺奇怪的，都快2年了也不出 Release 。这是在憋哪吒，准备发明「次时代多线程下载器」，直接上 `v2.0.0` 然后改叫 Aria3 么？
> > ![滑稽](https://user-images.githubusercontent.com/49941141/217287874-996efbc6-f3d5-4d43-9cab-fb9ac1161288.jpg)
> 
> 不知道啊，也没看出来有什么重磅的啊😄

aria也是基本处于弃坑的状态了，最晚的一次commit已经是6 months ago了，motrix已经快完了属于是

**Comment by Jerry23011** [comment]
确实，aria要是不维护了真挺可惜的

**Comment by SuSWhW** [comment]
> 确实，aria要是不维护了真挺可惜的

想当年，我正年少，不知天高地厚的想要接盘motrix（

**Comment by zkwolf** [comment]
> > 确实，aria要是不维护了真挺可惜的
> 
> 想当年，我正年少，不知天高地厚的想要接盘motrix（

Motrix还算比较简单的，核心都在aira2

**Comment by SuSWhW** [comment]
> > > 确实，aria要是不维护了真挺可惜的
> > 
> > 
> > 想当年，我正年少，不知天高地厚的想要接盘motrix（
> 
> Motrix还算比较简单的，核心都在aira2

不单止aria2，还有nodejs的依赖问题，现在motrix的很多依赖已经不支持最新版的nodejs了

**Comment by falseUtopia** [comment]
#1396

**Comment by blacklein** [comment]
> 

需要用fnm use 16来更换node版本，不然编译有一个module会安装失败，这个module能更新下yarn.lock解决么？
我自己在M1 Mac上编译zkwolf的fork版成功了，没有报错

**Comment by SuSWhW** [comment]
> > 
> 
> 需要用fnm use 16来更换node版本，不然编译有一个module会安装失败，这个module能更新下yarn.lock解决么？ 我自己在M1 Mac上编译zkwolf的fork版成功了，没有报错

不能的，有些包已经停止更新了，强行更新并编译依然会编译失败

**Comment by kaseeen** [comment]
唉可惜 有大佬能帮忙编译个action的最新版吗 有些功能用得上

**Comment by its-Hans** [comment]
stopped again
