### ISSUE TITLE
Needs an option to set a secret for the RPC interface on Aria2. 

### ISSUE THREAD

**Issue by joshkerr** [agalwood/Motrix#138]
**Is your feature request related to a problem? Please describe.**
There is a clear security problem with this app because it leaves aria2 running with RPC interface intact and no secret.

**Describe the solution you'd like**
Add an option in the settings to set an RPC secret for Aria2.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by agalwood** [comment]
This feature is currently supported, but there is no UI editing, which can be added later.
You can edit the Motrix configuration file: `system.json`, which has the rpc-secret field.

Windows
`%APPDATA%/Motrix/system.json`

Linux
`$XDG_CONFIG_HOME/Motrix/system.json` or `~/.config/Motrix/system.json`

macOS
`~/Library/Application Support/Motrix/system.json`

Save & Restart Motrix
