### ISSUE TITLE
外观跟随系统选择浅色/深色无效：系统为深色时，软件选择自动为浅色

### ISSUE THREAD

**Issue by KIL011** [agalwood/Motrix#1389]
如题所述，如需任何信息，请随时告诉我

**Comment by ImBIOS** [comment]
Can you inform us of your system information?
You can use this command to help you collect it:

```sh
npx envinfo --system --binaries --browsers 
```

add `| pbcopy` if you're in macOS for easy copy-paste.

**Comment by KIL011** [comment]
Hi, Here is the info of my laptop:

  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
    Memory: 6.61 GB / 13.69 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (112.0.1722.34)
    Internet Explorer: 11.0.22621.1

**Comment by ImBIOS** [comment]
谢谢，这让我们更容易找到问题的根本原因。

**Comment by KIL011** [comment]
问题已经修复，谢谢
