### ISSUE TITLE
官网没有 Windows exe 安装文件

### ISSUE THREAD

**Issue by xuejianxianzun** [agalwood/Motrix#1392]
刚才打开官网看看到有个 JS 文件加载出错，导致只显示默认的 Mac OS 安装包，无法选择其他平台的安装包。
https://motrix.app/

看到前面的 issue 说这个项目不维护了，那我把以前下载的 exe 文件的网址发这里吧：
Motrix-Setup-1.6.11.exe
https://dl.moapp.me/https://github.com/agalwood/Motrix/releases/download/v1.6.11/Motrix-Setup-1.6.11.exe

**Comment by Kylerie** [comment]
thx,bro

**Comment by zhaoaicheng** [comment]
感谢

**Comment by EdThePro101** [comment]
I see that there are two downloads in the GitHub release page for Windows: **Motrix-1.6.11.exe** and **Motrix-Setup-1.6.11.exe**. I'm finding it really difficult to differentiate between them.

**Comment by agalwood** [comment]
服务器上的 nginx 连接数设置太小了，已经调整了
