### ISSUE TITLE
windows 10 安装KB5023696更新后，16800端口被屏蔽，导致浏览器扩展不可用

### ISSUE THREAD

**Issue by FiberStudio** [agalwood/Motrix#1399]
**错误描述**
在windows 10 自动更新了“适用于基于x64系统（KB5023696）的Windows 10 Version 22H2 版本的2023-03”这个补丁后，16800端口已经被屏蔽了，导致当前无法使用浏览器拓展Aria2-for-chrome。
**如何重现**
重现步骤，如：
1. 在更新了KB5023696补丁后，打开motrix，再打开浏览器拓展Aria2-for-chrome，即使拓展已经配置了正确的端口号，依然无法连接上。

**预期的行为**
建议在motrix中添加自定义端口号的功能。

**截图**
![image](https://user-images.githubusercontent.com/46367587/226130063-25109cba-59a8-4fb4-93e0-20153f6eee60.png)

**运行环境**
 - 操作系统类型： windows 10
 - 具体版本：windows 10 22H2
 - Motrix 版本： v1.6.11
 - 安装包类型：exe

**更多信息**
可以在cmd中输入
```cmd
netsh interface ipv4 show excludedportrange protocol=tcp
```
查看当前windows屏蔽的端口
![image](https://user-images.githubusercontent.com/46367587/226130425-d8880551-eef6-4d49-a1fa-070e114d1d8d.png)
如上图所示，16800端口在屏蔽的区间

**Comment by zkwolf** [comment]
简单一点的办法，去用户下的AppData/Roaming/Motrix文件夹下的system.json里把rpc-listen-port改了

另：比较不确定这个端口是不是其他导致的，我这pc在Win11 beta通道完全没影响

**Comment by FiberStudio** [comment]
> 简单一点的办法，去用户下的AppData/Roaming/Motrix文件夹下的system.json里把rpc-listen-port改了
> 
> 另：比较不确定这个端口是不是其他导致的，我这pc在Win11 beta通道完全没影响

感谢，更改配置文件system.json里的rpc-listen-port完全有效。
另外，经过我一个个卸载更新，最终发现是KB5022834这个补丁导致的端口被屏蔽，而不是我前面说的KB5023696补丁。卸载KB5022834这个更新补丁后，也能解决问题。
但是修改motrix配置文件我认为是最优的解决方案，再次感谢！

**Comment by BLACKCHARGE** [comment]
我觉得造成这一情况的可能不是windows更新，KB5022834和KB5023696我都安装了，并没有出现端口屏蔽的情况
![image](https://user-images.githubusercontent.com/57131319/227553708-c8479eb0-44e9-4e82-ad30-cc80d6769833.png)
![image](https://user-images.githubusercontent.com/57131319/227553826-a2ceae88-785a-463f-830f-2836c4f9cd3f.png)

**Comment by BLACKCHARGE** [comment]
这个问题应该是与windows更新无关的，疑似是是windows的随机端口保留机制引发的问题，随机保留的端口正好覆盖了16800的范围，详细看这个https://stackoverflow.com/questions/54010365/how-to-see-what-is-reserving-ephemeral-port-ranges-on-windows有讨论解决方案

**Comment by FiberStudio** [comment]
> 这个问题应该是与windows更新无关的，疑似是是windows的随机端口保留机制引发的问题，随机保留的端口正好覆盖了16800的范围，详细看这个[https://stackoverflow.com/questions/54010365/how-to-see-what-is-reserving-ephemeral-port-ranges-on-windows有讨论解决方案](https://stackoverflow.com/questions/54010365/how-to-see-what-is-reserving-ephemeral-port-ranges-on-windows%E6%9C%89%E8%AE%A8%E8%AE%BA%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)

十分感谢，链接中的解决方法似乎是最完美的。
但在我卸载windows更新之后，这个问题在两周内暂时没有再出现了。结合链接中的信息，我觉得可能是我更新了wsl2，wsl2随机保留了端口的原因。等下次出现了同样的问题，我再试试。
再次感谢。

**Comment by FiberStudio** [comment]
> 这个问题应该是与windows更新无关的，疑似是是windows的随机端口保留机制引发的问题，随机保留的端口正好覆盖了16800的范围，详细看这个[https://stackoverflow.com/questions/54010365/how-to-see-what-is-reserving-ephemeral-port-ranges-on-windows有讨论解决方案](https://stackoverflow.com/questions/54010365/how-to-see-what-is-reserving-ephemeral-port-ranges-on-windows%E6%9C%89%E8%AE%A8%E8%AE%BA%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88)

在今天系统自动更新之后，又出现了同样的问题。经测试，链接中的方法完全适用。感谢。

现将具体操作记录如下，以便其他人参考：
```cmd
net stop winnat
Windows NAT Driver 服务已成功停止。
net start winat
Windows NAT Driver 服务已经启动成功。
```
重启winnat服务后，16800端口应该被释放了。但是这种操作只能是暂时性的，如果需要一劳永逸地解决这个问题，可以将16800端口加入排除名单，这样winnat就不会占用了。
```cmd
 netsh int ipv4 add excludedportrange protocol=tcp startport=16800 numberofports=1
```

**Comment by zkwolf** [comment]
感觉确实和wsl有关，今天更新wsl以后我也遇到了端口屏蔽，然后重启又没了
