### ISSUE TITLE
我不小心停止做种了，我在帮助手册里并未找到继续做种

### ISSUE THREAD

**Issue by JunSilckTar** [agalwood/Motrix#1401]
如果有这个功能，很抱歉我没找到，如果没有，我希望未来的版本能够有

**Comment by ImBIOS** [comment]
你是不是不小心停止了播种？我认为我们也应该为这个开源软件制作一个文档网站。

**Comment by JunSilckTar** [comment]
> 

是的，我不小心停止播种了，我想继续，但我并未找到任何按钮继续播种，可能是我安装的软件版本较低，我正在尝试更新到最新版本。如果需要制作文档网站，我应该可以帮忙做UI/UX设计以及翻译工作
