### ISSUE TITLE
Check for updates throw errors

### ISSUE THREAD

**Issue by happystraw** [agalwood/Motrix#142]
**错误描述**
检查更新异常

**如何重现**
重现步骤，如：
1. Menu: [File] > [Check for updates]
2. throw error

**预期的行为**
正常检查

**截图**
![image](https://user-images.githubusercontent.com/18533666/54187576-e107d880-44e8-11e9-8cec-32f22a33a964.png)

**运行环境**
 - 操作系统类型： Linux
 - 具体版本： Ubuntu 18.04
 - Motrix 版本： v1.1.3
 - 安装包类型：deb

**更多信息**
无

**Comment by agalwood** [comment]
试一下用 root 身份运行，然后检查更新试试？
我怀疑是检查更新时没有写权限

**Comment by agalwood** [comment]
不用试了，查到原因了 deb 类型 electron-builder AutoUpdate 不支持，Linux 用户请使用 AppImage
https://www.electron.build/auto-update#auto-updatable-targets
