### ISSUE TITLE
Can not delete the tasks at one time

### ISSUE THREAD

**Issue by leienshu** [agalwood/Motrix#143]
I have to download many large files , but i do not want to continue these tasks after a few minutes later. How can I delete these task at one time ? they are more than one hundred tasks!

**Comment by agalwood** [comment]
First, open the `Advanced` settings in the `Preferences`, there is a `download.session` address, open it in the folder, write down the download path of the task inside, I think you a bunch of tasks should be downloaded to the same directory, you can batch delete them, including `*.aria2`.
Finally, empty or delete the `download.session`.

**Comment by leienshu** [comment]
> First, open the `Advanced` settings in the `Preferences`, there is a `download.session` address, open it in the folder, write down the download path of the task inside, I think you a bunch of tasks should be downloaded to the same directory, you can batch delete them, including `*.aria2`.
> Finally, empty or delete the `download.session`.

Thanks a lot
