### ISSUE TITLE
Chocolatey上装的是最新版吗？

### ISSUE THREAD

**Issue by Anivie** [agalwood/Motrix#1433]
我看release里是两年前的版本，但是到现在一直都有commit，想问问想用上最新版的话Chocolatey上的是吗？还是只有自己构建？

**Comment by agalwood** [comment]
预计5月份会打包发布新的版本，目前请自己构建

**Comment by Anivie** [comment]
> 预计5月份会打包发布新的版本，目前请自己构建

好的，感谢贡献
