### ISSUE TITLE
WHEN UPDATE??? WHEN NEW RELEASE?????????

### ISSUE THREAD

**Issue by nickname76** [agalwood/Motrix#1437]
My whole body hurts, I need you to release new version of Motrix AFAP to stop my pain. I also require flatpak!!! Please; Thank you;

**Comment by xuangeyouneihan** [comment]
#1396 About the reasons for the suspension of Motrix, and the recent situation of the author agalwood

**Comment by Silicon7921** [comment]
updated bro

**Comment by Silicon7921** [comment]
close this issue()
