### ISSUE TITLE
armhf and arm64 linux support?

### ISSUE THREAD

**Issue by Austcool-Walker** [agalwood/Motrix#1443]
**Is your feature request related to a problem? Please describe.**
Linux arm release (deb and app image?)

**Describe the solution you'd like**
A armhf and arm64 .deb and appimage.

**Comment by liutun** [comment]
新版发布，已经支持了。

**Comment by Austcool-Walker** [comment]
Thank you! (I know this is unrelated but I also love Chinas MIUI I own a Enuma Tablet!)
