### ISSUE TITLE
[BUG]: v1.8.11无法下载内容

### ISSUE THREAD

**Issue by JayeGT002** [agalwood/Motrix#1451]
### Bug 描述

尝试使用motrix下载内容时失败，错误提示Failed to fetch
下载内容：https://releases.ubuntu.com/22.10/ubuntu-22.10-desktop-amd64.iso.torrent

### 环境

macOS 13.3.1 (22E261)
MacBook Pro（2021 M1 Pro）

### 复现步骤

1、点击种子文件
2、点击提交
3、弹出报错提示

### 额外信息

_没有回应_

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by lukas0013** [comment]
Same situation on macOS Ventura 😔

**Comment by JayeGT002** [comment]
> macOS Ventura上的情况也一样�

Well, we have exactly the same problem.

**Comment by CW-B-W** [comment]
It can be downloaded normally AppleSilicon version [Motrix-1.8.11-arm64-mac.zip](https://github.com/agalwood/Motrix/releases/download/v1.8.11/Motrix-1.8.11-arm64-mac.zip) on my M1 Mac.

But if I use the x86 version [Motrix-1.8.11-mac.zip](https://github.com/agalwood/Motrix/releases/download/v1.8.11/Motrix-1.8.11-mac.zip), I got `Failed to fetch`, as expected.

Env:
macOS Monterey Version 12.5.1
MacBook Air (M1, 2020)

**Comment by lukas0013** [comment]
Problem still persist in 1.8.14

**Comment by yyleung01** [comment]
我和@CW-B-W相反，1.8.14 ARM无法下载，应该是aria2的进程权限问题，但是不知道怎么设置回去，隔壁Linux平台下可以sudo开始下载进程，macos怎么处理呢？
系统 Monterey 12.6.2
型号 Macbook Pro 14 M1pro （2021）

**Comment by agalwood** [comment]
@JayeGT002 @lukas0013 @CW-B-W @yyleung01 

复制命令试下，贴一下执行结果
https://github.com/agalwood/Motrix/issues/1459#issuecomment-1526888482

**Comment by CW-B-W** [comment]
> @JayeGT002 @lukas0013 @CW-B-W @yyleung01
> 
> 复制命令试下，贴一下执行结果 [#1459 (comment)](https://github.com/agalwood/Motrix/issues/1459#issuecomment-1526888482)

![image](https://user-images.githubusercontent.com/76680670/235043464-1a25e3c6-ca6f-4f13-8eb0-f2be87d1ac87.png)

aria2c 可正常運行(我的 Motrix v1.6.11~v1.8.11 APP 一向都可以正常下載，並無其他用戶所述問題)

**Comment by JayeGT002** [comment]
> @JayeGT002 @lukas0013 @CW-B-W @yyleung01
> 
> 复制命令试下，贴一下执行结果 [#1459 (comment)](https://github.com/agalwood/Motrix/issues/1459#issuecomment-1526888482)

```
Last login: Thu Apr 27 03:38:29 on ttys000
jayegt002@heichuanyedeMBP ~ % /Applications/Motrix.app/Contents/Resources/engine/aria2c https://dl.motrix.app/release/Motrix-1.8.14-universal.dmg
dyld[45219]: Library not loaded: /opt/homebrew/opt/gmp/lib/libgmp.10.dylib
  Referenced from: <A3E45AB5-64BF-3DF8-BD60-9E696108B09C> /Applications/Motrix.app/Contents/Resources/engine/aria2c
  Reason: tried: '/opt/homebrew/opt/gmp/lib/libgmp.10.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/gmp/lib/libgmp.10.dylib' (no such file), '/opt/homebrew/opt/gmp/lib/libgmp.10.dylib' (no such file), '/usr/lib/libgmp.10.dylib' (no such file, not in dyld cache)
zsh: abort      /Applications/Motrix.app/Contents/Resources/engine/aria2c 
```

**Comment by agalwood** [comment]
Please update Motrix to v1.8.15+
请更新 Motrix 到v1.8.15+

https://github.com/agalwood/Motrix/releases/tag/v1.8.15
