### ISSUE TITLE
[BUG]: aria2与“Failed to fetch”错误

### ISSUE THREAD

**Issue by kamiMouse** [agalwood/Motrix#1459]
### Bug 描述

手动杀掉aria2进程后应用无法再启动内置aria了，新增下载会报“Failed to fetch”错误

### Motrix 版本

1.8.14

### 环境

macOs 13.3.1 (22E261)

### 复现步骤

手动杀掉aria2进程后应用无法再启动内置aria了，新增下载会报“Failed to fetch”错误

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by sinict** [comment]
我也是, 自动更新失败, 重新安装后 再也用不了

**Comment by agalwood** [comment]
打开 Terminal，执行下面的命令试下
```bash
/Applications/Motrix.app/Contents/Resources/engine/aria2c https://dl.motrix.app/release/Motrix-1.8.14-universal.dmg
```

**Comment by maizijuni** [comment]
> 打开终端，执行下面的命令试下>> ```外壳> /Applications/Motrix.app/Contents/Resources/engine/aria2c https://dl.motrix.app/release/Motrix-1.8.14-universal.dmg> ```运行后依然报错

**Comment by happykkAi** [comment]
是的  我重新测试了很多次  拓展使用motrix的拓展也不能下载 更新1.8.14后 aria2 无法连接下载 motrix拓展也一样

**Comment by agalwood** [comment]
> > 打开终端，执行下面的命令试下>> `外壳> /Applications/Motrix.app/Contents/Resources/engine/aria2c https://dl.motrix.app/release/Motrix-1.8.14-universal.dmg> `运行后依然报错

这并不是什么修复的命令，而是测试的，你贴一下执行结果

**Comment by happykkAi** [comment]
> > > 打开终端，执行下面的命令试下>> `外壳> /Applications/Motrix.app/Contents/Resources/engine/aria2c https://dl.motrix.app/release/Motrix-1.8.14-universal.dmg> `运行后依然报错
> 
> @maizijuni 这并不是什么修复的命令，而是测试的，你贴一下执行结果

Last login: Fri Apr 28 11:08:53 on ttys000
happy@MacBook-Pro ~ % /Applications/Motrix.app/Contents/Resources/engine/aria2c https://dl.motrix.app/release/Motrix-1.8.14-universal.dmg
dyld[3296]: Library not loaded: /opt/homebrew/opt/gmp/lib/libgmp.10.dylib
  Referenced from: <A3E45AB5-64BF-3DF8-BD60-9E696108B09C> /Applications/Motrix.app/Contents/Resources/engine/aria2c
  Reason: tried: '/opt/homebrew/opt/gmp/lib/libgmp.10.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/gmp/lib/libgmp.10.dylib' (no such file), '/opt/homebrew/opt/gmp/lib/libgmp.10.dylib' (no such file), '/usr/lib/libgmp.10.dylib' (no such file, not in dyld cache)
zsh: abort      /Applications/Motrix.app/Contents/Resources/engine/aria2c 
happy@MacBook-Pro ~ %

**Comment by agalwood** [comment]
@happykkAi 看来是 libgmp 没有正确静态编译到 aria2 里，我重新编译一下

**Comment by happykkAi** [comment]
> @happykkAi 看来是 libgmp 没有正确静态编译到 aria2 里，我重新编译一下

等你的好消息

**Comment by agalwood** [comment]
Please update Motrix to v1.8.15+
请更新Motrix到v1.8.15+

https://github.com/agalwood/Motrix/releases/tag/v1.8.15
