### ISSUE TITLE
"Motrix" cannot take over the browser downloads.

### ISSUE THREAD

**Issue by ranslong** [agalwood/Motrix#1460]
After installing the Motrix WebExtension on Google Chrome browser, it cannot take over the browser downloads.

**Comment by CW-B-W** [comment]
I think this issue should be posted on [gautamkrishnar/motrix-webextension](https://github.com/gautamkrishnar/motrix-webextension/issues) instead of here.

Did you correctly setup the extension with [motrix-webextension#how-to-use](https://github.com/gautamkrishnar/motrix-webextension#how-to-use)?
