### ISSUE TITLE
[BUG]: 1.8.x libgmp & libcares dylibs potential problem

### ISSUE THREAD

**Issue by yozhic** [agalwood/Motrix#1462]
### Description of the bug

Now `ariaf2c` is built with a dependency on two `*.dylib`

```
otool -L Motrix.app/Contents/Resources/engine/aria2c
    /opt/homebrew/opt/gmp/lib/libgmp.10.dylib (compatibility version 15.0.0, current version 15.1.0)
    /opt/homebrew/opt/c-ares/lib/libcares.2.dylib (compatibility version 2.0.0, current version 2.6.0)
```

So, this is a potential problem which will make the application not work in some cases.

**agalwood**, could you please build `aria2c` with the static `libgmp` and `libcares` libraries?

### Motrix Version

1.8.14 installed from `dmg` and `universal.dmg`

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
    Memory: 1.43 GB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    npm: 8.12.1 - /usr/local/bin/npm
  Browsers:
    Safari: 12.1.2
    Vivaldi: 5.6.2867.50

### Steps To Reproduce

Described in the first field.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a [GitHub Discussion](https://github.com/agalwood/Motrix/discussions) instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by agalwood** [comment]
Please update Motrix to v1.8.15+

https://github.com/agalwood/Motrix/releases/tag/v1.8.15
