### ISSUE TITLE
隐藏界面(也就是那个自动白屏)能不能搞个设置开关，还有任务能不能排序已经下载完的做种的排在最下面。不排序强迫症看着好难受加任务还要上拉下拉。

### ISSUE THREAD

**Issue by soneyang2333** [agalwood/Motrix#1463]
**Is your feature request related to a problem? Please describe.**
界面会自动隐藏，没有设置选择是否开启自动隐藏

进行中的任务不能排序。不排序强迫症看着好难受，加任务还要上拉下拉。

建立磁力任务保存的种子文件不是按下载任务名字命名，好像是以hash命名的？

**Describe the solution you'd like**
我能理解是为了避免突然打开被其他人看到正在下载敏感资源社死。但是能不能搞个设置选择开启与否，不然一遍遍CTRL+R 我要烦死了。。

已经下载完的做种的排在最下面。或者有几种排序方式自由选择。或者每项任务可以自由拖动排序。

保存的种子文件建议以资源名命名，就是进行的任务，那个任务的名字命名，不然好几个种子我都分不清了，然后重新打开软件接着下载的时候，我不知道要打开哪个种子继续进行未完成的任务

**Describe alternatives you've considered**
null

**Additional context**
总体来说软件非常棒，希望以上地方可以改动或者加入可选项，非常期待

**Comment by soneyang2333** [comment]
![image](https://user-images.githubusercontent.com/45317419/235145670-2bfb5cb0-4be9-444a-b792-8a5104220ebc.png)
额，才看到这个，不过其实好像昨天还是前天也更新了版本，只是官网可以下载，应该还没全体推送。

那将就用吧，其实上面说的那些都可以自己操作规避。只是舒适度问题。

希望作者赚得盆满钵满，并且还有剩余时间。

**Comment by soneyang2333** [comment]
![image](https://user-images.githubusercontent.com/45317419/235146314-0c5d2233-de0a-48ee-a03c-5d24830ca460.png)


额，才看到这个，不过其实好像昨天还是前天也更新了版本，只是官网可以下载，应该还没全体推送。

那将就用吧，其实上面说的那些都可以自己操作规避。只是舒适度问题。

希望作者赚得盆满钵满，并且还有剩余时间。

**Comment by soneyang2333** [comment]
这个隐藏界面好像可以降低偶尔突发飙升的CPU占用，甚至直接变成0.  而且最好是等他自动隐藏，如果没隐藏界面直接最小化到系统托都起不到降低CPU占用这个效果。。。

不过有时候需要看这个界面的时候还是不要自动隐藏的好，还是建议搞个是否自动隐藏的开关

**Comment by soneyang2333** [comment]
手动在tracker文本框添加的traker，在保存运用后不显示。不知道实际有没有添加成功，应该是成功了，之前没速度，添加之后速度起来了，不过文本框没显示。如果退出软件或者关机，下次启动应该就没了，又得重新手动添加一次，不知道能不能一直保留，直到更新或者手动更新

**Comment by DreamOfIce** [comment]
设置-自动隐藏窗口 不行嘛

**Comment by soneyang2333** [comment]
> 基础设置-自动隐藏窗口 不行嘛

之前觉得是不行，你说了我又去重试了一下。结果发现其实可以的，不过要等大概三四分钟的样子？是程序要在后台做一些东西吗，是必须的话也只能这样等等啦
