### ISSUE TITLE
Support Github Actions artifact direct link extraction

### ISSUE THREAD

**Issue by necros2k7** [agalwood/Motrix#1476]
**Is your feature request related to a problem? Please describe.**
App can`t extract Github Actions artifacts

**Describe the solution you'd like**
Direct download of Github Actions artifacts

**Describe alternatives you've considered**
make some general link extractor like yt-dlp does

**Additional context**
example link to download artifact:
https://github.com/EKA2L1/EKA2L1/suites/12599229339/artifacts/674063432

**Comment by agalwood** [comment]
This link needs to be logged in to GitHub to download, copy the link & your GitHub cookie into Motrix, it can be downloaded successfully

**Comment by berezovskyi** [comment]
@necros2k7 just downloaded it successfully with https://github.com/gautamkrishnar/motrix-webextension without any extra configuration.
