### ISSUE TITLE
新APP Bundle ID可能导致NSIS Installer额外安装新版本应用程序副本

### ISSUE THREAD

**Issue by Yanlin-Duanmu** [agalwood/Motrix#1477]
[Win10]今天软件升级后发现电脑存在两个motrix，一个是旧版本的在D盘，一个是新版本的静默装到C盘。排查原因发现，是新版本没安装到原来旧版本的目录里面去，所有再C盘又安装了一个，而且没有办法人为指定NSIS Installer的安装路径。

尝试过卸载新版本并重新安装，无论是给所有用户安装还是给仅当前用户安装，都会强制C盘安装。但我记得以前老版本motrix是可以指定D盘为安装路径的，希望不要去掉这个功能。

我一直会把软件安装到D盘，C盘只当作小而精的启动盘，这次更新强制安装到C盘，应该会给像我这样的用户带来了一些困扰，不知能否将指定安装路径的功能恢复呢？

PS：两年后的突然更新，有些惊喜，感谢作者依旧维护。

**Comment by agalwood** [comment]
实测官网提供的 Motrix-Setup-1.8.19.exe 可以更改安装路径呀

![setup_dir](https://user-images.githubusercontent.com/1032175/236589891-3337d854-8ba5-4d44-b28a-752b264fabe5.png)

**Comment by Yanlin-Duanmu** [comment]
Hum，这个界面我没有遇见诶。我是通过以下界面弹出的界面升级的。大致这个样子。
![image](https://user-images.githubusercontent.com/68236504/236593676-a1b4e790-bcc6-4eee-bed3-2acb5456c55f.png)
选择更新后，安装页面是这样的：
![image](https://user-images.githubusercontent.com/68236504/236593827-9513c40b-eba9-426c-bb03-3d46f2ad9909.png)
下一步后就直接进入了安装界面，如下，并没有您展示的路径选择页面，不是太清楚哪里出现了问题。
![image](https://user-images.githubusercontent.com/68236504/236593895-cf278cbe-daa1-4376-8e6a-91ca77910cf4.png)
![image](https://user-images.githubusercontent.com/68236504/236593925-317f1bad-1a45-4202-b7f6-1c5286055a43.png)
经测试，从https://motrix.app/download官网下载的NSIS Installer，同样出现了上述问题，原因尚不清晰。如有需要，可以为您提供更多环境信息。

**Comment by Yanlin-Duanmu** [comment]
[补充] 同时存在的两个Motrix示意如下，左侧为Ver1.8.19，右侧为Ver1.6.11：
![image](https://user-images.githubusercontent.com/68236504/236594112-5c88c856-99ad-4b30-882c-dcd56cf75285.png)
希望该信息对您有所帮助。

**Comment by Yanlin-Duanmu** [comment]
好的，谢谢您。不过您能否告诉我Motrix的用户配置文件是下图中的哪些？我想保留它们再卸载，这样可以避免重复进行应用设置。
![image](https://github.com/agalwood/Motrix/assets/68236504/f9529332-143b-4223-9a6a-315bbaebd15f)

**Comment by agalwood** [comment]
配置文件不在你图中这个目录，你打开 Motrix 偏好设置-进阶设置-拉到页面底部，有个`下载会话路径`，点击后面的文件夹图标，就可以看到 Motrix 的配置文件目录了，把`system.json`、`user.json`、`download.session`、`dht.data`、`dht6.dat`备份一下，想偷懒的话也可以直接备份这整个目录。

**Comment by Yanlin-Duanmu** [comment]
完全卸载所有版本并重启后，尝试重新安装，出现下方页面，允许自定义路径，问题解决。感谢您的帮助！
![image](https://github.com/agalwood/Motrix/assets/68236504/d2138397-7e42-4940-9861-1437b4c58a15)

**Comment by Yanlin-Duanmu** [comment]
**For English version, please scroll down**
**问题**
新APP Bundle ID可能导致NSIS Installer额外安装新版本应用程序副本

**解决方案**
完全卸载所有版本，重新安装最新版本，即可选择安装路径，且不会出现副本应用程序。卸载前请注意保留用户数据。

**注意**
用户数据可通过以下方式找到。“`Motrix 偏好设置-进阶设置-拉到页面底部-下载会话路径`”，点击后面的文件夹图标，就可以看到 Motrix 的配置文件目录了，把`system.json`、`user.json`、`download.session`、`dht.dat`、[`dht6.dat`]备份一下。展示如图。实际操作可能没有`dht6.dat`文件，属正常情况。也可不备份这四个文件，转而备份这四个文件所在的整个文件夹，这一样可行。
![image](https://github.com/agalwood/Motrix/assets/68236504/b40e63ad-5091-4ecd-ba3c-503d3e285f70)

---

**English version:**
**Issues**
New APP Bundle ID may cause NSIS Installer to install an additional copy of the new version of the application.

**Solution**
Completely uninstall all versions and reinstall the latest version, then you can select the installation path and no copy application will appear. Please be careful to retain user data before uninstalling.

**Notice**
User data can be found in the following ways. "`Motrix Preferences - Advanced Settings - Pull to the bottom of the page - Download Session Path`", click the folder icon behind, you can see the Motrix configuration file directory, put `system.json`, `user.json`, `download. session`, `dht.dat`, [`dht6.dat`] and backup them. The display is as shown. There may be no `dht6.dat` file, which is normal. Instead of backing up these four files, you can back up the entire folder where these four files are located, which will work just as well.
![image](https://github.com/agalwood/Motrix/assets/68236504/b40e63ad-5091-4ecd-ba3c-503d3e285f70)
