### ISSUE TITLE
[BUG]: 自从更新了 Version 1.8.19  引擎版本 1.36.0 磁力和bt都不动了

### ISSUE THREAD

**Issue by lvtao-net** [agalwood/Motrix#1484]
### Bug 描述

[BUG]: 自从更新了 Version 1.8.19  引擎版本 1.36.0 磁力和bt都不动了

### Motrix 版本

Version 1.8.19

### 环境

System:
    OS: macOS 12.6.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 549.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm

### 复现步骤

不论是直接使用bt文件，还是使用磁力链接，都不动了

### 验证

- [X] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [X] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by XM-HAQ** [comment]
我也碰到这个问题了

**Comment by laonuodr** [comment]
me too  真蛋疼

**Comment by laonuodr** [comment]
win11也不行

**Comment by Zer0xPoint** [comment]
同样遇到

**Comment by TroyEdwardLee** [comment]
Mac也是同样的问题，本来已经把迅雷卸载了，看来还得装回来继续忍受迅雷的恶心广告与限速

**Comment by livinghub** [comment]
普通下载也没速度

**Comment by shmilyyan** [comment]
me too

**Comment by Ted8000** [comment]
same

**Comment by spirodelazz** [comment]
me too

**Comment by ShawnKid** [comment]
me too

**Comment by ShawnKid** [comment]
哥们儿，我解决问题啦，你查看一下有没有打开其他带有aria2的软件，有冲突就下载不了了，需要关闭其他Aria2软件！

**Comment by Cecilia1026** [comment]
我也遇到了，而且进程中只有motrix一个程序打开了aria2进程。

**Comment by lvtao-net** [comment]
我没有其它的aria2软件，不过我重装过系统后，再用它就又正常，并且还是那些不动的资源，它动了....就很奇怪
