### ISSUE TITLE
从后台调到前台页面缺少

### ISSUE THREAD

**Issue by hegithub24** [agalwood/Motrix#149]
![image](https://user-images.githubusercontent.com/12218993/54468447-924b8e80-47c7-11e9-9215-b5aa01cc56ca.png)

**Comment by agalwood** [comment]
升级到 [v.1.2.2](https://github.com/agalwood/Motrix/releases/tag/v1.2.2) 试试，或者请按照以下模板提 issue
https://github.com/agalwood/Motrix/issues/new?assignees=&labels=&template=bug_report_cn.md&title=
