### ISSUE TITLE
希望增加window隐藏菜单栏

### ISSUE THREAD

**Issue by LouisYLWang** [agalwood/Motrix#15]
window的顶部菜单栏实在不美观，可否考虑Menu.setApplicationMenu(null)一下或者改成tab开启/关闭菜单栏

**Comment by agalwood** [comment]
Menu.setApplicationMenu(null)之后应用的键盘快捷键也会受到影响，我考虑过用 frame: false来搞

**Comment by agalwood** [comment]
因为正在做i18n处理，代码改动量较大，这个特性也放到 https://github.com/agalwood/Motrix/tree/feature/i18next_201901042000
这个分支上一起开发了，所以这个特性发布会晚一些：P

**Comment by jingle0927** [comment]
linux上面的菜单栏可以去掉吗？

**Comment by agalwood** [comment]
@jingle0927 需要测试 Linux 下 frame: false 的效果再看要不要把这个 Windows 版专属功能开放给 Linux，希望帮忙可以提供截图
https://github.com/agalwood/Motrix/pull/17#issuecomment-454828197

**Comment by liuwenhuan** [comment]
![image](https://user-images.githubusercontent.com/6106120/52386807-83840480-2ac2-11e9-9411-99cbc4e6df05.png)
在deepin下面标题栏不能隐藏，不美观。另外官网的deb包安装后，在任务栏上没有图标（可以看到最下面任务栏上的齿轮默认图标），暂不确认是软件的问题，还是deepin的问题。

**Comment by liuwenhuan** [comment]
更新到1.1.3以后，任务栏图标正常了。但是设置隐藏菜单和标题栏选项没有效果。

**Comment by agalwood** [comment]
测试不充分，翻车了🙃
https://github.com/agalwood/Motrix/issues/54
