### ISSUE TITLE
加密 DNS（DoQ、DoT 和 DoH 等）

### ISSUE THREAD

**Issue by cherinyy** [agalwood/Motrix#1509]
**请描述一下你的新功能请求是否与已知问题有关？**
由于某些泄露的数据库样本通过 BitTorrent 网络传播，BitTorrent DHT 的 Bootstrap Node 域名 DNS 解析记录曾经在中国内地被投毒过。
目前 Motrix 使用的 `dht.transmissionbt.com` 和大部分  Bootstrap Node 域名已恢复正常，只剩下 `router.bittorrent.com` 的 AAAA 记录（IPv6）仍然处于污染状态。
为了预防后续情况再次出现，希望能够在 Motrix 添加对于加密 DNS 的支持，因为部分 Tracker 域名也处于污染状态。
UDP 无 RST，所以只要 DNS 解析记录正确即可正常连接。

**描述你想要的解决方案**
Motrix 添加对于加密 DNS 的支持。

**描述你考虑过的替代方案**
提供内置 HOSTS 功能。

**更多信息**
相关 issue：#1444

**Comment by Numieo** [comment]
可以在系统里配置加密dns程序
https://github.com/AdguardTeam/dnsproxy
如`dnsproxy -l 127.0.0.1 -p 53 -u h3://1.1.1.1/dns-query --cache --cache-size=65536 --cache-optimistic`
dns改为127.0.0.1

**Comment by cherinyy** [comment]
> 可以在系统里配置加密dns程序 https://github.com/AdguardTeam/dnsproxy 如`dnsproxy -l 127.0.0.1 -p 53 -u h3://1.1.1.1/dns-query --cache --cache-size=65536 --cache-optimistic` dns改为127.0.0.1

我就是不想实现系统级的，因为这玩意需要合理配置，如果要搞系统级的，我完全可以在路由器上部署 [mosdns](https://github.com/IrineSistiana/mosdns).
