### ISSUE TITLE
chrome的插件，为什么不能上传至商店？这让我很不理解

### ISSUE THREAD

**Issue by mapleshadow** [agalwood/Motrix#151]
没有这个插件，该应用等同于废的，至少百度网盘是如此，为什么不上传插件至chrome商店呢？

**Comment by agalwood** [comment]
老铁，你提 issue 为什么不先搜索一下？这让我很不理解
https://github.com/agalwood/Motrix/issues/96

**Comment by mapleshadow** [comment]
好吧我道歉。。。。。
