### ISSUE TITLE
界面部分字词错误

### ISSUE THREAD

**Issue by YangHanlin** [agalwood/Motrix#154]
**错误描述**
Motrix 1.1.3 中，“新建任务”界面中的“User-Agent”误为“存储路径”。

**如何重现**
*注：可以在下文“截图”一节中查看复现问题步骤的每一步截图。*
1. 在 Motrix 主界面中，点击“新建任务”按钮（即左边栏加号图标）；
2. 勾选“高级选项”，查看“User-Agent“一栏；
3. 发现此文本框左侧的标签为“存储路径”，而非“User-Agent”或“UA”。

**预期的行为**
文本框左侧的标签应当是“User-Agent”或“UA”，以与文本框提示语对应，也与实际用途对应。

**截图**
*第 1 步*
![图片](https://user-images.githubusercontent.com/8692892/54819869-2fcb2480-4cd8-11e9-93fc-364146bd6e59.png)
*第 2 步*
![图片](https://user-images.githubusercontent.com/8692892/54819901-50937a00-4cd8-11e9-8584-29d186737265.png)
*第 3 步*
![图片](https://user-images.githubusercontent.com/8692892/54819938-73be2980-4cd8-11e9-962a-f35f9035058a.png)

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： Windows 10 版本 1903 (OS 版本 18358.1)
 - Motrix 版本： v1.1.3
 - 安装包类型：exe 安装程序

**更多信息**
**请注意：本问题不仅在中文界面下出现，也在英文界面下出现。不仅在添加链接任务时出现，也在添加种子任务时出现。**
以下是英文界面中出现问题的界面截图：
![图片](https://user-images.githubusercontent.com/8692892/54820046-cdbeef00-4cd8-11e9-8f9a-61cade45bfaf.png)

**Comment by agalwood** [comment]
感谢反馈，不过这是已修复的bug #59，新版本即将发布: D
