### ISSUE TITLE
Use different icons for "Maximize" and "Restore"

### ISSUE THREAD

**Issue by YangHanlin** [agalwood/Motrix#155]
**Is your feature request related to a problem? Please describe.**
When the `Preferences > Advanced > Hide App Menu (Windows & Linux Only)` is selected, the menu bar will not really hide (*I know it is a bug and will be fixed in the next release*), but the customized buttons for minimizing, maximizing and closing window appear (as is shown in the following screenshot).
![图片](https://user-images.githubusercontent.com/8692892/54820812-56d72580-4cdb-11e9-9f83-83a1878a5a8d.png)
The buttons work perfectly, but **the button for "Maximize" and "Restore" (i.e. the middle of the three buttons) does not change its appearance when the window changes between maximized window and a window of normal size**.

**Describe the solution you'd like**
Given that the button used currently causes user to think of "Maximize", I think it may be good to **use another icon for the action "Restore"**, just as VS Code, another app based on Electron, does:
![图片](https://user-images.githubusercontent.com/8692892/54821158-555a2d00-4cdc-11e9-87d1-6b1755fe05bb.png)
![图片](https://user-images.githubusercontent.com/8692892/54821172-5db26800-4cdc-11e9-80c9-3fb43df614c4.png)

**Describe alternatives you've considered**
None. (I think it is easy to use another icon for the action "Restore".)

**Additional context**
None.

PS: I think it will be better to provide a Chinese feature request template, just like bug reports.

**Comment by agalwood** [comment]
Maintaining the maximized state of the window is a bit cumbersome, and the state is easily inconsistent with the actual situation, such as manually adjusting the size of the form.
I don't want to implement this feature now.
Providing the Chinese version of the bug report issue template is a helpless, : (

**Comment by YangHanlin** [comment]
That's right. Thank you anyway for your effort devoted in the development of Motrix 🙂
