### ISSUE TITLE
README 和官网上几处错误拼写

### ISSUE THREAD

**Issue by stevenlele** [agalwood/Motrix#156]
如题，有几处错误拼写，将 Motrix 拼为 Motrix。

[/README-CN.md](https://github.com/agalwood/Motrix/blob/master/README-CN.md) 中……
> **Motirx** 是一款全能的下载工具，支持下载 HTTP、FTP、BT、磁力链、百度网盘等资源。它的界面简洁易用，希望大家喜欢 👻。

[官网的关于页面](https://motrix.app/zh-CN/about)中……
> **Motirx** 是一款全能的下载工具，支持下载 HTTP、FTP、BT、磁力链、百度网盘等资源。它的界面简洁易用，希望大家喜欢 👻。
> 我在 2018/12/19 开源了 **Motirx**（基于 MIT协议），欢迎大家 Fork 和 PR， GitHub Repo

^ 顺带一提，MIT 和协议之间漏了一个空格。

**Comment by agalwood** [comment]
已修正，谢谢
