### ISSUE TITLE
Creating .torrent files

### ISSUE THREAD

**Issue by alexwender1** [agalwood/Motrix#157]
**Describe the bug**
When you add magnetic links in Motrix, the application creates .torrent files in the storage location of these links.

Other applications of the genre, download normally, without creating any unnecessary file.

**Expected behavior**
The application downloads without creating .torrent files.

**Screenshots**
![Captura de Tela_selecionar área_20190324205351](https://user-images.githubusercontent.com/45263160/54887932-f977db80-4e76-11e9-9bf8-3079ca8e0e43.png)

**Environment (please complete the following information):**
 - OS & Version: Deepin 15.9.2 Beta
 - Motrix Version: 1.2.2
 - Installation package type: .AppImage

**Additional context**
This anomaly has occurred since earlier versions.

**Comment by agalwood** [comment]
This is not a bug, you can turn it off by modifying Motrix's system configuration `system.json` by adding the following options:

`bt-save-metadata=false`

**Comment by agalwood** [comment]
Forgot to say the path of `system.json`
You can open Motrix's Preferences - Advanced, then click on the folder icon to the right of the input box of the `download.session` and you will find `system.json` in the opened directory.

**Comment by alexwender1** [comment]
Motrix is creating 2 extra files for each download / torrent.

Files with the extension ".torrent" and ".aria2". Is there a possibility that Motrix does not create these files natively?

Since there is Magnetic Link sharing by Motrix, I do not see why the creation of such files.

![Captura de Tela_selecionar área_20190424160859](https://user-images.githubusercontent.com/45263160/56688041-0e31d400-66ae-11e9-9406-2cf8820ece73.png)
