### ISSUE TITLE
Download Speed Limit

### ISSUE THREAD

**Issue by alexwender1** [agalwood/Motrix#158]
**Is your feature request related to a problem? Please describe.**
I can not use Motrix in the background because the application uses all my internet bandwidth.

**Describe the solution you'd like**
Allow user to adjust internet bandwidth usage; defining global values ​​in the application.

**Additional context**
This "animation" could display a popup for the user to set limits on download speed.
![Captura de Tela_selecionar área_20190324211303](https://user-images.githubusercontent.com/45263160/54888202-cedb5200-4e79-11e9-8b61-eedef80e5dd5.png)

**Comment by agalwood** [comment]
Yes, I am planning this, and future versions will implement it : D
