### ISSUE TITLE
希望恢复Dock栏的下载速率显示

### ISSUE THREAD

**Issue by chxsong** [agalwood/Motrix#1582]
**请描述一下你的新功能请求是否与已知问题有关？**
无

**描述你想要的解决方案**
在过去的版本中（例如1.16.11），Motrix可以在Dock栏显示下载速率，然而最新的版本只能选择在menu bar显示下载速率。希望恢复该功能，或者添加一个选项让用户自选是否在Dock栏显示下载速率。

**描述你考虑过的替代方案**

**更多信息**

**Comment by Momo-ProMax** [comment]
你说的是mac端吗？可以显示速率啊。顺便说一句，这个项目bug怎么这么多啊

**Comment by chxsong** [comment]
你说得对，是我弄错了，要在设置里打开 Motrix 的通知权限。
