### ISSUE TITLE
update to aria2 1.37.0

### ISSUE THREAD

**Issue by mokurin000** [agalwood/Motrix#1590]
title says all

**Comment by jasonliul** [comment]
Oh, second the motion.

**Comment by necros2k7** [comment]
@poly000  why closed?

**Comment by mokurin000** [comment]
> @poly000 why closed?

There is no API breaking update, so users could replace aria2 to newer version theirself

**Comment by necros2k7** [comment]
@poly000 I did and it doesn`t work (Fetching error while adding file link to download)

**Comment by lisansas** [comment]
> @poly000我做了，但不起作用（添加文件链接下载时获取错误）

same here,have you solved?
