### ISSUE TITLE
系统托盘图标有点丑

### ISSUE THREAD

**Issue by zxj930057911** [agalwood/Motrix#161]

**Comment by youtiaoguagua** [comment]
那个win托盘图标是个八边形嘛？

**Comment by agalwood** [comment]
老铁，你们能吐槽的时候带上截图么？

**Comment by youtiaoguagua** [comment]
> 老铁，你们能吐槽的时候带上截图么？
> https://www.yuque.com/moapp/help/release-1.2

![image](https://user-images.githubusercontent.com/30404329/55051257-40d8b480-508f-11e9-861d-d9e18c8e2f2d.png)

**Comment by agalwood** [comment]
这是我 Windows 下使用的托盘图标，为啥在你们屏幕上会显示成那样。。。

常规状态
<img src="https://cdn.nlark.com/yuque/0/2019/png/129147/1553318589282-28796583-44d6-49bb-aed3-6b97eac05e85.png" width="24" height="24" alt="mo-tray-colorful-normal.png" />

下载状态
<img src="https://cdn.nlark.com/yuque/0/2019/png/129147/1553318745352-40352486-7038-4b24-8887-7949aca63897.png" width="24" height="24" alt="mo-tray-colorful-active.png" />

**Comment by youtiaoguagua** [comment]
> 这是我 Windows 下使用的托盘图标，为啥在你们屏幕上会显示成那样。。。
> 
> 常规状态
> <img alt="mo-tray-colorful-normal.png" width="24" height="24" src="https://camo.githubusercontent.com/2ce2e3fd0ee442d2eab1971cc7fc685682a64aad/68747470733a2f2f63646e2e6e6c61726b2e636f6d2f79757175652f302f323031392f706e672f3132393134372f313535333331383538393238322d32383739363538332d343464362d343962622d616564332d3662393765616330356538352e706e67">
> 
> 下载状态
> <img alt="mo-tray-colorful-active.png" width="24" height="24" src="https://camo.githubusercontent.com/2826be19b0a54e842d5105b0cc3fcc933d3a23fe/68747470733a2f2f63646e2e6e6c61726b2e636f6d2f79757175652f302f323031392f706e672f3132393134372f313535333331383734353335322d34303335323438362d373033382d346232342d383838372d3739343961636136333839372e706e67">
可能我用的是压缩版吧

**Comment by agalwood** [comment]
@youtiaoguagua 那你试下安装版？

还有你们都没说你们 Windows 什么版本的

**Comment by youtiaoguagua** [comment]
> @youtiaoguagua 那你试下安装版？
> 
> 还有你们都没说你们 Windows 什么版本的

win10 1809，安装版也一样

**Comment by agalwood** [comment]
Win 10环境我之前虚拟机和实体机都测试过显示正常显示的...orz

**Comment by youtiaoguagua** [comment]
> Win 10环境我之前虚拟机和实体机都测试过显示正常的...orz

知道了是缩放问题，我15寸笔记本缩放100%是那个八边形，120%就没问题了

**Comment by agalwood** [comment]
![image](https://user-images.githubusercontent.com/1032175/55052173-eb060b80-5092-11e9-81a6-6daf374d1562.png)

**Comment by youtiaoguagua** [comment]
知道了是缩放问题，我15寸笔记本缩放100%是那个八边形，120%就没问题了

**Comment by zxj930057911** [comment]
Mac下的状态栏图标是一个长条，可以设计成一个灰色的正常图标吗？因为我现在在实验室没带Mac还没办法截图

**Comment by jackytang** [comment]
mac下的状态栏图标在暗色模式下都看不清有个图标在那里，只显示了一个小绿点

**Comment by agalwood** [comment]
@jackytang 这版本的 tray 忘记做 Mojave 暗黑模式的适配了

**Comment by agalwood** [comment]
Motrix v1.3.x 做了深色模式的适配，请更新版本 https://github.com/agalwood/Motrix/releases
@jackytang
