### ISSUE TITLE
建议发布到Snap商店

### ISSUE THREAD

**Issue by iblader** [agalwood/Motrix#162]
我看到release里面已经构建了snap包，不知道是否可以考虑将Motrix发布到snap商店（https://snapcraft.io/store），这样更新起来会方便很多。

**Comment by agalwood** [comment]
前天已经提交，机器审核时提醒包里含有 aria2c 的可执行文件…
感觉要走人工审核 : (

**Comment by iblader** [comment]
发布为classic的应用貌似都需要经过人工审核的

**Comment by Lin-Buo-Ren** [comment]
Snap 打包者路過，請問是什麼原因需要用典型權限限縮(classic-confinement)呢？

**Comment by agalwood** [comment]
@Lin-Buo-Ren 我不大了解 Snap 的生态，Motrix 使用 electron-builder 作为打包工具，在 Travis CI 构建的 Snap 包，然后我就拿 GitHub 上的 Snap 包去提交了

PS. Motrix 内部集成了 aria2c

> Automated review for version 1.2.2: warning
1 Warning
Found files with executable stack. This adds PROT_EXEC to mmap(2) during mediation which may cause security denials. Either adjust your program to not require an executable stack, strip it with 'execstack --clear-execstack ...' or remove the affected file from your snap. Affected files: resources/engine/aria2c functional-snap-v2_execstack

**Comment by Lin-Buo-Ren** [comment]
Execstack 的问题可以参阅 [Snap and executable stacks - doc - snapcraft.io](https://forum.snapcraft.io/t/snap-and-executable-stacks/1812)

不过我目前不确定以 electron-builder 作为 Snap 包建构工具要怎么处理。

**Comment by Lin-Buo-Ren** [comment]
https://forum.snapcraft.io/t/snap-and-executable-stacks/1812/3

> AIUI, newer versions of electron-builder will no longer generate files with an executable stack.
> Furthermore, snapcraft 2.40 clears files with execstack automatically (displaying a warning about what it is doing).

**Comment by agalwood** [comment]
@Lin-Buo-Ren Motrix v1.2.2 使用的 electron-builder 是 v20.38.5 的，我尝试升级到 v20.39.0
但是升级之后 build 时会报 fsevents 的错，所以就没升级了

`node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.7/fse-v1.2.7-electron-v4.1-darwin-x64.tar.gz`

**Comment by Lin-Buo-Ren** [comment]
大概是这个议题：https://github.com/electron-userland/electron-builder/issues/3618

可能相关：[记一次前端VUE项目启动错误，vue项目npm install 时报错 - Jayslife的专栏 - CSDN博客](https://blog.csdn.net/Jayslife/article/details/84447604)

**Comment by agalwood** [comment]
这个 issue 我看过，也试过用以下命令解决，但是会和我 CI 使用的 Node 版本冲突，所以又移除了
`npm i --save-dev node@8.15.0`

**Comment by agalwood** [comment]
刚刚尝试升级 electron-builder 到 v20.39.0，发现现在 build 正常了...orz

**Comment by agalwood** [comment]
@Lin-Buo-Ren 提交到 Snapcraft 之后报了同样的问题：

> Found files with executable stack. This adds PROT_EXEC to mmap(2) during mediation which may cause security denials. Either adjust your program to not require an executable stack, strip it with 'execstack --clear-execstack ...' or remove the affected file from your snap. Affected files: resources/engine/aria2c functional-snap-v2_execstack

**Comment by Lin-Buo-Ren** [comment]
你這個是 electron 以外的程序(`aria2c`)有 execstack，看看能不能如同 <https://github.com/electron-userland/electron-builder/issues/2608#issuecomment-366898619> 所說的那樣用 afterPack hook 來自行清除

**Comment by agalwood** [comment]
已发布到 snapcraft
https://snapcraft.io/motrix
