### ISSUE TITLE
下载ed2k问题

### ISSUE THREAD

**Issue by TeemoDong** [agalwood/Motrix#163]
想下载MSDN里面的Office2016，复制ed2k到Motrix里想下载，提示“下载发生错误”。是软件暂不支持，还是我操作有误？
附链接：ed2k://|file|cn_office_professional_plus_2016_x86_x64_dvd_6969182.iso|2588266496|27EEA4FE4BB13CD0ECCDFC24167F9E01|/

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/14
