### ISSUE TITLE
[BUG]: 1.8.19的版本aria2下载可能存在异常。

### ISSUE THREAD

**Issue by Malygoslight** [agalwood/Motrix#1648]
### Bug 描述

我一般使用aria2下载文件或网盘直链，但是没速度且连接数卡在1。猜测应该不是网络问题，因为小白羊盘下载也是用aria2，调用motrix没速度，使用自带的aria2满速。(尝试过覆盖安装，没有解决。)

### Motrix 版本

Windows11 专业版23H2 Motrix版本1.8.19，引擎版本1.36.0，安装版。

### 环境

无

### 复现步骤

小白羊盘调用无速度，使用内置满速。

### 验证

- [ ] 遵循我们的[行为准则](https：//github.com/agalwood/Motrix/blob/master/CODE_OF_CONDUCT.md)
- [ ] 确认是否已经有一个报告了相同的 Bug，以避免创建重复的问题。
- [X] 确认此问题是一个具体的 Bug。若要进行问答，请开启 [GitHub 讨论](https://github.com/agalwood/Motrix/discussions)。
- [X] 提供的复现是该 Bug 的 [最小复现例子](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Cecilia1026** [comment]
在我的windows上也有相同的问题，但在linux端没有问题。

**Comment by deardeer7** [comment]
我也遇到这个情况了，调用motrix的aria2一点下载不动，不是很明白，我是用alist调用motrix的aria2下载阿里云盘文件

**Comment by PaiHL** [comment]
查看一下 aria2 的版本是多少

**Comment by Malygoslight** [comment]
版本是1.36.0.
![image](https://github.com/agalwood/Motrix/assets/74966344/4345f55e-411c-413a-a211-c21ad855371a)

**Comment by Malygoslight** [comment]
目前似乎回复问题了，具体原因为止。
