### ISSUE TITLE
Windows版本顶部菜单栏

### ISSUE THREAD

**Issue by WanYanYueCong** [agalwood/Motrix#165]
windows上1.2.2版本的顶部菜单栏是没有改进还是bug，我的还是上一个版本的样子
![image](https://user-images.githubusercontent.com/47966397/55135399-8a480300-5166-11e9-946f-f008df42ffd8.png)

**Comment by agalwood** [comment]
偏好设置-进阶设置-界面-隐藏菜单栏
启用，保存并应用
