### ISSUE TITLE
deepin下无法使用右键菜单退出程序

### ISSUE THREAD

**Issue by AppJ-GS** [agalwood/Motrix#167]
**错误描述**
在deepin上右键退出后仍存在进程，需要kill解决

**如何重现**
重现步骤，如：
1. 点击右键
2. 退出程序
3. 之后无法点击右键，仍存在进程

**预期的行为**
查看是否本人的OS错误

**截图**

![DeepinScreenshot_Desktop_20190330172203](https://user-images.githubusercontent.com/39146681/55274325-2c581e80-5312-11e9-996a-d63f04f90ad3.png)
![DeepinScreenshot_20190330172242](https://user-images.githubusercontent.com/39146681/55274326-2c581e80-5312-11e9-91e9-91c204981356.png)

**运行环境**
 - 操作系统类型： Linux
 - 具体版本： deepin 15.9.2
 - Motrix 版本： v1.2.2
 - 安装包类型：deb

**Comment by agalwood** [comment]
偶现问题，暂时没想到怎么解决，只能先进程管理手动杀进程了

**Comment by agalwood** [comment]
请升级到 v1.3.x 版本试试
https://github.com/agalwood/Motrix/issues/198#issuecomment-487298823
