### ISSUE TITLE
希望能加个功能，bt下载时可以自由选择文件下载

### ISSUE THREAD

**Issue by 1073661215** [agalwood/Motrix#168]
我觉得Motrix很好，但是在bt下载的时候都是完全下载的，不知道是否我没找到这个选项，如果没有的话，希望可以添加这个功能。

**Comment by agalwood** [comment]
待开发
https://trello.com/c/lzlwEmhn

**Comment by Leirgo** [comment]
> 我觉得Motrix很好，但是在bt下载的时候都是完全下载的，不知道是否我没找到这个选项，如果没有的话，希望可以添加这个功能。

同求此功能……

**Comment by agalwood** [comment]
Motrix v1.4.x 已经实现这个特性了，请更新到最新版本

https://github.com/agalwood/Motrix/releases
