### ISSUE TITLE
Don't want to see desktop integration tips when AppImage starts

### ISSUE THREAD

**Issue by 420116199208022715** [agalwood/Motrix#171]
![image](https://user-images.githubusercontent.com/44076708/55525729-cb8b6600-56c4-11e9-82d9-49352000d0da.png)

I don't want to see this, I just want to be a portable program.

**Comment by agalwood** [comment]
For this problem, most users of appimage have no feedback, so I may not change it at the moment. However, you can download the source code, refer to the following issue, modify the package.json to build your own.

https://github.com/electron-userland/electron-builder/issues/1962
