### ISSUE TITLE
修改设置之后，保存会重启软件

### ISSUE THREAD

**Issue by hlfshy** [agalwood/Motrix#172]
Version 1.2.2
修改设置之后，保存会重启软件，这个是设计成这样还是BUG？

一般来说，除非大的配置修改，普通小改动，软件不应该会重启吧。。。

另外是否可以做个开关，开启/关闭 悬浮窗显示网速和进度的功能呢？

**Comment by agalwood** [comment]
目前就是这么设计的，由于之前设置的逻辑设计，没有分离好哪些设置需要重启，所以现在是每次修改设置都会重启应用。

悬浮窗暂无计划
