### ISSUE TITLE
建议 加一个取消全部下载链接  的功能下载很多文件的要一个个取消 很麻烦

### ISSUE THREAD

**Issue by keyadd** [agalwood/Motrix#174]
建议 加一个取消全部下载链接  的功能下载很多文件的要一个个取消 很麻烦  在下载文件前加个选择框   大兄弟 软件狠不错 在linux下用的很顺手 同为程序员表示 谢谢啦      
![Screenshot from 2019-04-04 20-44-25](https://user-images.githubusercontent.com/19481784/55557230-fa80f680-571b-11e9-95d1-c496d8e16062.png)

**Comment by agalwood** [comment]
计划在下一版本里重构任务列表，预计会支持一些批量操作

不过最近比较忙，暂无具体时间点：P

**Comment by ChenyangGao** [comment]
对，这个功能确实很需要

**Comment by Planarians** [comment]
真的很需要这个功能 百度网盘的文件夹里有时候都有几百个文件 到了motrix就会变成几百个任务 一个个点确实很不现实 或者能直接归类到一个任务里也行

**Comment by agalwood** [comment]
已添加了鼠标拖拽选中任务批量删除功能，请更新 Motrix 到 v1.5.x 版本https://github.com/agalwood/Motrix/releases

**Comment by singularity2000** [comment]
> 已添加了鼠标拖拽选中任务批量删除功能，请更新 Motrix 到 v1.5.x 版本https://github.com/agalwood/Motrix/releases

你这个做了跟没做一样，蓝色矩形选中框，一滚动鼠标就被光标甩掉，分离到上面去了
