### ISSUE TITLE
下载到一半自动停止

### ISSUE THREAD

**Issue by NaixHw** [agalwood/Motrix#175]
度盘打开的链 无论大小下到一半就跳到已停止 按法恢复无效 复制链接到IDM还可以用 希望能修复如果可以的话

**Comment by agalwood** [comment]
https://www.yuque.com/moapp/help/extensions#9414e50b
如果按文档无法解决，请按照以下格式提issue：
https://github.com/agalwood/Motrix/issues/new?assignees=&labels=&template=bug_report_cn.md&title=
