### ISSUE TITLE
文件下载完全但是任务没有结束

### ISSUE THREAD

**Issue by alexjml** [agalwood/Motrix#179]
**错误描述**
文件下载完全但是任务没有结束

**如何重现**
重现步骤，如：
1. 种子文件上选择使用motrix打开
2. 提交下载，开始任务
3. 等文件下载完全，例如22.4MB/22.4MB，会通知下载完成，但该任务仍在下载状态
4. 检查下载好的文件，并没有损坏

**预期的行为**
任务跳转为完成或停止

**截图**
![Screen Shot 2019-04-08 at 14 21 46](https://user-images.githubusercontent.com/6121045/55702724-09acc080-5a0a-11e9-81be-f3bfdfac5fd8.png)

**运行环境**
 - 操作系统类型： macOS
 - 具体版本： macOS 10.13.6
 - Motrix 版本： v1.2.2
 - 安装包类型：Homebrew

**更多信息**
无

**Comment by agalwood** [comment]
BT下载完成之后，还会自动做种一段时间，如果你不想做种，可以手动点一次停止任务
https://aria2.github.io/manual/en/html/aria2c.html#aria2.onBtDownloadComplete

**Comment by alexjml** [comment]
@agalwood 👌
