### ISSUE TITLE
希望添加托盘图标

### ISSUE THREAD

**Issue by black2996** [agalwood/Motrix#18]
最小化状态无托盘图标，可以的话建议添加托盘图标或迅雷那样的浮动窗口，uget用多了总是习惯性新建任务就直接关闭。。。。

**Comment by agalwood** [comment]
收到，加到需求池了

**Comment by black2996** [comment]
> 收到，加到需求池了

给力啊，你mac可能不觉得，linux实在是缺全能美观的下载工具，我觉得这个放到snap store说不定会火

**Comment by agalwood** [comment]
最新版v1.2.x 已实现
https://github.com/agalwood/Motrix/releases/tag/v1.2.2
