### ISSUE TITLE
官网无法打开

### ISSUE THREAD

**Issue by gexiaosen** [agalwood/Motrix#180]
官网无法打开，百度网盘助手也无法下载

**Comment by agalwood** [comment]
老铁，你网络哪里的？
今天没有监测到服务器宕机和DNS解析异常呀

**Comment by gexiaosen** [comment]
上海电信的网络
[cid:image003.png@01D4EF06.086A6660]

发送自葛孝森

________________________________
发件人: Dr_rOot <notifications@github.com>
发送时间: Tuesday, April 9, 2019 6:54:25 PM
收件人: agalwood/Motrix
抄送: gexiaosen; Author
主题: Re: [agalwood/Motrix] 官网无法打开 (#180)


老铁，你网络哪里的？
今天没有监测到服务器宕机和DNS解析异常呀

―

**Comment by agalwood** [comment]
现在还是访问不了么？

**Comment by gexiaosen** [comment]
是的呢，你自己这边能打开吗 是不是因为我上班的这个地方屏蔽了这个网站？但是也不应该啊

发送自葛孝森

________________________________
发件人: Dr_rOot <notifications@github.com>
发送时间: Tuesday, April 9, 2019 7:00:15 PM
收件人: agalwood/Motrix
抄送: gexiaosen; Author
主题: Re: [agalwood/Motrix] 官网无法打开 (#180)


现在还是访问不了么？

―

**Comment by agalwood** [comment]
是的呀……你试下手机4g能否访问？

**Comment by gexiaosen** [comment]
得嘞 谢谢了  4G网络能访问

发送自葛孝森

________________________________
发件人: Dr_rOot <notifications@github.com>
发送时间: Tuesday, April 9, 2019 7:14:51 PM
收件人: agalwood/Motrix
抄送: gexiaosen; Author
主题: Re: [agalwood/Motrix] 官网无法打开 (#180)


是的呀……你试下手机4g能否访问？

―
