### ISSUE TITLE
Bug report: Windows size resized to default after restarting the app

### ISSUE THREAD

**Issue by sayo-melu** [agalwood/Motrix#181]
**Describe the bug**

Windows size resized to default after restarting the app.

For more, it is more elegant to display a smaller window just like [Transmission](https://transmissionbt.com).

**Expected behavior**

It keeps the same size as it was quit.

**Screenshots**

Before restarting

![Screen Shot 2019-04-09 at 15 25 41](https://user-images.githubusercontent.com/16492117/55783500-210aad00-5ae1-11e9-8a44-709cf51351ae.png)

After restarting

![Screen Shot 2019-04-09 at 15 25 49](https://user-images.githubusercontent.com/16492117/55783518-2c5dd880-5ae1-11e9-9f7c-4e8d70c078ed.png)

**Environment:**

 - OS & Version: macOS
 - Version: macOS 10.14.4
 - Motrix Version: 1.2.2
 - Installation package type: Homebrew

**Comment by sayomelu** [comment]
For more, it is more elegant to display a smaller window just like [Transmission](https://transmissionbt.com).

**Comment by agalwood** [comment]
Currently, the size and final position of the window are not saved. When the application starts, the main window is displayed with 1024x768 and centered.

**Comment by sayomelu** [comment]
Would you like to solve this issue?

**Comment by agalwood** [comment]
I think this is not a bug, but a new feature, so I will consider implementing it in the next version.

**Comment by agalwood** [comment]
Done https://github.com/agalwood/Motrix/pull/258
