### ISSUE TITLE
用Chrome装了YAAW之后，一直提示导出下载失败

### ISSUE THREAD

**Issue by szweee** [agalwood/Motrix#182]
不知道哪里的问题。是我还没配置对吗
<img width="254" alt="屏幕快照 2019-04-09 下午4 12 01" src="https://user-images.githubusercontent.com/20777870/55784278-d25e1280-5ae2-11e9-8df8-b33e551d91c3.png">
<img width="340" alt="屏幕快照 2019-04-09 下午4 12 59" src="https://user-images.githubusercontent.com/20777870/55784279-d2f6a900-5ae2-11e9-993e-289068308181.png">
<img width="555" alt="屏幕快照 2019-04-09 下午4 15 31" src="https://user-images.githubusercontent.com/20777870/55784280-d2f6a900-5ae2-11e9-9ff1-b691cdb6c5a3.png">

**Comment by agalwood** [comment]
老铁，你有先启动 Motrix 么？

**Comment by szweee** [comment]
@agalwood 启动了  app一直都没退

**Comment by agalwood** [comment]
你打开终端 Terminal ping一下 localhost 截图看看？要么把配置改成 http://127.0.0.1:16800/jsonrpc 试下
