### ISSUE TITLE
你好，想请教一下，里面的icon中使用的svg是怎么制作成对应的js，有什么快速的方法吗？

### ISSUE THREAD

**Issue by bulolo** [agalwood/Motrix#183]
你好，想请教一下，里面的icon中使用的svg是怎么制作成对应的js，有什么快速的方法吗？

**Comment by agalwood** [comment]
那些 svg icon 的是我一个个手撸成 js 的...

一开始我用了 [vue-awesome](https://github.com/Justineo/vue-awesome) 这个库，但是它对于 [nucleoapp](https://nucleoapp.com/) 导出的 svg 支持不大好「偷懒都用 raw」，所以我就拷贝了[vue-awesome/Icon.vue](https://github.com/Justineo/vue-awesome/blob/master/src/components/Icon.vue) 到项目里改造了一下 [Motrix/Icon.vue](https://github.com/agalwood/Motrix/blob/master/src/renderer/components/Icons/Icon.vue)
