### ISSUE TITLE
关于拖动窗口时的一个小问题

### ISSUE THREAD

**Issue by tottorishu** [agalwood/Motrix#186]
有时候会把界面上的文本框选，然后试图移动窗口，就会出现这个问题:
![`75B $4~4U3W16PH`9EOCGG](https://user-images.githubusercontent.com/40517459/55853168-7357d680-5b92-11e9-9292-5d2da973ee6b.png)
不如给这些文本加上user-select: none?
windows
1.2.2

**Comment by agalwood** [comment]
可以吧，之前做国际化的时候复制文字比较方便就没加，下版本处理

**Comment by agalwood** [comment]
顺手改掉了，待发布 https://github.com/agalwood/Motrix/commit/87440701ab9c137fcebe1220237816abb93554f3
