### ISSUE TITLE
machine size 、buffer size 

### ISSUE THREAD

**Issue by WangLeiGit123** [agalwood/Motrix#187]
I have a few questions. Could you tell me how to modify the appropriate buffer? Or is it necessary to change the buffer size? Whether the size of the buffer is strongly related to the size of the machine ?

**Comment by agalwood** [comment]
I don't understand what you mean, do you mean disk-cache?
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-disk-cache

aria2.conf
macOS:
```
/Applications/Motrix.app/Contents/Resources/engine/aria2.conf
```

Windows:
```
Motrix\resources\engine\aria2.conf
```
