### ISSUE TITLE
English trello, issues and everything else

### ISSUE THREAD

**Issue by mamal72** [agalwood/Motrix#189]
As the project is developed in English language and it's getting a lot of attention at Github, isn't it better to do communications, planning and everything else in English?

**Comment by Kanong017** [comment]
Chinese Speak Chinese
People whose native language is English speak English
No problem.

中国人说中国话
母语为英语的人说英语
没什么问题

@mamal72

**Comment by mamal72** [comment]
@Kanong017 I don't think so. If you want to be connected to the whole community and release something worldwide, you need to use the international language which is English ATM.

I'm also not a native English speaker but as we all know, we need to have the same language to communicate each other.

I was trying to read Trello and contribute, I couldn't. Because everything was Chinese.

I was trying to find out some issues to work on but again, I couldn't. Same reason here too.

That's what I thought.

**Comment by agalwood** [comment]
@mamal72 Thank you for your suggestion. If I have time, I will first translate the todo on trello into English.  

The full English version of the issue on GitHub is still difficult. Motrix has a large number of Chinese users and is a GitHub freshman.  Although the issues submitted by some people are not standardized, I think we cannot completely ignore their voices.

**Comment by mamal72** [comment]
@agalwood Thanks, buddy. Let me know if you need any help except translations as I do not understand even a single char of Chinese. 😅:+1:


Closing for now. Feel free to reopen it if you think we need to. 👍

**Comment by agalwood** [comment]
@mamal72 Most of the items in trello are translated into English.
