### ISSUE TITLE
Persian language translation

### ISSUE THREAD

**Issue by mamal72** [agalwood/Motrix#190]
In order to support Persian language translation, we may need to add support for RTL languages. This feature may be useful for other RTL languages like Arabic.

**Comment by agalwood** [comment]
I tried to support Motrix's layout of RTL and found that the ElementUI used does not support RTL https://github.com/ElemeFE/element/pull/12858. Some UI components have to be manually adapted. It feels that it is not so easy to fully support RTL.

**Comment by agalwood** [comment]
@mamal72  Can you help me classify the languages listed in the electron documentation (https://electronjs.org/docs/api/locales), which ones are RTL?

In addition to judging the language, is there any other way to know that typography is RTL?

**Comment by agalwood** [comment]
I have created a new branch to support rtl. This branch already supports rtl detection. You can fork it to do some UI adaptation.
https://github.com/agalwood/Motrix/tree/feature/rtl_support_201904141414

I don't know the typography habits of rtl.
If you have any suggestions or need help, please tell me: P

**Comment by mamal72** [comment]
@agalwood I'll try to do these this weekend. 👍

**Comment by agalwood** [comment]
Someone submitted it first : |
https://github.com/agalwood/Motrix/pull/235
