### ISSUE TITLE
[1.1.3] 无法进行更新

### ISSUE THREAD

**Issue by smallg0at** [agalwood/Motrix#193]
**错误描述**
旧版本无法正确更新，会报错。不知道在新版本还有没有。

**如何重现**
1. 文件>检查更新
2. 发现更新，是否安装
3. （如图
**预期的行为**
安装更新

**截图**
![image](https://user-images.githubusercontent.com/30719670/55939556-9eb0f300-5c70-11e9-8bc3-de1c344fc949.png)

**运行环境**
 - Windows 10 10.0.18865
 - Motrix 版本： 1.1.3
 - 安装包类型：exe

**更多信息**
无

**Comment by agalwood** [comment]
已修复，nginx 规则写漏了
https://motrix.app/release/Motrix-Setup-1.2.2.exe
