### ISSUE TITLE
无法拦截拦截 Chrome 普通下载任务

### ISSUE THREAD

**Issue by Zhaodoudou** [agalwood/Motrix#196]
**错误描述**
拦截 Chrome 普通下载任务
安装 YAAW for Chrome后，无法下载且报错，windows下YAAW界面与MAC下完全不一样，我配置的JSON-RPC地址，填的和文档一样，其他选项默认的。
**如何重现**
重现步骤，如：
1. 点击右键ARIA2 RPC任务按钮
2. 点击提交
3. 发现报错

**预期的行为**
拦截 Chrome 普通下载任务。

**截图**
http://a3.qpic.cn/psb?/V14C3C0N0S9TdW/fcRyrDD6F38zNkhCpCub*cX3BkgBd51Rxqxj5zcCZwo!/m/dL4AAAAAAAAAnull&bo=QAawBFUIQAYRB9k!&rf=photolist&t=5
http://a3.qpic.cn/psb?/V14C3C0N0S9TdW/DoU.lsO4rO27BTqZ76knq3Hc8b1dI8AANqppYaAoeT8!/m/dLYAAAAAAAAAnull&bo=gAcHBIAHBwQDByI!&rf=photolist&t=5
http://a3.qpic.cn/psb?/V14C3C0N0S9TdW/U6w.yk42MC*1B.zZFcblaljCe74w8QERRhRt*ky6x9c!/m/dLYAAAAAAAAAnull&bo=mQXNApkFzQIDByI!&rf=photolist&t=5
**运行环境**
 - 操作系统类型： Windows
 - 具体版本： Windows 10
 - Motrix 版本： v1.2.2
 - 安装包类型：exe

**更多信息**
添加有关此问题的任何其他上下文信息。

**Comment by Zhaodoudou** [comment]
> **错误描述**
> 拦截 Chrome 普通下载任务
> 安装 YAAW for Chrome后，无法下载且报错，windows下YAAW界面与MAC下完全不一样，我配置的JSON-RPC地址，填的和文档一样，其他选项默认的。
> **如何重现**
> 重现步骤，如：
> 
> 1. 点击右键ARIA2 RPC任务按钮
> 2. 点击提交
> 3. 发现报错
> 
> **预期的行为**
> 拦截 Chrome 普通下载任务。
> 
> **截图**
> http://a3.qpic.cn/psb?/V14C3C0N0S9TdW/fcRyrDD6F38zNkhCpCub*cX3BkgBd51Rxqxj5zcCZwo!/m/dL4AAAAAAAAAnull&bo=QAawBFUIQAYRB9k!&rf=photolist&t=5
http://a3.qpic.cn/psb?/V14C3C0N0S9TdW/DoU.lsO4rO27BTqZ76knq3Hc8b1dI8AANqppYaAoeT8!/m/dLYAAAAAAAAAnull&bo=gAcHBIAHBwQDByI!&rf=photolist&t=5
http://a3.qpic.cn/psb?/V14C3C0N0S9TdW/U6w.yk42MC*1B.zZFcblaljCe74w8QERRhRt*ky6x9c!/m/dLYAAAAAAAAAnull&bo=mQXNApkFzQIDByI!&rf=photolist&t=5

> **运行环境**
> 
> * 操作系统类型： Windows
> * 具体版本： Windows 10
> * Motrix 版本： v1.2.2
> * 安装包类型：exe
> 
> **更多信息**
> 添加有关此问题的任何其他上下文信息。

**Comment by cbwang2016** [comment]
遇到了同样的问题，请问解决了吗？
