### ISSUE TITLE
点击“保存并应用”按钮后窗体自动最小化到系统托盘

### ISSUE THREAD

**Issue by AlexLiu-CN** [agalwood/Motrix#197]
**错误描述**
点击“保存并应用”按钮后窗体自动最小化到系统托盘

**如何重现**
重现步骤，如：
1. 打开偏好设置
2. 点击“保存并应用”按钮
3.窗体自动最小化到系统托盘，且仅有当前页面的设置被保存

**预期的行为**
显示保存成功，窗口保存原装，而不是最小化到系统托盘。

**截图**
请添加屏幕截图以帮助解释您的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

**运行环境**
 - 操作系统类型：Windows
 - 具体版本：  Windows 10
 - Motrix 版本： 1.2.2
 - 安装包类型：exe

**Comment by agalwood** [comment]
系统托盘图标一直都在的，只是现在保存偏好设置会重启应用
https://github.com/agalwood/Motrix/issues/172
