### ISSUE TITLE
Application does not close after closing it

### ISSUE THREAD

**Issue by alexwender1** [agalwood/Motrix#198]
**Describe the bug**
At certain times, after clicking "Quit Motrix"; the application icon still persists on the taskbar.
When you right-click the icon, no function is displayed.

**Screenshots**
When you open Motrix again... The taskbar has 2 application icons.
![Captura de Tela_selecionar área_20190412161223](https://user-images.githubusercontent.com/45263160/56061184-1a797100-5d3f-11e9-9477-da82d34bebdb.png)

On the system monitor, the Motrix (no icon) is the process with problems - which does not close. Obviously, I can kill the process manually.
![Captura de Tela_selecionar área_20190412161356](https://user-images.githubusercontent.com/45263160/56061185-1c433480-5d3f-11e9-9d37-a93a28cfc7bc.png)

**Environment (please complete the following information):**
 - OS & Version: Deepin 15.9.3
 - Motrix Version: 1.2.2
 - Installation package type: AppImage

**Comment by agalwood** [comment]
Occasionally this problem occurs in the deepin os, and I don't know how to solve it for the time being. You can use the process management manual kill process to exit.

**Comment by alexwender1** [comment]
I can not say, I just use Deepin. The system is expected to receive a major upgrade (the basis of the system will be Debian Stable) in the coming days... I will be reporting if the problem still persists.

**Comment by agalwood** [comment]
The new Motrix v1.3.x adds logic to destroy the system tray icon when the app exits. Try upgrading it.
https://github.com/agalwood/Motrix/releases

**Comment by alexwender1** [comment]
> The new Motrix v1.3.x adds logic to destroy the system tray icon when the app exits. Try upgrading it.
> https://github.com/agalwood/Motrix/releases

Problem solved!
