### ISSUE TITLE
请提供AppImage

### ISSUE THREAD

**Issue by probonopd** [agalwood/Motrix#2]
提供AppImage http://appImage.org/将具有以下优势：

-打包为AppImage的应用程序可以在许多发行版上运行（包括Ubuntu、Fedora、OpenSUSE、CentOS、Elementary OS、Linux Mint等）

-一个app=one file=super simple对于用户：只需下载一个appimage文件，使其可执行，然后运行
-无需开箱或安装
-不需要根
-未更改任何系统库
-开箱即用，无需安装运行时间
-与“appimaged”的可选桌面集成
-可选的二进制增量更新，例如，对于使用AppImageUpdate的连续构建（仅下载二进制diff）
-可以选择gpg2签名您的应用程序映像（在文件中）
-在现场ISOS上工作
-双引导多个分发时可以使用相同的AppImages
-可以在可用AppImages的https://appImage.github.io/apps中心目录中列出
-可以使用“--appImage extract”参数作为自解压压缩存档
-不需要存储库。适用于气隙（离线）机器

以下是已经向上游分发的项目的概述，提供的官方应用程序映像：https://appimage.github.io/apps

**Comment by agalwood** [comment]
Vielen Dank für Ihren Vorschlag. Linux wurde getestet und kann verwendet werden. AppImage wird in Kürze hochgeladen.

Thank you for your suggestion, Linux has been tested and can be used, and AppImage will be uploaded soon.

Although my English level is relatively poor, you can still submit the issue in English.
: D

**Comment by probonopd** [comment]
👍 谢谢你用德语回答。它实际上是正确的德语。

**Comment by agalwood** [comment]
@probonopd I pre-release v1.0.9, Application packages for Windows and Linux are now available!
Please help test the Linux version.

**Comment by woodwm** [comment]
@agalwood The download link of mac version in the website is not updated yet.

**Comment by probonopd** [comment]
:+1:  Thank you very much. My automated test was able to run this AppImage just fine.

Before we add it to the catalog at https://appimage.github.io/ could you give it an English user interface (UI) please on an English system?

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/bfe874c45b1434b9aef34f94533ab104cc1dcf20/database/Motrix/screenshot.png)

**Comment by agalwood** [comment]
@probonopd I think this should be a OS character set problem?
English User Interface is coming soon...

**Comment by probonopd** [comment]
Looks better now:

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/9b07b625ebfdf36982bb23a40db92bbf3bbe6a80/database/Motrix/screenshot.png)

Thank you very much.
