### ISSUE TITLE
v1.2.2在deepin下关闭后，状态栏仍然存在图标，右键无反应

### ISSUE THREAD

**Issue by dickzhenhua** [agalwood/Motrix#200]
v1.2.2在deepin最新的15.9.3下关闭后，状态栏仍然存在图标，在图标上面右键无反应

**Comment by agalwood** [comment]
重复问题 https://github.com/agalwood/Motrix/issues/198 https://github.com/agalwood/Motrix/issues/167 待处理

**Comment by agalwood** [comment]
请更新到 v1.3.x 版本，https://github.com/agalwood/Motrix/releases
