### ISSUE TITLE
How to  use Thunder

### ISSUE THREAD

**Issue by EDsoft2018** [agalwood/Motrix#201]
how to  download   as   thunder://QUFodHRwOi8vZGw2MjMuODBzLmltOjkyMC8xOTA0L+mdkuiho+mBk+W4iC/pnZLooaPpgZPluIgubXA0Wlo=

**Comment by agalwood** [comment]
You can use the 'New Task' to add link task, but I think many Thunder links are dead links to other download tools.

**Comment by EDsoft2018** [comment]
I think you can add a function convert Thunder links  to other links

**Comment by agalwood** [comment]
Someone mentioned it in January and it has already been implement.  Have you tried it?
https://github.com/agalwood/Motrix/issues/8

New Task - URL - Paste thunder link - Submit
