### ISSUE TITLE
Add a local server to listen the download request

### ISSUE THREAD

**Issue by pea3nut** [agalwood/Motrix#202]
在本地起一个端口监听下载请求。

是这样的，我写了个 [Pxer](http://pxer.pea3nut.org/) 脚本来抓取 [Pixiv](https://www.pixiv.net/) 的图片下载地址，但是仅仅能够抓到地址，没办法实现下载，因此想要借助贵软件来实现下载更名一条龙服务。

目前 Pxer 稳定 PV 在 300 左右。如果可以支持的话，我可在下载结果输出页和官网推荐贵软件。

**Comment by agalwood** [comment]
Motrix 内置的 aria2 是开放了端口的，端口号 16800，协议是 JSON-RPC 2.0，建议你了解一下 [aria2](https://aria2.github.io/manual/en/html/aria2c.html)

我看了你的项目，也是用 js 写的，你可以先看下[aria2文档](https://aria2.github.io/manual/en/html/aria2c.html#aria2.addUri) ，参考一下 Motrix 这里的实现：
https://github.com/agalwood/Motrix/blob/master/src/renderer/api/Api.js

然后我们再继续讨论你的需求哈
