### ISSUE TITLE
窗口变黑

### ISSUE THREAD

**Issue by ghost** [agalwood/Motrix#203]
运行下载文件，小窗在菜单栏，过一会打开显示整个窗口黑屏了。
系统环境：Ubuntu 18.04 
![Selection_046.png](https://i.loli.net/2019/04/15/5cb3c3da7b9d7.png)

**Comment by agalwood** [comment]
请按照以下模板补充更多信息：
https://github.com/agalwood/Motrix/issues/new?assignees=&labels=&template=bug_report_cn.md
