### ISSUE TITLE
实测：校园网下载视频速度600-700k，但是最后几秒下载速度降为2k，希望能够速度不会降下来

### ISSUE THREAD

**Issue by wp867007845** [agalwood/Motrix#204]
**Before feedback**
Before you feedback, please search for the issues to see if there are similar problems that can solve your problem.

**Please delete the above and the contents of this line, then fill in the feedback form in the following format, Thanks.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & Version: [e.g. macOS, Windows, Linux]
 - Version: [e.g. macOS 10.14.2, Windows 10, Ubuntu 18.04]
 - Motrix Version: [e.g. v1.1.3, v1.1.0]
 - Installation package type: [e.g. dmg, AppImage]

**Additional context**

**Comment by agalwood** [comment]
aria2 的速度计算方式就是这样的，下载到最后没数据了，速度就下来了
https://aria2.github.io/manual/en/html/aria2c.html#aria2.getGlobalStat
