### ISSUE TITLE
Invisible menu icon in Mac dark mode

### ISSUE THREAD

**Issue by ForeverArt** [agalwood/Motrix#206]
**Issue**
Menu icon is almost invisible when mac is in dark mode.

**Expected behavior**
Menu icon switch to white when mac is in dark mode.

**Environment**
macOS Mojave 10.14.4

**Screenshots**
![image](https://user-images.githubusercontent.com/23061097/56196512-8c1c2c80-6069-11e9-8e6b-3d569cb73b01.png)

![image](https://user-images.githubusercontent.com/23061097/56196528-95a59480-6069-11e9-8092-9f4bf2ed251d.png)

**Comment by agalwood** [comment]
Known issues, the next version will be fixed.
