### ISSUE TITLE
1.2.2 系统托盘图标 可以根据 系统主题区分一下黑白吗？

### ISSUE THREAD

**Issue by ImYuanY** [agalwood/Motrix#207]
1.2.2 系统托盘图标 可以根据 系统主题区分一下黑白吗？
在暗色主题下，黑色的图标什么也看不见，就是正在下载的过程中也是只有一个小绿点。 
必竟以后应该用暗色主题的多一些（大多系统都在主推暗色主题的特性，Mac OS/Windows 10/iOS/Android ,皆是如此）
![20190417092853](https://user-images.githubusercontent.com/15044611/56254451-6f2c3b80-60f3-11e9-8391-caeae73f7e56.png)
![20190417092919](https://user-images.githubusercontent.com/15044611/56254452-6f2c3b80-60f3-11e9-9700-bd06e6bc7745.png)

![20190417093147](https://user-images.githubusercontent.com/15044611/56254543-cc27f180-60f3-11e9-9426-12510dfb96c3.png)
![20190417093201](https://user-images.githubusercontent.com/15044611/56254544-cc27f180-60f3-11e9-8640-2675b499d570.png)

**Comment by agalwood** [comment]
已知问题，待修复
https://github.com/agalwood/Motrix/issues/161#issuecomment-478195745
