### ISSUE TITLE
希望能支持Google Drive的下载

### ISSUE THREAD

**Issue by ifrankwang** [agalwood/Motrix#208]
**Is your feature request related to a problem? Please describe.**
Google Drive的文件不会通过该应用下载（已经装过「添加到Aria2」插件并配置好了`JSON-RPC`），手动copy下载地址，并在Motrix中创建新任务也无法下载

**Describe the solution you'd like**
点击Google Dirve中的下载按钮能直接下载（通过插件转向下载？）

**Comment by agalwood** [comment]
大概看了一下，下载 Google Drive 文件需要导入 cookie，你可以参考一下这个：
https://gist.github.com/iamtekeste/3cdfd0366ebfd2c0d805

这个功能暂无计划

**Comment by ifrankwang** [comment]
@agalwood Thx~
