### ISSUE TITLE
希望能支持thunder://链接

### ISSUE THREAD

**Issue by ChromeHu** [agalwood/Motrix#209]
**问题**
如题，thunder://链接在国内还是挺常见的。所以希望能支持一下。

**思路/方案**
我在Motrix中下载thunder://链接都是先在[下载地址在线转换](https://tool.lu/urlconvert/)中转换真实地址再下载的，但是每次这样操作一下就显得麻烦起来，所以如果能自动转换下载就好了。

>话说老哥能不能加一个国内下载方式，Github下载真是太慢了

**Comment by agalwood** [comment]
迅雷链接解码失误了，已经修正，下版本发布
