### ISSUE TITLE
增加一个开机自启动和端口设置功能吧可以配合camtd

### ISSUE THREAD

**Issue by blazefizz** [agalwood/Motrix#210]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by agalwood** [comment]
我看了一下 Camtd 设置支持设置 JSON-RPC 地址，Motrix 内置 aria2 的 RPC 端口是 16800，改下 Camtd 的 Aria2 RPC 地址为 `127.0.0.1:16800/jsonrpc`

> https://github.com/jae-jae/Camtd/wiki/Camtd%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B

**Comment by blazefizz** [comment]
作为服务自启也友必要吧
