### ISSUE TITLE
Selective download

### ISSUE THREAD

**Issue by Ritashaiev** [agalwood/Motrix#211]
Greetings,

I would like to appreciate the dev creating this wonderful software.
Here is my modest suggestion for the next improvement/function: Allow user to select which document(s) to be downloaded. 
To my best knowledge, not all files in a torrent are needed for a user such that there may be several formats of the same document in a single torrent. Thus, avoid redundant downloading definitely will save time for users.

Regards,

**Comment by agalwood** [comment]
Thanks, this feature is in development.

**Comment by iuen** [comment]
> Thanks, this feature is in development.

第一次用issue，只看了中文没看英文不好意思
