### ISSUE TITLE
关于BT任务的建议

### ISSUE THREAD

**Issue by Prurite** [agalwood/Motrix#212]
**Is your feature request related to a problem? Please describe.**
Yep. 在bt下载时，无法手动设置tracker（至少我没在GUI里找到），并且下载完成后卡在下载中 0KB/s（目测是做种中，但是这个逻辑确实有点奇怪）。

**Describe the solution you'd like**
加入对bt下载手动设置tracker的支持（手动改配置文件对多数用户不友好）；在下载列表中加入“已完成”一项，做种中的任务放到这里，并显示实时上传速度。（能像utorrent那样显示一下peer详细信息就更好了，我不确定能否做到）

**Describe alternatives you've considered**
(None)

**Additional context**
下载列表的问题也有人提过了 https://github.com/agalwood/Motrix/issues/71

**Comment by agalwood** [comment]
Motrix 默认的 tracker 配置用的是 https://github.com/ngosang/trackerslist/blob/master/trackers_best.txt ，大部分修改的需求也是改成这个吧，所以还没做 UI 设置

列表会在下版本重构和分类

**Comment by agalwood** [comment]
升级一下 Motrix，v1.3.8 已经支持手动设置 tracker 服务器，偏好设置-进阶设置-Tracker服务器
https://github.com/agalwood/Motrix/releases
