### ISSUE TITLE
Windows10 下载磁力链接发生错误

### ISSUE THREAD

**Issue by InCerryGit** [agalwood/Motrix#213]
**错误描述**
window10 上使用Motrix下载磁力链接发生错误，错误信息如下图所示。
![TIM截图20190419124017](https://user-images.githubusercontent.com/36690780/56405950-611c1d80-62a1-11e9-9efc-d6fc44d6ac56.png)

**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接（ed2k://|file|cn_windows_10_business_edition_version_1809_updated_sept_2018_arm64_dvd_104983b1.iso|4298262528|FE2D82693ECB2DC2804299A13DC570D5|/）
3. 点击提交
4. 发现报错

**预期的行为**
清楚简洁地描述您期望发生的事情。

**截图**
![TIM截图20190419125032](https://user-images.githubusercontent.com/36690780/56406006-c07a2d80-62a1-11e9-986e-e89ea5c61ace.png)
![TIM截图20190419125022](https://user-images.githubusercontent.com/36690780/56406008-c1ab5a80-62a1-11e9-97fc-4d637dd2f7da.png)

**运行环境**
![TIM截图20190419124142](https://user-images.githubusercontent.com/36690780/56405969-86109080-62a1-11e9-8cc5-9c1705a5ceaf.png)
![TIM截图20190419124104](https://user-images.githubusercontent.com/36690780/56405972-87da5400-62a1-11e9-870d-948d64ecd3f5.png)
![TIM截图20190419124036](https://user-images.githubusercontent.com/36690780/56405976-8b6ddb00-62a1-11e9-9941-ea1f7ca3404d.png)
 - 安装包类型：[setup.exe、zip 均重现该错误]

**Comment by agalwood** [comment]
老铁，你贴的链接是 电驴链接（ed2k），不是磁力链

因下载引擎原因，不支持 ed2k 的链接 https://github.com/agalwood/Motrix/issues/170

**Comment by InCerryGit** [comment]
> 老铁，你贴的链接是 电驴链接（ed2k），不是磁力链
> 
> 因下载引擎原因，不支持 ed2k 的链接 #170
Sorry  忘了这是基于aria2，不支持ed2k
