### ISSUE TITLE
下载百度网盘资源出现多个重复文件

### ISSUE THREAD

**Issue by lwanglynn** [agalwood/Motrix#214]
**Describe the bug**
使用MO下载百度网盘资源时，出现多个重复文件

**Screenshots**
![image](https://user-images.githubusercontent.com/49808609/56455685-09aaaa00-6394-11e9-81f0-b5f3337b038b.png)

**Environment (please complete the following information):**
 - OS & Version: macOS
 - Version: macOS 10.14.3
 - Motrix Version: v1.2.2
 - Installation package type:dmg

**Comment by agalwood** [comment]
我觉得是你自己多点了一次：|
