### ISSUE TITLE
希望能够添加监听剪贴板的功能

### ISSUE THREAD

**Issue by pdkst** [agalwood/Motrix#215]
### 复制链接过来时不能自动的粘贴，所以希望能够添加监听剪贴板的功能
当剪贴板的内容为可以下载的链接时自动提示添加下载任务，可以不用强提示，只显示一个按钮添加剪贴板的链接为下载任务就可以

**Comment by agalwood** [comment]
暂无计划
https://github.com/agalwood/Motrix/issues/194
