### ISSUE TITLE
当下载失败时，没有按钮重新开始下载

### ISSUE THREAD

**Issue by pdkst** [agalwood/Motrix#216]
### 当下载失败时，没有按钮重新开始下载
在不删除文件的前提下，只能重新新建这个任务，然后motrix会重新继续刚才中断的下载，希望能提供一个方式快速恢复下载

**Comment by agalwood** [comment]
待处理 https://trello.com/c/BDoG06UU/36

**Comment by agalwood** [comment]
Motrix v1.4.x 已经支持重新开始下载，请更新到最新版

https://github.com/agalwood/Motrix/releases
