### ISSUE TITLE
任务列表分类很不错，但是希望能提供一个全部任务的分类

### ISSUE THREAD

**Issue by pdkst** [agalwood/Motrix#217]
### 任务列表分类很不错，但是希望能提供一个全部任务的分类
分类变为四个：全部任务、下载中、已暂停、已完成
全部任务显示其他三个分类，并按照下载中、已暂停、已完成的顺序进行排序，当然，提供给我一个不使用其他分类的按钮更好，只显示所有任务，按照我的习惯，我是把分类当做过滤器过滤任务的，下载完成的任务一般会清理掉，所以不会很多，只显示全部分类的话比较直观
![image](https://user-images.githubusercontent.com/8915631/56456745-32866b80-63a3-11e9-9ad9-08522b646d1a.png)

**Comment by agalwood** [comment]
列表分类会优化，不过大概率不会加“全部任务”，aria2 的列表接口没有提供全部任务的分类，数据的聚合和分页是比较难处理的问题

**Comment by pdkst** [comment]
了解
