### ISSUE TITLE
希望增加一个用户下载前百度账号登录状态提示

### ISSUE THREAD

**Issue by zealson** [agalwood/Motrix#22]
因为众所周知，下载要下载百度云盘的链接之前都必须是登录状态方可下载成功，而目前motrix在百度用户未登录的状态也提示下载成功，导致我几次忘记登录了，以为下载好了文件，结果一看都没有下载呢，希望插件能够检测百度用户登录状态，在未登录时，提示登录，方才提示“下载成功”

**Comment by agalwood** [comment]
收到，有精力想全新开发一个 MO Helper的浏览器扩展😑

**Comment by zealson** [comment]
希望早日实现，谢谢了~

**Comment by agalwood** [comment]
已放弃度盘支持，请自行探索
