### ISSUE TITLE
很不错的项目，electron 能否使用4.0/5.0

### ISSUE THREAD

**Issue by zuohuadong** [agalwood/Motrix#220]
当前依赖的 vue-electron 使用的是 electron ，貌似其他vue 整合的使用的也都是 2.x 。

但是 angular 的 https://github.com/maximegris/angular-electron  使用了 electron 。

2.0 迟早还是淘汰的

**Comment by agalwood** [comment]
老铁，你能看下本项目的 package.json 再提问么...
https://github.com/agalwood/Motrix/blob/829eb83a4c2f76754308f3a024515c70940dcbba/package.json#L203

electron 5.0 目前还不考虑，只会跟随最新稳定版本升级

顺手去翻了一下 git 提交记录，刚在 GitHub 开源时的 electron 版本也不是 2.x
https://github.com/agalwood/Motrix/blob/dc2a11cd1aa05f281f69fe3e3c5bd98853a5c0bd/package.json#L154

**Comment by zuohuadong** [comment]
> 老铁，你能看下本项目的 package.json 再提问么...
> [Motrix/package.json](https://github.com/agalwood/Motrix/blob/829eb83a4c2f76754308f3a024515c70940dcbba/package.json#L203)
> 
> Line 203 in [829eb83](/agalwood/Motrix/commit/829eb83a4c2f76754308f3a024515c70940dcbba)
> 
>  "electron": "^4.1.1", 
> electron 5.0 目前还不考虑，只会跟随最新稳定版本升级
> 
> 顺手去翻了一下 git 提交记录，刚在 GitHub 开源时的 electron 版本也不是 2.x
> [Motrix/package.json](https://github.com/agalwood/Motrix/blob/dc2a11cd1aa05f281f69fe3e3c5bd98853a5c0bd/package.json#L154)
> 
> Line 154 in [dc2a11c](/agalwood/Motrix/commit/dc2a11cd1aa05f281f69fe3e3c5bd98853a5c0bd)
> 
>  "electron": "^3.0.11",

![image](https://user-images.githubusercontent.com/11203929/56496215-00077a80-652b-11e9-9e13-7d089883d99e.png)

底下那个是开发依赖吧，核心依赖还是这个

**Comment by agalwood** [comment]
你可以看下 vue-electron 这个 npm 包的源码，你就会知道这个根本和 electron 版本无关了
https://github.com/SimulatedGREG/vue-electron/blob/master/index.js

**Comment by agalwood** [comment]
electron 就是作为开发依赖使用的，它在 build 过程是作为二进制文件被使用的
