### ISSUE TITLE
下载失败，是不是没启动某个MO？

### ISSUE THREAD

**Issue by roachsinai** [agalwood/Motrix#223]
Chrome扩展无法打开Motrix进行下载，已经启动了MO.

**截图**

![image](https://user-images.githubusercontent.com/9500049/56563902-7b2a6880-65df-11e9-8c07-341a13d493f9.png)

**运行环境**
 - 操作系统类型： [Linux]
 - 具体版本： [Manjaro 18.04]
 - Motrix 版本： [如 v1.2.2]
 - 安装包类型：[如 dmg, AppImage]

**Comment by agalwood** [comment]
试下这个操作
https://github.com/agalwood/Motrix/issues/20#issuecomment-468956081

**Comment by roachsinai** [comment]
好的。

**Comment by roachsinai** [comment]
可以下载了。就是网速略喜人，不过网速低了，安全。。
