### ISSUE TITLE
关于窗口的建议

### ISSUE THREAD

**Issue by liyiliuxingyu** [agalwood/Motrix#224]
关于Windows系统的建议
1.窗口能否设计成缩放模式，因为我电脑屏幕13寸的，窗口正好顶着上端无法缩放很难受
2.能否设计成开机自启动，要不然每次使用都要点一下很不方便

**Comment by agalwood** [comment]
窗口大小做了简单的优化，小屏幕时初始大小为原来的 0.875，即将发布新版

开机自启动待开发

**Comment by agalwood** [comment]
Motrix v1.3.x 新版已经发布，请更新版本 https://github.com/agalwood/Motrix/releases
