### ISSUE TITLE
在已完成的菜单列表下增加一些小建议

### ISSUE THREAD

**Issue by kyytyp** [agalwood/Motrix#23]
1.能够双击文件直接用系统默认工具自动打开
2.打开文件夹的时候能默认选中下载的文件,不然文件太多找不到

**Comment by agalwood** [comment]
收到，感谢

> 1.能够双击文件直接用系统默认工具自动打开

加到需求池了：P

第二点现在就是这样子的呀？我 macOS 上点击文件夹之后就是自动选中当前文件的
请提供一下你的操作系统信息

**Comment by agalwood** [comment]
@kyytyp 
> 点开新增下载的时候 能够自动粘贴下 把复制的链接自动放进去

已实现， 下次发布就有这特性了 https://github.com/agalwood/Motrix/commit/7011160587b16470e857ea5bf80b049e700dea6d
