### ISSUE TITLE
how to keep the window size?

### ISSUE THREAD

**Issue by whorusq** [agalwood/Motrix#230]
**Is your feature request related to a problem? Please describe.**
Every time I open the software, the window is always maximized.

**Describe the solution you'd like**
I want to keep the window size after i adjust it.

**Describe alternatives you've considered**

**Additional context**

**Comment by agalwood** [comment]
Not supported yet

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/181

**Comment by whorusq** [comment]
> Not supported yet

ok ,

**Comment by agalwood** [comment]
The new Motrix v1.3.x makes simple optimizations for small screens.
You can upgrade the Motrix :
https://github.com/agalwood/Motrix/releases

The feature of keeping the window size please discuss at #181
