### ISSUE TITLE
种子和磁力链下载错误 

### ISSUE THREAD

**Issue by lixuedong1024** [agalwood/Motrix#231]
已测试多个磁力链接和种子文件
平台为Ubuntu 1804
使用系统aria2软件下载正常

使用motrix直接提交瞬间就抛出错误

![2019-04-26 10-04-50 的屏幕截图](https://user-images.githubusercontent.com/28880091/56779799-3553e700-680f-11e9-9c48-9373425455ee.png)

**Comment by agalwood** [comment]
补充一下截图

请添加屏幕截图以帮助解释您的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

对于这种不按错误反馈模板提交的 issue，真的没精力处理...

**Comment by sanhu88** [comment]
看下是不是酸酸乳修改了IE的代理，因为关掉小飞机，IE代理还在。

**Comment by lixuedong1024** [comment]
新版本可以了
