### ISSUE TITLE
Bug occurred that I couldn't click

### ISSUE THREAD

**Issue by RoderickQiu** [agalwood/Motrix#233]
**Describe the bug**
It's the second time the bug occurred. I stopped my downloading task and restarted the app, and I couldn't click anymore, every buttons including the ones on bar stopped working and everything like the badge stopped. After let it be hidden to the tray and re-opened it, everything was OK now.

**Expected behavior**
It's expected to work.

**Screenshots**
![图片](https://user-images.githubusercontent.com/42290260/56815040-f5265000-6872-11e9-8e6c-73a482721484.png)

**Environment (please complete the following information):**
 - OS & Version: Windows
 - Version: Windows 10
 - Motrix Version: 1.2.2
 - Installation package type: exe Installer

**Additional context**
I really don't know why. Maybe some hidden mistake in coding?

**Comment by agalwood** [comment]
Need more information, can you call up the developer tool in this state, and take a screenshot of the console?

**Comment by RoderickQiu** [comment]
![图片](https://user-images.githubusercontent.com/42290260/57137848-9ec19000-6de3-11e9-878b-6f115f919906.png)
The problem occurred again. This time, I tried to stretch it, but it just kept sticking (with the black thing) and I cannot call devtool.
Again fixed by clicking the tray icon.

**Comment by agalwood** [comment]
I seem to find the problem code, this issue is triggered when the second instance is started.
https://github.com/agalwood/Motrix/blob/b89c651132f5a45c05bd21d2dc51a03002e9b4ba/src/main/ui/WindowManager.js#L65
This api has problems with Windows : x

**Comment by agalwood** [comment]
It should have been fixed and wait for the next release.

**Comment by RoderickQiu** [comment]
hope things can be settled :D

**Comment by agalwood** [comment]
You can clone the master code and build it.
