### ISSUE TITLE
暗黑模式下面右上角图标完全看不见

### ISSUE THREAD

**Issue by nstylec** [agalwood/Motrix#234]
**Is your feature request related to a problem? Please describe.**
我喜欢隐藏dock，暗黑模式下完全看不到右上角的motrix图标

**Describe the solution you'd like**
需要重绘motrix的图标，只要描个白线的那种

**Describe alternatives you've considered**

**Additional context**

**Comment by RoderickQiu** [comment]
查一查electron官方检测暗黑模式的api 自己也能干

**Comment by RoderickQiu** [comment]
当然 前提是 你能看懂代码

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/207

@RoderickQiu 其实 master 代码上已经修好了，新版本即将发布 : p
@nstylec 着急的话自己克隆代码 build 一下
