### ISSUE TITLE
反馈几个问题

### ISSUE THREAD

**Issue by Alion548** [agalwood/Motrix#24]
系统环境：
`Windows 10 1809 x64 Pro，Motrix 1.0.10 单文件版`
`BUG反馈：`
1. 进阶设置 保存并应用 后软件闪退
2. 官网( https://motrix.app/ )很难打开
3. 每次启动aria释放到随机目录，导致上次防火墙规则失效 

`功能建议：`
1. 支持远程web界面控制，现在支持aria2c RPC？
2. 进阶设置开放更多aria配置参数
3. 支持限速功能，最好提供不同时段限速（用于区分闲时、忙时网络情况）
4. 百度云盘一次添加很多任务(1000+个文件，上百G)时，任务下载后期Cookies过期情况如何处理？
5. 提供纯Web界面，降低内存占用

感谢作者开发！

**Comment by agalwood** [comment]
感谢你的反馈和建议……点有点多，所以没有马上回复🤓

官网慢的原因是前段时间CDN被刷爆了，被我临时下线了
闪退和防火墙问题可以试下安装版？

1. 暂时不支持远程管理其他 aria2 服务
2. aria2 支持的配置项太多了，全放出来不实际，常用的我会尽量放出来，如果有特殊需求可以自行编辑
`C:\Users\用户名\AppData\Motrix\system.json`
3. 限速会支持
4. 我也不知道:-I
5. 精力有限，暂无计划
