### ISSUE TITLE
基础设置无法保存

### ISSUE THREAD

**Issue by clj15602** [agalwood/Motrix#240]
**错误描述**
偏好设置-基础设置无法保存，点击保存并应用 不会重启。

**如何重现**
重现步骤，如：
1. 点击偏好设置
2. 修改基础设置中的默认下载路径，
3. 点击“保存并应用”
4. 发现不会重启，切换回来基础设置仍然未发生改动。

**预期的行为**
基础设置能够修改保存。

**截图**
请添加屏幕截图以帮助解释您的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

**运行环境**
 - 操作系统类型：Windows 10
 - 具体版本： 专业版 1809
 - Motrix 版本：1.3.7
 - 安装包类型：exe

**Comment by agalwood** [comment]
v1.3.8 已经修复了，升级一下
https://github.com/agalwood/Motrix/releases
