### ISSUE TITLE
OpenSUSE + KDE，软件图标为空白

### ISSUE THREAD

**Issue by yeeuyz** [agalwood/Motrix#243]
开发者你好，我的使用环境是OpenSUSE Leap 15 + KDE。

在使用1.2.2版本时，Motrix在“开始”菜单和任务栏的启动图标是正常显示的。
然而今天更新到1.3.8版本时，我发现Motrix在上述位置的图标为空白。
（软件启动后任务栏程序按钮和托盘正常显示图标，任务栏启动图标依然为空白。）

**Comment by agalwood** [comment]
这个问题似乎无能为力，我翻了一遍提交记录，可能有影响的点就是升级了 electron-builder 了，没有发现其他有关的改动 : (
你能试下删除重装么？

**Comment by weearc** [comment]
请降级electron到1.44看一下。


 
---原始邮件---
发件人: "yeeuyz"<notifications@github.com>
发送时间: 2019年5月3日 11:39:26
收件人: "agalwood/Motrix"<Motrix@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [agalwood/Motrix] OpenSUSE + KDE，软件图标为空白 (#243)



开发者你好，我的使用环境是OpenSUSE Leap 15 + KDE。
 
在使用1.2.2版本时，Motrix在“开始”菜单和任务栏的启动图标是正常显示的。
 然而今天更新到1.3.8版本时，我发现Motrix在上述位置的图标为空白。
 （软件启动后任务栏程序按钮和托盘正常显示图标，任务栏启动图标依然为空白。）

**Comment by yeeuyz** [comment]
今天开机发现图标自己出现了，好神奇，我也没改动什么东西，除了昨天suse的几个安全更新= =
