### ISSUE TITLE
BT下载没有速度

### ISSUE THREAD

**Issue by wei-xun** [agalwood/Motrix#244]
我已经进行了做种子，但是下载依旧没有速度
我是每次进行Bt下载都需要作种子嘛

**Comment by AppJ-GS** [comment]
这是因为这个资源的持有者太少，建议换一个资源

**Comment by zwb124** [comment]
我下载http://mac-torrent-download.net这个网站的bt资源，就都无法下载，但是用fdm就没问题

**Comment by agalwood** [comment]
建议你们去了解一下 BT 的下载原理

![image](https://user-images.githubusercontent.com/1032175/57175165-53f35700-6e7b-11e9-8f95-c7f7beb9f00c.png)
