### ISSUE TITLE
带账户密码的ftp支持

### ISSUE THREAD

**Issue by zwb124** [agalwood/Motrix#245]
ftp://m:m@tv.kaida365.com:2199/权力的游戏第八季未删减版V2-720P-03.mp4
--
类似这样的链接无法下载

**Comment by agalwood** [comment]
找了你一下你发的这个链接，发现不是支不支持 ftp 的问题，这地址应该是个障眼法，除了用迅雷以外的客户端都下不动的

**Comment by zwb124** [comment]
这样啊，那太糟心了，迅雷还得坑多久啊，哎
