### ISSUE TITLE
开发者模式下启动的时候,界面白屏

### ISSUE THREAD

**Issue by chengdonglin** [agalwood/Motrix#247]
操作系统:win10 x64
node: 8.11.9
npm:5.5.6

采用开发者模式git clone下来, 安装完依赖, npm run dev启动发现白屏.

**Comment by agalwood** [comment]
老铁，你作为程序员都是这样报 Bug 的么？

麻烦提交 shell 报错截图和审查元素 console 的截图

**Comment by chengdonglin** [comment]
> 老铁，你作为程序员都是这样报 Bug 的么？
> 
> 麻烦提交 shell 报错截图和审查元素 console 的截图

好吧!尴尬! 没表述清楚! shell和console没有报错!
 11:40:46.264 > [Motrix] Engine start sh===> [ 'E:\\electron_project\\Motrix\\extra\\win32\\engine\\aria2c.exe',
    '--conf-path=E:\\electron_project\\Motrix\\extra\\win32\\engine\\aria2.conf',
    '--save-session=C:\\Users\\xxx\\AppData\\Roaming\\Electron\\download.session',
    '--input-file=C:\\Users\\xxx\\AppData\\Roaming\\Electron\\download.session',
    '--allow-overwrite=true',
    '--auto-file-renaming=true',
    '--bt-tracker=udp://62.138.0.158:6969/announce,udp://188.241.58.209:6969/announce,udp://188.241.58.209:6969/announce,udp://208.83.20.20:6969/announce,udp://151.80.120.115:2710/announce,udp://185.225.17.100:1337/announce,udp://151.80.120.113:2710/announce,udp://62.210.88.151:1337/announce,http://176.113.71.19:6961/announce,http://104.27.134.253:8080/announce,udp://5.2.79.219:1337/announce,udp://91.216.110.52:451/announce,udp://5.206.58.23:6969/announce,udp://159.100.245.181:6969/announce,udp://5.2.79.22:6969/announce,udp://176.31.241.153:80/announce,udp://95.211.168.204:2710/announce,udp://188.246.227.212:80/announce,udp://51.38.184.185:6969/announce,udp://51.15.40.114:80/announce,udp://tracker.coppersurfer.tk:6969/announce,udp://tracker.open-internet.nl:6969/announce,udp://tracker.leechers-paradise.org:6969/announce,udp://exodus.desync.com:6969/announce,udp://tracker.internetwarriors.net:1337/announce,udp://9.rarbg.to:2710/announce,udp://9.rarbg.me:2710/announce,udp://tracker.opentrackr.org:1337/announce,http://tracker3.itzmx.com:6961/announce,http://tracker1.itzmx.com:8080/announce,udp://open.demonii.si:1337/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.tiny-vps.com:6969/announce,udp://tracker.cyberia.is:6969/announce,udp://denis.stalker.upeer.me:6969/announce,udp://thetracker.org:80/announce,udp://bt.xxx-tracker.com:2710/announce,udp://open.stealth.si:80/announce,udp://tracker.port443.xyz:6969/announce,udp://ipv4.tracker.harry.lu:80/announce',
    '--continue=true',
    '--dht-file-path=C:\\Users\\xxx\\AppData\\Roaming\\Electron\\dht.dat',
    '--dht-file-path6=C:\\Users\\xxx\\AppData\\Roaming\\Electron\\dht6.dat',
    '--dir=C:\\Users\\xxx\\Downloads',
    '--max-concurrent-downloads=5',
    '--max-connection-per-server=16',
    '--max-download-limit=0',
    '--max-overall-download-limit=0',
    '--max-overall-upload-limit=128K',
    '--min-split-size=1M',
    '--pause=true',
    '--rpc-listen-port=16800',
    '--split=16',
    '--user-agent=Transmission/2.94' ]

┗ ----------------------------

┏ Electron -------------------

  11:40:46.309 > [Motrix] Engine pid===> 6504

┗ ----------------------------

┏ Electron -------------------

  11:40:46.465 > [Motrix] Engine started===>

┗ ----------------------------

┏ Electron -------------------


  05/05 11:40:46 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

  05/05 11:40:46 [NOTICE] IPv4 RPC: listening on TCP port 16800

  05/05 11:40:46 [NOTICE] IPv6 RPC: listening on TCP port 16800

┗ ----------------------------

┏ Electron -------------------


  05/05 11:41:16 [NOTICE] Serialized session to 'C:\Users\xxx\AppData\Roaming\Electron\download.session' successfully.

┗ ----------------------------

**Comment by chengdonglin** [comment]
已经搞定了! 把node_module删调,重新install就可以了.
