### ISSUE TITLE
如果程序已运行，再次打开程序图标，会出现一个假死的页面

### ISSUE THREAD

**Issue by sdgmlj** [agalwood/Motrix#248]
win10系统，64位，
在该程序已经运行的情况下,（缩小到通知栏），如果再点击程序图标（不小心重新打开，或者已经忘记了程序还在后台运行），这时会打开一个假死的程序，任何点击都无效。在常规情况下，再次运行程序，会激活后台的窗口，而不应该出现上述情况，不知道算不算一个bug

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/233 已经修复了，下版本发布

目前的解决方案是点击系统托盘图标就能恢复正常
