### ISSUE TITLE
Windows下关于传递下载参数的一个功能建议

### ISSUE THREAD

**Issue by ted423** [agalwood/Motrix#249]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/7042766/57204808-94261700-6fec-11e9-87f8-e0b361f5a7c3.png)

我使用的cent browser,通常这个下载框调用迅雷或IDM会很方便。
感觉这是通过com控件做的？个人也不是很懂。
现在用motrix的话只能通过复制下载连接的方式。

**Comment by ted423** [comment]
另外就是下载没有已完成有点不大习惯，完成的在已停止里，然后上面还有个恢复下载感觉怪怪的

**Comment by agalwood** [comment]
拦截 http 下载可以按照教程试下
https://www.yuque.com/moapp/help/extensions#22993f87

**Comment by ted423** [comment]
> 拦截 http 下载可以按照教程试下
> https://www.yuque.com/moapp/help/extensions#22993f87

以前用过扩展调用aria2c，感觉不是很喜欢，一些小文件我是习惯直接走浏览器的，还有一些图片批量保存有时候我会设置不询问直接保存。

好像出现响应不及时的情况,具体什么情况太久没用有点想不起来了。
当时好像还有个文件命名的问题。
