### ISSUE TITLE
已经基于源代码为archlinux用户打包

### ISSUE THREAD

**Issue by weearc** [agalwood/Motrix#25]
aur：https://aur.archlinux.org/packages/motrix/

**Comment by agalwood** [comment]
🙏感谢，对arch木有研究，如果需要的话我可以加上更多的 linux build target ？

**Comment by weearc** [comment]
不是有Linux unpacked 的么，那个一般的发行版都能直接跑。打包更多是方便用包管理来操作

**Comment by Aquarian-Age** [comment]
> 感谢，对arch木有研究，如果需要的话我可以加上更多的 linux build target ？

希望添加rpm包的支持 谢谢

**Comment by weearc** [comment]
> > 感谢，对arch木有研究，如果需要的话我可以加上更多的 linux build target ？
> 
> 希望添加rpm包的支持 谢谢

请新开issue...忘记close这个是我的责任...
