### ISSUE TITLE
添加磁链或种子就出错，添加普通下载正常。

### ISSUE THREAD

**Issue by anglesccs** [agalwood/Motrix#250]
添加磁链或种子就出错，见截图。添加普通下载正常。
出问题之前，在motrix有文件正在下载的情况下重启了电脑，电脑重启后原来下载的文件出错无法继续下载，然后添加添加磁链或种子都出错，添加普通下载正常。
重新在github下载了绿色的motrix，仍然有同样的问题。
另外，发现失败的任务出现在任务列表”已停止“中，而下载文件也已经在下载文件夹中生成，但是如果选择删除任务列表的同时删除文件，下载文件夹里的文件并不会被删除。
所生成的文件夹的属性如图：
![Annotation 2019-05-07 173150](https://user-images.githubusercontent.com/49857157/57289518-1b0ee880-70ee-11e9-88a4-ad928d49ed12.jpg)

**截图**
没有找到“打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。”
![Annotation 2019-05-07 140538](https://user-images.githubusercontent.com/49857157/57278438-05db8f00-70d9-11e9-9c25-1c23fc48d962.jpg)

**运行环境**
 - 操作系统类型：WINDOWS
 - 具体版本：Windows 10 64位
 - Motrix 版本：1.3.8
 - 安装包类型：EXE

**Comment by agalwood** [comment]
偏好设置-进阶设置-下载会话路径，点击右边的文件夹图标，去把 download.session 删一下试试吧

**Comment by anglesccs** [comment]
删过，C:\Users\用户名\AppData\Roaming\Motrix这个文件夹都删过，重新安装motrix，把注册表里所有motrix的项都删过，还是不行，一样的问题。

**Comment by anglesccs** [comment]
试了一下1.2.2版本，1.2.2版本可以正常使用，然后卸载1.2.2再安装1.3.8还是一样的问题。
另外还试了一下1.2.2版本在正常使用的情况下，覆盖安装1.3.8版本，还是一样的问题。
