### ISSUE TITLE
在下载多子文件任务时无法选择需下载的个别子文件

### ISSUE THREAD

**Issue by iuen** [agalwood/Motrix#253]
在下载多子文件任务时无法选择需下载的个别子文件，比如下指环王电影合集的中的第一部，没有选择的地方，只能全部下载，是不是我操作不当？

**Comment by grandsong** [comment]
同问。
有些BT里会包含下载者不一定需要的文件（比如合集、之前的同系列作品等）。
我猜作者可能还没有开发这个功能……

**Comment by agalwood** [comment]
重复问题 https://github.com/agalwood/Motrix/issues/229 ，待开发，提 issue 之前建议先搜索一下
