### ISSUE TITLE
GPL and MIT violation

### ISSUE THREAD

**Issue by HarukaMa** [agalwood/Motrix#254]
Aria2 uses GPL license, Electron and Vue.js use MIT license, but there are even no acknowledgements anywhere in the app.

Please respect open source softwares and comply with related licenses.

**Comment by agalwood** [comment]
Thanks, this is my mistake, not enough to understand the open source license. I will add open source license content in the next version.

Now how can I quickly fix the problem with the open source license? Is it possible to add an open source license copyright in the software section (jump to the official website about the page)?

**Comment by agalwood** [comment]
There is still a question to ask if the GNU open source license aria2 can be integrated into the MIT software, which is also a problem that bothers me.

**Comment by agalwood** [comment]
I have added a license page for third-party open source software on the official website.

https://motrix.app/about

https://motrix.app/license

The open source license page will be added to the next version of the Motrix app.

**Comment by agalwood** [comment]
I have added a license for third-party open source software on the official website.

https://motrix.app/about

https://motrix.app/license

The open source license page will be added to the next version of the Motrix app.

**Comment by agalwood** [comment]
The License link has been added to Motrix v1.4.1 About panel.

![image](https://user-images.githubusercontent.com/1032175/60655433-46a91780-9e80-11e9-8839-34dfbfe9f15c.png)
