### ISSUE TITLE
百度云下载下载的文件夹没有自动按目录存放，全部放在了download目录下面

### ISSUE THREAD

**Issue by ihxperfect** [agalwood/Motrix#256]
从百度云用mo下载文件夹，下载下来的文件夹内的文件没有按目录存放，而是全部变成了单独文件放在下载目录。
例如下载这样的文件夹：
目录1
——2级目录
————3级目录文件1
————3级目录文件2
——2级目录
————3级目录文件3
————3级目录文件4
下载之后，在下载目录得到的文件是
3级目录文件1
3级目录文件2
3级目录文件3
3级目录文件4

这样的结果，遇到多级目录的文件夹，下载之后的结果很不理想，有时候文件名一样还不知道如何手动分类回去。

BaiduExporter那边似乎有过更新修复，请考虑同步更新一下mo的扩展，谢谢。

**Comment by agalwood** [comment]
MO.app-设置
![image](https://user-images.githubusercontent.com/1032175/57458594-37548600-72a4-11e9-961b-31355cc47b01.png)
