### ISSUE TITLE
我发现在motrix在windows 10上无法把线程数设置为64

### ISSUE THREAD

**Issue by amocken** [agalwood/Motrix#263]
现在最大只能把线程数设置为16，然后就无法再往上调了
motrix版本是1.3.8，Windows 10版本是1809
![批注 2019-05-12 133001](https://user-images.githubusercontent.com/48198083/57578246-c6d38200-74ba-11e9-8bca-255c1ff164f7.jpg)

**Comment by zyiii12** [comment]
因为是aria2的原因吧，aria2最多只能设置到16

**Comment by Takwah** [comment]
我也是

**Comment by agalwood** [comment]
Motrix Windows 和 Linux 版集成的 aria2 是官方原版的，单任务最大线程限制为 16，macOS 版我也考虑改回用官方原版的…线程数太大下 du 盘其实容易被封的 :-I

**Comment by amocken** [comment]
> Motrix Windows 和 Linux 版集成的 aria2 是官方原版的，单任务最大线程限制为 16，macOS 版我也考虑改回用官方原版的…线程数太大下 du 盘其实容易被封的 :-I

设置多线程不一定只在下网盘的时候用啊，去国外的网站下东西也需要多线程来提高速度，现在电脑的下载器普遍都最高只能设置成10个线程，所以我当我去国外的网站下载东西比较慢的时候都要用手机上的夸克浏览器下，下完之后传电脑里

**Comment by agalwood** [comment]
已经升级到 aria2 v1.3.5 并全系统开放了 64 线程下载，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases

**Comment by maxTanAlpha** [comment]
mac上1.5.15可以最多到64，但是我实际下载只到四五个，大佬有什么解决办法吗
