### ISSUE TITLE
希望可以添加chrome下载支持功能

### ISSUE THREAD

**Issue by ShadyWhite** [agalwood/Motrix#264]
希望可以添加chrome和firefox下载支持功能，像别的下载软件(IDM，迅雷等)通过浏览器拓展插件实现，谢谢

**Comment by AppJ-GS** [comment]
百度网盘的话可以用扩展，至于网站下载可以右键先复制下载地址，打开就会自动粘贴了（前提是要先运行）

**Comment by agalwood** [comment]
Chrome 接管下载可以看下这个文档：
https://www.yuque.com/moapp/help/extensions#22993f87

**Comment by lanw0622** [comment]
> Chrome 接管下载可以看下这个文档：
> https://www.yuque.com/moapp/help/extensions#22993f87

safari有什么别的方式吗 大佬

**Comment by agalwood** [comment]
@lanw0622 Safari 拦截参见 https://github.com/agalwood/Motrix/issues/291#issuecomment-496001432
