### ISSUE TITLE
求助，npm run dev时报错“process is not defined...”

### ISSUE THREAD

**Issue by wjf2016** [agalwood/Motrix#267]
报错信息：
![截图](https://s2.ax1x.com/2019/05/15/ETafBQ.png)

 ERROR in Template execution failed: ReferenceError: process is not defined      
                                                                                 
 ERROR in   ReferenceError: process is not defined                               
                                                                                 
   - index.ejs:11 eval                                                           
     [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:11:2                
                                                                                 
   - index.ejs:16 module.exports                                                 
     [.]/[html-webpack-plugin]/lib/loader.js!./src/index.ejs:16:3                
                                                                                 
   - index.js:284                                                                
     [Motrix]/[html-webpack-plugin]/index.js:284:18                              
                                                                                 
   - task_queues.js:89 processTicksAndRejections                                 
     internal/process/task_queues.js:89:5

**Comment by agalwood** [comment]
老铁，你目前提供的这些信息我帮不了你，麻烦补充一下 node 相关的信息

目前这些信息我也只能提醒你升级一下 node 版本、npm 版本、删除 node_modules 重新 npm install 什么的

**Comment by jjandxa** [comment]
确认一下 node、npm 版本，请使用 node v10.15.3、npm 6.4.1 版本

**Comment by caryhgq** [comment]
遇到同样问题

![image](https://user-images.githubusercontent.com/6456736/59157866-e8894e80-8ae4-11e9-8f12-ca539784badf.png)
![image](https://user-images.githubusercontent.com/6456736/59157870-f63ed400-8ae4-11e9-8fc8-1db5f12ec030.png)

**Comment by agalwood** [comment]
@caryhgq 删除 node_modules 目录，重新安装依赖

```
npm config set registry 'https://registry.npm.taobao.org'
export ELECTRON_MIRROR='https://npm.taobao.org/mirrors/electron/'
export SASS_BINARY_SITE='https://npm.taobao.org/mirrors/node-sass'
npm install
```

**Comment by a646911949** [comment]
我今天也遇到，谷歌了很久，终于解决了，技术把node 12.4开发版还原到10.16稳定版 然后删除node_modules 再install就可以了

**Comment by Joeyscat** [comment]
> 我今天也遇到，谷歌了很久，终于解决了，技术把node 12.4开发版还原到10.16稳定版 然后删除node_modules 再install就可以了

 感谢
