### ISSUE TITLE
没有批量删除任务功能？

### ISSUE THREAD

**Issue by nickrogit** [agalwood/Motrix#27]
没有批量删除任务功能？

**Comment by agalwood** [comment]
会有的，暂未实现😑

**Comment by lolstudio** [comment]
+1，请尽快实现

**Comment by huanzhiyi** [comment]
这个的确很需要  今天狂删出错的网盘任务  上百个

**Comment by xysemies** [comment]
误加入上百个出错的任务....
好像MO每次启动会重新加载一遍,然后狂跳...
+1 
希望增加批量删除功能

**Comment by Thinkbond** [comment]
+ 1

**Comment by boomstack** [comment]
Linux系统，安装xdotool（一个模拟键盘鼠标事件的软件,apt-get install xdotool即可安装），把鼠标悬停在删除按钮，执行下面的脚本即可，
一个一个慢慢删除，省的人工操作
`for I in {1..1000};do
	xdotool mousedown 1
	xdotool mouseup 1
	xdotool keydown Down
	sleep 1
	xdotool keydown Return
	sleep 1
	echo "delete one file success $I"
done`

**Comment by jegooCN** [comment]
批量删除+1

**Comment by dbcoffee** [comment]
批量删除，很期待！

**Comment by EricInCD** [comment]
半年过去了，同求。。。

**Comment by yanli0303** [comment]
+1

**Comment by allonli** [comment]
今天删除了500多个文件，我是不是很厉害

**Comment by venhow** [comment]
确实很需要

**Comment by agalwood** [comment]
已添加了鼠标拖拽选中任务批量删除功能，请更新 Motrix 到 v1.5.x 版本https://github.com/agalwood/Motrix/releases

**Comment by yaner92** [comment]
亲测可用！进入以下目录\AppData\Roaming\Motrix\，删除这个download.session，实现全部删除(教程来自原网址https://www.shuge.org/meet/topic/16089/)
