### ISSUE TITLE
:BUG REPOR: it seems that the downloader will download a copy of the web page instead of the file

### ISSUE THREAD

**Issue by Hellzbellz123** [agalwood/Motrix#271]
**Describe the bug**
file downloads are downloading the entire html page instead of just the target file

**To Reproduce**
copy link
download link
open downloaded file in text editor and poof its html

**Expected behavior**
download manager shjould download the file on the page first try instead of downloading the entire webpage

 - OS & Version: Windows
 - Version: Windows 10
 - Motrix Version: 1.3.8 [engine version 1.34.0]
 - Installation package type: [e.g. dmg, AppImage]

**Comment by Hellzbellz123** [comment]
also 2 things, the download manager should 100% not switch to a torrent when you drag a link over and why does the windows variant use 32bit aria2c?

**Comment by Hellzbellz123** [comment]
im busy digging in the source to try to find out why

**Comment by ChenyangGao** [comment]
Many downloaders also this proplem, I think there was a complex jump mechanism. When I use the link in browsers, some JavaScript code would be executed, that might be the problem.

**Comment by Hellzbellz123** [comment]
JDownloader2 can handle the link just fine if that's any help

**Comment by agalwood** [comment]
1. Please provide the link you said.
2. Drag and drop operations currently only support drag-in for torrents.
3. In order to support the Windows 32-bit version. The installation package (Motrix-Setup-1.3.8.exe) supports both 32-bit and 64-bit systems, so aria2c uses a 32-bit version under compromise. Maybe it's my understanding of the electron-builder documentation is not enough.

**Comment by Hellzbellz123** [comment]
using aria2c 32bit would mean that it cant handle large files wouldnt it? or does aria store files as it downloads?

**Comment by Hellzbellz123** [comment]
https://megaup.net/26uyW/testfile.zip

careful on what you click and i really would recommend using a browser with ublock origin

**Comment by agalwood** [comment]
This is not a bug. This kind of network disk link is not directly downloadable, it is a real link to the resource, and there is also a verification code authentication. This type of network disk link is not supported at this time.
