### ISSUE TITLE
启动时能最小化以及能重手动新载入

### ISSUE THREAD

**Issue by ChromeHu** [agalwood/Motrix#275]
1. 希望能有在启动时最小化到托盘的参数。
2. 希望能添加一个手动重新加载软件的功能。

**原因**
1. 我将此设置成开机自启项目，但是每次进入桌面都会有个窗口来关闭。希望能直接最小化的启动。
2. 有时候此应用RPC会出现连接不上的情况，需要退出重新打开。但是我并没有放快捷方式在桌面上，因为我桌面东西太多了。所以造成了一些麻烦。

**或许可行的解决方式**
1. 添加一个最小化启动参数（或许有这个操作，但是我并不清楚）。
2. 希望在托盘图标的右键菜单中添加一个重新载入的选项。

**Comment by agalwood** [comment]
1. 开机自动启动的特性已经实现了 https://github.com/agalwood/Motrix/pull/246 ，下版本发布
2. 应该是 aria2c 没启动成功，重新载入（重启 aria2c ）这个功能可以加一下

**Comment by agalwood** [comment]
Motrix 新版本 v1.4.x 已经发布，更新到最新版本就支持开机自动启动了（启动后不会显示主窗体）

新版本还提高了引擎保活次数，手动重启引擎这个功能还要等下版本了

https://github.com/agalwood/Motrix/releases

**Comment by ChromeHu** [comment]
好的。

顺便问下，代理服务怎么用，我无法连接到我的 v2ray 。 v2ray 允许来自局域网的连接，但是我怎样都不行，下载出现错误代码 “1” ，可以的话希望能出个教程。

**Comment by agalwood** [comment]
v2ray 配置你参考下 https://github.com/v2ray/v2ray-core/issues/603 ，输出 http 协议的代理

然后找到 Motrix ——偏好设置——进阶设置——代理，打开「使用代理服务器」
输入类似 `http://127.0.0.1:3128` 的地址，保存并应用
