### ISSUE TITLE
下不了种子

### ISSUE THREAD

**Issue by Juddd** [agalwood/Motrix#276]
**错误描述**
清楚简洁地描述错误，方便我们复现之后处理。
下不了种子文件

**截图**
![](https://i.stack.imgur.com/wzTgt.png)

**运行环境**
 - 操作系统类型： Windows10
 - 具体版本： 版本号是1803
 - Motrix 版本： v1.3.8
 - 安装包类型：exe

有些还是能下的，但有些种子就下不来，比如附件里娄烨导演的《颐和园》就下不来，可以帮我看下吗？是我的种子有问题还是你的下载工具有问题呢

[颐和园.zip](https://github.com/agalwood/Motrix/files/3201407/default.zip)

**Comment by wenliyang** [comment]
下载附件看了，这种子文件生成日期是2013年4月18日

楼主你确定还有人在做种么

**Comment by Juddd** [comment]
我也不知道，网上下的...听您这么说的话可能是种子有问题？

**Comment by weearc** [comment]
BT能下载动的前提是有人在做种（一个人下载靠其他人的上传）。没人做种就凉了。


 
---原始邮件---
发件人: "yode"<notifications@github.com>
发送时间: 2019年5月21日 16:59:03
收件人: "agalwood/Motrix"<Motrix@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [agalwood/Motrix] 下不了种子 (#276)



我也不知道，网上下的...听您这么说的话可能是种子有问题？

**Comment by Juddd** [comment]
好吧，谢谢两位，我原以为种子是永远不会凉的，所以大家才用它来存小黄片...
