### ISSUE TITLE
按钮的有效区域太小了

### ISSUE THREAD

**Issue by HanqingTony** [agalwood/Motrix#277]
**Is your feature request related to a problem? Please describe.**
左侧功能栏的按钮，默认状态下并没有很明显的边界，需要使用的时候，才发现必须把鼠标移到那个小小的范围内才可以，使得使用起来并不流畅。

建议向win10的ui学习，按钮有效区直接就是大方块，贼爽。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by agalwood** [comment]
你可以使用快捷键：D
