### ISSUE TITLE
百度云盘下载的文件解压密码不对

### ISSUE THREAD

**Issue by seed1107** [agalwood/Motrix#279]
从百度云盘下载下来的文件，解压密码提示错误，用官方客户端重新下载，同样的解压密码可以解压。换了个文件试了一下还是一样。

**Comment by agalwood** [comment]
老铁，你这是空口报 bug 啊，请按 issue 模板补充信息
https://github.com/agalwood/Motrix/issues/new?assignees=&labels=&template=bug_report_cn.md&title=
