### ISSUE TITLE
希望下载源做个国内CDN加速

### ISSUE THREAD

**Issue by liyuxi** [agalwood/Motrix#280]
Motrix下载更新的话不挂梯子真的越来越难下了，而且最近局势。。。

**Comment by agalwood** [comment]
没有赞助商，CDN用不起...你可以简单算下一个月要多少流量
https://www.somsubhra.com/github-release-stats/?username=agalwood&repository=Motrix

**Comment by SPRCSY** [comment]
希望可以把项目转到码云Gitee上

**Comment by ookangzheng** [comment]
試一試這些
https://cdn.statically.io/gh/agalwood/Motrix/releases/download/v1.3.8/Motrix-1.3.8.dmg
https://cdn.statically.io/gh/agalwood/Motrix/releases/download/v1.3.8/Motrix-1.3.8.exe
https://cdn.statically.io/gh/agalwood/Motrix/releases/download/v1.3.8/Motrix-Setup-1.3.8.exe
https://cdn.statically.io/gh/agalwood/Motrix/releases/download/v1.3.8/Motrix-1.3.8-ia32-win.zip
https://cdn.statically.io/gh/agalwood/Motrix/releases/download/v1.3.8/Motrix_1.3.8_amd64.deb

**Comment by lengthmin** [comment]
github 有个项目 jsproxy 
可以网页版代理github来下载

**Comment by agalwood** [comment]
搞了台 CN2 线路的主机作为安装包的下载镜像，现在官网下载应该快多了

不过一个月就 1TB 的流量，希望够用
