### ISSUE TITLE
百度云下载提示错误

### ISSUE THREAD

**Issue by joshatt** [agalwood/Motrix#281]
**错误描述**
清楚简洁地描述错误，方便我们复现之后处理。

初次使用,尝试了下载4集电视剧,第7到第10集....下载第7集出现提示"错误,是否已经运行aria2", 其实我已经运行了啊...我点击了按钮菜单中的"启动mo"，这时候提示文件协议, 我点了自动并同意协议，这时候去mo查看发现已经开始下载了，然后我尝试第8集和第9集的下载都在网页中提示已经成功开始，但是去mo查看闪现红字错误"xxxx下载错误"，然后就错误提示消失，这两集都自动归入"已停止"中了...........然后第7集没有下载完的状况下我去截图,打开了mo的开发者模式, 此时第8集第9集也出现在第7集旁边了，但是第7集变成了进度零未开始的状态........关掉了开发者模式，我尝试下载第10集,这次仍然提示是否已打开aria2. 去mo查看发现也开始下载了，但是点击第789集的开始三角, 仍然提示红字错误,并归入已停止

**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接（如链接不涉及到隐私和版权问题，请顺便提供）
3. 点击提交
4. 发现报错

**预期的行为**
清楚简洁地描述你期望发生的事情。

**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

![Alt Text](https://images2.imgbox.com/90/0e/FZ2RK85L_o.jpg)

**运行环境**
 - 操作系统类型： [如 macOS, Windows, Linux] Windows
 - 具体版本： [如 macOS 10.14.2, Windows 10, Ubuntu 18.04]  win7 x64
 - Motrix 版本： [如 v1.1.3, v1.1.0] v1.3.8
 - 安装包类型：[如 dmg, AppImage] exe

**更多信息**
补充有关该问题的其他信息。

**Comment by agalwood** [comment]
应该是被限速了，百度服务器断开了连接报错造成了 aria2 的崩溃
https://www.yuque.com/moapp/help/extensions#9414e50b

**Comment by joshatt** [comment]
> 应该是被限速了，百度服务器断开了连接报错造成了 aria2 的崩溃
> https://www.yuque.com/moapp/help/extensions#9414e50b

谢谢帮助

**Comment by joshatt** [comment]
后续测试, 稳定了很多了, 每次添加任务都提示下载错误是否已运行mo, 但实际上都正常开始下载了. 仍然处于限速期, 每个任务20-40k, 只有一个任务100-200k速度. 等正常了再试
