### ISSUE TITLE
磁力链接识别

### ISSUE THREAD

**Issue by xyyuchn** [agalwood/Motrix#282]
希望能够识别去掉开头“magnet:?xt=urn:btih:”的磁力链接
如将BEFC37E56981937E7645C8613FC62BC6F711A430&dn=Grand%20Theft%20Auto%20IV%20-%20Complete%20Edition%20%5BFitGirl%20Repack%5D
识别为
magnet:?xt=urn:btih:BEFC37E56981937E7645C8613FC62BC6F711A430&dn=Grand%20Theft%20Auto%20IV%20-%20Complete%20Edition%20%5BFitGirl%20Repack%5D

**描述你想要的解决方案**
我不懂该如何实现。。。我觉得有这个功能会方便一些。
Thank you for your time.

**Comment by agalwood** [comment]
好冷门的需求...自己补全吧

https://zh.wikipedia.org/wiki/%E7%A3%81%E5%8A%9B%E9%93%BE%E6%8E%A5
没有前面那部分其实都没法确定是什么协议的

**Comment by xyyuchn** [comment]
好吧。
Thank you for your time.
