### ISSUE TITLE
在arm64的debian上编译遇到问题

### ISSUE THREAD

**Issue by MCredbear** [agalwood/Motrix#283]
**错误描述**
下面是我的log:
firefly@firefly:~/Motrix$ proxychains npm install
[proxychains] config file found: /etc/proxychains4.conf
[proxychains] preloading /usr/lib/aarch64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.13
[proxychains] DLL init: proxychains-ng 4.13
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  registry.npmjs.org:443  ...  OK

> node-sass@4.11.0 install /home/firefly/Motrix/node_modules/node-sass
> node scripts/install.js

[proxychains] DLL init: proxychains-ng 4.13
[proxychains] DLL init: proxychains-ng 4.13
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/linux-arm64-64_binding.node
[proxychains] Strict chain  ...  127.0.0.1:2333  ...  github.com:443  ...  OK
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/linux-arm64-64_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@4.11.0 postinstall /home/firefly/Motrix/node_modules/node-sass
> node scripts/build.js

[proxychains] DLL init: proxychains-ng 4.13
[proxychains] DLL init: proxychains-ng 4.13
Building: /usr/bin/node /home/firefly/Motrix/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
[proxychains] DLL init: proxychains-ng 4.13
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/home/firefly/Motrix/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.2 | linux | arm64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 10.15.2
gyp verb command install [ '10.15.2' ]
gyp verb install input version string "10.15.2"
gyp verb install installing version: 10.15.2
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 10.15.2
gyp verb build dir attempting to create "build" dir: /home/firefly/Motrix/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/firefly/Motrix/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/firefly/Motrix/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/firefly/Motrix/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/firefly/Motrix/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
[proxychains] DLL init: proxychains-ng 4.13
gyp info spawn args [ '/home/firefly/Motrix/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/firefly/Motrix/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/firefly/Motrix/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/firefly/.node-gyp/10.15.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/firefly/.node-gyp/10.15.2',gyp info spawn args   '-Dnode_gyp_dir=/home/firefly/Motrix/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/firefly/.node-gyp/10.15.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/firefly/Motrix/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
[proxychains] DLL init: proxychains-ng 4.13
[proxychains] DLL init: proxychains-ng 4.13
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/firefly/Motrix/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.4.114-00004-gdfc5669-dirty
gyp ERR! command "/usr/bin/node" "/home/firefly/Motrix/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/firefly/Motrix/node_modules/node-sass
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/firefly/.npm/_logs/2019-05-23T14_23_18_212Z-debug.logfirefly@firefly:~/Motrix$
**运行环境**
 debian sid arm64

**Comment by agalwood** [comment]
你这看起来是 node-sass 安装失败啊
安装依赖的问题可以看下 README
https://github.com/agalwood/Motrix/blob/master/README-CN.md#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96

以及这个 issue https://github.com/agalwood/Motrix/issues/278
