### ISSUE TITLE
YAAW无法使用

### ISSUE THREAD

**Issue by cainingw** [agalwood/Motrix#284]
**错误描述*
YAAW报错 导出下载失败，YAAW的界面也和帮助文档里面长得不一样

**如何重现**
重现步骤，如：
1. 右键ARIA2 RPC
2. 发现报错

**预期的行为**
能够成功下载
**截图**
![image](https://user-images.githubusercontent.com/47291283/58302556-5e857a00-7db1-11e9-930b-f9e8987e0bd2.png)
![image](https://user-images.githubusercontent.com/47291283/58302586-8e348200-7db1-11e9-859c-d44b43aa99e4.png)
![image](https://user-images.githubusercontent.com/47291283/58302609-af956e00-7db1-11e9-8e89-8f1919818813.png)

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： Windows 10
 - Motrix 版本： v1.3.8
 - 安装包类型：exe

**更多信息**
补充有关该问题的其他信息。

**Comment by agalwood** [comment]
Motrix 启动了么？

**Comment by cainingw** [comment]
> Motrix 启动了么？

启动了，百度网盘的插件可以正常使用

**Comment by agalwood** [comment]
这个扩展有两个选项，一个是内置的 YAAW，另一个是右键菜单和拦截文件的选项页面，
地址复制到 Chrome 地址栏打开，把 RPC 地址配置一下： http://localhost:16800/jsonrpc
chrome-extension://dennnbdlpgjgbcjfgaohdahloollfgoc/options.html

**Comment by cainingw** [comment]
> 这个扩展有两个选项，一个是内置的 YAAW，另一个是右键菜单和拦截文件的选项页面，
> 地址复制到 Chrome 地址栏打开，把 RPC 地址配置一下： http://localhost:16800/jsonrpc
> chrome-extension://dennnbdlpgjgbcjfgaohdahloollfgoc/options.html

谢谢，可以了
