### ISSUE TITLE
Mac OS 无法新建任务 fail to fetch

### ISSUE THREAD

**Issue by DiumSuGie** [agalwood/Motrix#285]
Mac OS 10.14.3 官网最新版.dmg

问题：无法新建任务，尝试多个种子和链接，全部显示**fail to fetch**

aria2c进程是开的，也尝试用sudo命令重新打开Motrix，仍不能解决。

尝试添加任务后，一直无限报错
![image](https://user-images.githubusercontent.com/23391831/58344347-ff466900-7e87-11e9-8e55-80cdac1db3d8.png)

**Comment by agalwood** [comment]
你用系统的“终端”，输入
`ping localhost`
看下是否解析为 127.0.0.1

不是的话去`/etc/hosts` 里加一条记录
`127.0.0.1 localhost`

**Comment by DiumSuGie** [comment]
是解析为127.0.0.1，hosts里也已经有这一条了 但还是不能添加，磁力链接或种子都是fail to fetch

**Comment by agalwood** [comment]
看下这个 issue https://github.com/agalwood/Motrix/issues/109 是否有关

**Comment by mugkid** [comment]
macOS 10.14.5 Motrix 1.3.8, same issue here.

**Comment by lipomzx** [comment]
macOS 10.14.4 motrix 1.4.1 终端没有问题，还是fail to fetch

**Comment by uniquepengpeng** [comment]
检查下代理设置,我的是添加了socks5代理,没有添加localhost例外,导致上面一样的错误.改下就好了.
