### ISSUE TITLE
Setting to disable BitTorrent

### ISSUE THREAD

**Issue by davidchalifoux** [agalwood/Motrix#287]
**Describe the solution you'd like**
Most of my time is spent at University where I am "jailed" whenever BitTorrent traffic is detected. I'd like to use Motrix as a JDownloader2 replacement, however I'm fearful of accidentally starting a BitTorrent download and having my connection shut-off because of it.

What would be useful for me, which I know is a niche problem, would be a toggle in the settings for completely disabling BitTorrent. That way there would be no worry.

**Comment by agalwood** [comment]
Motrix's built-in download engine is [aria2](https://aria2.github.io/manual/en/html/aria2c.html), and I didn't find the relevant settings to disable the BT feature.

**Comment by davidchalifoux** [comment]
@agalwood Maybe it could be blocked through the UI in some way?

**Comment by theweavrs** [comment]
@davidchalifoux see #305 maybe that is what you require. The most you can do is disable Motrix as the default client for handling magnet links. We have added this in #308

**Comment by davidchalifoux** [comment]
@theweavrs This is better than nothing. Thanks for letting me know!

**Comment by agalwood** [comment]
The new version has been released and it is now possible to turn off Motrix's binding to the magnet link.

https://github.com/agalwood/Motrix/releases
