### ISSUE TITLE
新建任务时无法用回车直接开始任务

### ISSUE THREAD

**Issue by dutry** [agalwood/Motrix#288]
完全键盘操作，Command+N打开新建任务，然而回车或者Ctrl/Command+回车都无法开始，还得用触摸板挪动点击开始，这比较不方便。‘

希望能回车直接开始。

**Comment by agalwood** [comment]
Good advice, added to TODO https://trello.com/c/IRfuhrbk/52

**Comment by agalwood** [comment]
已支持，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
