### ISSUE TITLE
Linux希望增加种子或者磁力链接的下载文件列表编辑功能

### ISSUE THREAD

**Issue by hzz1189** [agalwood/Motrix#289]
**请描述一下你的新功能请求是否与已知问题有关？**
反馈问题之前特地查询了一下反馈列表，还没人提出过这个功能需求

**描述你想要的解决方案**
当添加磁力链接或者种子任务后，能让使用者编辑决定需要下载哪些文件哪些不需要。

**描述你考虑过的替代方案**
非要考虑替代的话，当然是使用迅雷了，但我更想支持Linux原生应用。

**更多信息**
正在Linux发行版deepin上使用发现的问题。

**Comment by agalwood** [comment]
这功能已经开发完了，下版本发布，如果想尝鲜，你可以克隆代码自己 build，具体参考 https://github.com/agalwood/Motrix/blob/master/README-CN.md#%EF%B8%8F-%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91

**Comment by agalwood** [comment]
Motrix v1.4.x 已经发布，请更新到最新版

https://github.com/agalwood/Motrix/releases
