### ISSUE TITLE
下载文件名残缺BUG！

### ISSUE THREAD

**Issue by zealson** [agalwood/Motrix#29]
如图所示，偶尔遇到过，一直忘了反馈

![xnip2019-01-19_00-15-04](https://user-images.githubusercontent.com/19618658/51398784-6f15b180-1b7f-11e9-8bfb-ce7ac05898dd.png)
![xnip2019-01-19_00-14-43](https://user-images.githubusercontent.com/19618658/51398788-71780b80-1b7f-11e9-86d0-ec22fc8ecf48.png)

**Comment by zealson** [comment]
呃😓，之前貌似一直没有这个问题的，现在几乎100%出现了。。。。也不知道怎么解决。。
<img width="1043" alt="xnip2019-01-21_09-49-39" src="https://user-images.githubusercontent.com/19618658/51448501-06d2f580-1d62-11e9-9a75-e89b73abda39.png">

**Comment by agalwood** [comment]
通过抓包发现，直接下载他人分享的文件会出现文件名截断的问题，临时解决方案是先“保存到网盘”再下载就正常了，可能和某度最近的改动有关：（
已更新到使用文档
https://www.yuque.com/moapp/help/extensions#evqwnu

**Comment by zealson** [comment]
😄~看来下一版的MO Helper扩展就要上线了~

**Comment by zealson** [comment]
我今天突发奇想到一个建议，希望开发者能够考虑下，间接解决方案：
用户点击网页的“MO下载”是唤起一个Motrix的对话框，让用户可以自定义下载文件的文件名，这样省的我每次一定要等Motrix下载完之后，再去记起去重命名缺省的文件名了，类似新建下载任务一样那种，我现在几乎在百度盘下载的文件，文件名全部都是缺失的， 这样导致我每次都要去导出复制正确的文件夹，进行二次重命名的，真心麻烦，希望能把这个重命名的操作前置，方便用户及时处理，谢谢了~

**Comment by agalwood** [comment]
@zealson 不用这么麻烦了，这个问题我应该修掉了
https://github.com/agalwood/BaiduExporter/commit/4403745782733d13477e0aad01f51686334ee65e

你帮忙验证一下，重新下载 BaiduExporter
https://motrix.app/release/BaiduExporter.zip
照着 [教程](https://www.yuque.com/moapp/help/extensions) 再安装一遍测试一下

**Comment by zealson** [comment]
> @zealson 不用这么麻烦了，这个问题我应该修掉了
> [agalwood/BaiduExporter@4403745](https://github.com/agalwood/BaiduExporter/commit/4403745782733d13477e0aad01f51686334ee65e)
> 
> 你帮忙验证一下，重新下载 BaiduExporter
> https://motrix.app/release/BaiduExporter.zip
> 照着 [教程](https://www.yuque.com/moapp/help/extensions) 再安装一遍测试一下
> 
> 还有，下次请新开 issue 讨论

已测试，完全OK了，谢谢开发者😉

**Comment by zealson** [comment]
希望日后能提供一个MO Helper的crx扩展文件就完美了 @agalwood

**Comment by tiritr** [comment]
![2019-03-13 (2)](https://user-images.githubusercontent.com/42647440/54255234-364bf480-4592-11e9-920c-55cb84dd4623.png)
wei未封装的的拓展程序什么意思
