### ISSUE TITLE
希望能添加safari插件，更改safari的默认下载方式

### ISSUE THREAD

**Issue by lanw0622** [agalwood/Motrix#291]
如题。。。因为现在主要用的 safari，每次想用matrix 都要复制下载链接。。比较麻烦，希望可以开发safari拓展插件。。。谢谢啦

**Comment by agalwood** [comment]
更多的浏览器扩展暂时没精力开发：|

Safari 你可以先试试这个扩展：
https://github.com/miniers/safari2aria
