### ISSUE TITLE
提交任务后错误提示不够友好

### ISSUE THREAD

**Issue by axer0910** [agalwood/Motrix#293]
**错误描述**
1. 新建任务点击提交按钮后直接提示下载发生错误，并且任务消失，需要重新添加任务。下载未开始的文件占用了磁盘空间。错误原因需要手动在代码里console才能发现。

**预期的行为**
希望能够友好地把开始任务错误原因显示出来或者日志里可以有所体现。
磁盘空间不足建议开始任务前先检测磁盘空间是否足够，端口的话可以先检测一下BT端口是否被占用，最好有类似迅雷编辑端口的界面。

**截图**
**发生错误截图**
![MotrixError](https://user-images.githubusercontent.com/17276259/58399813-f58d5300-808b-11e9-958f-92f8989f457a.jpg)
**下载磁盘空间不足错误**
![noenoughspace](https://user-images.githubusercontent.com/17276259/58399862-1fdf1080-808c-11e9-9676-aaa9beb65034.jpg)
**BT端口绑定错误**
![Motrixerror2](https://user-images.githubusercontent.com/17276259/58399873-279eb500-808c-11e9-9457-bf9d326c0115.jpg)

**运行环境**
 - 操作系统类型：Windows
 - 具体版本：Windows10 1903
 - Motrix 版本： v1.3.8
 - 安装包类型：exe

**Comment by agalwood** [comment]
感谢，我知道这里有报错信息和报错码，每个报错信息都得做国际化比较麻烦就先偷懒了 : (
https://aria2.github.io/manual/en/html/aria2c.html#id1

**Comment by agalwood** [comment]
Motrix 新版本 v1.4.x 对下载错误信息做了简单的优化，请升级到最新版本

https://github.com/agalwood/Motrix/releases
