### ISSUE TITLE
download.session无法删除任务

### ISSUE THREAD

**Issue by inidan** [agalwood/Motrix#297]
**请描述一下你的新功能请求是否与已知问题有关？**
简明扼要地描述了问题所在。

**描述你想要的解决方案**
简明扼要地描述你想要的解决方案。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by inidan** [comment]
清空或者删除download.session文件无法达到删除任务的目的，并且在文件设置为只读的情况下，会生成download.sessiontmp文件是的下载能够继续。

**Comment by inidan** [comment]
想请问一下下载的逻辑是什么或者读取的文件是哪个。

**Comment by agalwood** [comment]
1. 找到 download.session 后完全退出 Motrix
2. 删除 download.seesion
3. 启动 Motrix

还有，老铁，你这明明是问题反馈，为啥用新特性请求的 issue 模板？

**Comment by inidan** [comment]
哈哈，抱歉，以问题的形式发起了新特性请求。
