### ISSUE TITLE
建议: 添加手动检查更新

### ISSUE THREAD

**Issue by FTFX** [agalwood/Motrix#298]
**请描述一下你的新功能请求是否与已知问题有关？**
否。

**描述你想要的解决方案**
添加手动检查更新按钮。

**描述你考虑过的替代方案**
例如在设置中，或者在托盘图标菜单中添加“检查更新”。

**Comment by agalwood** [comment]
主菜单里第一项里有「检查自动更新」，Windows 和 Linux 默认隐藏了主菜单，在偏好设置-进阶设置-隐藏菜单栏 的勾去掉，保存并应用，主菜单就出现了

下版本在偏好设置里再加个检查的入口吧

**Comment by FTFX** [comment]
对了，还有一个是“检查自动更新”选项是开机检查更新还是启动软件检查更新啊

**Comment by agalwood** [comment]
启动应用的时候
