### ISSUE TITLE
UI建议：保存设置按钮位置

### ISSUE THREAD

**Issue by AdrianDuan** [agalwood/Motrix#299]
**请描述一下你的新功能请求是否与已知问题有关？**
<img width="1136" alt="屏幕快照 2019-06-05 上午11 40 52" src="https://user-images.githubusercontent.com/26034046/58929120-18082600-8788-11e9-8869-6b4140acc5c5.png">

当设置内容太多时，下方的保存设置的按钮会遮挡住后方的设置内容

**描述你想要的解决方案**

建议将“保存并应用”的按钮移到右上角，和“进阶设置”的标题栏对齐

**Comment by agalwood** [comment]
感谢建议，让我考虑一下

**Comment by agalwood** [comment]
已调整，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
