### ISSUE TITLE
如何设置为chrome默认下载器

### ISSUE THREAD

**Issue by saivin** [agalwood/Motrix#30]
就像IDM,FDM那样能够嗅探到下载链接那种。我不想每次用motrix下载东西还要复制地址进来新建下载啊？

**Comment by agalwood** [comment]
暂不支持，需要开发新的浏览器扩展 MO Helper 才能实现吧

**Comment by agalwood** [comment]
发现市场上有扩展可以配合支持：P
https://github.com/agalwood/Motrix/issues/38#issuecomment-458887401
