### ISSUE TITLE
用scoop无法安装Motrix

### ISSUE THREAD

**Issue by Safe-And-Sound** [agalwood/Motrix#302]
个人先要便捷版的 所以根据readme.md里的说明 在电脑上安装 scoop之后 运行scoop install motrix 命令 无法安装 
这是运行scoop search motrix.后的返回结果
Results from other known buckets...
(add them using 'scoop bucket add <name>')

'extras' bucket:
    bucket/motrix
执行scoop install motrix 命令 返回以下错误:
Couldn't find manifest for 'motrix'.

**Comment by agalwood** [comment]
Motrix 属于 scoop 的 extras 包，所以要先添加 extras 这个 bucket
`scoop bucket add extras`
添加完之后再执行`scoop install motrix`，我更新一下 README

**Comment by Safe-And-Sound** [comment]
本来是打算来提可以自定义安装位置的,后面阅读后发现了便捷安装的方式由于第一次使用scoop,就不是很清楚,打扰了
