### ISSUE TITLE
macOS 10.14.1 百度网盘下载错误

### ISSUE THREAD

**Issue by suleymanqian** [agalwood/Motrix#303]
**错误描述**
百度网盘点击“使用MO下载”按钮后显示“下载成功”，打开MO之后却发现任务显示在“已停止”一栏中并且不可恢复。

**如何重现**
1. 点击“使用MO下载”
2. 显示“下载成功”
3. 进入MO发现任务显示在“已停止”一栏中并且不可恢复

**预期的行为**
恢复百度网盘正常下载

**截图**
![屏幕快照 2019-06-07 11 54 06](https://user-images.githubusercontent.com/51469594/59080407-23d82180-891b-11e9-8656-0ba42732bcc3.png)

**运行环境**
 - 操作系统类型： macOS
 - 具体版本：macOS 10.14.1 
 - Motrix 版本： 1.33.1
 - 安装包类型：dmg

**Comment by agalwood** [comment]
度盘链接发下

https://www.yuque.com/moapp/help/extensions#ec09647d

**Comment by agalwood** [comment]
如果添加任务出现 `SSL/TLS handshake failure: Unspecified error -9847` 错误，检查一下系统的 DNS 是不是 `223.5.5.5` 或 `223.6.6.6`，换成 `114.114.114.114` 试试

**Comment by agalwood** [comment]
Motrix 新版本 v1.4.x 不再校验服务器的 SSL 证书有效性，建议更新到最新版

https://github.com/agalwood/Motrix/releases
