### ISSUE TITLE
希望能增加各个协议的绑定开关

### ISSUE THREAD

**Issue by allenfoxtc** [agalwood/Motrix#305]
装了Motrix后发现Chrome打开magnet连接都默认用Motrix打开了，看了ProtocolManager.js发现默认绑定了magnet，这个可以在设置里面变成可配的开关不？

谢谢~

**Comment by theweavrs** [comment]
Yes, this should be an option. @agalwood I can make a PR addressing this request if you want.

**Comment by agalwood** [comment]
![image](https://user-images.githubusercontent.com/1032175/59171158-5d579980-8b74-11e9-93b2-5285ee6970ad.png)

Hi @theweavrs,

Very welcome if you want to implement this feature request. You can refer to my implementation plan. 
And I have completed part of it yesterday, you can continue development on this branch, and submit MR after development.

Git commit message Please refer to https://www.conventionalcommits.org/

- [x] Add a key named 'protocols' to the ConfigManager.userConfig. Defaults: {'magnet': true, 'thunder': false}
- [x] Add a key named 'protocols' to src/shared/configKeys.js userKeys.
- [x] Refactor the ProtocolManager's init method to remove the setup method. Implement the register and unregister functions in the setup method. 
- [x] Put this setting in Preferences - Labs, the UI refers to the above screenshot.
- [ ] When saving the Lab's settings, send a command called 'setup-protocols-client' to the main process via IPC.
- [ ] In the Application class handle the 'setup-protocols-client' command, calling the ProtocolManager's setup.
- [ ] Finally, if you are happy, you can complete the internationalization of this setting, refer to the [translation contribution guid](https://github.com/agalwood/Motrix/blob/master/CONTRIBUTING.md#-translation-guide).

PS. Translation of new features I have turned through the Google Translator. Welcome enthusiasts in the community to improve translation.

Some references:
app.removeAsDefaultProtocolClient
https://electronjs.org/docs/all#appremoveasdefaultprotocolclientprotocol-path-args-macos-windows

ipcRenderer
https://electronjs.org/docs/api/ipc-renderer

If you have questions, we can continue to discuss in this issue.

**Comment by theweavrs** [comment]
@agalwood no problem. I will continue your work. I have taken a fairly thorough look through the project and it's relatively easy. Besides, you have done the UI part. I will make a merge request as soon as I am done and then we will see if there are changes needed.

I have one question: will I need to translate this setting into all languages?

**Comment by theweavrs** [comment]
@agalwood one other thing. Does this setting need to be under Lab menu? Wouldn't it make more sense to put it in Advanced?

**Comment by agalwood** [comment]
@theweavrs Yes, you can move to Advanced, before the Lab has a Protocols switch - whether to display BT related features, for Apple Mac App Store review.  

Later, after Motrix opened source, it did not completely remove the relevant logic.  So I am lazy to put the new features in the Lab.

**Comment by agalwood** [comment]
@theweavrs Translation is a chore. Sometimes, in order not to affect the release of the new version, I will use Google Translate to complete the translation of all currently supported languages.

If you feel trouble, leave it to me.
