### ISSUE TITLE
希望可以添加Firefox下载支持功能

### ISSUE THREAD

**Issue by dg1vg4** [agalwood/Motrix#307]
**请描述一下你的新功能请求是否与已知问题有关？**
简明扼要地描述了问题所在。

**描述你想要的解决方案**
简明扼要地描述你想要的解决方案。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by agalwood** [comment]
提的 issue 说的不明不白，我只能猜你是问 BaiduExporter 了，

Firefox 安装请参照文档：
https://github.com/acgotaku/BaiduExporter#install

**Comment by dg1vg4** [comment]
抱歉，准确的说是嗅探下载链接的插件，重点是
，我没有在官网上看到Firefox相关的下载链接。
发自我的 iPhone

**Comment by agalwood** [comment]
可以试下这个扩展
https://addons.mozilla.org/zh-CN/firefox/addon/aria2-manager/

配置教程参考：
https://www.yuque.com/moapp/help/extensions#22993f87
