### ISSUE TITLE
未登录百度网盘时，下载不成功却在“已完成”生成下载进程

### ISSUE THREAD

**Issue by zealson** [agalwood/Motrix#31]
目前遇到一个这样的问题：
当我百度盘没有登录的情况下，选择MO下载，肯定不会下载成功的，但是在已完成的列表里面会生成一个下载的进程，会残留下来，重启应用依旧残留

**Comment by agalwood** [comment]
只能手动删除，或者出错之后用「清除已完成任务」删除任务

**Comment by zealson** [comment]
日后的MO Helper扩展能彻底解决这个问题吗？

**Comment by agalwood** [comment]
不知道，某度未来的规则…🙄
