### ISSUE TITLE
A little suggestion of description of task status

### ISSUE THREAD

**Issue by fanvinga** [agalwood/Motrix#312]
**Is your feature request related to a problem? Please describe.**
  In the latest stable version of motrix, the possible states of a task are classified as downloading, waiting, stopped.In the Chinese description, they are `下载中` `等待中` `已停止`.

**Describe the solution you'd like**
  For the task being downloading, the downloaded state can accurately describe the status of the task in progress.However, in my personal opinion, the two descriptions being used for tasks that are in a suspended state and in a completed state are less accurate and tend to cause confusion, especially the state named stopped.
  For some well-known download tools, such as IDM, FDM, Folx, etc. They mostly use paused to describe the state of the paused task and use completed to describe the status of the finished task.
  Considering the Chinese description, they use `下载中` `已暂停` `已完成`.
  I think Motrix has directions for improvement in the relevant descriptions, and more discussioners in the community are welcome to participate in the discussion about the description: -D

**Describe alternatives you've considered**
Use Downloading & Paused & Completed as the description of status of tasks

**Additional context**

**Comment by fanvinga** [comment]
At the same time, I strongly expect the release of the new version. Because I think the new features #246  are very good. Can I get a general idea of ​​the release time of the new version?

**Comment by theweavrs** [comment]
The problem with putting all stopped tasks in Completed is that currently even the failed downloads are put under Stopped which makes sense. However, we can't put failed tasks under Completed as they aren't completed.

Perhaps adding another menu for failed tasks would be more appropriate. We would need to manually filter though (afaik aria2 has no method to get failed tasks only).

**Comment by fanvinga** [comment]
Is it achievable to perform special filtering on failed tasks in the completed state?
If this is possible, I think it is feasible to mark the failed task in the completed task list with a clear color like red

**Comment by fanvinga** [comment]
Or I think I can refer to the classification of Thunder. For those tasks that failed to download, they will be kept in the category of the download instead of moving to the completed category. Users can manually delete such tasks.

**Comment by theweavrs** [comment]
@fanvinga Failed tasks are already clearly marked with a red border and a red progress bar. But it would still be confusing to put them in Completed state.

**Comment by fanvinga** [comment]
> @fanvinga Failed tasks are already clearly marked with a red border and a red progress bar. But it would still be confusing to put them in Completed state.

Thanks to the powerful capabilities of motrix, so I have not encountered the download failure yet, and I have not found the existing annotations 😆

**Comment by fanvinga** [comment]
> Or I think we can refer to the classification of Thunder. For those tasks that failed to download, they will be kept in the category of the download instead of moving to the completed category. Users can manually delete such tasks.

@theweavrs How about this ?

**Comment by theweavrs** [comment]
@fanvinga Failed tasks cannot be re-downloaded or restarted yet. There is no such capability. Hence, keeping them in Downloading section wouldn't make sense because all the user can really do is delete it. Until functionality to restart/refresh link is added, I think it would make more sense to make a separate Failed menu or keep it how it is.

**Comment by agalwood** [comment]
I used the local database to refactor the task list classification, which is a lot of work and is still under development.

**Comment by fanvinga** [comment]
> Edit: We can also add "Completed" menu in addition to the already implemented menus.

@theweavrs That's a great idea and i hope it will appear in the new version :-)

**Comment by fanvinga** [comment]
@agalwood Thank all of you for your great job 😘

**Comment by agalwood** [comment]
The new version is delayed by this feature refactoring. I have considered going to the v1.5.x version : (

In fact, the new code on the master branch is actually enough to release a new version.

**Comment by fanvinga** [comment]
> 新版本因此功能重构而延迟。我考虑过去v1.5.x版本:(
> 
> 实际上，master分支上的新代码实际上足以发布新版本。

I think it's a good choice to release the new version first. This will satisfy the needs of many users (such as users who want to start functions like login like me), and developers can have more time to finish refactor and optimize.
