### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by zz1616611** [agalwood/Motrix#313]
希望支持
1，ed2k://
2.制作种子
3.chrome扩展资源嗅探

**Comment by weearc** [comment]
其实我觉得这个要和aria2的开发者提比较好…而且由于许可之类的原因ed2k怕是需要额外加添电驴的后端

**Comment by wsxy162** [comment]
Aria2 不会添加电驴协议支持的，真的要实现只得依赖别的后端，比如 amule 这类还在维护的。

**Comment by agalwood** [comment]
1. 重复问题 #259
2. 暂不考虑
3. 已有扩展支持，麻烦看下文档
