### ISSUE TITLE
使用Motrix9天后的反馈

### ISSUE THREAD

**Issue by Safe-And-Sound** [agalwood/Motrix#315]
使用Motrix已经9天了,虽然以前也用过几次,但都没几天都卸载了主要原因是安装的时候默认安装到C盘,个人有强迫症,想软件都放在指定位置,其他 下载器都能自定义安装位置 ,那我为什么还要选择这个呢?  9天前就突然看到了可以自定义安装位置后,局打算开始用了.. 
用了9天了,发现问题蛮多的,

最大的痛点是 不能支持浏览器扩展,为什么说这是最大的痛点呢,在使用的过程中 我浏览网页时点击下载是通过浏览器本身的下载器下载的,但是浏览器本身下载是比较慢的有时候还有问题,我不能每次都把这个下载任务取消,再复制下载链接到 Motrix里 ,这样太累了,太不方便了,   不要说我没看文档 没有设置 拦截 Chrome 普通下载任务  但是这个配置是在右键上,有很多地方的下载不是你用右键另存为这样简单的 . 其他的下载器像 IDM,FDM,迅雷等等 ,都支持拦截下载任务,我个人认为这是最基础的能力 ,
就是系统代理的问题, 我觉得应该默认就使用系统代理的呀,但是我去下载 yutube 上的视频的时候是不行的.. 

最后 Motrix 再见

**Comment by agalwood** [comment]
虽然你说了再见，看你写了这么长长一段，我还是回答一下吧

提炼一下你这长文，说的就两点：

1. 拦截普通下载任务
2. 下载代理

1. YAAW for Chrome 设置里有个“下载拦截”选项，你可以勾上试下

![image](https://user-images.githubusercontent.com/1032175/59549009-a13e0a80-8f89-11e9-86a9-4d11c7c3f80d.png)

2. 偏好设置-进阶设置-代理 里可以独立配置代理，比如设置为本地的 http 代理：`http://127.0.0.1:7777`

![image](https://user-images.githubusercontent.com/1032175/59549035-11e52700-8f8a-11e9-8180-a1c024672c66.png)

**Comment by Mr-xn** [comment]
> 虽然你说了再见，看你写了这么长长一段，我还是回答一下吧
> 
> 提炼一下你这长文，说的就两点：
> 
> 拦截普通下载任务，YAAW for Chrome 设置里有个“下载拦截”选项，你可以勾上试下
> 
> 
> 下载代理，偏好设置-进阶设置-代理 里可以独立配置代理，比如设置为本地的 http 代理：http://127.0.0.1:7777

测试e也支持` socks5`，这种：`socks5://127.0.0.1:1080`，老哥应该把这两种格式包括你写的http代理格式，写在文档里面，对于小白来说有用。
