### ISSUE TITLE
开启代理后，未开启之前的任务会丢失

### ISSUE THREAD

**Issue by giveup** [agalwood/Motrix#316]
**错误描述**
开启代理后，未开启之前的任务会丢失

**如何重现**
重现步骤，如：
1:未开启代理时，添加BT任务，
2:此时开启代理，并保存，程序自动重启
3:刚才成功添加正在下载的任务时候丢失。

**预期的行为**
下载任务正常进行

**截图**
请添加屏幕截图以帮助解释你的问题：
不需要。

**运行环境**
 - 操作系统类型： macOS
 - 具体版本： 10.14.5 (18F132)
 - Motrix 版本：  Version 1.3.8
 - 安装包类型：dmg

**更多信息**
无。

**Comment by agalwood** [comment]
任务列表右上角的暂停全部任务点一下，会自动保存一下 download.session，任务应该就在了

下一版本保存偏好设置的选项时就不会重启应用
https://github.com/agalwood/Motrix/pull/294

**Comment by giveup** [comment]
还有个问题，就是开启代理后，添加任何任务都是failed to fetch。
`http_proxy=http://127.0.0.1:1234
https_proxy=http://127.0.0.1:1234`
两种格式都尝试过，这个本地代理确定可用。

**Comment by agalwood** [comment]
参考一下这个 issue https://github.com/agalwood/Motrix/issues/109
