### ISSUE TITLE
macOS 10.14.5 百度网盘下载错误

### ISSUE THREAD

**Issue by renjinlong** [agalwood/Motrix#318]
**错误描述**
macOS 10.14.5 使用chrome插件下载的文件，文件有600M，下载速度是144K,下载到220左右会下载失败，不可恢复，需要到百度下载页面点击重新下载才能继续开始，但是下载失败里还是有一条失败记录

**如何重现**
重现步骤，如：
1. 安装插件后，在百度下载页面点击mo.app下载
2. 去mo看下载进度在等待30左右会发现错误

**预期的行为**
1，不要出现下载失败
2，出现下载失败后希望可以正常恢复

**截图**
![7592A795-1E1D-48D4-B168-5E24B44AE868](https://user-images.githubusercontent.com/7300841/59662814-43efc680-91e0-11e9-9e99-8c8c5e59aa21.png)

**运行环境**
 - 操作系统类型： macOS
 - 具体版本：  macOS 10.14.5
 - Motrix 版本： 1.3.8
 - 安装包类型：dmg

**更多信息**
感觉是百度网盘的用户有有期过期导致的。

**Comment by agalwood** [comment]
出错的任务可以恢复下载了（按住Alt键一起点击还可以修改资源地址），请更新到 v1.4.x 版本

https://github.com/agalwood/Motrix/releases
