### ISSUE TITLE
Motrix无法下载

### ISSUE THREAD

**Issue by lelelemonade** [agalwood/Motrix#319]
用Motrix添加下载，开始下载即报错，如图
![motrix报错](https://user-images.githubusercontent.com/33286387/59678953-39452980-9200-11e9-96c8-b11450b77dd4.gif)

是archLinux，用yay装的，各种包都是最新的，安装过程也没报错，但就是无法下载，无限报错

**Comment by mokamk** [comment]
我也是突然所有提外链下载的方式都gg了qwq

**Comment by Li-quor** [comment]
初始下载全部速度都是0

**Comment by zhyass** [comment]
命令行里sudo motrix启动一下就好了。 参考 #20

**Comment by agalwood** [comment]
Motrix 内置的 aria2 的进程挂了，重启一下应用
如果是 Linux 系统，参考一下 zhyass 的建议

> 命令行里sudo motrix启动一下就好了。 参考 #20
