### ISSUE TITLE
希望添加系统代理设置

### ISSUE THREAD

**Issue by koyi5** [agalwood/Motrix#320]
如下图
<img src="https://s2.ax1x.com/2019/06/19/VOCRFx.jpg" alt="VOCRFx.jpg" border="1" />

**Comment by koyi5** [comment]
一般我们开了代理软件的话，都是软件自动修改了IE连接设置
Motrix直接调用IE代理设置，就不需要填写代理服务器了。
可以设置三个选项【1】不使用代理服务器【2】使用系统代理设置(IE代理服务器)【3】自定义代理服务器(也就是1.3.8版本里的那个代理设置)

**Comment by koyi5** [comment]
毕竟有些用户可能不知道如何设置这个代理，或者他购买的代理服务并没有提供这个代理服务器的选项

**Comment by agalwood** [comment]
偏好设置——进阶设置——使用代理服务器

代理配置的说明
https://github.com/agalwood/Motrix/wiki/Proxy
