### ISSUE TITLE
「新功能请求」希望扩展状态栏 icon 以及添加 aria2 远程连接的功能

### ISSUE THREAD

**Issue by zipeijun** [agalwood/Motrix#321]
**请描述一下你的新功能请求是否与已知问题有关？**
无。

**描述你想要的解决方案**
1. 状态栏 icon 希望可以选择隐藏。
2. 希望增加状态栏速度显示（这里包括下载速度、上传速度）
3. 希望状态栏 icon 点击后能出现快速操作面板
4. 希望添加连接远程 aria2 服务器的功能

**更多信息**
状态栏 icon 相关的应该不太复杂、我自己有时间会去看看代码。
远程 aria2 这一块说实话我还不知道 electron 是怎么和 aria2 集成在一起的。
希望提供一个简明贡献说明、方便其他开发者来进行开发。

**感谢**
最后感谢作者开发这个软件。

**Comment by agalwood** [comment]
1. 总有人想要，又有人想隐藏，真是众口难调
2. 调研过，Electron 系统托盘图标的 API 可能没法满足我的需求
3. 右键点击有菜单，我估计你是没看过 v1.3.x 的更新日志
4. 远程连接这功能计划排的有点远～。～

aria2 启动之后可以开放 RPC 服务，支持 AJAX 和 WebSocket 调用它的 API
https://aria2.github.io/manual/en/html/aria2c.html#rpc-options

**Comment by zipeijun** [comment]
> 1. 总有人想要，又有人想隐藏，真是众口难调
> 2. 调研过，Electron 系统托盘图标的 API 可能没法满足我的需求
> 3. 右键点击有菜单，我估计你是没看过 v1.3.x 的更新日志
> 4. 远程连接这功能计划排的有点远～。～
> 
> aria2 启动之后可以开放 RPC 服务，支持 AJAX 和 WebSocket 调用它的 API
> https://aria2.github.io/manual/en/html/aria2c.html#rpc-options

首先感谢开源作者在百忙之中可以回复我。

1. 这里必然是两类人都会有、所以设置中增加一个按钮会是一个好的解决方案。
2. Electron 我不是很熟悉、但我会去看看的。
3. 我去看了下 v1.3.x 的更新日志、但我没看懂要如何开启这个菜单 😂
4. 有点远没关系、只是有个小小的想法、具体是否实现、还要看作者对软件后续发展的看法。

最后再次感谢作者。

**Comment by agalwood** [comment]
还想到一个情况，Windows 下如果隐藏了系统托盘图标，关掉主窗口之后就没有地方可以恢复界面了……更早的版本没有系统托盘图标功能时这种情况就直接退出应用了

**Comment by agalwood** [comment]
在系统托盘的 Motrix 图标上右键点击，就会弹出菜单了

**Comment by zipeijun** [comment]
对不起、是我太蠢了😂
Windows 的问题说的是、这个只能功能分系统、Windows 不能隐藏这个 icon、macOS 可以、Linux 不清楚什么情况。
