### ISSUE TITLE
能不能提高最高线程数

### ISSUE THREAD

**Issue by MCredbear** [agalwood/Motrix#325]
大家不一定都是下度盘啊。。。（而且调大了线程的人应该也有觉悟）

**Comment by agalwood** [comment]
老铁，自己修改编译一个 aria2c 替换到 Motrix 里吧

**Comment by MCredbear** [comment]
> 
> 
> 老铁，自己修改编译一个 aria2c 替换到 Motrix 里吧

替换是替换了，可是你这个软件不让我调上去啊，，，，

**Comment by agalwood** [comment]
可以的，修改 Motrix 的 system.json 配置，修改 `max-connection-per-server` 为你需要的值，保存重启应用

Windows
`%APPDATA%/Motrix/system.json`

Linux
`$XDG_CONFIG_HOME/Motrix/system.json or ~/.config/Motrix/system.json`

macOS
`~/Library/Application Support/Motrix/system.json`

**Comment by MCredbear** [comment]
![图片](https://user-images.githubusercontent.com/40625974/60957623-8ae06000-a337-11e9-8ac9-412d86efb97d.png)
然而并没有找到这个文件

**Comment by agalwood** [comment]
> Windows
> `%APPDATA%/Motrix/system.json`

Windows 对应的目录应该是这个，把`用户名`换成你电脑登录的用户名
C:\Users\用户名\AppData\Motrix\system.json

**Comment by giveup** [comment]
做成一个选项吧，加载外部aria2c和配置文件。

**Comment by GitH123i** [comment]
> > 老铁，自己修改编译一个aria2c替换到Motrix里吧
> 
> 替换是替换了，可是你这个软件不让我调上去啊，，，，

目前的主力下载软件，不足的只能是16线程最高，期望可以手动的选择是否支持64线程的下载，如果朋友你已经做好了，可否发给我使用否。

**Comment by agalwood** [comment]
已经升级到 aria2 v1.3.5 并全系统开放了 64 线程下载，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
