### ISSUE TITLE
能否增加通配符批量下载并且重命名功能？

### ISSUE THREAD

**Issue by ScienceZone** [agalwood/Motrix#326]
下载某些有规律的文件时经常遇到需要批量下载的需求，有时下载的文件名不是利于排序的名字有需要批量重命名的功能。
       比如有很多图片，URL样式为：
https://www.XXX.com/XX/XXXX/Book?fd7152a2a2b8c790ef&page=1,
https://www.XXX.com/XX/XXXX/Book?fd7152a2a2b8c790ef&page=2,
……
https://www.XXX.com/XX/XXXX/Book?fd7152a2a2b8c790ef&page=100
等等。
使用其他工具比如IDM利用通配符批量下载时，可能将文件名自动命名为Book1.jpg，Book2.jpg……Book100.jpg等，这还是比较好的（接近自己的需求），有些直接命名为fd7152a2a2b8c790ef&page=1……fd7152a2a2b8c790ef&page=100等，连文件类型都无法识别，直接没有扩展名。
        我的需求就是能否添加批量下载（或者用通配符，或者批量粘贴链接也可以，使用Excel也方便操作），并且可以每个链接后添加一个自己定义的文件名，可以使用Excel将链接和文件名分列两列，粘贴到软件后直接下载。最好能支持添加多个批量任务。
        希望您能看到我的需求，还没摆脱贫困，若开发出来，我很乐意勒紧腰带捐助一百，以示感谢，谢谢！

**Comment by agalwood** [comment]
看了你之前提的 issue https://github.com/padeoe/nju-lib-downloader/issues/5 ，大概了解你的需求了

应该可以在「添加任务-重命名」那里支持几种约定的重命名规则，比如：

```javascript
abc_(001+).jpg

xyz_(129-).jpg
```

代码上怎么实现还要试试看吧

**Comment by ScienceZone** [comment]
期待！

**Comment by agalwood** [comment]
该特性已经合并到 master，不过暂时不会发新版，你可以自己按照 README 克隆代码编译打包
