### ISSUE TITLE
#1 错误不能下载

### ISSUE THREAD

**Issue by NeoopS** [agalwood/Motrix#327]
![image](https://user-images.githubusercontent.com/24501789/60062131-780c3f80-972a-11e9-99d6-63aeb2c1c147.png)
下载提示#1 不能下载，win10系统

**Comment by agalwood** [comment]
按F12打开控制台，console 里有具体出错原因
麻烦提问题按模板提交信息

https://github.com/agalwood/Motrix/issues/new?assignees=&labels=&template=bug_report_cn.md&title=

**Comment by DannielZhang** [comment]
![image](https://user-images.githubusercontent.com/4921818/60247483-56aa7f80-98f3-11e9-8a54-3696e56388b1.png)
我也是#1，这是日志里报错的内容，下载的链接是一个ed2k链接； 迅雷的也不行

**Comment by agalwood** [comment]
@DannielZhang 本来就不支持 ed2k 链接 https://github.com/agalwood/Motrix/issues/14

迅雷的链接解析出来的链接对应的资源不一定存在的

**Comment by NeoopS** [comment]
> @DannielZhang 本来就不支持 ed2k 链接 #14
> 
> 迅雷的链接解析出来的链接对应的资源不一定存在的

Motrix] download error===> Gid: 1d81880509193ee9, #1, 
(anonymous) @ index.js:1
Promise.then (async)
onDownloadError @ index.js:1
emit @ events.js:182
_onnotification @ C:\Program Files\Motrix\resources\app.asar\node_modules\aria2\lib\Aria2.js:29
_onobject @ C:\Program Files\Motrix\resources\app.asar\node_modules\aria2\lib\JSONRPCClient.js:145
_onmessage @ C:\Program Files\Motrix\resources\app.asar\node_modules\aria2\lib\JSONRPCClient.js:139
socket.onmessage.event @ C:\Program Files\Motrix\resources\app.asar\node_modules\aria2\lib\JSONRPCClient.js:156

**Comment by AnCoSONG** [comment]
下载不了，种子磁链都下载不了 ERROR CODE #1

![image](https://user-images.githubusercontent.com/32268203/63938323-81ee4e00-ca9f-11e9-9301-cc2571265c91.png)

**Comment by agalwood** [comment]
> 下载不了，种子磁链都下载不了 ERROR CODE #1
> 
> ![image](https://user-images.githubusercontent.com/32268203/63938323-81ee4e00-ca9f-11e9-9301-cc2571265c91.png)

BT 端口绑定失败，是不是被某安全软件拦截了
