### ISSUE TITLE
百度网盘+百度网盘助手下载出现#1错误

### ISSUE THREAD

**Issue by SimonHunter217** [agalwood/Motrix#329]
**错误描述**
通过百度网盘助手启动下载后，出现 #1 错误

**如何重现**
启动 MO，通过百度网盘助手下拉菜单的 `MO 下载` 添加下载任务，基本上秒出现 #1 错误。

在控制台发现许多如下报错信息：

```
[Motrix] download error===> Gid: 606a19d2a2da1d4f, #1, SSL/TLS handshake failure: Unspecified error -9847
```

**截图**

![image](https://user-images.githubusercontent.com/42352765/60162100-69f21800-982b-11e9-989c-087c3e532319.png)

**运行环境**
 - 操作系统类型： MacOS
 - 具体版本： macOS 10.14.5
 - Motrix 版本： v1.4.1
 - 安装包类型：官网下载的dmg

**Comment by agalwood** [comment]
这个是度盘某些资源服务器的证书有问题，你可以按住Alt键点击任务操作栏的「重新下载」按钮，把资源地址复制到浏览器里打开看看，浏览器应该也会报错的
