### ISSUE TITLE
官网下载按钮不可用

### ISSUE THREAD

**Issue by Seevil** [agalwood/Motrix#331]
**错误描述**
官网下载按钮不可用
**如何重现**
重现步骤，如：
1. Download 按钮不可用
  
**截图**
![TIM截图20190628150945](https://user-images.githubusercontent.com/7334510/60324420-5a9fd580-99b7-11e9-8436-2509b30e28f4.png)
![TIM截图20190628151514](https://user-images.githubusercontent.com/7334510/60324508-8de26480-99b7-11e9-80b4-8a334cbead8a.png)

**运行环境**
 - 操作系统类型： Windows 10 1809
 - chrome 版本： 75.0.3770.100

**Comment by agalwood** [comment]
老铁，这个错误是被你浏览器的广告过滤插件给屏蔽了吧

**Comment by Seevil** [comment]
不是，我关掉了也不行，拦掉的是百度统计

**Comment by agalwood** [comment]
没有复现 : |

Windows 10 1803
Google Chrome 75.0.3770.100

**Comment by Seevil** [comment]
![TIM截图20190701092218](https://user-images.githubusercontent.com/7334510/60405285-cc5b6780-9be1-11e9-87ea-366ceed58520.png)
找到了，是这个油猴脚本导致的。
