### ISSUE TITLE
下载发送错误#1

### ISSUE THREAD

**Issue by Li-xianhua** [agalwood/Motrix#336]
**错误描述**
下载种子或磁力链时，直接提示下载发生错误#1。

**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接或拖入任何种子文件
3. 点击提交
4. 发现报错

**预期的行为**
开始下载。

**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： windows10 1809 x64 （版本号17763.557）
 - Motrix 版本： 1.4.1
 - 安装包类型：Motrix-Setup-1.4.1.exe这个包

**更多信息**
在1.2.2版本上没有，1.3.8和1.4.1都这样。

**Comment by Li-xianhua** [comment]
![image](https://user-images.githubusercontent.com/52340828/60379945-31428080-9a6f-11e9-9bf1-f005d54d437b.png)

**Comment by agalwood** [comment]
我翻了代码提交记录，https://github.com/agalwood/Motrix/commit/110c83bcb80c795ddfd92d4e3866a6ebb8e09707 修改了 BT 的监听端口，似乎这几个端口在你系统上监听不了。

你试着手动编辑安装目录下的 aria2.conf 吧，Windows 版的 aria2.conf 在 `Motrix\resources\engine` 目录里，打开找到下面的配置，修改为 `listen-port=51413` 试试

```
# BT监听端口, 当端口被屏蔽时使用, 默认:6881-6999
listen-port=50101-50109
```

**Comment by Li-xianhua** [comment]
改为51413后可以了，谢谢！
