### ISSUE TITLE
永远的“下载发生错误#1”

### ISSUE THREAD

**Issue by XxxX12370** [agalwood/Motrix#337]
**错误描述**
在一次意外断网之后下载的所有东西都变成0B/s且迅速停止下载。此后不论多少次重新安装都无法下载且显示“#1”错误代码
**如何重现**
重现步骤：
1. 在百度云里用扩展插件点击按钮使用下载功能
2. 需要下载的任务进入”下载中“队列
3. 显示0B/s，几秒后任务退到”已停止“一栏且发送报错通知
4. 重新安装软件及扩展程序，且重复以上步骤

**预期的行为**
能够正常地进行任务下载，像往常一样
**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

【一会儿会进行补充】
**运行环境**
 - 操作系统类型： [ Windows]
 - 具体版本： [Windows 10]
 - Motrix 版本： [ v1.4.1]
 - 安装包类型：[ exe]

**更多信息**
断网前一直使用正常，此后重复下载无效。

**Comment by XxxX12370** [comment]
![批注 2019-06-29 173201](https://user-images.githubusercontent.com/52346321/60382313-df602180-9a93-11e9-86e3-6a87d7cab012.png)
如图

**Comment by agalwood** [comment]
你下载的是度盘的资源吧？

参考这个操作一下看看 https://github.com/agalwood/Motrix/issues/329

**Comment by XxxX12370** [comment]
> 你下载的是度盘的资源吧？
> 
> 参考这个操作一下看看[＃329](https://github.com/agalwood/Motrix/issues/329)
事实上，这些资源此前曾能够用此软件进行下载。只是现在出现了问题。

**Comment by agalwood** [comment]
因为看报错信息是 SSL 握手时被远程服务器断开，可以说并不是 Motrix 的问题

**Comment by XxxX12370** [comment]
> 因为看报错信息是SSL握手时被远程服务器断开，可以说并不是Motrix的问题

明白，我会检测一下百度云盘的。谢谢答复！

**Comment by agalwood** [comment]
你可以删除任务重新添加一下试试

**Comment by XxxX12370** [comment]
> 你可以删除任务重新添加一下试试

已经实验若干次，重新下载任务，软件，扩展程序以及重启电脑等。却起不到作用

**Comment by agalwood** [comment]
卸载重新安装试过么？

**Comment by XxxX12370** [comment]
> 卸载重新安装试过么？

试过数次。

**Comment by agalwood** [comment]
能下载其他普通 http 任务么？

**Comment by XxxX12370** [comment]
> 能下载其他普通 http 任务么？

其他普通任务一般都是Chrome浏览器自己自动下载，Motrix是插不上手的
且说， “SSL 握手时被远程服务器断开”，这意味着什么

**Comment by agalwood** [comment]
可以复制一个地址进去下载试试

其实普通任务也可以拦截的，参考 https://www.yuque.com/moapp/help/extensions#22993f87

**Comment by agalwood** [comment]
度盘的有些服务器节点的 SSL 证书有毒

**Comment by XxxX12370** [comment]
> 可以复制一个地址进去下载试试
> 
> 其实普通任务也可以拦截的，参考 https://www.yuque.com/moapp/help/extensions#22993f87

很不幸的，在这个网址里的扩展下载网址无法被打开
![批注 2019-06-29 180133](https://user-images.githubusercontent.com/52346321/60382613-35cf5f00-9a98-11e9-8a0a-52f790b3c1a4.png)

**Comment by XxxX12370** [comment]
> 度盘的有些服务器节点的 SSL 证书有毒

事实上，这次出事是在一次意外的网络崩盘之后。许多任务是一个系列的。前几个下载成功了而后几个则不是那么幸运。

**Comment by agalwood** [comment]
你安装 https://chrome.google.com/webstore/detail/yaaw-for-chrome/dennnbdlpgjgbcjfgaohdahloollfgoc 成功了么？在它的图标上右键能找到选项的

**Comment by XxxX12370** [comment]
> 你安装 https://chrome.google.com/webstore/detail/yaaw-for-chrome/dennnbdlpgjgbcjfgaohdahloollfgoc 成功了么？在它的图标上右键能找到选项的

谢谢帮助，我最后选择了给电脑系统重置，一切重新安装。这使这个情况得到了很好的解决~
