### ISSUE TITLE
反应三个问题

### ISSUE THREAD

**Issue by Iota4836** [agalwood/Motrix#34]
我下的东西多，下着没一会就好多出错，然后速度就300kb/s左右；还有下着下着就任务列表都没了，一片白的；还有一个问题，就是我原来路径错了，不能批量删除任务，因为任务太多了，没办法，只能重新安装。麻烦改进下，谢谢大佬。

**Comment by agalwood** [comment]
1. 下载度盘资源是容易出现速度波动，度度有时候会断开连接
2. 如果出现过多报错，有可能造成下载核心崩溃
3. 批量操作开发中…其实你可以去删一下下载会话 download.session，偏好设置里有存放路径

**Comment by Iota4836** [comment]
谢谢大佬，因为下百度云网速太慢，重新用回pcs，你可以试试 https://github.com/iikira/BaiduPCS-Go 下很快。motrix比aria2容易用多了，如果能自己添加tracker就好了， https://github.com/ngosang/trackerslist 添加了tracker速度会快好多。
