### ISSUE TITLE
需要 ed2k 的支持啊

### ISSUE THREAD

**Issue by kovior** [agalwood/Motrix#342]
**请描述一下你的新功能请求是否与已知问题有关？**
简明扼要地描述了问题所在。

**描述你想要的解决方案**
简明扼要地描述你想要的解决方案。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by ZeroAurora** [comment]
鉴于引擎是 aria2c，个人认为原理不可行？有不对烦请指教
