### ISSUE TITLE
How to start downloads automatically in Motrix?

### ISSUE THREAD

**Issue by Alireza29675** [agalwood/Motrix#344]
Hey guys, I enjoyed what you did, and I'm still testing Motrix out.

Can you tell me if there's a feature for connecting chrome to Motrix, so before a file starts downloading in chrome, it starts in Motrix.

Keep up good work!

**Comment by agalwood** [comment]
Yes, try [YAAW for Chrome](https://chrome.google.com/webstore/detail/yaaw-for-chrome/dennnbdlpgjgbcjfgaohdahloollfgoc)

But its interface is not internationalized, I will briefly introduce you how to configure.

After YAAW for Chrome installed, open the extended options page (copy to the Chrome address bar to open)

`chrome-extension://dennnbdlpgjgbcjfgaohdahloollfgoc/options.html`

![image](https://user-images.githubusercontent.com/1032175/60665565-61d35180-9e97-11e9-8d58-f87cb16857a6.png)

Download with Motrix | http://127.0.0.1:16800/jsonrpc
-- | --

Of course, you can also set the file size larger than xx M to intercept and download to Motrix.

**Comment by Alireza29675** [comment]
Cool, yup it works well!

Any plan for making an easier-to-configure solution? This is absolutely difficult for a non-programmer user.

**Comment by agalwood** [comment]
Yes, you are right, this temporary solution is a bit difficult for non-programmer users.

Motrix's browser extensions are in the roadmap and are awaiting development.

**Comment by Alireza29675** [comment]
Waitin for it 👍
