### ISSUE TITLE
希望不要占用Dock栏

### ISSUE THREAD

**Issue by xieqing0428** [agalwood/Motrix#345]
**描述你想要的解决方案**
既然有开机自启的功能，希望增加一个选项不占用Dock栏，作为默认下载组件使用

**描述你考虑过的替代方案**
目前使用cDock隐藏，但是必须关掉SIP

**Comment by agalwood** [comment]
可以考虑，下版本加吧

目前你可以先从应用菜单-帮助-开发者工具，切换到 Console，输入下面的命令隐藏 dock 图标（下次启动应用需再次输入）
```javascript
global.app.$electron.remote.app.dock.hide()
```

**Comment by xieqing0428** [comment]
> 可以考虑，下版本加吧
> 
> 目前你可以先从应用菜单-帮助-开发者工具，切换到 Console，输入下面的命令隐藏 dock 图标（下次启动应用需再次输入）
> 
> ```js
> global.app.$electron.remote.app.dock.hide()
> ```

万分感谢，辛苦啦
