### ISSUE TITLE
18年至今下载种子或磁力链接从未有过速度...

### ISSUE THREAD

**Issue by fansangg** [agalwood/Motrix#346]
**请描述一下你的新功能请求是否与已知问题有关？**
简明扼要地描述了问题所在。

**描述你想要的解决方案**
简明扼要地描述你想要的解决方案。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

如何在macos上取消网页磁力链接由此app打开？

**Comment by agalwood** [comment]
这位老铁，你从 2018年就开始用 Motrix 了么？

Motrix v1.4.x 偏好设置-进阶设置-下载协议，关掉磁力链接的开关，保存并应用

还有，你需要打开其他 BT 客户端把磁力链接拦截走

**Comment by fansangg** [comment]
记忆中好像是18年用过下百度云，反正下磁力链接没有过速度...
