### ISSUE TITLE
源代码编译的错误问题

### ISSUE THREAD

**Issue by lotuso** [agalwood/Motrix#347]
![深度截图_选择区域_20190705161111](https://user-images.githubusercontent.com/44076708/60708054-bb8f5680-9f3f-11e9-82f0-185d3b496002.png)

- 操作步骤:
```
npm install
```
- 试过好多回了，依然是这个错误

**Comment by Raistlin916** [comment]
像是网络代理链接失败，可以检查下代理设置

**Comment by mela93** [comment]
可以尝试tabao源 ` npm install --registry=https://registry.npm.taobao.org`
