### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by cccccabbage** [agalwood/Motrix#349]
**错误描述**
使用种子下载时，速度一直为0kb/s，今天一个上午一直挂着，只下载了7.4M
如果使用磁力链接下载，甚至不能读取到下载文件的目录和具体内容，直接创建任务，速度仍为0kb/s

**如何重现**
目前为止，未有任何文件下载成功

**预期的行为**
希望能获取到和其他用户相近的舒适体验
起码能用吧

**截图**
7.8MB/34.9GB              0KB/s 剩余 超过一天
（不会截图欸）

**运行环境**
 - 操作系统类型：windows
 - 具体版本：win10
 - Motrix 版本：v1.4.1
 - 安装包类型：这是个啥玩意

**更多信息**
补充有关该问题的其他信息。

**Comment by agalwood** [comment]
老铁，可以把种子和磁力链发下

我看你下载的资源大小为 34.9GB，BT 下载这么大的东西，如果本来就是偏冷门资源，没人做种就没有速度了

磁力链本身并不包含文件目录和具体内容，需要通过 DHT 网络解析成种子，再从种子中解析出文件目录
如果是直接添加磁力链，目前是不支持选择性下载部分文件的

推荐了解下BT的原理：
https://www.bilibili.com/video/av57748098

**Comment by cccccabbage** [comment]
> 老铁，可以把种子和磁力链发下
> 我看你下载的资源大小为 34.9GB，BT 下载这么大的东西，如果本来就是偏冷门资源，没人做种就没有速度了
> 磁力链本身并不包含文件目录和具体内容，需要通过 DHT 网络解析成种子，再从种子中解析出文件目录
> 如果是直接添加磁力链，目前是不支持选择性下载部分文件的
> 推荐了解下BT的原理：
> https://www.bilibili.com/video/av57748098

是这样的，不光是这个34.9G的文件一直0KB/s，其他内容也都基本无法下载，以前我下载的时候，看他0KB一天左右就直接换迅雷了，迅雷上可以下载，租个会员还可以达到几MB的下载速度，所以我想应该不是文件的问题。
此链接如下：magnet:?xt=urn:btih:03384dec411d3b9488decc7835f5e246ec24bb84&tr=http://open.acgtracker.com:1096/announce
（种子不会上传）

**Comment by emhui** [comment]
我也是，没成功下载过任何东西

**Comment by wheat0r** [comment]
aria2本身应该是允许磁力链下载完种子之后进行文件选择的，webui-aria2和aria2ng应该都有这个功能

**Comment by HK1170961** [comment]
我也是任何文件都没速度

**Comment by WWWalterrr** [comment]
同样，不同类型的bittorrent都打不开（同样连接可以在迅雷和folx中完成下载）。希望告知解决办法

操作系统类型：MACOS
具体版本：catalina 10.15.1
Motrix 版本：v1.4.1

**Comment by ForainCai** [comment]
感觉是motrix这软件太高级了，我们不会用呀。我用它下东西经常不成功
