### ISSUE TITLE
下载不了，显示下载失败

### ISSUE THREAD

**Issue by Panda-xp** [agalwood/Motrix#35]
![snipaste_2019-01-26_11-36-07](https://user-images.githubusercontent.com/34712898/51782145-97dd0e80-215e-11e9-9334-bfccea75398d.png)
我打开了MO，但是它还是提示下载失败，提示我没有打开MO，怎么回事……

**Comment by agalwood** [comment]
试下单个文件下载看看，如果还是不行，打开系统任务管理器看下是否有 aria2 进程

**Comment by Panda-xp** [comment]
> 试下单个文件下载看看，如果还是不行，打开系统任务管理器看下是否有 aria2 进程
单个下载也不行，任务管理器里面，好像没有aria2的进程
![image](https://user-images.githubusercontent.com/34712898/51782693-babff080-2167-11e9-896e-989c27b755f2.png)
