### ISSUE TITLE
希望可以隐藏macOS上的DOCK栏上的速度

### ISSUE THREAD

**Issue by mela93** [agalwood/Motrix#350]
**请描述一下你的新功能请求是否与已知问题有关？**
希望可以隐藏macOS上的DOCK栏上的速度

**描述你想要的解决方案**
在设置中添加一个选项可以根据需求是否隐藏速度

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
其实与这个有相似之处[issues#345](https://github.com/agalwood/Motrix/issues/345)，如果#345可以解决这个需求可以忽略。个人认为，这个需求可能更好实现？

需求场景，主要不想让别人一眼就看出来在疯狂下载

**Comment by agalwood** [comment]
临时方案参考 https://github.com/agalwood/Motrix/issues/345#issuecomment-509062548
