### ISSUE TITLE
Failed to fetch when create a new task

### ISSUE THREAD

**Issue by hzxie** [agalwood/Motrix#351]
**Describe the bug**
I got an error message saying "Failed to Fetch" when creating a new downloading task.

**To Reproduce**
1. Open Motrix
2. Create a new task whose URL is `https://anaconda.org/anaconda/pytorch/1.0.1/download/linux-64/pytorch-1.0.1-cuda92py36h65efead_0.tar.bz2`.

**Expected behavior**
Got an error message saying "Failed to Fetch"

**Screenshots**
![Screenshot from 2019-07-08 15-19-58](https://user-images.githubusercontent.com/1730504/60791148-9dbb2f00-a195-11e9-80b7-bfef615bd819.png)

**Environment (please complete the following information):**
 - OS & Version: Arch Linux
 - Version: N/a
 - Motrix Version: 1.3.8 & 1.4.1
 - Installation package type: [AUR package](https://aur.archlinux.org/packages/motrix/)

**Comment by agalwood** [comment]
The first boot in Linux may require sudo to run. The reason is that there is no permission to create the file `/var/cache/aria2.session`

https://github.com/agalwood/Motrix/issues/20#issuecomment-468956081
