### ISSUE TITLE
希望不自动做种，或者提供设置选项是否自动做种

### ISSUE THREAD

**Issue by guodongAndroid** [agalwood/Motrix#355]

**Comment by agalwood** [comment]
不会提供

你 BT 下载的资源都是从别人那里汲取的，却想完全不分享，这就跟某吸血雷一样了

**Comment by guodongAndroid** [comment]
目前我看到在[issue#179](https://github.com/agalwood/Motrix/issues/179)中，不想做种的话，可以手动点击停止任务，这和吸血雷差不多吧
