### ISSUE TITLE
3DM/游侠的迅雷/BT资源无法下载

### ISSUE THREAD

**Issue by v21cesc** [agalwood/Motrix#356]
**错误描述**
3DM/游侠的 迅雷/BT资源无法创建连接

**预期的行为**
3DM和游侠的资源应该是非常热门了，长期有官方服务器种，资源数量应该不是问题，同样的链接wine迅雷是可以轻松开到满速的。链接资源总尺寸大约在30-50G左右，单个文件被分割限制在最多1G。是否需要我这边再提供什么具体运行信息反馈，谢谢。

**运行环境**
 - 操作系统类型： Linux
 - 具体版本： Fedora30
 - Motrix 版本： 1.4.1
 - 安装包类型：AppImage

**Comment by v21cesc** [comment]
放置一段时间后(十多分钟)连接可以建立并开始下载，但速度只有20KB/s以下

**Comment by agalwood** [comment]
请问你作为对照的迅雷是否使用了迅雷VIP？

如果是，迅雷的 P2SP 是会比常规的 P2P 下载快的，因为迅雷可以从它的离线加速服务器下载资源提速（不对其他 BT 客户端开放，包括 Motrix）

**Comment by v21cesc** [comment]
> 请问你作为对照的迅雷是否使用了迅雷VIP？
> 
> 如果是，迅雷的 P2SP 是会比常规的 P2P 下载快的，因为迅雷可以从它的离线加速服务器下载资源提速（不对其他 BT 客户端开放，包括 Motrix）

你说的对，我当时登录了vip，前面这个比较不可靠。
后来注销了重启，大概可以下到100-300KB/s，还是要快一些。
