### ISSUE TITLE
重装win7后不能捕获chrome百度云下载了

### ISSUE THREAD

**Issue by joshatt** [agalwood/Motrix#359]
**错误描述**
清楚简洁地描述错误，方便我们复现之后处理。

重装win7后不能捕获chrome百度云下载了

**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接（如链接不涉及到隐私和版权问题，请顺便提供）
3. 点击提交
4. 发现报错

本来能用. 重装win7后, chrome免安装版里面点击百度云下载, 百度网盘助手有反应, 但motrix没反应. 重装了motrix v1.3.8 然后用v1.4.1zip包覆盖升级, 仍然一样. 重装了网盘助手, 仍然一样

**预期的行为**
清楚简洁地描述你期望发生的事情。

**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

**运行环境**
 - 操作系统类型： [如 macOS, Windows, Linux]windows
 - 具体版本： [如 macOS 10.14.2, Windows 10, Ubuntu 18.04]windows 7
 - Motrix 版本： [如 v1.1.3, v1.1.0]v1.4.1
 - 安装包类型：[如 dmg, AppImage]exe

**更多信息**
补充有关该问题的其他信息。

**Comment by AppJ-GS** [comment]
不要用免安装软件，最好都用硬盘安装的，不然会破坏程序的唤醒机制。chrome和motrix都建议用安装包重装到最新版，而不是所谓的覆盖升级

**Comment by joshatt** [comment]
> 不要用免安装软件，最好都用硬盘安装的，不然会破坏程序的唤醒机制。chrome和motrix都建议用安装包重装到最新版，而不是所谓的覆盖升级

谢谢答复. chrome本来就是免安装版, 原来没问题的. motrix似乎1.4.1版只有zip包? 所以我又用了1.3.8安装版尝试

**Comment by AppJ-GS** [comment]
如有兴趣，可加qq：1044100652继续探讨

joshatt <notifications@github.com> 于2019年7月14日周日 下午12:00写道：
