### ISSUE TITLE
请问如何设置线程数为64

### ISSUE THREAD

**Issue by xifan-fh** [agalwood/Motrix#36]
就我安装的版本最高只能调到16,再往上就不行了

**Comment by agalwood** [comment]
什么操作系统？

左下角偏好设置-进阶设置-“每个服务器最大连接数”调高

如果不能…

Motrix Windows和Linux的版本内封的aria2没修过编译参数，最大只能到16

下一版本处理

**Comment by xifan-fh** [comment]
win10的 好的

> 什么操作系统？
> 
> 左下角偏好设置 - 进阶设置 - “每个服务器最大连接数”调高
> 
> 如果不能...
> 
> Motrix Windows和Linux的版本内封的aria2没修过编译参数，最大只能到16
> 
> 下一版本处理

win10 好的

**Comment by Anyfc** [comment]
@agalwood win最新版还是不能设置16进程以上

**Comment by agalwood** [comment]
抱歉，aria2-fast 的 CI 编译还没搞定，v1.1.3 版本没替换内置的 aria2c，忘记在 issue 通知了

**Comment by amocken** [comment]
现在win 10的1.3.8版依然最大只能设置到16线程。。

**Comment by weearc** [comment]
可以直接修改aria2.conf实现，详情见aria2的man page


 
---原始邮件---
发件人: "amocken"<notifications@github.com>
发送时间: 2019年5月11日 13:31:37
收件人: "agalwood/Motrix"<Motrix@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [agalwood/Motrix] 请问如何设置线程数为64 (#36)



现在win 10的1.3.8版依然最大只能设置到16线程。。

**Comment by weearc** [comment]
啊对了忘了说…Arch的是链了系统的aria2c到engine下面…不好意思…但是同样可以手动改编译参数实现，都一样的

**Comment by GitH123i** [comment]
> 啊对了忘了说…Arch的是链了系统的aria2c到engine下面…不好意思…但是同样可以手动改编译参数实现，都一样的

你好朋友，目前的主力下载软件，不足的只能是16线程最高，期望可以手动的选择是否支持64线程的下载，如果朋友你已经做好了，可否发给我使用否。

**Comment by agalwood** [comment]
已经升级到 aria2 v1.3.5 并全系统开放了 64 线程下载，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
