### ISSUE TITLE
Name the application on the system monitor

### ISSUE THREAD

**Issue by alexwender1** [agalwood/Motrix#362]
**Describe the bug**
System Monitor incorrectly displays the Motrix name. "Tray: Motrix" instead of simply "Motrix".

**Screenshots**
![Captura de Tela_selecionar área_20190715143153](https://user-images.githubusercontent.com/45263160/61264154-e8264800-a761-11e9-8b12-89b35e66f20e.png)

**Environment (please complete the following information):**
 - Deepin 15.10.2 Lion
 - Motrix 1.4.1 (AppImage)

**Comment by agalwood** [comment]
I don't know how to modify the name of this process. Do you know?

https://electronjs.org/docs/api/tray

**Comment by alexwender1** [comment]
I do not know how to solve. But someone should come and fix it.

Let's wait.

**Comment by alexwender1** [comment]
It is a feature of Deepin System Monitor application, in pointing out the tray process.
