### ISSUE TITLE
UI错误及使用建议

### ISSUE THREAD

**Issue by constantine001** [agalwood/Motrix#365]
1.“关于”界面上一直显示©2018 Motrix  强迫症实在没法忍了，所以来提个修改issue，麻烦大佬改成2019吧。
2.有的资源下载时会一直卡在100%  不会转到已停止，一直显示在下载中。

**Comment by agalwood** [comment]
1. 好的
2. BT 下载完成之后会开始做种（BT下载，人人为我，我为人人），如果你实在不想做种，可以点击任务上的第一个按钮（⏹）停止做种。

**Comment by constantine001** [comment]
2.第2个问题原来是在做种，我倒是支持做种的人，只是一直卡在那感觉跟别扭，个人的建议是下载完成后转到“已停止”（个人觉得应该改为“已下载”），然后默认打开Motrix的时候就是在“已下载”任务里的所有任务都在做种（设置里可以限制做种的总上传速度），只有删除“已下载”里面的记录的时候才不再做种。并且该方案在更新说明里给大家说明，这样应该能照顾到绝大部分人了。一直支持您，十分感谢您的制作。
