### ISSUE TITLE
中文名称和后缀名问题

### ISSUE THREAD

**Issue by hqyxd** [agalwood/Motrix#366]
中文名称乱码
后缀名为rar时下载下来没有后缀名了
系统为macOS 10.14.4
motrix版本为1.4.1

**Comment by agalwood** [comment]
麻烦提供一下资源的下载地址

**Comment by hqyxd** [comment]
> 麻烦提供一下资源的下载地址

https://pan.baidu.com/xxxx 这样的地址 你在
https://pan.baidu加上wp
最后得到的链接就是
https://pan.baiduwp.com/xxxx
找一个百度网盘分享的链接 这样处理之后的链接去下载 中文名会乱码 压缩rar文件没有后缀名

**Comment by hqyxd** [comment]
> 麻烦提供一下资源的下载地址
目前发现使用这种方式下载的文件现在开始出现22错误了

**Comment by agalwood** [comment]
我测试了一下 pandown 这个方式，文件名和后缀名都是正常的

错误码 22 是因为度盘封锁或者度盘的资源服务器有问题，Motrix 无能为力
