### ISSUE TITLE
无法连接rpc服务

### ISSUE THREAD

**Issue by zhangzsv** [agalwood/Motrix#367]
**错误描述**
新建任务无反应 打开console发现无法连接rpc服务 但aria2c进程正常

**截图**
<img width="541" alt="屏幕快照 2019-07-21 下午9 05 55" src="https://user-images.githubusercontent.com/23657836/61591649-b0088480-abfb-11e9-8199-bbc388778f66.png">
![屏幕快照 2019-07-21 下午9 08 36](https://user-images.githubusercontent.com/23657836/61591672-04abff80-abfc-11e9-87ff-63a264728142.png)

**运行环境**
 - 具体版本： macOS 10.13
 - Motrix 版本： 1.4.1
 - 安装包类型：dmg

**Comment by agalwood** [comment]
用进程管理器杀掉 aria2c 进程，然后重启应用试试

**Comment by zhangzsv** [comment]
> 用进程管理器杀掉 aria2c 进程，然后重启应用试试

试过了 还是一样的错误

**Comment by agalwood** [comment]
这个状况是突然出现的还是一直就这样的？

**Comment by zhangzsv** [comment]
> 这个状况是突然出现的还是一直就这样的？

今天升级的1.4.1出现的 我试了降级回1.3.8是正常的

**Comment by agalwood** [comment]
本地是否有系统代理？

如果是，打开 macOS 的系统偏好设置-网络-代理，将 127.0.0.1 添加到“忽略这些主机与域的代理设置” 试试

**Comment by zhangzsv** [comment]
> 本地是否有系统代理？
> 
> 如果是，打开 macOS 的系统偏好设置-网络-代理，将 127.0.0.1 添加到“忽略这些主机与域的代理设置” 试试

确实是代理的原因 已解决 感谢🙏
