### ISSUE TITLE
jsonrpc is not working

### ISSUE THREAD

**Issue by libook** [agalwood/Motrix#368]
**Describe the bug**
Browser extension isn't able to connect to jsonrpc port. And:
```bash
 $ telnet 127.0.0.1 16800
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

In the console of Motrix:
```
[Motrix] fetchPreference===> Object
/opt/motrix/resources/app.asar/node_modules/aria2/lib/JSONRPCClient.js:150 WebSocket connection to 'ws://127.0.0.1:16800/jsonrpc' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
open @ /opt/motrix/resources/app.asar/node_modules/aria2/lib/JSONRPCClient.js:150
127.0.0.1:16800/jsonrpc:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
index.js:1 fetchDownloadingTaskList fail===> TypeError: Failed to fetch
2index.html#/:1 Uncaught (in promise) TypeError: Failed to fetch
2127.0.0.1:16800/jsonrpc:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
4index.html#/:1 Uncaught (in promise) TypeError: Failed to fetch
127.0.0.1:16800/jsonrpc:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
2index.html#/:1 Uncaught (in promise) TypeError: Failed to fetch
127.0.0.1:16800/jsonrpc:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
```

**To Reproduce**
1. Start Motrix.
2. Type commands in shell.

**Expected behavior**
It respond as a TCP connection.

**Screenshots**

**Environment (please complete the following information):**
 - OS & Version: Linux
 - Version: Arch Linux 5.2.1-arch1-1-ARCH x86_64
 - Motrix Version: v1.4.1
 - Installation package type: aur/motrix v1.4.1-1

**Additional context**
Motrix is awesome!

**Comment by agalwood** [comment]
Motrix may need to run with `sudo` for the first time in Linux because there is no permission to create the download session file (`/var/cache/aria2.session`).

**Comment by libook** [comment]
@agalwood It works, thank you!
