### ISSUE TITLE
现在是否不支持设置为chrome/Edge的默认下载器？

### ISSUE THREAD

**Issue by chunguangfu** [agalwood/Motrix#369]
很喜欢软件的界面，什么时候可以支持以上两个浏览器的默认下载器啊，可以自动嗅探到下载网址的。

**Comment by agalwood** [comment]
暂时可以使用 [YAAW for Chrome](https://chrome.google.com/webstore/detail/yaaw-for-chrome/dennnbdlpgjgbcjfgaohdahloollfgoc) 这个扩展实现，配置方法请参考文档：
https://www.yuque.com/moapp/help/extensions#22993f87

**Comment by leezn** [comment]
> 暂时可以使用 [YAAW for Chrome](https://chrome.google.com/webstore/detail/yaaw-for-chrome/dennnbdlpgjgbcjfgaohdahloollfgoc) 这个扩展实现，配置方法请参考文档：
> https://www.yuque.com/moapp/help/extensions#22993f87

可否增加下载确认的提示窗？还有使用Tampermonkey获取的百度云下载到的文件名是乱码无后缀的

**Comment by asnfohsdgfbkxcv** [comment]
> > 暂时可以使用 [YAAW for Chrome](https://chrome.google.com/webstore/detail/yaaw-for-chrome/dennnbdlpgjgbcjfgaohdahloollfgoc) 这个扩展实现，配置方法请参考文档：
> > https://www.yuque.com/moapp/help/extensions#22993f87
> 
> 可否增加下载确认的提示窗？还有使用Tampermonkey获取的百度云下载到的文件名是乱码无后缀的

这个并不好用，不是每个链接都是直连，而且不是每个页面都有右键菜单

**Comment by tpnet** [comment]
@asnfohsdgfbkxcv @leezn  设置大小拦截
![image](https://user-images.githubusercontent.com/17380722/68463309-5202ba00-0249-11ea-8207-f89da47dab56.png)
