### ISSUE TITLE
ProcessOn下载流程图大概率出现#22错误

### ISSUE THREAD

**Issue by xieqing0428** [agalwood/Motrix#374]
**Describe the bug**
ProcessOn下载流程图大概率出现#22错误

**To Reproduce**
1. 在ProcessOn画好流程图
2. 点击'下载'
3. YAAW插件接管导出下载任务到 'Motrix'
4. 大概率出现#22错误, ‘已停止’栏显示文件名flow

**Screenshots**
![image](https://user-images.githubusercontent.com/30398157/61918709-e9871a00-af84-11e9-9e81-68b32906d67c.png)

**Environment (please complete the following information):**
 - OS & Version: macOS
 - Version: macOS 10.14.6
 - Motrix Version: 1.4.1
 - Installation package type: dmg

**Comment by agalwood** [comment]
ProcessOn 这种需要服务器响应你“下载”请求之后再生成文件给你下载，有点一次性的感觉

[Motrix] download error===> Gid: 515d2ad83c7dace9, #22, The response status is not successful. status=405
(anonymous) @ index.js:1

所以不建议用 Motrix 拦截，你可以设置 YAAW 的文件拦截大小稍微大点，比如 > 10M

**Comment by xieqing0428** [comment]
> ProcessOn 这种需要服务器响应你“下载”请求之后再生成文件给你下载，有点一次性的感觉
> 
> [Motrix] download error===> Gid: 515d2ad83c7dace9, #22, The response status is not successful. status=405
> (anonymous) @ index.js:1
> 
> 所以不建议用 Motrix 拦截，你可以设置 YAAW 的文件拦截大小稍微大点，比如 > 10M

嗷嗷好的，谢谢啦
