### ISSUE TITLE
下载到最后速度降为 0 

### ISSUE THREAD

**Issue by leirt97** [agalwood/Motrix#375]
**错误描述**
一个文件在下载到最后的时候，文件进度已经是 100% 了，但是速度变为 0KB/s，一直未完成，处于下载中的状态。  

**如何重现**
1. 新建磁链任务，链接为 magnet:?xt=urn:btih:28578671D5E855F173072F1A5ABC13B976003537 
2. 提交后开始下载，然后出现错误描述中的内容。

**预期的行为**
文件下载完成，进入已停止列表中。

**截图**
![WechatIMG47](https://user-images.githubusercontent.com/31821058/61940516-2e807000-afc8-11e9-8a0c-6b895240a53e.png)

**运行环境**
Mac
10.12.6
Motrix 版本：1.4.1
安装包类型：dmg

**Comment by agalwood** [comment]
这是BT任务已经下载完但是在做种状态，如果你不想做种，可以点击⏹按钮停止做种。

系统消息通知里有提示了在做种中，下版本优化下做种状态的展示吧

**Comment by leirt97** [comment]
原来是这样，所以最后如果我不想要做种的话，点击 暂停 按钮停止做种，文件就会下载完成了是吗？
多谢回复，开发辛苦了。

**Comment by agalwood** [comment]
是的，你可以试下
