### ISSUE TITLE
添加一个清楚所有当前任务的按钮吧，一个一个删除，还要再点击，同时删除文件，恶心到我了

### ISSUE THREAD

**Issue by NoahCodeMonkey** [agalwood/Motrix#376]
**请描述一下你的新功能请求是否与已知问题有关？**
简明扼要地描述了问题所在。

**描述你想要的解决方案**
简明扼要地描述你想要的解决方案。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by lidongpeng11** [comment]
我也遇到了同样的问题,我下载的是一个大文件夹,大文件夹内有很多小文件夹,然后小文件夹有很多小文件,我在大文件夹上点了个下载,然后下载了全部的文件,我后来想了想,可以先要某个小文件夹,然后看完了再看一个小文件夹,我点了暂停,但是没有批量删除功能,清楚全部的那种,手点的次数太多了

**Comment by ted423** [comment]
试了下，可以在yaaw里删

**Comment by agalwood** [comment]
已添加了鼠标拖拽选中任务批量删除功能，请更新 Motrix 到 v1.5.x 版本https://github.com/agalwood/Motrix/releases
