### ISSUE TITLE
cmd 调用

### ISSUE THREAD

**Issue by lesterpang** [agalwood/Motrix#378]
是否可以通过 api 接口，或者命令行调用motrix新建下载任务？

**Comment by agalwood** [comment]
Motrix 内置的下载引擎是 [aria2](https://aria2.github.io/manual/en/html/aria2c.html) 

你可以试试这个 npm 包以 json-rpc 的形式调用 Motrix 内置的 aria2 服务
https://www.npmjs.com/package/aria2

Host: 127.0.0.1
Port: 16800
