### ISSUE TITLE
下载插件的问题

### ISSUE THREAD

**Issue by YLXDXX** [agalwood/Motrix#38]
请问，能否增加一个能够把一般的下载直接导入的功能？
(现在的下载插件虽然对百度网盘好用，但是对于其它的下载任务还是需要手动导入，希望能够接管浏览器的下载)

**Comment by agalwood** [comment]
功能待开发
https://trello.com/c/cQCY8ddA/5-mo-helper-浏览器扩展

**Comment by agalwood** [comment]
目前可以使用 YAAW for Chrome 接管下载到 Motrix，Motrix 内置的 aria2 的 RPC 端口为 16800
配置 JSON-RPC 为 http://localhost:16800/jsonrpc 即可
chrome-extension://dennnbdlpgjgbcjfgaohdahloollfgoc/options.html
