### ISSUE TITLE
希望增加重复下载链接的检测功能

### ISSUE THREAD

**Issue by ted423** [agalwood/Motrix#380]
https://photo.weibo.com/5643044717/talbum/index#!/mode/1/page/1
+
https://greasyfork.org/zh-CN/scripts/18036-%E5%BE%AE%E5%8D%9A%E7%9B%B8%E5%86%8C%E5%9B%BE%E7%89%87%E5%9C%B0%E5%9D%80%E6%89%B9%E9%87%8F%E8%8E%B7%E5%8F%96%E5%B7%A5%E5%85%B7

一次的连接3000多个，但是不全

所以想靠多提取几次看看，但是motrix会直接覆盖文件

**Comment by agalwood** [comment]
又是如此残暴的任务数...

你可以通过修改 Motrix 的配置文件 `system.json` 关掉自动覆盖的特性试试
https://github.com/agalwood/Motrix/issues/325#issuecomment-509575864

**Comment by ted423** [comment]
> 又是如此残暴的任务数...
> 
> 你可以通过修改 Motrix 的配置文件 `system.json` 关掉自动覆盖的特性试试
> [#325 (comment)](https://github.com/agalwood/Motrix/issues/325#issuecomment-509575864)

我试下
