### ISSUE TITLE
提供aria2c的源代码

### ISSUE THREAD

**Issue by zaoqi** [agalwood/Motrix#381]
https://github.com/agalwood/Motrix/blob/master/extra/linux/engine/aria2c

aria2的LICENSE是[GPLv2](https://github.com/aria2/aria2/blob/master/COPYING)
我在这个项目内找不到它的源代码

**Comment by agalwood** [comment]
https://github.com/agalwood/aria2

虽然之前 fork 了改了点，但其实 Motrix 内置的 Linux 版本 aria2c 就是官方版本源码编译的
