### ISSUE TITLE
希望增加递归下载功能

### ISSUE THREAD

**Issue by ysway** [agalwood/Motrix#386]
希望能增加像Wget类似的递归下载的功能，适用于webdav和其他的文件目录下载。

**Comment by agalwood** [comment]
这个暂时无能为力：|

https://superuser.com/questions/935413/how-do-i-download-an-entire-folder-with-aria2/

**Comment by yswysc** [comment]
应该还是有解决方案的吧，现在有些三方百度网盘下载器就是使用aria2，但是可以完整下载百度云的文件夹。
还有找到了一个适用于aria2递归下载的脚本，可是完全不知道怎么使用。
https://github.com/PeterCxy/yarmd
