### ISSUE TITLE
能不能把软件的框架重新设计一下

### ISSUE THREAD

**Issue by underlaw** [agalwood/Motrix#388]
现有的框架搞成三联式的，个人觉得真不好用，能不弄个左右两框的，纯个人喜好，供参考。

*

**Comment by agalwood** [comment]
精力有限，暂无计划，UI大的改动我估计要等 2.0 了吧：p

**Comment by underlaw** [comment]
[https://github.com/wapznw/aria2desktop/blob/master/screenshot/windows10-aria2desktop.png](url)

类似这种不很好看吗
