### ISSUE TITLE
YAAW一直提示导出下载失败

### ISSUE THREAD

**Issue by KylinShi** [agalwood/Motrix#389]
设置以后还是提示导出下载失败
![image](https://user-images.githubusercontent.com/29354129/62834977-ceefb900-bc85-11e9-83b2-c8d2962538d1.png)

**Comment by agalwood** [comment]
这个 YAAW 插件导出任务到 Motrix 时，需要先启动 Motrix 的

**Comment by KylinShi** [comment]
非常感谢
