### ISSUE TITLE
下载时fail to fetch进程

### ISSUE THREAD

**Issue by DebussyQi** [agalwood/Motrix#390]
**错误描述**
任何的下载都显示fail to fetch，尝试重装也无效
小白请求帮助，谢谢您
**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接
3. 点击提交
4. 发现报错fail to fetch
后台未运行aria2c进程

**运行环境**
 - 操作系统类型：Windows10
 - 具体版本： [如 macOS 10.14.2, Windows 10, Ubuntu 18.04]
 - Motrix 版本： 1.4.1
 - 安装包类型：exe
**更多信息**
补充有关该问题的其他信息。

**Comment by agalwood** [comment]
Motrix 内置的 aria2c 进程如果没启动成功，新建任务就会报 Failed to fetch 的，你检查一下是否有什么安全软件阻止了 aria2c 的启动

**Comment by TTTPOB** [comment]
原来这里也有受害者，可是我没有发现什么软件阻止了，再看看吧

**Comment by weizhizhu** [comment]
这个需要怎么检查？？？

**Comment by gchengyu** [comment]
> Motrix 内置的 aria2c 进程如果没启动成功，新建任务就会报 Failed to fetch 的，你检查一下是否有什么安全软件阻止了 aria2c 的启动

在win10运行环境下任务管理器中有aria2进程
昨天正常
今天就不行了

操作系统类型：Windows10
具体版本：Windows10
Motrix 版本： 1.4.1
安装包类型：exe

**Comment by HyangXsea** [comment]
贴吧看到的野方法可以解决：
关掉Motrix后到你的C盘找到C:\Users\Administrator\AppData\Roaming文件夹里的Motrix文件夹，全部删除就可以了
