### ISSUE TITLE
Unable to make Motrix autostart at startup

### ISSUE THREAD

**Issue by huyndnse63331** [agalwood/Motrix#397]
Hi, i really love this tool. But i'm having a trouble with making it autostart at startup. I'm using Ubuntu 18.04.3 (amd64). As i noticed in the changelog of version 1.4.1, you guys mentioned `Startup automatically at login` but i don't see such thing + there is no option in preferences allowing user to make the tool autostart at startup. Please consider this option. Thank you so much for the great tool.

**Comment by agalwood** [comment]
Limited by Electron's API, `Startup automatically at login` currently only supports macOS and Windows.

https://electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows

**Comment by huyndnse63331** [comment]
so is there any alternative way to make the app autostart at startup (without showing the gui, just stay minimized on the taskbar)?

**Comment by agalwood** [comment]
Minimization at startup can be achieved by passing parameters, you can try to write your own startup scripts in the system.

```bash
# macOS
open -a /Applications/Motrix.app --args --opened-at-login=1
```

**Comment by huyndnse63331** [comment]
But im using Ubuntu 18, how can i make that happen?
