### ISSUE TITLE
English User Interface

### ISSUE THREAD

**Issue by probonopd** [agalwood/Motrix#4]
Please add an English User Interface. Thank you very much.

**Comment by agalwood** [comment]
Thank you for your continued attention. The English version is still thinking about a better implementation. Do you have any suggestions?

**Comment by probonopd** [comment]
Thanks for your reply, I don't understand what the question is.

Here is what I am asking for:
If the system language is not Chinese, then the application should show no Chinese.
This would be very useful for an international audience.

Thanks for your consideration and kind regards.

**Comment by agalwood** [comment]
I mean code level suggestions...

**Comment by agalwood** [comment]
I have seen the following two APP international ways:
- All texts use the aaa.bbb.ccc.ddd id to take place.
- Translate the complete text directly as an id.
I haven't thought about it that way.

**Comment by rguedes** [comment]
Maybe you could use this: https://www.i18next.com/

**Comment by agalwood** [comment]
@rguedes Let me try, tks

**Comment by agalwood** [comment]
@probonopd @rguedes 
The English interface is still under development...
![](https://cdn.nlark.com/yuque/0/2019/png/129147/1546704242283-c7076cda-2902-463e-a3c1-7d97cded6edb.png)

**Comment by agalwood** [comment]
@probonopd 
The Internationalized version has been released, please update the screenshot of Motrix.
https://github.com/agalwood/Motrix/releases
