### ISSUE TITLE
无法使用64线程下载文件

### ISSUE THREAD

**Issue by fzh2003** [agalwood/Motrix#404]
![捕获](https://user-images.githubusercontent.com/36395790/63737058-bc959200-c8b7-11e9-9e7a-97d031114abe.PNG)
我用的是motrix 1.4.1版本，操作系统是Windows 10 64位。我最多只能开启16线程下载文件，不能使用64线程。

**Comment by newtype0079** [comment]
A 64bit system is not equal to being able to download with 64 connections form the server.

**Comment by fzh2003** [comment]
@newtype0079 However,I can use it on linux or Mac in Virtualbox.

**Comment by agalwood** [comment]
已经升级到 aria2 v1.3.5 并全系统开放了 64 线程下载，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
