### ISSUE TITLE
兄弟，这个工具是你自建了VPS服务器做代理？

### ISSUE THREAD

**Issue by beanhacker** [agalwood/Motrix#406]
兄弟，这个工具是你自己开了VPS服务器做代理？速度比浏览器快很多很多，下一个GITHUB RELEASE能把人着急死，你这是神器啊！

**Comment by blurHY** [comment]
不会吧？

**Comment by agalwood** [comment]
并没有...多线程下载所以比较快

**Comment by blurHY** [comment]
> 并没有...多线程下载所以比较快

多线程也不能突破瓶颈吧

**Comment by beanhacker** [comment]
不过还是发现有点问题，100多兆的GET RELEASE网络还可以，下着下着就失败放到停止列表里了，网络正常，原因不明，而且貌似多个并发下载更容易失败，除了GITHUB链接外，其他链接并未复现类似突然中断停止问题～
