### ISSUE TITLE
使用网页调用Motrix的实例

### ISSUE THREAD

**Issue by Liupaperbox** [agalwood/Motrix#408]
在做完哔哩哔哩工具网页之后，我发现啦这个好用的下载器，
于是在提取专栏图片的批量下载上增加了使用Motrix下载，
方式是jsonrpc调用
[哔哩哔哩工具](https://www.boxpaper.club/bilitools/#)
可以支持下我吗

**Comment by Liupaperbox** [comment]
如果可以的话能不能增加另一个专门控制软件的接口，可以改变下载路径的

**Comment by agalwood** [comment]
Motrix 内置的下载引擎是 aria2，你可以看下 aria2 的文档：
https://aria2.github.io/manual/en/html/aria2c.html#aria2.addUri

下载路径的参数是 `dir` 和 `out`

推荐使用 aria2.js 快捷调用 JSON-RPC 接口
https://www.npmjs.com/package/aria2

Motrix JSON-RPC 地址：
```plaintext
http://127.0.0.1:16800
```

**Comment by Liupaperbox** [comment]
在哪里关闭下载完之后的提示？多个任务下载完成时会出现满屏幕的提示
