### ISSUE TITLE
Add dependabot to the repo

### ISSUE THREAD

**Issue by Eddi2015** [agalwood/Motrix#41]
Dear developer! Please add dependabot to the repo. It's a free bot that regularly scans the repo for outdated dependencies and creates pull-requests to update the dependency. This is important in terms of security, because newer releases often fix bugs and security problems. Thanks in advance.

https://github.com/marketplace/dependabot

**Comment by agalwood** [comment]
I will try it, Tks !

**Comment by agalwood** [comment]
I prefer to manually maintain npm dependencies.
