### ISSUE TITLE
目前只有批量暂停 没有批量删除

### ISSUE THREAD

**Issue by ziduwang** [agalwood/Motrix#410]
目前只有批量暂停 没有批量删除

**Comment by liveskai** [comment]
这个确实很难受

**Comment by 0akarma** [comment]
难受+1，而且百度云文件夹下下来不会自己分文件夹～

**Comment by agalwood** [comment]
已添加了鼠标拖拽选中任务批量删除功能，请更新 Motrix 到 v1.5.x 版本https://github.com/agalwood/Motrix/releases
