### ISSUE TITLE
任务管理页面增加多选

### ISSUE THREAD

**Issue by TTTPOB** [agalwood/Motrix#415]
**请描述一下你的新功能请求是否与已知问题有关？**
没有
**描述你想要的解决方案**
我想要任务列表可以多选，这样删任务会比较方便，希望也能给一个默认删除文件的选项。
**描述你考虑过的替代方案**
没有
**更多信息**
没有

**Comment by hikerpig** [comment]
+1

**Comment by agalwood** [comment]
已添加了鼠标拖拽选中任务以及选中所有任务，然后批量删除功能，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
