### ISSUE TITLE
建议添加自动更新track服务器的功能

### ISSUE THREAD

**Issue by nanba-dengtao** [agalwood/Motrix#42]
不然下载bt是真的没速度，可以用https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt
建议整合这个track更新到程序或者写个脚本

**Comment by nanba-dengtao** [comment]
@agalwood

**Comment by weearc** [comment]
@nanba-dengtao tracker可以通过手动更改aria2.conf来变更

**Comment by chenps10** [comment]
> @nanba-dengtao tracker可以通过手动更改aria2.conf来变更

同求这个功能，
mac下压根找不到aria2.conf的位置

**Comment by Oldmoooon** [comment]
强烈希望加入这个功能，我没找着aria2.conf。。。

**Comment by agalwood** [comment]
Motrix v1.3.x 已实现，请更新版本 https://github.com/agalwood/Motrix/releases
@nanba-dengtao 
@Oldmoooon
