### ISSUE TITLE
我在国外下载东西,都不动的

### ISSUE THREAD

**Issue by fantasthu** [agalwood/Motrix#421]
**错误描述**
在国外随便搜索了一个磁力

**如何重现**
重现步骤，如：
1. 放入磁力
2. 下载

**运行环境**
- macos

**Comment by TTTPOB** [comment]
bt之类的东西，很玄学的，你换个软件很可能也下不动，就是没有人做种呗；
另外在国外没有保护措施下磁力不会有事吗
