### ISSUE TITLE
还请开发者支持一下ed2k（电驴）的下载链接协议吧

### ISSUE THREAD

**Issue by PianCat** [agalwood/Motrix#429]
**请描述一下你的新功能请求是否与已知问题有关？**
是，无法从msdn.itellu.cn下载镜像文件，因为他们使用的全部都是ed2k协议

**描述你想要的解决方案**
支持ed2k协议下载

**描述你考虑过的替代方案**
尝试ed2k转其他协议链接，均失败

**更多信息**
支持ed2k协议的下载链接

**Comment by wheat0r** [comment]
aria2本身不支持

**Comment by ScottLiu88** [comment]
transmisson一样不支持，更别提aria2了。

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/442
