### ISSUE TITLE
反馈几个问题

### ISSUE THREAD

**Issue by xhot** [agalwood/Motrix#43]
软件用起来很棒，速度也很快，界面漂亮
反馈几个问题，希望改进的更好：
1.软件最小化后会退出，任务栏右侧无通知小图标。
2.不自动保存上次的下载目录。
3.无法直接打开种子文件，需到下载菜单拖拉或选择。
4.下载任务列表右上的图标菜单点击无效

**Comment by agalwood** [comment]
1, 2, 3 问题都能理解，第4点有点不明白，是指点击“ 。。。”没反应么？
那个“更多操作”还没开发完，我应该隐藏掉的...

**Comment by agalwood** [comment]
除了第 2 条（暂不考虑），其他都已经完成，请更新到最新版本 v1.3.8
