### ISSUE TITLE
建议使用改版 aria2

### ISSUE THREAD

**Issue by YeungKC** [agalwood/Motrix#433]
目前 aria2 是官方版本编译，最大下载线程仅为 16，希望可以改版增加到 256，分片最小也希望降低，比如 128k 256k 左右，很多时候下载影响很大，比如 GitHub 下载东西…这样我就可以从 aria2GUI 转到这里来了……………

**Comment by agalwood** [comment]
已经升级到 aria2 v1.3.5 并全系统开放了 64 线程下载（其他和官方原版一致），请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
