### ISSUE TITLE
热门种子是什么？能提供一个吗？

### ISSUE THREAD

**Issue by weidongzhou1994** [agalwood/Motrix#434]
哪位大佬提供一个热门种子啊，找了好多都不行

**Comment by underlaw** [comment]
小姐姐的片子都是热门

**Comment by agalwood** [comment]
https://releases.ubuntu.com/20.04/ubuntu-20.04-desktop-amd64.iso.torrent

**Comment by sp42** [comment]
上面种子已经失效，请再提供
