### ISSUE TITLE
如何在Python中调用motrix？

### ISSUE THREAD

**Issue by Jarvis-Cai** [agalwood/Motrix#436]
**请描述一下你的新功能请求是否与已知问题有关？**
由于这个motrix非常好用，所以我在想，能否在Python程序里面调用这个软件呢？

**描述你想要的解决方案**
比如说，是否有相应的指令呢？例如传入链接，重命名，开始下载之类的。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by weearc** [comment]
motrix使用aria2c作为后端，因此可参考使用python调用aria2c

**Comment by Jarvis-Cai** [comment]
hi~ @weearc Thanks a lot. It's very helpful.

**Comment by cn-src** [comment]
用 aria2c 感觉速度跟没法跟 Motrix 比啊。很多资源用 Motrix 很快，用命令行程序慢的要死，包括 aria2c。要是能从命令行调用就太好了。

**Comment by weearc** [comment]
cli下用需要加参数的。motrix的默认加了多线程肯定要快


 
---原始邮件---
发件人: "永夜"<notifications@github.com&gt;
发送时间: 2019年12月13日 16:26:42
收件人: "agalwood/Motrix"<Motrix@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Binye Qi"<q19981121@163.com&gt;;
主题: Re: [agalwood/Motrix] 如何在Python中调用motrix？ (#436)



用 aria2c 感觉速度跟没法跟 Motrix 比啊。很多资源用 Motrix 很快，用命令行程序慢的要死，包括 aria2c。要是能从命令行调用就太好了。

**Comment by cn-src** [comment]
@weearc 谢谢，问下2个问题：
1. Motrix 是只封装了下 aria2 么
2. aria2 优化的一些参数能不能分享下，只是增加了多线程么

**Comment by weearc** [comment]
@cn-src  根据我的理解以及打包过程来讲，motrix确实是封装了aria2（这点和其他许多下载工具相同）。另外aria2参数可以自行在手册里查找，我一Linux用户的参数不是通用的...

**Comment by agalwood** [comment]
Motrix 内置 aria2，开放的 JSON-RPC 端口为 `16800`

可以使用 HTTP 请求调用，参考 https://gist.github.com/lpimem/3b505fa85739671a8dde504f607a25d3

aria2 的 API 请参考官方文档：
https://aria2.github.io/manual/en/html/aria2c.html#methods
