### ISSUE TITLE
对官网提一些建议

### ISSUE THREAD

**Issue by RoderickQiu** [agalwood/Motrix#44]
这个官网写的不很清楚，也不很友好。
- 比如你的这个“立即下载”会转到一个需要登陆才能下载的界面，会让很多用户放弃你的软件。
- 你的整个网站竟然没有写项目的GitHub地址……
- 你的帮助文档目录中有不存在的地址。
- 关于页的版本号比首页的旧。
- 你的menu打开之后会有一些平台的icon，让我最开始以为是项目的页面，后来才发现是开发者的。
- 特性页面里面的蓝色字符让人觉得是链接。

你的程序本身写的很不错，不过为什么不加一个最小化到托盘菜单的功能呢，Windows上很希望有。
_如果有需要我也可以参与，毕竟本人这段时间也在搞Electron，搞了两个项目，[wnr](https://github.com/RoderickQiu/wnr) 和 [ydic](https://github.com/RoderickQiu/ydic)。其中第一个已经基本完工，第二个还在鸽，还没有推广过，欢迎star。_

**Comment by RoderickQiu** [comment]
@agalwood

**Comment by RoderickQiu** [comment]
话说你的个人网站还没做完吗 都是空着的
首页的那些links会动 极其不友好

**Comment by agalwood** [comment]
感谢你的反馈和建议
1. 我一直登录着语雀，竟然没发现下载要登录，尴尬了😅...已替换为 GitHub 的链接
2. 临时搭的官网，本来是上架苹果Mac App Store 审核用的，有些东西就没加...正在重构🙃
3. 目录里有篇文章未发布，已从目录移除
4. 关于页的版本号已更新
5. 同2，会重新调整，加上更多项目相关的链接
6. 是会引起误会，已移除
7. 远离 Windows 好多年，没意识到这个“最小化到托盘菜单”的需求的迫切性，已在 [TODO](https://trello.com/c/IiaO9nx7/3-%E6%89%98%E7%9B%98%E5%9B%BE%E6%A0%87%E5%8A%9F%E8%83%BD) 里
8. 欢迎参与，有兴趣可以看下项目的 [Trello](https://trello.com/b/qNUzA0bv/motrix)
9. 个人网站几次开坑都没填完，有点成烂尾楼了哈...那些链接就当彩蛋吧，本来就没想给人点哈哈哈

**Comment by agalwood** [comment]
应用的国际化已经基本开发完成，等官网重构完一起发布
https://github.com/agalwood/Motrix/tree/feature/i18next_201901042000

**Comment by RoderickQiu** [comment]
😃 

---
话说还忘了一件事情
考虑做个这个吗
https://electronjs.org/docs/tutorial/progress-bar
方便看进度

**Comment by RoderickQiu** [comment]
这个做起来虽然不是特别复杂
但却实有两个重点：
- 多任务时如何处理
- 如果算法不佳或是进度条改变频率太高等都会对cpu产生在任务管理器中清晰可见的影响

**Comment by agalwood** [comment]
Motrix限制了同时下载任务数为10，统计下载中的总进度还好，可以和下载速度和任务列表共用轮循的

PS. issue里有些用户一次性提交几百个任务的😵

**Comment by agalwood** [comment]
@RoderickQiu 官网重构了一版上线了

**Comment by RoderickQiu** [comment]
也许是我的iPad版本太低
但至少iOS10的Safari里看
motrix的主界面在最大化时 会遮住标题
也许是屏幕太小了
（当然这一点无关紧要毕竟用户基本都是会用电脑端访问的屏幕大也许就没事）
iPad上看不出你使用了什么技术作自适应
但如果说是bootstrap的话做起来会很方便
把col-md改成col-lg就行了

**Comment by agalwood** [comment]
最低高度 100vh在iPad上是容易有这个问题
响应式是手撸 media query

**Comment by agalwood** [comment]
最新版 v1.2.x 已实现系统托盘图标功能
https://github.com/agalwood/Motrix/releases/tag/v1.2.2
