### ISSUE TITLE
是否可以用其它方法来实现对ed2k的支持？

### ISSUE THREAD

**Issue by nilcay** [agalwood/Motrix#442]
看了一下，其它小伙伴已经提到这个问题了。
但还是希望能能增加更多常用协议。不支持ed2k是硬伤。
不想安装迅雷，但Motrix支持的协议又不能满足需求。安装了迅雷，那还有Motrix什么事？

**Comment by weearc** [comment]
ed2k是edonkey使用的协议，由于许可的问题应该难以添加到除了电驴以外的程式中。具体请自行Google
