### ISSUE TITLE
希望能添加自定义做种时间

### ISSUE THREAD

**Issue by R-Josef** [agalwood/Motrix#443]
**请描述一下你的新功能请求是否与已知问题有关？**
我发现在BT种子下载好之后，过一段时间就会停止做种，我希望能设置更长时间的做种时间，而软件内没有可以设置的地方。

**描述你想要的解决方案**
我了解到aria2有`seed-ratio`这项设定，设否能在设置内提供相应的项呢？

**Comment by agalwood** [comment]
可以手动编辑 `system.json`，文件路径自己看下操作系统对应的
https://github.com/agalwood/Motrix/issues/138#issuecomment-473632340

```json
"seed-ratio": 1,
"seed-time": 60,
```
