### ISSUE TITLE
如果连ed2k都不支持，又如何称得上全能？这软件只开发给程序员用？

### ISSUE THREAD

**Issue by davyliuhong** [agalwood/Motrix#445]
如果连ed2k都不支持，又如何称得上全能？这软件只开发给程序员用？？难道非程序员就不配用这款下载软件？ui界面可以人性化点吗？

**Comment by davyliuhong** [comment]
如果只开发给程序员用，这软件的存在意义是什么?
问的比较直接，没有恶意

**Comment by davyliuhong** [comment]
如果觉得没有收入，大可以加入广告，捐赠二维码等。相信广大非程序员用户还是希望不被迅雷垄断的

**Comment by Xuyiyang23333** [comment]
界面我倒觉得还行，然后ed2k似乎aria2本身就不支持。

**Comment by Frank17** [comment]
一股酸味，想要支持自己去开发啊，开源社区还有键盘侠？没有意义不要用啊，建议closed

**Comment by AndyZhoukh** [comment]
你要想要这个功能自己开发啊，这是开源的，别人没有义务帮你开发功能

**Comment by weearc** [comment]
1. 别人本来就没义务一直给新功能。帮了是情分不帮是本分。
2. aria2不支持。
3. 添加了amule会出现许可证问题。
4. 就算无视许可证添加会带来不必要的内存开销，本身就是electron应用你以为谁都是动辄16GB内存吗（笑哭）


 
---原始邮件---
发件人: "davyliuhong"<notifications@github.com&gt;
发送时间: 2019年10月13日 07:33:32
收件人: "agalwood/Motrix"<Motrix@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [agalwood/Motrix] 如果连ed2k都不支持，又如何称得上全能？这软件只开发给程序员用？ (#445)



如果连ed2k都不支持，又如何称得上全能？这软件只开发给程序员用？？难道非程序员就不配用这款下载软件？ui界面可以人性化点吗？

**Comment by 2276193373** [comment]
这里是开源社区，你用得不爽自己贡献一份呗

**Comment by martin0752** [comment]
xswl，github就是给程序员用的，你也要去提个issue吗？

**Comment by 44667788** [comment]
根本是两种不同的协议。bt和电驴是不同的东西。

**Comment by Sciroccogti** [comment]
那你是没见过真正给程序员用的下载器，命令行下载器axel了解一下。

**Comment by boxsnake** [comment]
> axel

> 那你是没见过真正给程序员用的下载器，命令行下载器axel了解一下。

程序员都是手动一个字节一个字节打的，俗称人肉下载器
[滑稽]
