### ISSUE TITLE
V1.4.1 在Ubuntu18.04上退出后，图标仍然存在

### ISSUE THREAD

**Issue by BloveDawn** [agalwood/Motrix#446]
**Describe the bug**
在Ubuntu18.04上关闭后，图标仍然存在，右键可以调出菜单但是点击任何按钮都无反应，在任务管理器杀掉进程才能完全关闭

**To Reproduce**
1. 启动程序
2. 点击左上角的关闭按钮
3. 程序无法完全退出

**Expected behavior**
完全退出

**Environment (please complete the following information):**
 - OS & Version: Linux
 - Version: Ubuntu 18.04
 - Motrix Version: 1.4.1
 - Installation package type: AppImage

**Comment by History-exe** [comment]
同样有这个问题，ubuntu20.04, 软件版本是自带snap商店里的1.5.12
