### ISSUE TITLE
下载发生错误#22

### ISSUE THREAD

**Issue by ckin6122** [agalwood/Motrix#452]
浏览器重置后重新安装后就出现此情况：文件名 下载发生错误#22
浏览器：chrome 77.0.3865.90 
motrix版本：1.4.1

**Comment by colibris79** [comment]
我也是.
chrome 77.0.3865.90
motrix：1.4.1
BaiduExporter 1.0.2
Ubuntu 18.04

**Comment by Mingyi** [comment]
我也是，很头疼，解决不了。

看错误页面显示原因是。If HTTP response header was bad or unexpected.

chrome 版本 78.0.3904.70（正式版本）
motrix：1.4.1  

升级到这个版本就出问题了

**Comment by tpnet** [comment]
需要登录账号

**Comment by colibris79** [comment]
> 需要登录账号

在哪里登录?

**Comment by HBSITION** [comment]
你们解决了吗？我登了谷歌账号也没用啊。

**Comment by colibris79** [comment]
> 你们解决了吗？我登了谷歌账号也没用啊。

还没有

**Comment by Sciroccogti** [comment]
应该是指 不能下载 需要登录才有权限下载的东西，下载器好像只会复制你的下载链接，你在另一个没有登录的浏览器里打开下载链接试试看，应该也是不能下载的。

**Comment by colibris79** [comment]
> 应该是指 不能下载 需要登录才有权限下载的东西，下载器好像只会复制你的下载链接，你在另一个没有登录的浏览器里打开下载链接试试看，应该也是不能下载的。

在百度盘一直登录.解决了,APPIMAGE的文件在我的电脑不能用.安装DEB文件以后没问题了

**Comment by ugfly1210** [comment]
同样问题。  和google账户无关。只要是百度云的资源就报#22

**Comment by yozorarica** [comment]
雲盤登陸過了 也是一樣報#22

chorme版本 79.0.3945.88（正式版本）
motrix版本 1.4.1(引擎版本1.34)

**Comment by jiwenyi163** [comment]
是哇，我也碰到这个问题了，同一个目录里，有的文件可以下载，有的不能。最近正在下载庆余年，很无奈啊

**Comment by z1277724487** [comment]
chrome+macOS
有没有人解决可以下载百度云的
求教
我也是报错显示#22

**Comment by jiwenyi163** [comment]
发现规律了，貌似从百度云下载，一个一个下载是没问题的。就是很慢，几十k，但是，同时下载多个就会报这个#22错误。

**Comment by tpnet** [comment]
@jiwenyi163  mac版本，怎么下载都错误

**Comment by lynnchae** [comment]
> @jiwenyi163 mac版本，怎么下载都错误

+1

**Comment by 15815337432** [comment]
mac版本，怎么下载都错误

**Comment by gaoyuke** [comment]
同mac版本 下载百度云 报错22

**Comment by harichen** [comment]
同mac版本，百度云 报错22

**Comment by did999** [comment]
复制直链到motrix，点击 + 号新建下载任务，拉到该页面下方，找到高级设置，将chrome f12 开发者选项中的配置一一对应填入，就能正常下载了。

**Comment by lickumap** [comment]
> 复制直链到motrix，点击 + 号新建下载任务，拉到该页面下方，找到高级设置，将chrome f12 开发者选项中的配置一一对应填入，就能正常下载了。
将chrome f12 开发者选项中的配置一一对应填入  是哪些?  F12 出来看不懂

**Comment by vnnw** [comment]
今天在B站看到一个解决方案，把网址中的alipan改为aliyundrive即可，亲测有效。
原文：https://www.bilibili.com/read/cv29481811/

**Comment by stardust495** [comment]
> aliyundrive

谢谢！！！超有用！！！！
