### ISSUE TITLE
安装包都下载不了，点击就404

### ISSUE THREAD

**Issue by Xanthuim** [agalwood/Motrix#455]
下载地址都打不开：
找不到此 github-production-release-asset-2e65be.s3.amazonaws.com 页面

**运行环境**
 - 操作系统类型： Windows 10
 - Motrix 版本： 1.4.1
 - 安装包类型：exe

**更多信息**

**Comment by Huiaei** [comment]
github的日常情况，推荐去它的[官方网页](https://motrix.app/zh-CN/)下载，中文语言下的下载链接用的是国内的加速。

# 1.4.1
+ Windows：https://dl.motrix.app/release/Motrix-Setup-1.4.1.exe
+ Macos：    https://dl.motrix.app/release/Motrix-1.4.1.dmg
+ Linux：      https://dl.motrix.app/release/Motrix-1.4.1-x86_64.AppImage
