### ISSUE TITLE
顶栏重合错乱

### ISSUE THREAD

**Issue by lin4578** [agalwood/Motrix#46]
![bgjt1 cxh o2nyd4 47 x3](https://user-images.githubusercontent.com/41137500/52265056-27a86700-296e-11e9-8db4-d9df16ab31b6.png
![bgjt1 cxh o2nyd4 47 x3](https://user-images.githubusercontent.com/41137500/52265118-4d357080-296e-11e9-93f4-a431071a9ca4.png)
)
当在Tampermonkey打开百度网盘直接下载器时出现图一情况

**Comment by agalwood** [comment]
这看起来是多个浏览器插件引起的样式冲突吧？请自己关掉其他插件试一下

**Comment by lin4578** [comment]
我知道是Tampermonkey中的“百度网盘直接下载器”这个插件的问题。所以我想问是能适配一下，让二者共存可以吗？

**Comment by agalwood** [comment]
🙃greasyfork上找了一个“百度网盘直接下载”的脚本看了一下，快2000行，精力有限，放弃

PS. 报问题麻烦把插件链接带上
