### ISSUE TITLE
关闭按钮区域功能优化

### ISSUE THREAD

**Issue by PaTTeeL** [agalwood/Motrix#461]
刚开始用，功能大赞，特别是跟插件配合实现浏览器的网页下载整合，比之前单独用的pandowload以及firefox和edge上的各种插件都要舒服，基本上是迅雷的完美替代品！
有个功能希望能优化一下，具体如图：
按照win10窗口的基本设计，当鼠标移到整个桌面右上角的时候，关闭按钮是点亮状态，但motrix好像保留了2-3个像素的窗体空间？然后就会出现关不掉窗口的问题，每次都需要多点几下。
希望能优化一下关闭按钮的位置，能否跟win10的系统默认一致，这样对于程序的使用和切换也会更舒服一些~~

motrix的关闭按钮示意图
![image](https://user-images.githubusercontent.com/9150277/67839227-1de31700-fb2e-11e9-8f0b-5951c2bc065a.png)

win10默认窗口的关闭按钮位置
![image](https://user-images.githubusercontent.com/9150277/67839692-2d169480-fb2f-11e9-816a-5cdec68238e1.png)

**Comment by agalwood** [comment]
已调整，下一个版本发布
#544
