### ISSUE TITLE
无法使用motrix下载百度云文件和迅雷文件

### ISSUE THREAD

**Issue by oranges-eating** [agalwood/Motrix#468]
我尝试了下，我提交任务后没有出现任何提示，没有出现下载失败，只是界面一片空白，就跟没有提交任务一样，迅雷和百度云下载都是如此

**Comment by fuhx** [comment]
尝试过，可以从百度云下载，不过速度只有几十KB，浏览器需要安装百度网盘助手，通过助手提取直下链接放到motrix下载。

**Comment by jiwenyi163** [comment]
百度云有的可以下载，有的会提示#22错误，希望帮忙看看

**Comment by agalwood** [comment]
应用内置的 aria2 可能没正常启动，重启应用尝试，或更新到最新版本

另外：百度云的问题请自行探索
