### ISSUE TITLE
批量下载百度盘文件时，出现多个文件无法下载

### ISSUE THREAD

**Issue by YourOlderBrother** [agalwood/Motrix#47]
问题如题

下载了一个文件夹，里面大概有180+压缩文件，总大小5g。
很多文件下载失败，然后就跳到了已完成里面，但是这个文件根本没有下载，且没有办法重新下载。

 - Version [e.g. 1.0.10]

**Comment by agalwood** [comment]
已完成列表包含“下载成功complete”、“出错的error”、“已移除的removed”

看来这个列表名得改个名字了😑

重新下载也是个bug吧

**Comment by YourOlderBrother** [comment]
那么如何让出错的下载成功呢？复制出错的任务链接放到浏览器里，下载地址是正确的。所以是读取下载列表的流出了问题吗？

**Comment by agalwood** [comment]
完全退出应用，重新启动应用，然后试一下右上角的“恢复所有任务”

**Comment by konia** [comment]
Mac 版本确实有这个问题，批量下载会多文件报错，并且软件会 crash，重启软件之后，再次恢复下载，还会 crash

**Comment by ZYLHL** [comment]
> Mac 版本确实有这个问题，批量下载会多文件报错，并且软件会 crash，重启软件之后，再次恢复下载，还会 crash

不仅仅是MAC，我win10也遇到了。
