### ISSUE TITLE
复制磁力链接能不能不要带那么长的后缀

### ISSUE THREAD

**Issue by liveskai** [agalwood/Motrix#478]
后缀实在是太长了还不知道有什么用

**Comment by gqbre** [comment]
难道不是 tracker 信息？

**Comment by liveskai** [comment]
> 难道不是 tracker 信息？

这么长的后缀有什么用吗？

**Comment by gadfly3173** [comment]
> > 难道不是 tracker 信息？
> 
> 这么长的后缀有什么用吗？

tracker用于寻找网络中正在共享或者需要该资源的计算机，提升bt体验 这种东西建议去百度一下

**Comment by liveskai** [comment]
> 用于寻找
我问的是后缀有什么用，直接复制磁力链不好吗？

**Comment by liveskai** [comment]
> > > 难道不是 tracker 信息？
> > 
> > 
> > 这么长的后缀有什么用吗？
> 
> tracker用于寻找网络中正在共享或者需要该资源的计算机，提升bt体验 这种东西建议去百度一下

回复我之前麻烦先看清楚我说的什么

**Comment by liveskai** [comment]
> > > 难道不是 tracker 信息？
> > 
> > 
> > 这么长的后缀有什么用吗？
> 
> tracker用于寻找网络中正在共享或者需要该资源的计算机，提升bt体验 这种东西建议去百度一下
