### ISSUE TITLE
默认窗口高度过大，建议适当调整

### ISSUE THREAD

**Issue by liuwenhuan** [agalwood/Motrix#48]
在linux 平台（deepin，屏幕缩放设置为1.25倍） 打开后Motrix的默认窗口打开以后，其高度会撑满整个屏幕。感觉是默认高度被设置为整个屏幕分辨率减去任务栏高度（更换多个分辨率也是如此）
建议调整高度算法，使得窗口大小更为协调和使用方便。

![_desktop_20190209155548](https://user-images.githubusercontent.com/6106120/52518314-cb05be80-2c83-11e9-8295-2b8eec8c2e0f.png)

**Comment by agalwood** [comment]
主窗体默认大小为1024x768……这都还太大么🙃

**Comment by liuwenhuan** [comment]
我量了一下尺寸，在deepin下
1.包括窗口栏和菜单栏的大小为 1024x840
2.如果只看窗体，大小为 1024x793
设置为1.25倍放缩，高度就分别变成了1050和991。如果屏幕分辨率为1980x1080 ，考虑到底部的任务栏最小42的高度，实际显示空间高度为1038。 在linux下由于默认有窗口栏和菜单栏，1050>1038 ，就完全撑满屏幕了。
因此，考虑到各种操作系统和桌面环境的适配性，建议默认高度设置为600以下（感觉对窗口响美观的影响不大）

**Comment by agalwood** [comment]
v1.1.3版本已经支持隐藏标题栏和菜单栏，在偏好设置里启用，你可以试下效果

https://github.com/agalwood/Motrix/releases/tag/v1.1.3

**Comment by liuwenhuan** [comment]
在deepin下该设置没有效果，仍然显示菜单栏和标题栏。

**Comment by asins** [comment]
UI整体尺寸设计上有过于空的，希望对UI调整得紧凑些。

**Comment by agalwood** [comment]
Linux版的隐藏菜单和外框功能的修复已发布新版，请更新到 1.2.x 
https://github.com/agalwood/Motrix/releases/tag/v1.2.2
