### ISSUE TITLE
「反馈建议」改进删除界面的UI，且记住删除文件

### ISSUE THREAD

**Issue by gongyoyo** [agalwood/Motrix#482]
**请描述一下你的新功能请求是否与已知问题有关？**
删除任务界面UI不好看，而且无法记住同时删除文件删除
最好可以多选和框选任务，快速删除任务和文件
![image](https://user-images.githubusercontent.com/36725275/69952269-cde2e000-1531-11ea-9b10-9269f1d9fcd0.png)

**描述你想要的解决方案**
可以参考下迅雷极速版
![image](https://user-images.githubusercontent.com/36725275/69952308-e4893700-1531-11ea-9739-6f6b4706c5c8.png)

**描述你考虑过的替代方案**
记住选项就行

**更多信息**
没呢，希望下个版本可以更新

**Comment by agalwood** [comment]
已经增加里 shift 点击删除任务默认选中 “同时删除文件” 的特性
https://github.com/agalwood/Motrix/pull/353

下个版本发布，自己编译开发版可以提前尝鲜
