### ISSUE TITLE
文件名称不对

### ISSUE THREAD

**Issue by hqyxd** [agalwood/Motrix#486]
**错误描述**
清楚简洁地描述错误，方便我们复现之后处理。
下载文件 文件名称乱码
**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接（如链接不涉及到隐私和版权问题，请顺便提供）
https://development2.baidupan.com/121010bb/2019/12/09/4d2bb875e40e9006a59563612cd45b44.dmg?st=XL9BhrmOAQ3BomU4v_52dw&e=1575947156&b=B31eMwBhUjRYJAcUUE5QEgMfXuYGvwqHVe4BsVHrVLMDyACoVGZUfwdkUSkGZlVxA3hZYVc7AGE_c&fi=15036061&up=
3. 点击提交
4. 发现报错
发现文件名称乱码
**预期的行为**
清楚简洁地描述你期望发生的事情。

**截图**
请添加屏幕截图以帮助解释你的问题：
![image](https://user-images.githubusercontent.com/30140395/70600833-b12e6280-1c2b-11ea-972a-1cdc1d33a222.png)

打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

**运行环境**
 - 操作系统类型： [如 macOS, Windows, Linux]
 - 具体版本： [如 macOS 10.14.2, Windows 10, Ubuntu 18.04]
 - Motrix 版本： [如 v1.1.3, v1.1.0]
 - 安装包类型：[如 dmg, AppImage]

**更多信息**
补充有关该问题的其他信息。

**Comment by agalwood** [comment]
用 PanDown 这样导出的资源名称乱码是它服务的问题，你可以使用新建任务面板里的 “重命名” 修改文件名
