### ISSUE TITLE
有关代理服务器的设置

### ISSUE THREAD

**Issue by pastay** [agalwood/Motrix#488]
在下载国外资源的时候经常很慢，能否通过连接代理服务器加速下载过程。

**描述你想要的解决方案**

个人有国外的VPS部署了V2ray以及SSR，本地是通过路由器进行透明代理，代理模式选择GFWlist白名单。能否在不去路由器改变代理模式的情况下，在本地通过MotriX的代理服务器进行代理下载？需要在服务器端安装新的软件？还是说可以通过配置连接到服务器？

![image](https://user-images.githubusercontent.com/21967597/70937901-25c82d80-2080-11ea-99a1-f835df673a81.png)
请问，这个设置可以用来连接外网服务器吗？如何设置？

**Comment by NJCCJohnWason** [comment]
进阶设置里有代理选项 把端口填进去就OK

**Comment by pastay** [comment]
感谢回答，我看到代理选项了，[http://][USER:PASSWORD@]HOST[:PORT]，我的服务器端SS服务有算法要求（aes-256-cfb)，这个要求填在哪？V2ray是用UUID连接的没有用户名。

**Comment by NJCCJohnWason** [comment]
在V2Ray客户端里把HTTP代理打开，记下它的代理端口，然后把它填进去就好 比如Windows是 127.0
.0.1 + Port

**Comment by madboy324** [comment]
[http：//] [USER：PASSWORD @] HOST [：PORT] 看不明白这个格式，请举例说明一下可以吗

**Comment by agalwood** [comment]
代理配置的说明
https://github.com/agalwood/Motrix/wiki/Proxy
