### ISSUE TITLE
Incompleted downloads in the downloaded window

### ISSUE THREAD

**Issue by eviluess** [agalwood/Motrix#49]
**Describe the bug**
The downloaded view display the unfinished download task.

**To Reproduce**
1. Download the url: https://motrix.app/release/Motrix-1.0.10.dmg

**Expected behavior**
File can be downloaded completely someday.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.  Windows7 x64]
 - Version [e.g. Windows7 x64]

**App (please complete the following information):**
 - Version [e.g. 1.0.10]

**Additional context**

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/47#issuecomment-462013609
