### ISSUE TITLE
希望可以增加一个批量操作（开始，删除）（包含全选）的功能

### ISSUE THREAD

**Issue by Sakuraine** [agalwood/Motrix#491]
有一次下载了很多文件，想删除任务要一个个删除，太多了一个个点根本删不完，体验太差了

**Comment by lxygithub** [comment]
+10086

**Comment by fendaabc** [comment]
我刚想试下软件好用吗,就点了一个文件夹开始下载....然后我现在还没删完

**Comment by matchlesshero** [comment]
不能同意更多了。。。

**Comment by liveskai** [comment]
很早就反馈了，一直没更新过

**Comment by a645162** [comment]
> 我刚想试下软件好用吗,就点了一个文件夹开始下载....然后我现在还没删完

我也是，希望添加批量删除
我是下载Bilibili上的网课
直接下载全集
然后，删了俩，我就决定，把他们都下完了删文件夹吧。

**Comment by Alphabet1226** [comment]
+1

**Comment by agalwood** [comment]
已添加了鼠标拖拽选中任务批量删除功能，请更新 Motrix 到 v1.5.x 版本https://github.com/agalwood/Motrix/releases
