### ISSUE TITLE
有些资源没有版权，如果可以直接提示无版权，可能更好。 

### ISSUE THREAD

**Issue by Reid00** [agalwood/Motrix#498]
例如资源:
ftp://7:7@dx.dl1234.com:8006/[%E7%94%B5%E5%BD%B1%E5%A4%A9%E5%A0%82www.dy2018.com]%E9%AA%87%E5%AE%A2%E4%BA%A4%E9%94%8BBD%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97.rmvb

**Comment by agalwood** [comment]
你这资源根本就不是没有版权的问题，而是目标服务器的权限问题
