### ISSUE TITLE
win10上无法使用，下载失败，提示发生错误

### ISSUE THREAD

**Issue by PikachuHy** [agalwood/Motrix#5]
我刚从GitHub上下载了win的安装包，安装完后试着下载Motrix
然后直接提示下载失败
![](https://img-blog.csdnimg.cn/20190103092937353.png)

**Comment by agalwood** [comment]
是全都不行么？

请给一下系统版本，是win 10 32位还是64位的？

**Comment by agalwood** [comment]
@PikachuHy 能否看下任务管理器里是否有 aria2c 的进程？

**Comment by PikachuHy** [comment]
![](https://img-blog.csdnimg.cn/20190103104431615.png)

**Comment by agalwood** [comment]
@PikachuHy aria2c进程有启动的呀: (，麻烦打开 Motrix—帮助—开发者工具，发下console的报错信息

**Comment by PikachuHy** [comment]
(⊙﹏⊙)没有任何报错信息，但是就是会提示下载错误
![](https://img-blog.csdnimg.cn/20190103105651402.png)

**Comment by agalwood** [comment]
@hhhuaang github的release里有，或者在这里下载：
https://motrix.app/release/

首页还要重新设计一下，再提供各种下载地址

**Comment by looha518** [comment]
下载的时候必须在账号登录的情况下下载，不然会下载失败

**Comment by yuu2lee4** [comment]
win10   下载 https://motrix.app/release/BaiduExporter.zip 直接失败

**Comment by agalwood** [comment]
@yuu2lee4 官网新版上线时浏览器扩展迁移漏了，先从这里下载吧：
https://moapp.me/release/BaiduExporter.zip

PS. 下次有问题请新开issue
