### ISSUE TITLE
建议：编译后的应用安装包中能将 单文件免安装版 换为 绿色免安装版

### ISSUE THREAD

**Issue by Ryanjiena** [agalwood/Motrix#50]
建议：编译后的应用安装包中能将 **单文件免安装版** 换为 **绿色免安装版**。

**单文件免安装版**和**绿色免安装版**区别：
&emsp;&emsp;**单文件免安装版**：在执行的时候将所有文件释放到系统临时目录，关闭程序后自动删除解压出来的文件，这就有两个缺点，第一，如果程序体积较大，每回执行时浪费在解压的时间就比较多；第二，执行程序所做的参数调整如果保存在文件内而不是注册表中，则重新执行时这些设置就无法保存下来。
&emsp;&emsp;**绿色免安装版**：不用等安装程序释放文件，配置好路径就能用。其实就是把安装过程的文件释放给跳过了，每次重装都是默认配置（不容易出问题）。换电脑使用时将整个目录再打包之后在其他电脑上解压直接使用，无需重新设置各种配置信息。

**Comment by Ryanjiena** [comment]
虽然自己也能打包编译，但是还是建议您能在官网添加一个绿色免安装版。

谢谢您😊😊

**Comment by agalwood** [comment]
我试试

**Comment by agalwood** [comment]
v1.1.3版本提供了zip版的exe，你看下是不是你要的“绿色免安装版”
https://github.com/agalwood/Motrix/releases/tag/v1.1.3
