### ISSUE TITLE
v1.4.1 linux版无所示的开机启动选项

### ISSUE THREAD

**Issue by RandnYC** [agalwood/Motrix#501]
环境: Ubuntu 16.04
![2020-01-03 04-02-14屏幕截图](https://user-images.githubusercontent.com/35365902/71689797-e585e080-2ddd-11ea-86f3-d1cfa7cfebb4.png)

**Comment by agalwood** [comment]
Motrix 基于 Electron 构建，Electron 开机启动项的 API 暂不支持 Linux
https://www.electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows
