### ISSUE TITLE
求助，能否提供一下删除文件的脚本和删除.aria2文件的脚本

### ISSUE THREAD

**Issue by SuperNG6** [agalwood/Motrix#504]
我自己尝试写过，但是远不如您写的好，在子文件夹下创建任务无法删除文件和.aria2文件，想参考一下您是怎么写的

**Comment by agalwood** [comment]
不是用 shell 脚本写的，删文件操作调用的是 Electron 的 API

代码都开源了，还找不到么。。。伸手党可耻哟 : \
https://github.com/agalwood/Motrix/blob/1f6c2a6ff0eb2774c5cbb8df8620f455781949e3/src/renderer/components/Native/utils.js#L45
