### ISSUE TITLE
支持P2P下载链接  ed2k://

### ISSUE THREAD

**Issue by AlfredMiss** [agalwood/Motrix#506]
**请描述一下你的新功能请求是否与已知问题有关？**
简明扼要地描述了问题所在。

**描述你想要的解决方案**
简明扼要地描述你想要的解决方案。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by AlfredMiss** [comment]
有序有么有将e2dk://的下载模式提上功能开发的日程呢
itellyou上面所有的下载链接全都是e2dk的模式
感觉这个功能还是很有需求的
谢谢老板 ！
老板大气！

**Comment by gztpro** [comment]
现在下载器除了迅雷就没支持电驴的了，希望这个软件能加进

**Comment by mroooone** [comment]
同希望能支持。 MSDN上的都是 
ed2k://|file|cn_windows_10_business_editions_version_1909_updated_jan_2020_x64_dvd_b3e1f3a6.iso|5311711232|3527D2A9845FF4105F485CC364655B66|/

**Comment by agalwood** [comment]
#442
