### ISSUE TITLE
Tip # 1 when downloading all magnet links and edk links

### ISSUE THREAD

**Issue by link-www** [agalwood/Motrix#509]
**Describe the bug**
Tip # 1 when downloading all magnet links and edk links
magnet：
magnet:?xt=urn:btih:ee0be01aa97e5c646549f8be60402b1ab559fbf2&tr=udp://9.rarbg.to:2710/announce&tr=udp://9.rarbg.me:2710/announce&tr=http://tr.cili001.com:8070/announce&tr=http://tracker.trackerfix.com:80/announce&tr=udp://open.demonii.com:1337&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://p4p.arenabg.com:1337&tr=wss://tracker.openwebtorrent.com&tr=wss://tracker.btorrent.xyz&tr=wss://tracker.fastcast.nz
ed2k://|file|%E8%89%AF%E5%8C%BB.The.Good.Doctor.S01E01.%E4%B8%AD%E8%8B%B1%E5%AD%97%E5%B9%95.WEBrip.720P-%E4%BA%BA%E4%BA%BA%E5%BD%B1%E8%A7%86.V4.mp4|563565647|db91e477566b81455c5e2cadc17ccf03|h=dqpfkvnxy2me2wteg57l3dpt2nwfkqyj|/
**Expected behavior**
hope successfully

**Environment (please complete the following information):**
 - OS & Version:  Windows, 
 - Version:  Windows 10, 
 - Motrix Version:  v1.4.1
 - Installation package type: Motrix-Setup-1.4.1.exe
[log.log](https://github.com/agalwood/Motrix/files/4048922/log.log)

**Comment by agalwood** [comment]
If dht.dat is not generated, downloading the magnet will be difficult.

The ed2k protocol is not supported #442
