### ISSUE TITLE
检查更新报错

### ISSUE THREAD

**Issue by yuu2lee4** [agalwood/Motrix#51]
![image](https://user-images.githubusercontent.com/8046366/52560697-1ced4680-2e34-11e9-9129-6b96e6b1084b.png)

**Comment by agalwood** [comment]
官网新版上线迁移漏了自动更新的配置，稍后修正

**Comment by agalwood** [comment]
@yuu2lee4 已修正，可以检查更新了
现在更新用的的GitHub Releases的CDN，在天朝大陆🤐下载有点慢
