### ISSUE TITLE
mac版本无法添加下载任务

### ISSUE THREAD

**Issue by CottonChou** [agalwood/Motrix#52]
mac版本上添加种子下载任务，但是任务列表中不显示。系统中已经启动了aria2c。重新安装也没办法无法下载。

**Comment by agalwood** [comment]
目测是种子编码有问题，aria2 解析不了，之前遇到过一例，换个其他种子试试

**Comment by CottonChou** [comment]
> 目测是种子编码有问题，aria2 解析不了，之前遇到过一例，换个其他种子试试
用链接也不行 尝试了各种方式都不行  始终任务列表无显示，也不报错。PS：我用的是官网的下载的dmg文件，不是自己编译的。

**Comment by CottonChou** [comment]
> 目测是种子编码有问题，aria2 解析不了，之前遇到过一例，换个其他种子试试

不下载种子，用链接也不行。。  我是下载dmg直接安装的，应该没问题。但是不知道为什么无法下载。
添加任务后，不报错，任务列表也无显示，任务也没开始下载

**Comment by agalwood** [comment]
顶部菜单-帮助-开发者工具，看下console里有没有报错信息，完整截图发一下

**Comment by CottonChou** [comment]
> 顶部菜单-帮助-开发者工具，看下console里有没有报错信息，完整截图发一下

谢谢
![jietu20190212-204002](https://user-images.githubusercontent.com/17818375/52636047-78880480-2f06-11e9-89d6-dd16252adad7.jpg)

**Comment by agalwood** [comment]
看起来一开始没连上aria2 rpc服务，后来连上了，理论上应该OK的呀: (
你试下用系统的“活动监视器”强制退出一下aria2c的进程，然后彻底退出Motrix再重新启动应用试下

**Comment by CottonChou** [comment]
> 看起来一开始没连上aria2 rpc服务，后来连上了，理论上应该OK的呀: (
> 你试下用系统的“活动监视器”强制退出一下aria2c的进程，然后彻底退出Motrix再重新启动应用试下

尝试了很多次还是不行 我录制了一个视频 清晰度很差，不过应该可以看清楚逻辑。谢谢啦
github不支持视频，我只好传到百度云上了，很小800多k
https://pan.baidu.com/s/1H-iHQVWJhOwSsOVEm4y1mQ

谢谢

**Comment by agalwood** [comment]
看不出哪里的毛病，你加下 QQ 交流群：257097026 吧
