### ISSUE TITLE
下载百度文件速度很慢

### ISSUE THREAD

**Issue by desmonna** [agalwood/Motrix#53]
利用mo app成功提取任务后，下载速度基本在10-50kb，已经换过模拟代理，和不使用代理，但是都没有用。我是win10的。
<img src="https://ww1.sinaimg.cn/large/007i4MEmgy1g043zmt2kcj30iw029a9u.jpg">

**Comment by desmonna** [comment]
非百度文件速度很快
<img src="https://ww1.sinaimg.cn/large/007i4MEmgy1g044o6r3snj30is03ajr8.jpg">

**Comment by agalwood** [comment]
最近有用其他工具下过度盘资源么？度盘免费用户每个月有“额度”的

**Comment by desmonna** [comment]
最近一直都是分享链接下载，不知道算不算

**Comment by lihongbin100** [comment]
花钱买个会员

**Comment by javaLuo** [comment]
额 我还以为可以绕过百度速度限制

**Comment by meininghang** [comment]
- 我也遇见这个问题，只是能下载，但是稳定在500kb以下；
- 所以我试了试把获取任务的同时cookie也添加进去，终于提升在1M以上。
- 但不是很确定是不是像上面说的，是本月的“额度”。
