### ISSUE TITLE
考虑开放更多的设置可能

### ISSUE THREAD

**Issue by wenpo1975** [agalwood/Motrix#530]
按以下格式填写反馈信息，谢谢
-->

BT、PT下载可能需要更多的设置、比如说DHT、IPV6、缓存大小、单个种子连接数等等

可以提供aira2 BT板块的所有配置脚本、并添加上备注，跳转到记事本打开
然后提供一个恢复默认状态的位置即可

**Comment by agalwood** [comment]
其实所有的 aria2 相关的参数都是可以通过修改 Motrix 的 system.json 文件来配置的

`system.json` 的位置自己根据操作系统类型找下
https://github.com/agalwood/Motrix/issues/138#issuecomment-473632340

https://aria2.github.io/manual/en/html/aria2c.html#input-file
