### ISSUE TITLE
隐藏菜单栏功能失效

### ISSUE THREAD

**Issue by mokeyjay** [agalwood/Motrix#54]
系统：Win10 LTSC
![image](https://user-images.githubusercontent.com/6757507/52694737-a7a18300-2fa5-11e9-9000-08be131811fe.png)

**Comment by agalwood** [comment]
已知bug，代码已修正，下一版本发布
https://github.com/agalwood/Motrix/commit/1bdaeeb3a64f000d61078cc3144f5bd04da9a984
https://github.com/agalwood/Motrix/commit/32f0a3d084a1bd297a8734481c8e5dca6f1225d3

**Comment by mokeyjay** [comment]
👍
