### ISSUE TITLE
ed2k链接，希望早日推出可下载！

### ISSUE THREAD

**Issue by mroooone** [agalwood/Motrix#541]
ed2k://|file|cn_windows_10_business_editions_version_1909_updated_jan_2020_x64_dvd_b3e1f3a6.iso|5311711232|3527D2A9845FF4105F485CC364655B66|/

-
MSDN 上的 ed2k链接，希望升级能补充！

**Comment by weearc** [comment]
https://github.com/agalwood/Motrix/issues/442
