### ISSUE TITLE
请求打包成 flatpak

### ISSUE THREAD

**Issue by HougeLangley** [agalwood/Motrix#546]
**请描述一下你的新功能请求是否与已知问题有关？**
没有问题，仅仅是请求打包成 flatpak ，snap 包启动速度和性能较 flatpak 稍差

**描述你想要的解决方案**
打包 flatpak

**描述你考虑过的替代方案**
无

**更多信息**
没有，就是为了方便安装到其他发行版

**Comment by aarestu** [comment]
@HougeLangley I don't understand what you wrote there.
But I can read "Flatpak" written there. and I guess I agree we need this app in flatpak.

**Comment by candrapersada** [comment]
when will it be released for Flatpak?

**Comment by proletarius101** [comment]
https://github.com/flathub/flathub/pull/2334
