### ISSUE TITLE
KDE无法打开软件

### ISSUE THREAD

**Issue by Mackel123** [agalwood/Motrix#554]
启动Motrix时报错：
Gtk-Message: Failed to load module "canberra-gtk-module"
Invalid MIT-MAGIC-COOKIE-1 key% 

系统信息：
Operating System: openSUSE Tumbleweed 20200213
KDE Plasma Version: 5.18.0
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.5.2-1-default
OS Type: 64-bit
Processors: 6 × Intel® Core™ i5-9400F CPU @ 2.90GHz
Memory: 7.7 GiB of RAM

软件版本：1.41

**Comment by agalwood** [comment]
试试这个 https://www.jianshu.com/p/71bc8b33e1a6

**Comment by Mackel123** [comment]
谢谢，我看到代码里已经更新到了上个月，我打包的时候发现electron包因为在github上所以抓取不下来，所以打包失败了，请问是否可以打包一下呢？谢谢啦～

**Comment by Mackel123** [comment]
你好，appimage运行正常，但snap版本无法运行，可能是snap的目录缺失，我重新装snap尝试一下，感谢。
