### ISSUE TITLE
无法下载迅雷的链接

### ISSUE THREAD

**Issue by 276562578** [agalwood/Motrix#555]
例如[这个链接](http://wot.kongzhong.com/ziliao/yxxz.html)，里面的迅雷下载点完之后显示
![image](https://user-images.githubusercontent.com/11238775/74825737-64f75100-5345-11ea-83e6-fc435cba38ef.png)设置里把迅雷链接启用了

**Comment by agalwood** [comment]
你点的链接地址是 `javascript:;`，是调用迅雷 js sdk 呼出你截图的弹层，根本就不是真正的下载地址，你复制 HTTP分包下载 里的地址进行下载吧

https://open.thunderurl.com/#/

**Comment by 276562578** [comment]
额，其实我的本意只是举个例子，有好多的网站都是这样的调用迅雷，很多网站甚至没有http这种方式，仅仅是js调用，可否增加这一类迅雷链接的解析调用呢？

**Comment by 276562578** [comment]
@agalwood
