### ISSUE TITLE
目前的主力下载软件，不足的是只能16线程最高，期望可以手动的选择是否支持64线程的下载

### ISSUE THREAD

**Issue by GitH123i** [agalwood/Motrix#558]
**Is your feature request related to a problem? Please describe.**
目前的主力下载软件，不足的只能是16线程最高，期望可以手动的选择是否支持64线程的下载

**Describe the solution you'd like**
目前的主力下载软件，不足的只能是16线程最高，期望可以手动的选择是否支持64线程的下载

**Describe alternatives you've considered**
目前的主力下载软件，不足的只能是16线程最高，期望可以手动的选择是否支持64线程的下载

**Additional context**

**Comment by VoidxHoshi** [comment]
去...\Motrix\resources\engine下找aria2.conf配置文件然后修改，GUI目前改不了。
顺便提issue别无视模板，谢谢。

**Comment by GitH123i** [comment]
谢谢，对不起，下次会注意的。我按照说的试了一下  把# 同一服务器连接数, 添加时可指定, 默认:1
#@max-connection-per-server=64 改为64 了，然后Motrix 的 system.json 配置里面的 max-connection-per-server 也改为64 了，下载文件显示这个错误  Failed to fetch

**Comment by VoidxHoshi** [comment]
> 谢谢，对不起，下次会注意的。我按照说的试了一下 把# 同一服务器连接数, 添加时可指定, 默认:1
> #@max-connection-per-server=64 改为64 了，然后Motrix 的 system.json 配置里面的 max-connection-per-server 也改为64 了，下载文件显示这个错误 Failed to fetch

我试了下修改貌似GUI上没有变化，可能在程序里已经写死了16，或者已经达到64线程但GUI未显示。
另外我不认为增加线程能提高多少下载速度，P2P资源看Peer数，纯服务器资源取决于服务器和CDN的网络状况。

**Comment by TTTPOB** [comment]
motrix采用的核心是aria2,这个项目官方的限制最高16线程；需要更高可以自己编译一份支持更多线程的文件替换进去

**Comment by qianyeLC** [comment]
啥?这个不是GUI里就能直接指定并行数为64么...我MacOS版本难道不一样?

**Comment by Goog686ii** [comment]
老哥 window电脑 苹果电脑是可以的 不知道开发者弄啥嘞

**Comment by agalwood** [comment]
已经升级到 aria2 v1.3.5 并全系统开放了 64 线程下载，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
