### ISSUE TITLE
能不能考虑下在Windows上实现类似vscode的自己绘制的标题栏

### ISSUE THREAD

**Issue by 500InternalError** [agalwood/Motrix#56]
感觉Windows默认的丑的一批

**Comment by 500InternalError** [comment]
话说感觉Windows上大部分electron应用标题栏都很丑啊。。。Windows没人权qwq

**Comment by agalwood** [comment]
本来v1.1.3版本已经可以设置隐藏标题栏和菜单栏，测试不够充分，翻车了
https://github.com/agalwood/Motrix/issues/54

**Comment by 500InternalError** [comment]
那。。。要不要考虑下加个常驻后台啥的

**Comment by agalwood** [comment]
计划中，开发计划可以看下 readme 里的 trello 看板

**Comment by agalwood** [comment]
已发布，请更新
https://github.com/agalwood/Motrix/releases/tag/v1.2.2
