### ISSUE TITLE
关于当BT监听端口被占用后BT下载报#1错的建议

### ISSUE THREAD

**Issue by tangjihe0** [agalwood/Motrix#560]
**请描述一下你的新功能请求是否与已知问题有关？**
当BT监听端口被占用后BT下载报#1错。

**描述你想要的解决方案**
建议报出更具体的错误，并且设置界面中给出BT监听端口的修改入口。

**描述你考虑过的替代方案**
或者给出多个端口段，可以在占用时切换。

**更多信息**
希望开放更多的设置项。

**Comment by agalwood** [comment]
偏好设置——进阶设置——监听端口 已支持 BT 和 DHT 端口修改

请更新 Motrix 到 v1.5.x 版本 https://github.com/agalwood/Motrix/releases
