### ISSUE TITLE
无法接收到Chrome插件Aria2助手推送的RPC请求

### ISSUE THREAD

**Issue by Antecer** [agalwood/Motrix#572]
使用的Chrome插件商店链接为:
https://chrome.google.com/webstore/search/aria2

故障现象:
在网上找到任意下载链接,右键->Aria2RPC
然后会发现Motrix没有Get到下载任务,并且没有任何提示.

已多次核对配置,应该是没问题的.
但是从该插件的AriaNg管理器可以正常创建下载任务.

因为不确定是哪边的问题,所以我两边都反馈了下.

**Comment by agalwood** [comment]
Motrix 内置 aria2 开放的 JSON-RPC 端口是 16800，你配置对了么？

`http://localhost:16800/jsonrpc`

**Comment by Antecer** [comment]
@agalwood
配置对了的,要不然也不能从AriaNg能正常创建任务啊.

**Comment by Antecer** [comment]
然后我又试了下原版的Aria2,能够正常推送下载任务了.

**Comment by Antecer** [comment]
找到原因了,是因为Motrix复制出来的url直接带了端口号,然后插件的端口号是单独设置的,然后就出问题了..
