### ISSUE TITLE
http - user/password authentication

### ISSUE THREAD

**Issue by mariomare22** [agalwood/Motrix#576]
**Is your feature request related to a problem? Please describe.**
I am trying to download a file from easybytez.com with my premium account, but Motriz is not prompting user/pwd authentication

**Describe the solution you'd like**
would like to add credentials for a specific domain i.g.: easybytez.com.

**Describe alternatives you've considered**

**Additional context**

**Comment by agalwood** [comment]
Try .netrc ?

https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-netrc-path

> References:
> https://gist.github.com/tpope/4247721
> https://ec.haxx.se/usingcurl/usingcurl-netrc

**Comment by lzzy12** [comment]
shouldn't this be implemented in the UI itself? The end user should not have to do any manual work for something as basic as this
