### ISSUE TITLE
百度网盘下载文件名问题

### ISSUE THREAD

**Issue by wenliyang** [agalwood/Motrix#58]
在知道 Motrix 这个软件后，经常用它下载一些百度网盘的资源，还是比较让我满意的，速度不能说很快，但比百度云管家故意限速已经好很多了

比较困扰我的一个问题，就是下载百度云网盘资源时，文件名称经常不对，或者只是原文件名称的一部分，甚至有时是一串乱码

比如这个：
https://pan.baidu.com/s/16QQmqkL9HrE4RpgAqP_A6A
提取码：i2bc

文件名应该是：[pniao.com]过年.CCTV高清.mkv.pdf
而用 Motrix 下载时文件名成了 6bf083a9b486cf81062b1832de1fd7e4 这一串不知所云的字符

用的操作系统是 Windows 7 和 8.1，都出现同样问题，Motrix 用的是 1.1.3 版本

**Comment by agalwood** [comment]
碰到问题可以先看下文档和搜下之前的 issue，谢谢
https://www.yuque.com/moapp/help/extensions
https://github.com/agalwood/Motrix/issues/29
