### ISSUE TITLE
批量任务下载支持按序号重命名

### ISSUE THREAD

**Issue by yeahwell** [agalwood/Motrix#584]
**请描述一下你的新功能请求是否与已知问题有关？**
批量任务下载支持按序号重命名

**描述你想要的解决方案**
批量任务下载支持按序号重命名，同时支持更改后缀

**描述你考虑过的替代方案**
目前使用的时候，是下载到本地然后批量重命名

**更多信息**
产生原因：我下载某些http请求的视频链接，地址没有后缀，导致下载后的文件名称都为index.html，实际期望***.mp4，目前仅支持单个任务重命名，能否可以加一个按序号重命名或者使用uuid作为文件名，自定义后缀

**Comment by agalwood** [comment]
master 上已经实现了这个功能 #341，克隆源码自己 build 一下提前体验

> Out rule sample:
> abc_(001+).jpg
> xyz_(100-2).html

以 `abc_(001+).jpg` 为例，
`abc_` 是固定前缀，可以没有；`()` 内为规则，`001`是初始序号，`+`代表每次序号递增+1

**Comment by yeahwell** [comment]
> master 上已经实现了这个功能 #341，克隆源码自己 build 一下提前体验
> 
> > Out rule sample:
> > abc_(001+).jpg
> > xyz_(100-2).html
> 
> 以 `abc_(001+).jpg` 为例，
> `abc_` 是固定前缀，可以没有；`()` 内为规则，`001`是初始序号，`+`代表每次序号递增+1

谢谢，我自己build体验下
