### ISSUE TITLE
菜单栏指什么？

### ISSUE THREAD

**Issue by Miao-Jingkun** [agalwood/Motrix#586]
图一
![image](https://user-images.githubusercontent.com/61610467/77977669-e5d93d80-7332-11ea-8014-5bd013b2a09e.png)
图二
![image](https://user-images.githubusercontent.com/61610467/77977650-cfcb7d00-7332-11ea-993a-31467b15b365.png)
图三
![image](https://user-images.githubusercontent.com/61610467/77977749-1ae59000-7333-11ea-81bc-e6f62560aca4.png)
这个“隐藏菜单栏”只有是非两个选项，为啥我能看到三种情况？？？
还不如砍掉这个隐藏菜单栏，或者把这三种情况让大家任选~

**Comment by Miao-Jingkun** [comment]
> ![image](https://user-images.githubusercontent.com/61610467/77977669-e5d93d80-7332-11ea-8014-5bd013b2a09e.png)


> ![image](https://user-images.githubusercontent.com/61610467/77977650-cfcb7d00-7332-11ea-993a-31467b15b365.png)


> ![image](https://user-images.githubusercontent.com/61610467/77977749-1ae59000-7333-11ea-81bc-e6f62560aca4.png)
> 这个“隐藏菜单栏”只有是非两个选项，为啥我能看到三种情况？？？
> 还不如砍掉这个隐藏菜单栏，或者把这三种情况让大家任选~

**Comment by agalwood** [comment]
为了界面一致性，才把窗体外框和菜单栏一起隐藏了的，没搞明白你说的这情况是怎么出现的，也许是版本久远的 issue 了 : |
