### ISSUE TITLE
关于“重命名（仅支持单文件）”

### ISSUE THREAD

**Issue by Miao-Jingkun** [agalwood/Motrix#587]
**错误描述**
建议将“重命名（仅支持单文件）”中的“（仅支持单文件）”去掉

**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴多个链接，并在重命名一栏中随意填写文件名
3. 点击提交
4. 发现出现截图中的情况

**预期的行为**
可以不提示“（仅支持单文件）”，而且截图中的文件名称可以更符合中国人习惯，以截图为例，比如第一个文件希望是today.1.mp4或today(1).mp4而不是today.mp4，第二个文件希望是today.2.mp4或today(2).mp4而不是today.1.mp4

**截图**
![image](https://user-images.githubusercontent.com/61610467/78101315-b6513080-7419-11ea-8443-bc288526bdb4.png)
![image](https://user-images.githubusercontent.com/61610467/78101349-d41e9580-7419-11ea-991e-11d4aa1024ce.png)

**运行环境**
Win7下Version 1.4.1

**Comment by agalwood** [comment]
请更新到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases

重命名规则详见：
https://github.com/agalwood/Motrix/pull/341#issue-293306529
