### ISSUE TITLE
希望可将每个服务器最大连接数的上限提高到32

### ISSUE THREAD

**Issue by ZZY2357** [agalwood/Motrix#589]
**请描述一下你的新功能请求是否与已知问题有关？**
下载速度偏慢，多些连接会快很多。像XDM可调的下载进程最大为32个，用起来非常爽

**描述你想要的解决方案**
将每个服务器最大连接数的上限提高到32

**描述你考虑过的替代方案**
这款软件的确不错，界面非常美观，就希望在下载上能快一些。如果实在忍受不了的话，备用方案就是用XDM或其它软件。

**更多信息**
无

**Comment by CeresCa** [comment]
支持，这个编译的版本可以解除线程数限制，  
https://github.com/myfreeer/aria2-build-msys2  
替换后正常使用但是Windows版前端还是有最大16的限制

**Comment by Soniceso** [comment]
同希望可以提高上限

**Comment by agalwood** [comment]
已经升级到 aria2 v1.3.5 并全系统开放了 64 线程下载，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
