### ISSUE TITLE
_____padding_file_0_如果您看到此文件，请升级到BitComet(比特彗星)0.85或以上版本____

### ISSUE THREAD

**Issue by animationhankhuo** [agalwood/Motrix#591]
![image](https://user-images.githubusercontent.com/20492352/78471257-83cd6d80-7762-11ea-8ba1-1b833fcaa5a8.png)

**Comment by VoidxHoshi** [comment]
这是比特彗星的私有功能边界补齐（比特彗星的黑历史一堆）
其他BT软件可能出现兼容性问题，但是可以不管它继续下载
其实Motrix的BT下载功能挺一般的甚至偏差，如果重度使用BT下载，推荐使用qBittorrent
Motrix（aria2）对于非BT下载更优

**Comment by animationhankhuo** [comment]
好的 谢谢！

**Comment by cherinyy** [comment]
> 这是比特彗星的私有功能

错误的，这个功能实际上有个[标准化草案（BEP 47）](https://github.com/bittorrent/bittorrent.org/blob/master/beps/bep_0047.rst "Padding files and extended file attributes
")，只是还没有被确认为官方规范。但是由于该草案被 [BitTorrent 协议规范 v2（BEP 52）](https://github.com/bittorrent/bittorrent.org/blob/master/beps/bep_0052.rst "The BitTorrent Protocol Specification v2")引用，因此它实际上被标准化了。

所以 qBittorrent 在支持 BitTorrent v2 的同时，顺带[隐藏了填充文件](https://github.com/qbittorrent/qBittorrent/pull/15468)。
