### ISSUE TITLE
官网下载一直出错（在Wi-Fi环境下）

### ISSUE THREAD

**Issue by giannisnao** [agalwood/Motrix#593]
官网点击windows安装包下载时一直出错，望解决！！！

**Comment by agalwood** [comment]
http://dl.motrix.app/ 绑定的服务器带宽超限额被强制关机了，已经切换到另一台服务器，应该可以下载了

**Comment by giannisnao** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Dr_rOot"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月5日(星期天) 晚上9:41
收件人:&nbsp;"agalwood/Motrix"<Motrix@noreply.github.com&gt;;
抄送:&nbsp;"Eric"<1784311370@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [agalwood/Motrix] 官网下载一直出错（在Wi-Fi环境下） (#593)

已经下载成功了，界面美观，给好评
