### ISSUE TITLE
希望支持百度云盘下载链接带提取码

### ISSUE THREAD

**Issue by realtanwei** [agalwood/Motrix#597]
@agalwood 

现在百度云盘分享必须带提取码，所以下载根本无法支持呀。

![image](https://user-images.githubusercontent.com/17842104/78628557-0a9b5b00-78c7-11ea-87ea-f82d19794323.png)

**Comment by tanwe1** [comment]
![image](https://user-images.githubusercontent.com/17842104/78628598-24d53900-78c7-11ea-8b20-5762d29de226.png)
