### ISSUE TITLE
希望能增加每个线程对应一个代理服务器的多代理功能

### ISSUE THREAD

**Issue by wukong-laiqujing** [agalwood/Motrix#598]
**请描述一下你的新功能请求是否与已知问题有关？**
简明扼要地描述了问题所在。

**描述你想要的解决方案**
简明扼要地描述你想要的解决方案。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by agalwood** [comment]
已实现，添加任务——高级选项——代理
请更新 Motrix 到 v1.5.x 版本 https://github.com/agalwood/Motrix/releases
