### ISSUE TITLE
Mac上无法下载，下载发生错误

### ISSUE THREAD

**Issue by looha518** [agalwood/Motrix#6]
浏览器安装了百度云扩展，打开百度分享的文件，使用mo下载，在mo客户端显示下载发生错误

**Comment by agalwood** [comment]
刚测试了macOS版，我这边是OK的，能否看下任务管理器里是否有 aria2c 的进程？

**Comment by looha518** [comment]
![wechatimg726](https://user-images.githubusercontent.com/16890588/50625617-39a87b80-0f64-11e9-8c9a-7279ae2c22d9.png)

**Comment by looha518** [comment]
![7271546497140_ pic](https://user-images.githubusercontent.com/16890588/50625641-63fa3900-0f64-11e9-959b-e1d7c24dd7a0.jpg)

**Comment by agalwood** [comment]
@looha518 你发的链接我可以下载

**Comment by agalwood** [comment]
@looha518 光靠这些截图想不出问题出在哪里，如果能提供更多信息请加QQ群交流：257097026

**Comment by looha518** [comment]
这两天忙 没来及查看，抱歉，QQ群管理员拒绝申请

**Comment by agalwood** [comment]
不好意思，是我忘记改加群验证方式了🤣，你可以再加一下

**Comment by looha518** [comment]
谢谢大佬，在大佬的指导下，问题解决了 ，下载的时候必须在账号登录的情况下下载，不然会下载失败
