### ISSUE TITLE
RPC授权密钥 设置无效

### ISSUE THREAD

**Issue by tea1111980** [agalwood/Motrix#603]
**错误描述**
设置RPC授权密钥之后，重启Motrix之后，再进设置里查看RPC授权密钥框里面是空的。PS：之前是设置过密钥的。

**如何重现**
重现步骤，如：
1. 打开Motrix，进入【偏好设置】-----【进阶设置】。
2. 找到 【RPC 授权密钥】 项。
3. 点击此项目框右边的随机生成密钥功能
4. 关闭Motrix端，再次开启Motrix端，再重复1，2步骤，你就会看到之前生成的随机密钥消失了。

**预期的行为**
希望修复这个问题，或者 望请指导一下如何解决此问题。

**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

### 相关截图：

图一：设置RPC授权密钥时，Motrix并未重开

![image](https://user-images.githubusercontent.com/16295097/79550081-7604da00-80ca-11ea-987d-aa3a1ce86874.png)

图二：设置RPC授权密钥后，Motrix重开后
![image](https://user-images.githubusercontent.com/16295097/79550468-f1ff2200-80ca-11ea-8b6d-8d15f927d476.png)

**运行环境**
 - 操作系统类型： Windows 10

 - 具体版本：Windows 10 专业工作站版
                      版本号 1909
                      操作系统版本 18363.778

 - Motrix 版本： v1.4.1
 - 安装包类型：Motrix-Setup-1.4.1.exe

**更多信息**
1. 除了以上问题之后，还想再问一下，设置RPC链接的http头，能否支持https。如果支持应该怎么设置呢?

2. 另外还发现添加磁力链下载之后，重开Motrix端，磁力链依然需要重新下载，不知道这是否 是一个问题。

3. 打开Motrix后，进入【偏好设置】-----【进阶设置】，【开发者: 应用日志路径】项，能不能修改，如果能怎么改？

谢谢！以上就是我要问的全部问题了。

**Comment by agalwood** [comment]
`RPC 授权密钥` 修改之后点击“保存并应用”了么？

`RPC 授权密钥` 这个配置修改保存之后应该重启应用的，但 Motrix v1.4.1 版本判断有问题，没有重新启动应用。

master 已经修复了，但是还没发布新版本

1. https 需要配置 SSL 证书（需绑定域名），作为应用内置的 RPC 服务，设置了 RPC 授权密钥 之后安全性已经有一定的保障，我觉得不适合这个场景。
2. 应该是 Bug
3. 应用日志的路径 没开放修改

**Comment by tea1111980** [comment]
> `RPC 授权密钥` 修改之后点击“保存并应用”了么？
> 
> `RPC 授权密钥` 这个配置修改保存之后应该重启应用的，但 Motrix v1.4.1 版本判断有问题，没有重新启动应用。
> 
> master 已经修复了，但是还没发布新版本
> 
> 1. https 需要配置 SSL 证书（需绑定域名），作为应用内置的 RPC 服务，设置了 RPC 授权密钥 之后安全性已经有一定的保障，我觉得不适合这个场景。
> 2. 应该是 Bug
> 3. 应用日志的路径 没开放修改


1. 修改 `RPC 授权密钥` 后，我保存并应用了，截图1中有体现（截图顶上有提示）。

2. 我还发现一个问题，就是设置代理后，再关闭代理。在 `download.session` 会话文件里，代理设置项依然存在，这是否会影响下载？

3. 在使用过程中，我觉得 http 和 https 形式的代理，没有socks5代理好用，请作者增加socks5的代理。

4. 在使用过程中，还发现，暂停单个下载项 或 开始下载项的时候，有延时。具体 体现在按完相应按钮之后，在过很长时间（5秒 <---> 10秒以上）按钮才会有反应，并且任务也才有相应的动作。当然，操作的提示早已 提示，但是动作还未 做出反应。不知道这是否  是一个问题。
