### ISSUE TITLE
trackerlist同步按钮失效，下载完成和做种的通知弹出混乱

### ISSUE THREAD

**Issue by Absolves** [agalwood/Motrix#604]
_**错误描述**_
1.trackerlist同步功能失效
2.下载完成后点击停止按钮，“BT任务下载完成，正在做种...”的提示会重复出现一次（第一次出现是链接下载完成时，第二次是点击停止按钮）

**如何重现**
1.点击trackerlist同步按钮，trackerlist列表未更新，同步按钮无等待标志
2.在磁力链接下载完成时弹出提示“BT任务下载完成，正在做种...”，此时点击停止按钮，会再次出现“BT任务下载完成，正在做种...”提示

**预期的行为**
1.trackerlist同步按钮出现旋转等待标识，trackerlist列表自动更新
2.磁力链接下载完成后弹出提示“BT任务下载完成，正在做种...”，此时点击停止按钮直接弹出提示”下载完成！“并终止做种。

**截图**
请添加屏幕截图以帮助解释你的问题：
![image](https://user-images.githubusercontent.com/47398005/79720320-e69e3780-8312-11ea-9306-69443f83d325.png)

下载完成后：
![image](https://user-images.githubusercontent.com/47398005/79720709-a8554800-8313-11ea-84cc-14699aee7c90.png)
点击终止按钮后：
![image](https://user-images.githubusercontent.com/47398005/79721240-9fb14180-8314-11ea-90c0-22bd474255f5.png)

**运行环境**
 - 操作系统类型：Windows10 专业版
 - 版本号1909
 - 操作系统版本18363.778
 - Motrix 版本： v1.4.1
 - 安装包类型：Motrix-Setup-1.4.1.exe

**更多信息**
希望未来可以手动填入trackerlist的更新路径，而不是只能使用默认路径更新

**Comment by tea1111980** [comment]
请尝试 `Motrix 1.5.10` 版本

**Comment by tea1111980** [comment]
> _**错误描述**_
> 1.trackerlist同步功能失效
> 2.下载完成后点击停止按钮，“BT任务下载完成，正在做种...”的提示会重复出现一次（第一次出现是链接下载完成时，第二次是点击停止按钮）
> 
> **如何重现**
> 1.点击trackerlist同步按钮，trackerlist列表未更新，同步按钮无等待标志
> 2.在磁力链接下载完成时弹出提示“BT任务下载完成，正在做种...”，此时点击停止按钮，会再次出现“BT任务下载完成，正在做种...”提示
> 
> **预期的行为**
> 1.trackerlist同步按钮出现旋转等待标识，trackerlist列表自动更新
> 2.磁力链接下载完成后弹出提示“BT任务下载完成，正在做种...”，此时点击停止按钮直接弹出提示”下载完成！“并终止做种。
> 
> **截图**
> 请添加屏幕截图以帮助解释你的问题：
> ![image](https://user-images.githubusercontent.com/47398005/79720320-e69e3780-8312-11ea-9306-69443f83d325.png)
> 
> 下载完成后：
> ![image](https://user-images.githubusercontent.com/47398005/79720709-a8554800-8313-11ea-84cc-14699aee7c90.png)
> 点击终止按钮后：
> ![image](https://user-images.githubusercontent.com/47398005/79721240-9fb14180-8314-11ea-90c0-22bd474255f5.png)
> 
> **运行环境**
> 
> * 操作系统类型：Windows10 专业版
> * 版本号1909
> * 操作系统版本18363.778
> * Motrix 版本： v1.4.1
> * 安装包类型：Motrix-Setup-1.4.1.exe
> 
> **更多信息**
> 希望未来可以手动填入trackerlist的更新路径，而不是只能使用默认路径更新



我试过了，不是这个按钮无效，是需要 `挂代理` ，才能更新这些 `Tracker 服务器` 。

你可以使用 `Ctrl + Shift + i` 这个快捷键 进入 `开发模式` 。

然后，在此模式下，再点击 `Network` 选项 。

前面打开的 `开发模式` 别关了，最后，再次点击这个 `Tracker 按钮` ，你就知道是什么原因导致的了。

**Comment by agalwood** [comment]
aria2 BT任务停止做种的方法是调用 [changeOption](https://aria2.github.io/manual/en/html/aria2c.html#aria2.changeOption) 修改任务的 `seed-time` 来实现的。
调用 changeOption 之后，aria2 会暂停任务并重新启动该任务，所以会触发相应的通知。

重构了通知的逻辑来减少对用户的干扰 #718
