### ISSUE TITLE
求大神指点如何让Aria2c程序不出现cmd窗口

### ISSUE THREAD

**Issue by sucjblon** [agalwood/Motrix#610]
求大神指点如何让Aria2c程序不出现cmd窗口

**Comment by kaihangchen** [comment]
there is a same question

**Comment by kaihangchen** [comment]
> 求大神指点如何让Aria2c程序不出现cmd窗口

1.4.1版本 默认不会显示cmd窗口

**Comment by sucjblon** [comment]
> > 求大神指点如何让Aria2c程序不出现cmd窗口
> 
> 1.4.1版本 默认不会显示cmd窗口

下载的源码，在编译时始终出现cmd窗口，是什么原因

**Comment by kaihangchen** [comment]
> > > 求大神指点如何让Aria2c程序不出现cmd窗口
> > 
> > 
> > 1.4.1版本 默认不会显示cmd窗口
> 
> 下载的源码，在编译时始终出现cmd窗口，是什么原因

我觉得可能是在开发新版本的时候修改了某些文件件忽略啦这个问题，你可以从release里面下载源码就可以啦

**Comment by tea1111980** [comment]
@sucjblon 同样的问题，刚刚编译好最新的版本。默认启动Motrix aria2c的窗口就弹出来了，可是还没有发布正式版，这样利用调试吧。
