### ISSUE TITLE
Windows下下载突然只显示一个空白的窗口

### ISSUE THREAD

**Issue by leienshu** [agalwood/Motrix#62]
windows10 下面百度网盘，下载了好多东西，速度很快，然而下载着下载着突然任务不见了，只有菜单栏还在，其他全是一片空白。关掉重启，恢复任务正常，过一会儿又不行了。不知道什么问题。

**Comment by leienshu** [comment]
![image](https://user-images.githubusercontent.com/46070462/52877889-47256800-3196-11e9-9240-4087e02c765b.png)

**Comment by Shigma** [comment]
啊刚刚没看到这个 issue……可能我的重复了

#65 你看下如果打开开发者工具是不是同样的情况？

**Comment by leienshu** [comment]
> 啊刚刚没看到这个 issue……可能我的重复了
> 
> #65 你看下如果打开开发者工具是不是同样的情况？

是一样的情况，哈哈，因为这个问题，我只好买了个百度云盘的会员了。希望赶紧修复，加油，另外donate页面赶紧弄起来，好东西，值得拥有！

**Comment by vincentzlt** [comment]
我在mac下有同样问题，只是下载一个文件。。
