### ISSUE TITLE
删除任务时, 有没有默认删除文件的选项

### ISSUE THREAD

**Issue by tty5** [agalwood/Motrix#622]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by agalwood** [comment]
按住 <kbd>Shift</kbd> 点击删除任务按钮时，会默认勾选“删除相关文件”

还有，偏好设置——基础设置——任务管理 加了个“删除任务前无需确认”，勾选保存之后，按住 <kbd>Shift</kbd> 点击删除任务，确认框也不会弹了。

请更新到 v1.5.x 版本：
https://github.com/agalwood/Motrix/releases
