### ISSUE TITLE
设置了sock5的代理, 怎么不生效

### ISSUE THREAD

**Issue by tty5** [agalwood/Motrix#623]
**Before feedback**
Before you feedback, please search for the issues to see if there are similar problems that can solve your problem.

**Please delete the above and the contents of this line, then fill in the feedback form in the following format, Thanks.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & Version: [e.g. macOS, Windows, Linux]
 - Version: [e.g. macOS 10.14.2, Windows 10, Ubuntu 18.04]
 - Motrix Version: [e.g. v1.1.3, v1.1.0]
 - Installation package type: [e.g. dmg, AppImage]

**Additional context**

**Comment by jawil** [comment]
这个软件底层用的是开源 [aria2](https://github.com/aria2/aria2) 进行封装，arisa2 好像不支持 socket5 代理。

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/wiki/Proxy
