### ISSUE TITLE
aria2c 不是静态编译版本

### ISSUE THREAD

**Issue by wenbingzhang** [agalwood/Motrix#628]
**错误描述**
Motrix.app/Contents/Resources/engine/aria2c
dyld: Library not loaded: /usr/local/opt/libssh2/lib/libssh2.1.dylib
  Referenced from: /Users/bing/Documents/Project/Electron/Motrix/release/mac/Motrix.app/Contents/Resources/engine/aria2c
  Reason: image not found
[1]    4322 abort

**运行环境**
 - 操作系统类型： macOS
 - 具体版本：macOS 10.13.6
 - Motrix 版本： v1.5.7
 - 安装包类型：自己编译

**Comment by agalwood** [comment]
感谢报告，已经重新编译提交 aria2c 合并到 master 了，你可以更新一下代码再自己编译试试了
