### ISSUE TITLE
下载线程

### ISSUE THREAD

**Issue by zhuleigit** [agalwood/Motrix#631]
请问介绍上说单个任务最多64个线程，为什么我最多只能选16个
![image](https://user-images.githubusercontent.com/3584998/81474163-1ff10580-9236-11ea-828e-8094ce6f7aad.png)

**Comment by agalwood** [comment]
已经升级到 aria2 v1.3.5 并全系统开放了 64 线程下载，请更新 Motrix 到 v1.5.x 版本
https://github.com/agalwood/Motrix/releases
