### ISSUE TITLE
任务栏图标加入下载进度显示

### ISSUE THREAD

**Issue by greenhand520** [agalwood/Motrix#633]
如题
就像IDM这样的
![Clip_20200510_001327](https://user-images.githubusercontent.com/32732204/81478960-1a55e880-9253-11ea-94ba-8bd96b24d6aa.png)
![Clip_20200510_001314](https://user-images.githubusercontent.com/32732204/81479005-5ee18400-9253-11ea-9ad9-487634fb664b.png)

**Comment by chuxinyuan** [comment]
确实，那个任务栏图标一点用都没有，Ubuntu20.04下软件关闭后还赖在哪里没法退出。
