### ISSUE TITLE
源代码更新导致Linux下运行出现问题

### ISSUE THREAD

**Issue by weearc** [agalwood/Motrix#64]
**Describe the bug**
左侧全部按钮无法点击，右侧按钮正常
**Desktop (please complete the following information):**
 - OS: [e.g. macOS, Windows, Linux]
 - Version [e.g. 10.14.2, Win 10]
OS Linux

注：aur上的motrix为保证可以正常使用将切换到release版本的源代码

**Comment by agalwood** [comment]
收到，请问 release v1.1.3 的源码能正常使用么？
我得搞个虚拟机装下aur试试

**Comment by agalwood** [comment]
可以的话，运行之后打开：帮助-开发者工具-console
贴一下完整截图

**Comment by weearc** [comment]
@agalwood 目前只有v1.1.1能正常使用，[motrix-aur](http://aur.archlinux.org/motrix)已经切换为v1.1.1的源码

**Comment by agalwood** [comment]
@weearc master上把左侧的拖拽移动应用的特性移除了，能否再帮忙试下

PS. 在 VMware 里安装 Arch Linux 有点🥚疼

**Comment by weearc** [comment]
@agalwood 干脆分包成了两个，一个[motrix-git](http://aur.archlinux.org/motix-git)跟随你的主分支代码，一个[motrix](http://aur.archlinux.org/motrix)跟随release的代码，主分支正在测试中

**Comment by weearc** [comment]
[![5d6ce5b60206c662459caa2564b026f9.png](http://picb.weearc.top/images/2019/02/17/5d6ce5b60206c662459caa2564b026f9.png)](http://picb.weearc.top/image/wJt) 似乎会变成这样，但是左侧功能正常了

**Comment by agalwood** [comment]
这个报错是没连上内置的 aria2c RPC 服务，进程管理器看下 aria2c 是否有启动成功？

**Comment by weearc** [comment]
@agalwood 前两天忙起来了，今晚看看是不是package.json被我删多了某几行...
