### ISSUE TITLE
Menu bar mode doesn't work on Windows for 1.5.10

### ISSUE THREAD

**Issue by RoderickQiu** [agalwood/Motrix#641]
**错误描述**
Menu bar mode doesn't work on Windows for 1.5.10, as it is only showed in standard mode. Persists even quitted and reopened Motrix.

**如何重现**
1. go to settings
2. select `run as menu bar program`
3. save & reply
4. quit and reopen Motrix

**预期的行为**
Motrix to work.

**截图**

> 请添加屏幕截图以帮助解释你的问题：
> 打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。
> 

在开发者工具->Console里找不到相应API，用Windows默认截图工具剪的。

![image](https://user-images.githubusercontent.com/42290260/82104212-88654880-9748-11ea-84fa-f1b76279f026.png)

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： Windows 10 v1909
 - Motrix 版本：v1.5.10
 - 安装包类型：Setup exe

**更多信息**
---

**Comment by agalwood** [comment]
Maybe this feature description is not necessarily accurate : |

The difference between standard mode and menu bar mode on mac is that there is no Motrix application icon on the dock.

Other systems do not seem to have a dock, and it feels like a macOS exclusive feature, and I forgot to hide it from other operating systems.
