### ISSUE TITLE
macOS 菜单栏速度显示

### ISSUE THREAD

**Issue by KYLN24** [agalwood/Motrix#643]
**请描述一下你的新功能请求是否与已知问题有关？**
无

**描述你想要的解决方案**
macOS中，运行为“菜单栏应用”时，希望在菜单栏的motrix logo旁（或者上）显示当前下载（或者及上传）速度，如果可以的话，最好再显示一下全局进度

**描述你考虑过的替代方案**
不用运行为“菜单栏应用”，在dock栏将就一下motrix的巨大图标以监控网速（但是强迫倾向表示真不能忍😭）

**更多信息**
希望添加该功能😆谢谢！感激不尽！祝better！

**Comment by agalwood** [comment]
托盘图标旁边展示“速度”要好看得用双行小字，Electron 没有直接提供这样得 API https://www.electronjs.org/docs/api/tray ，有思路，但实现有点难度

**Comment by agalwood** [comment]
![image](https://user-images.githubusercontent.com/1032175/84673350-2b81cb80-af5c-11ea-85dc-7ae4866adb6d.png)

实验了三种实现方式，差不多 OK 了，下个大版本发布

**Comment by KYLN24** [comment]
good！
