### ISSUE TITLE
Out of memory when downloading many files

### ISSUE THREAD

**Issue by Shigma** [agalwood/Motrix#65]
**Describe the bug**
When downloading many files (1000+), Motrix crashes easily.

**To Reproduce**
- start a new task with many urls (1000+), each of them is about 1MB

**Expected behavior**
Download

**Screenshots**
White screen, or
![screenshot](https://user-images.githubusercontent.com/33423008/52898697-e2acec00-321b-11e9-925b-df6c1a0e22bc.png)

In DevTool Scripts:
```
Pause before potential out-of-memory crash.
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Win 10

**App (please complete the following information):**
 - Version: 1.1.3

**Additional context**
(既然大家都说中文我也就说中文好了2333) 可能需要限制内存占用, 或者再次检查一下是否存在内存泄漏的问题.

**Comment by agalwood** [comment]
你们这样一次性提交 1000+ 下载任务的，真的好挑战 Motrix 的性能啊🙃

**Comment by Raistlin916** [comment]
准备把 message 改写下，现在光几千个 message 都会吃掉很多内存，造成卡顿。

**Comment by agalwood** [comment]
v1.2.2 已经优化了消息的提示和减小了任务列表条数限制，下版本会重构优化任务列表
