### ISSUE TITLE
aria2的守护进程怎么隐藏window窗口

### ISSUE THREAD

**Issue by mikealYao** [agalwood/Motrix#654]
大神，aria2的守护进程怎么隐藏window窗口，我现在打包发布的版本，运行aria2的窗口还在显示，谢谢

**Comment by agalwood** [comment]
请确保 `forever-monitor` 的版本为 1.7.2

**Comment by agalwood** [comment]
#610 
https://github.com/agalwood/Motrix/pull/615#issue-409813701
