### ISSUE TITLE
BT下载时出现Unauthorized提示

### ISSUE THREAD

**Issue by jnkxz** [agalwood/Motrix#661]
**错误描述**
BT下载时出现Unauthorized提示

**如何重现**
点击磁力链接时
出现下载提示
确认后就渺无声息
没有任何提示

使用.torrent文件启动下载
出现下载提示
确认后等待了几秒
出现Unauthorized提示

**预期的行为**
更新1.5.12版后出现这样的状况

**截图**
![image](https://user-images.githubusercontent.com/44166207/82738103-f375d700-9d67-11ea-9064-0cdceda01c19.png)
![image](https://user-images.githubusercontent.com/44166207/82738114-012b5c80-9d68-11ea-90f5-e5bd9a085e02.png)

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： Windows 10
 - Motrix 版本： v1.5.12
 - 安装包类型：exe

**更多信息**
无

**Comment by agalwood** [comment]
你是设置了“RPC 授权密钥”么？

**Comment by jnkxz** [comment]
> 你是设置了“RPC 授权密钥”么？

是的 我试试取消看看

**Comment by agalwood** [comment]
理论上设置了“RPC 授权密钥”之后应用会重启，（顺带会重启 aria2 并加载新的配置），我感觉是你不是的 aria2 进程没有正常退出，手动杀掉 aria2 进程试试

**Comment by jnkxz** [comment]
> 理论上设置了“RPC 授权密钥”之后应用会重启，（顺带会重启 aria2 并加载新的配置），我感觉是你不是的 aria2 进程没有正常退出，手动杀掉 aria2 进程试试

好了 问题解决了 谢谢

**Comment by dotennin** [comment]
> 理论上设置了“RPC 授权密钥”之后应用会重启，（顺带会重启 aria2 并加载新的配置），我感觉是你不是的 aria2 进程没有正常退出，手动杀掉 aria2 进程试试

遇到同样的问题, 杀掉aria2解决了 💯
