### ISSUE TITLE
全屏下运行为菜单栏应用的Motrix不能显示窗口关闭按钮

### ISSUE THREAD

**Issue by KYLN24** [agalwood/Motrix#663]
**错误描述**
清楚简洁地描述错误，方便我们复现之后处理。
macOS 版 Motrix 1.5.10 以菜单栏应用模式打开后，进入全屏不显示窗口顶部包含“关闭、最小化”等按钮的标题栏（不知道是不是叫“标题栏”。。。）

**如何重现**
重现步骤，如：
1. 设置 - 基础设置 - 运行为 - 菜单栏应用
2. 点击窗口左上角绿色全屏按钮进入全屏
3. 无法正确显示“标题栏”以退出全屏，只能使用 Mission Control 把全屏 Motrix 拖出来关掉

**预期的行为**
全屏模式运行的运行为菜单栏应用的 Motrix 应有和运行为标准应用一样的行为

**运行环境**
 - 操作系统类型： macOS
 - 具体版本： macOS 10.15.4
 - Motrix 版本： 1.15.10
 - 安装包类型：dmg

**更多信息**
补充有关该问题的其他信息。

**Comment by KYLN24** [comment]
（我觉得也许不用提供截图。。。）

**Comment by agalwood** [comment]
似乎是 Electron 8.x 的 Bug，官方已经在 9.x 修复了

Motrix 下个版本才会升级到 9.x，因为需要测试和适配 Electron API 的变更

**Comment by agalwood** [comment]
用了点 hack 的方法解决了，下个小版本修复

**Comment by KYLN24** [comment]
太棒了，持续跟进中～

**Comment by agalwood** [comment]
全屏模式的优化已经发布，请更新到 v1.5.13 版本

https://github.com/agalwood/Motrix/releases

**Comment by KYLN24** [comment]
运行为“菜单栏应用”的 Motrix 1.5.13 在 macOS 10.15.4 上全屏运行时，点击“偏好设置”里的“保存并应用”会出现奇妙的bug（Motrix 窗口成为桌面的背景，只能通过 command + W 退出～～）

> 似乎是 Electron 8.x 的 Bug，官方已经在 9.x 修复了
> Motrix 下个版本才会升级到 9.x，因为需要测试和适配 Electron API 的变更
> 用了点 hack 的方法解决了，下个小版本修复

还是等 Motrix 用上 Electron 9 好些

**Comment by KYLN24** [comment]
<img width="1280" alt="截屏2020-05-26 23 30 00" src="https://user-images.githubusercontent.com/54014142/82919748-03302e00-9fa9-11ea-9e15-77147a5a29eb.png">

**Comment by agalwood** [comment]
验证了一下，只在基础设置保存时会出现，和 Electron 版本无关，是代码逻辑问题
