### ISSUE TITLE
debian + mate 桌面托盘图标没了

### ISSUE THREAD

**Issue by jing2uo** [agalwood/Motrix#665]
debian bullseye/sid
mate-desktop 1.24.0
motrix Version 1.5.12

从 Motrix v1.5.10 开始系统托盘图标就没有了，如果点击窗口右上角x关闭应用，motrix 还在后台运行，要想看界面只能重新打开了。

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/583#issuecomment-620323913

**Comment by jing2uo** [comment]
抱歉，之前没有搜索现有issue…话说这个办法有点奇怪，会带进来xfce4的一些依赖呢。谢谢

**Comment by agalwood** [comment]
对于 Linux 千奇百怪的桌面环境我也不甚了解 : |
