### ISSUE TITLE
显示的用了64线程，但实际上windows里只有2个线程

### ISSUE THREAD

**Issue by DeXtmL** [agalwood/Motrix#666]
下载时主界面显示63线程，有时跳到64，但打开windows resource monitor，aria2c的实际连接只有2个（见下图）
![64t](https://user-images.githubusercontent.com/13725477/82783778-bdcd0d00-9e91-11ea-87f8-e97be98dc965.jpg)
![tt](https://user-images.githubusercontent.com/13725477/82783781-bf96d080-9e91-11ea-90d7-069335962c17.jpg)

**Comment by agalwood** [comment]
![image](https://user-images.githubusercontent.com/1032175/82786046-6b421f80-9e96-11ea-8727-966ded698b49.png)

TCP 连接里数一下
