### ISSUE TITLE
插件认证失败

### ISSUE THREAD

**Issue by huanghaobaobao** [agalwood/Motrix#669]
![image](https://user-images.githubusercontent.com/9583815/82892207-a705e380-9f81-11ea-8a64-76bc46240e84.png)
![image](https://user-images.githubusercontent.com/9583815/82892252-ba18b380-9f81-11ea-9cad-14734a119c70.png)
请问我一直认证失败是怎么回事？如何解决？更新到最新版motrix后就出现这个问题了。1.41版完全没问题。现在的情况是可以拦截下载，但是点击插件不能显示，只显示认证失败

**Comment by agalwood** [comment]
你RPC密码填了啥？Motrix 随机产生的密码没那么长吧

**Comment by huanghaobaobao** [comment]
原来是这样，已成功解决问题，谢谢，我把token地址填上去了

> 你RPC密码填了啥？Motrix 随机产生的密码没那么长吧
