### ISSUE TITLE
Request failed with status code 503,如何解决

### ISSUE THREAD

**Issue by torlix** [agalwood/Motrix#675]
12:35:24.405 › [Motrix] auto sync tracker failed: Request failed with status code 503
closeClient===>
closeClient===>

**Comment by agalwood** [comment]
科学上网，或者把 tracker 源地址改为如下 cdn 地址：

https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_best_ip.txt


修改方式详见 https://github.com/agalwood/Motrix/issues/677
