### ISSUE TITLE
最新版本里新增的自定义 Tracker 列表在哪里添加？

### ISSUE THREAD

**Issue by hezhijie0327** [agalwood/Motrix#677]
当前版本：v1.5.10

我希望是能自己添加/订阅 Tracker 列表，而不是像现版本那样在已有的选项中选择

比如说在同步按钮旁添加一个 “添加” 按钮，然后弹出表单输入“列表名”+“订阅地址”；
添加的自定义列表将显示在当前（1）所指位置加一个“自定义列表”的表头，然后从中选择（2）

![Xnip2020-05-30_12-12-18](https://user-images.githubusercontent.com/58100052/83319196-d3b24780-a26e-11ea-8b92-bfa61fc1db10.jpg)
![Xnip2020-05-30_12-23-58](https://user-images.githubusercontent.com/58100052/83319375-833be980-a270-11ea-80af-7966c28ba5e1.jpg)

**Comment by agalwood** [comment]
复制 tracker 源列表地址，黏贴到选择框里回车

**Comment by hezhijie0327** [comment]
👌原来在这里，万分感谢～
