### ISSUE TITLE
插件Download with FlashGet失效了

### ISSUE THREAD

**Issue by vizshrc** [agalwood/Motrix#688]
原本使用DownLoad with FlashGet插件能够接管chrome和firefox的下载，调用mo'trix，设置没变但现在只能调出motrix界面，却不能传递下载链接过来建立任务了，很苦恼，使用实验室里的别的插件也不行，包括motrix的自身的调用插件开发版

**Comment by agalwood** [comment]
麻烦提供一下 DownLoad with FlashGet 里的配置

![image](https://user-images.githubusercontent.com/1032175/83774634-85f76e00-a6b8-11ea-94f1-c6055d1350bb.png)

**Comment by vizshrc** [comment]
<img width="663" alt="截屏2020-06-05 上午10 19 01" src="https://user-images.githubusercontent.com/56945974/83829710-0ef0c280-a716-11ea-9847-12148a6f0586.png">

**Comment by agalwood** [comment]
原来 Motrix 是什么版本？现在的版本呢？

**Comment by vizshrc** [comment]
先说抱歉，我没有描述清问题，给您添麻烦了。现在使用的Motrix v1.5.10,原来使用的版本我没注意，后来尝试了一下motrix v1.5.7的结果也不行,我不知道这是否和系统版本有关，我不久前升级了Catalina 10.15.5。某个时刻我在发现brave浏览器上插件失效了，接着打开电脑上原来使用的firefox\chrome也失效了。

**Comment by agalwood** [comment]
我测试了 Motrix 1.4.1 版本的确是支持的，1.5.x 版本不支持，翻了代码记录感觉 Tag v1.4.1 之后的提交记录，也没啥改动，理论上都是 **不支持** 的才对，不知道为啥 1.4.1 就可以呢 : |

https://github.com/agalwood/Motrix/blob/d2cff6356aa3208babf260c6267bb6b1ca9fe63e/src/main/core/ProtocolManager.js#L43-L59

这个问题好处理，加上 http，https，ftp 等链接的判断就行了，这两天会发布 v1.5.x 的新版本

新的 motrix:// 协议在重新设计了，v1.6.x 版本会发布
到时候可以使用以下方式调用

`motrix://new-task?uri=https://github.com/&out=my_github`

**Comment by agalwood** [comment]
更新到 v1.5.15 版本再试下 DownLoad with FlashGet
https://github.com/agalwood/Motrix/releases

**Comment by vizshrc** [comment]
不愧是你，又很舒服地用了，赞👍
