### ISSUE TITLE
无缘故报错 client is destroyed

### ISSUE THREAD

**Issue by exoticknight** [agalwood/Motrix#691]
**错误描述**
弹窗报错 client is destroyed

**如何重现**
不做任何事，过一段时间就会出现

**预期的行为**
不报错

**截图**
无

**运行环境**
 - 操作系统类型：macOS
 - 具体版本：10.15.4
 - Motrix 版本： 1.5.10
 - 安装包类型：dmg

**更多信息**
补充有关该问题的其他信息。

**Comment by exoticknight** [comment]
https://github.com/agalwood/Motrix/commit/dc2876098da7891db68195ee2061ed7a36127124

**Comment by exoticknight** [comment]
使用最新的 1.5.13 之后，报错没有了，但是又出现 cb is not a function 这个报错

**Comment by exoticknight** [comment]
https://github.com/agalwood/Motrix/pull/674
https://github.com/agalwood/Motrix/issues/668

**Comment by agalwood** [comment]
更新到 v1.5.15 版本
https://github.com/agalwood/Motrix/releases
