### ISSUE TITLE
Motrix 实验室无法加载

### ISSUE THREAD

**Issue by Nofated095** [agalwood/Motrix#693]
**错误描述**
Motrix 实验室 报错：504 Gateway Time-out，nginx/1.15.9 (Ubuntu)

**如何重现**
1. 打开偏好设置
2. 打开偏好设置的实验室
3. 等待加载
4. 发现报错：504

**预期的行为**
这肯定就是服务器的问题，修一下不就好了「滑稽」

**截图**
![](https://s1.ax1x.com/2020/06/06/t68pXF.png)
_现在我也没找着一个好的图床，可能加载有点慢_

**运行环境**
 - 操作系统类型： macOS
 - 具体版本：macOS 10.14.6
 - Motrix 版本： v1.5.15
 - 安装包类型：dmg

**Comment by Nofated095** [comment]
艹，这垃圾图床，给你们直链访问吧，是截图[戳我访问👇](https://s1.ax1x.com/2020/06/06/t68pXF.png)

**Comment by agalwood** [comment]
你赶上新版本发布了，发布了 v1.5.15

**Comment by NANAyano** [comment]
我也是这样，有什么解决方法吗？😭
