### ISSUE TITLE
竟然不能批量删除任务！！！！！！！

### ISSUE THREAD

**Issue by fskypro** [agalwood/Motrix#695]
别告诉我，让我更新到 v1.5.x 可以鼠标选中批量了。
更新后，虽然可以拖动鼠标选中多个任务了，但是只能选中当前显示的几个任务。不能拖着滚动列表。
所以最多能选 7 个任务。假如有 1000 个任务，这样每拖一次，删除 7 个，手都累断。而且选中多个的时候，还没选中状态的，根本不知道已经选中了多个。

你就不能加个选框，点击 “全选” 吗，然后在每个任务前面加个 CheckBox

**Comment by Waynehfut** [comment]
提个issues这么大的戾气，作者免费开源，社区讨论请你友善。

**Comment by 291663174** [comment]
我这边碰到了一个BUG 吧，网络不稳定导致提交了自动无限循环任务，现在又不想下载，清空也没办法，希望作者可以在等待中的任务里加上一个清空下载任务的功能，不然我的下载列表怎么更新就都是那些任务，每次下东西就只显示当前的任务，视觉难受。。
![image](https://user-images.githubusercontent.com/64113334/84125799-abe19180-aa6f-11ea-9a6a-4bae9fa10efb.png)

**Comment by cqzaiercn** [comment]
怎么关闭了 我任务 多了也不好删除
