### ISSUE TITLE
无法打开实验室？

### ISSUE THREAD

**Issue by NANAyano** [agalwood/Motrix#697]
![image](https://user-images.githubusercontent.com/54680256/83983936-caa73180-a964-11ea-815d-5ea8fd3774ba.png)
你好，我想问一下为什么我的motrix更新后无法打开实验室？一直在缓冲，最后只能是502。

**Comment by agalwood** [comment]
实验室现在是加载网页的，你看下下面的网址能否打开

https://motrix.app/lab

**Comment by Huiaei** [comment]
+1，浏览器正常，客户端显示504
![](https://gitee.com/huiaei/ImageDB/raw/master/img/20200610163931.png)

**Comment by liulongrong** [comment]
想问一下，这种情况最后解决了吗？应该怎么解决呢？（实验室出现504情况）

**Comment by Huiaei** [comment]
截至2020.04.18 11:40:00，依旧客户端504，网页正常

**Comment by underthestars-zhy** [comment]
504是服务器问题吧。有可能服务器加载过慢。如果需要服务器我可以提供哈。

**Comment by agalwood** [comment]
检查了一下，好像是上次把官网的 vue-i18n 换成 nuxt-i18n 出的问题

**Comment by agalwood** [comment]
已经回滚代码修复了
