### ISSUE TITLE
Inaccurate translation

### ISSUE THREAD

**Issue by tangxiaodao** [agalwood/Motrix#699]
**Inaccurate translation from Release Note**
org:fix: too fast to shut down the engine, reduce error logs
trans:修复：调整下载引擎退出时机，减少报错日志
More accurate：修复：因下载速度过快而导致的引擎崩溃，缩减错误日志

**Comment by agalwood** [comment]
你的理解有问题，这个修复就是处理了引擎过早关闭的问题的

https://github.com/agalwood/Motrix/commit/ee111c92ee7c47048aeb8831c1f2d29a67823d50
