### ISSUE TITLE
无法下载，添加任务后就提示“Failed to fetch”请问怎么解决~~

### ISSUE THREAD

**Issue by wwqq33** [agalwood/Motrix#700]
**错误描述**
安装后添加什么任务都弹出提示：Failed to fetch

**如何重现**
打开软件
点+号添加任务
比如QQ的：https://down.qq.com/qqweb/PCQQ/PCQQ_EXE/PCQQ2020.exe
然后点“提交”按钮 就出提示

**截图**
![QQ截图20200609201145](https://user-images.githubusercontent.com/34265680/84147715-7305e480-aa90-11ea-9a4b-7d627a2d7043.png)
![QQ图片20200609194818](https://user-images.githubusercontent.com/34265680/84147740-7ac58900-aa90-11ea-905c-34928dc6a6b3.png)

**运行环境**
 - 操作系统类型： Windows 
 - 具体版本：Windows 10 专业版 1909  18363.836
 - Motrix 版本： 1.5.15

 - 安装包类型：exe

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/390#issuecomment-520666824

**Comment by wwqq33** [comment]
> 
> 
> [#390 (comment)](https://github.com/agalwood/Motrix/issues/390#issuecomment-520666824)

是差不多 怎么了？他也没有人解决啊？我看错了吗？他解决了?
