### ISSUE TITLE
新功能-网盘结合

### ISSUE THREAD

**Issue by underthestars-zhy** [agalwood/Motrix#708]
我发现使用pan.somedrive.cn网盘的时候。在网盘网页端获取直链再在motrix下载速度可以达到3mb。能否把这个网页集成在一个选项卡里，然后点击下载默认就调用motrix。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by KyonCN** [comment]
这个是cloudreve 本身不提供存储的 挂载的onedrive或者其他云存储

**Comment by underthestars-zhy** [comment]
我的意思是内置一会选项卡
