### ISSUE TITLE
cannot download，No response

### ISSUE THREAD

**Issue by ltxman** [agalwood/Motrix#725]
When downloading, no matter whether it is right-click download or interception download, there is no reaction, and there is no reaction when adding link download. The same is true for uninstalling and reloading
下载的时候不管是右键下载还是拦截下载，都没有任何反应，添加链接下载也没有任何反应，卸载重装也是一样

**Comment by agalwood** [comment]
你这样提问，我帮不了你

https://github.com/agalwood/Motrix/issues/new?assignees=&labels=&template=bug_report_cn.md&title=
