### ISSUE TITLE
增加文件分片选项，磁盘缓存设置，以及硬盘空间预分配功能设置

### ISSUE THREAD

**Issue by KevinMX** [agalwood/Motrix#727]
1.希望增加文件分片选项（即`--split`）。

1.希望增加硬盘缓存设置选项。在（进阶）设置中增加硬盘缓存选项（即配置文件中的`disk-cache`），由使用者自行决定缓存大小。

2.关于硬盘空间分配，aria2默认采用的是prealloc方式，在下载大文件时会对硬盘进行连续写入，大量占用IO。希望能在（进阶）设置中增加硬盘空间分配方式的选项。默认选项保持prealloc即可。在Windows下，如为NTFS，经测试可使用falloc方式快速分配硬盘空间，大幅降低硬盘IO。Linux下（如EXT4）可允许设置为trunc，macOS我没有用过，不过听说是只能使用prealloc。

**Comment by agalwood** [comment]
1. 自行编辑 `system.json` 修改，暂不准备开发界面。你的 issue 连你用什么系统都没说，`system.json` 文件路径自己搜下之前的 issue
2. disk-cache 默认改成 32M 了，暂不准备开放，如果要自行覆盖，同上
3. 麻烦先看下现在的代码，https://github.com/agalwood/Motrix/tree/master/extra ，已经做了多系统的对应配置

**Comment by KevinMX** [comment]
1. `system.json`文件我当然已经改过了
