### ISSUE TITLE
Native window decorations

### ISSUE THREAD

**Issue by tiotrom** [agalwood/Motrix#728]
Would be great if this app had a native window decoration, so in Linux it matches the default theme. Cheers and thanks a lot for this!

**Comment by agalwood** [comment]
Unchecked Preference -> Basic -> Hide App Menu (Windows & Linux Only), Save & Apply

**Comment by tiotrom** [comment]
Ah that's true it works. It is not as intuitive I guess. Why is it called "hide app menu"? I would suggest to leave it by default with the native window decoration. And add an option to switch to a custom window decoration. Sounds more intuitive for me ;).
