### ISSUE TITLE
Tracker服务器列表无法同步

### ISSUE THREAD

**Issue by Absolves** [agalwood/Motrix#729]
**错误描述**
1.5.15版本中不再提供预置的Tracker服务器列表（我看服务器列表现在是空白），点击从服务器同步按钮没有任何反馈

**如何重现**
重现步骤，如：
1. 点击从服务器同步按钮
2. 没有更新Tracker服务器信息

**预期的行为**
从设定的网址自动获取Tracker服务器列表并进行更新

**截图**
请添加屏幕截图以帮助解释你的问题：
打开应用菜单中的「帮助」——「开发者工具」—— 切换到 console，然后**完整**截图。

![image](https://user-images.githubusercontent.com/47398005/86424303-c7f5ed00-bd14-11ea-8405-43864e2da2ea.png)
![image](https://user-images.githubusercontent.com/47398005/86424322-d6440900-bd14-11ea-9c09-bb8db1f9c3ab.png)

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： 专业版1909
 - Motrix 版本：v1.5.15
 - 安装包类型：Motrix-Setup-1.5.15 

**更多信息**
补充有关该问题的其他信息。

**Comment by agalwood** [comment]
天朝的网络问题，默认的是 GitHub 地址，你删掉内置的两个源，改用以下两个源吧

> https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_best.txt
> https://cdn.jsdelivr.net/gh/ngosang/trackerslist@master/trackers_best_ip.txt
