### ISSUE TITLE
Tracker 服务器订阅问题

### ISSUE THREAD

**Issue by hezhijie0327** [agalwood/Motrix#730]
订阅地址1：https://source.zhijie.online/trackerslist/list_exclude.txt
订阅地址2：https://source.zhijie.online/trackerslist/list_full.txt
订阅地址3：https://source.zhijie.online/trackerslist/list_tracker.txt

在 BitCommet 上能正常订阅更新，但在 Motrix 上更新异常（curl wget 返回值均正常）
![Xnip2020-07-04_14-45-28](https://user-images.githubusercontent.com/58100052/86506790-74af9780-be05-11ea-9c38-42a16f98e90b.jpg)
![Xnip2020-07-04_14-45-39](https://user-images.githubusercontent.com/58100052/86506793-75e0c480-be05-11ea-98b8-0d4ae8afcc7f.jpg)
![Xnip2020-07-04_14-52-45](https://user-images.githubusercontent.com/58100052/86506868-0919fa00-be06-11ea-8576-42b26f785b99.jpg)

**Comment by agalwood** [comment]
Motrix 请求 tracker 服务器时，会在地址里增加一个 t=timestamp 的请求参数来防止缓存，如：
> https://source.zhijie.online/trackerslist/list_exclude.txt?t=1593850549295

你自己打开这个网址就知道为什么了，我觉得大概是你配置的 nginx 代理有问题

**Comment by hezhijie0327** [comment]
行
