### ISSUE TITLE
同时删除文件，把我下载目录清空了

### ISSUE THREAD

**Issue by MOFLY-M** [agalwood/Motrix#75]
深度系统Deepin 15.9.1 （一个LInux发行版）下，移除任务时，选择同时删除文件，然后我下载目录被清空了。。。清空了。。。清空了。。。

**Comment by hellof20** [comment]
这么牛批

**Comment by agalwood** [comment]
囧...是删除到回收站了吧？
我只能猜测是你的任务文件名可能为空，然后拼装文件路径时就只剩文件的目录了，所以造成整个目录被删了

**Comment by agalwood** [comment]
能否提供一下那个任务的下载链接以及你用的 Motrix 版本？

**Comment by MOFLY-M** [comment]
> 囧...是删除到回收站了吧？
> 我只能猜测是你的任务文件名可能为空，然后拼装文件路径时就只剩文件的目录了，所以造成整个目录被删了

好像是这样，把几个没能下载的种子磁力 任务移除了，勾选了同时删除文件，用的最新版

**Comment by agalwood** [comment]
重构了一下`getTaskFullPath` 方法，`moveTaskFilesToTrash` 加了个判断，如果路径和下载目录相同时，不执行文件删除操作
