### ISSUE TITLE
win10安装打开后出现系统错误

### ISSUE THREAD

**Issue by IsoyaYuki** [agalwood/Motrix#763]
![image](https://user-images.githubusercontent.com/41873059/89514337-5116ad00-d808-11ea-8436-3c6bb63b1d9c.png)
![image](https://user-images.githubusercontent.com/41873059/89514358-5673f780-d808-11ea-88f6-1fa9d28b8a5d.png)

**Comment by Ma1otru** [comment]
我也出现相同问题有解决吗
