### ISSUE TITLE
Windows下勾选同时删除文件无效

### ISSUE THREAD

**Issue by Wisonan** [agalwood/Motrix#77]
在Windows下删除任务时，勾选了“同时删除文件”，但文件夹中文件依然存在，在Mac下文件会被删除到废纸篓里。

**Comment by agalwood** [comment]
收到，是个bug，待修复，谢谢

**Comment by agalwood** [comment]
修复已发布，请更新
https://github.com/agalwood/Motrix/releases/tag/v1.2.2
