### ISSUE TITLE
打开后弹报错

### ISSUE THREAD

**Issue by freddiehsu** [agalwood/Motrix#776]
**错误描述**

**如何重现**
打开后就报错

**预期的行为**
希望正常打开

**截图**
![image](https://user-images.githubusercontent.com/69743957/91627723-ee21cb80-e9eb-11ea-9379-7ff683530e04.png)
![image](https://user-images.githubusercontent.com/69743957/91627727-faa62400-e9eb-11ea-93c2-dfab70652f18.png)
**运行环境**
win10 Pro 19041.450
motrix版本1.5.15

**更多信息**
补充有关该问题的其他信息。

**Comment by maodaxian** [comment]
你这问题我也遇到过 解决了  原因就是一些系统组件应该破坏了  我无意中安装游戏 重装了 什么VC++ 那些东西 就好了

**Comment by Ma1otru** [comment]
> 你这问题我也遇到过 解决了  原因就是一些系统组件应该破坏了  我无意中安装游戏 重装了 什么VC++ 那些东西 就好了

重装了一下运行库果然解决了，谢谢！

**Comment by liuzhenqi77** [comment]
Same problem here after closing a white-screened Motrix. Solved by manually removing user-added tracked servers in `%USERPROFILE%\AppData\Roaming\Motrix\user.json`, and re-opening Motrix. After program opened normally, `tracker-source` in `user.json` and `bt-tracker` in `system.json` became default values.

**Comment by shanezhan** [comment]
卸载motrix，把%USERPROFILE%\AppData\Roaming\Motrix  也删掉，重装就好了。
