### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by 18668180370** [agalwood/Motrix#78]
**Describe the bug**
下载文件时，文件总是下载到99%，就没速度了，也不显示已完成，怎么回事？
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [windows7]

**App (please complete the following information):**
 - Version [1.1.3]

**Additional context**
请尽快处理该问题，多谢

**Comment by agalwood** [comment]
下载的什么任务？普通链接任务呢，还是磁力链？还是BT？

麻烦提供更详细的信息，谢谢

**Comment by huige666a** [comment]
同该问题，dy2018里面的BT链接

**Comment by huige666a** [comment]
[https://imgur.com/a/rlOXinE](url)

**Comment by huige666a** [comment]
退出后可以了，暂停不行哈哈

**Comment by agalwood** [comment]
BT 下载会上传资源，如果不想分享，请手动停止任务
