### ISSUE TITLE
请问Motrix是否支持作为Aria2 Server，还是只能在应用内添加任务？

### ISSUE THREAD

**Issue by celleo** [agalwood/Motrix#788]
在Windows 10上安装了Motrix Lab中推荐的Aria2 for Chrome，结果插件一直提示说“未连接”。刚开始怀疑我安装的Motrix 1.5.10版本过低，更新到1.5.15后还是不行。我自己在终端执行aria2c --enable-rpc ，马上就显示连接上了。查了Motrix以前的一些信息，作者有个回答是Motrix支持外部通过RPC侦听的。。。请问我是哪儿做得有问题吗？

**Comment by syhyz1990** [comment]
默认端口号是16800
