### ISSUE TITLE
支持迅雷

### ISSUE THREAD

**Issue by zhouxiang1991** [agalwood/Motrix#8]
可以支持迅雷吗，应该只需要把协议后面的base64解码成原始地址就可以了吧

**Comment by agalwood** [comment]
特性已经合并到master，下个版本发布
但是我感觉意义不大，很多迅雷链接即使转成真实链接也下不动的，原资源已失效，缓存在迅雷的高速服务器上而已

**Comment by zhuxiaoxi** [comment]
意义不大，光是靠解码base64可以支持qqdl flashget等，但这些也不能通过服务器离线加速，走的也是原始链接。
