### ISSUE TITLE
Translation into Portuguese from Brazil

### ISSUE THREAD

**Issue by alexwender1** [agalwood/Motrix#80]
How can I help translate into my language?

There is no clear explanation about this, I found it quite confusing.

**Comment by agalwood** [comment]
Sorry, Motrix has not provided a contribution guide yet. I will write it out as soon as possible.
You can refer to the two PRs first.

https://github.com/agalwood/Motrix/pull/67
https://github.com/agalwood/Motrix/pull/70

The internationalization of Motrix is divided into three parts:
- Element UI
- Application Menu
- Main User Interface

**Comment by alexwender1** [comment]
Great, good to know.

**Comment by agalwood** [comment]
@alexwender1 I wrote a detailed translation contribution guide, you can take a look.
https://github.com/agalwood/Motrix/blob/master/CONTRIBUTING.md#-translation-guide

**Comment by brunoalvs** [comment]
I wish contribute too 👍

**Comment by alexwender1** [comment]
> I wish contribute too

I'm used to translation platforms, I do not have much experience with what the developer has proposed (I'm kind of confused :joy:).

You can pull the front if you know how to start.

**Comment by franco27** [comment]
I think I will make the French version of your download manager

  I'm not sure I understood everything, but I'll try.

**Comment by alexwender1** [comment]
Thanks @andrenoberto, for uploading the Brazilian Portuguese translation.

I'll be closing this topic.
