### ISSUE TITLE
Motrix 在 macOS Big Sur 状态栏的图标错误

### ISSUE THREAD

**Issue by 0xJacky** [agalwood/Motrix#804]
**错误描述**
Motrix 在 macOS Big Sur 状态栏的图标颜色错误

**如何重现**
在 macOS Big Sur 下打开 Motrix

**预期的行为**
macOS Big Sur 浅色模式下，Motrix 的状态栏图标应该为白色

**截图**
<img width="241" alt="截屏2020-11-12 上午12 13 54" src="https://user-images.githubusercontent.com/13096985/98836013-2168e800-247c-11eb-9b26-9393f6c7aa88.png">

**运行环境**
 - 操作系统类型： macOS
 - 具体版本： 11.0.1 (20B28)
 - Motrix 版本： 1.5.15
 - 安装包类型：Homebrew cask

**更多信息**
无

**Comment by hooke007** [comment]
bugsur的图标颜色不光受深浅模式影响，还受壁纸影响，motrix还是卡特琳娜的那套逻辑
