### ISSUE TITLE
Motrix下载报错#22

### ISSUE THREAD

**Issue by Carrol888** [agalwood/Motrix#806]
软件及系统如下,看了其他相关Issues,没找到Mac OS相关的解决配置
![1111](https://user-images.githubusercontent.com/56289048/99863561-aae58c00-2bd9-11eb-8e09-96c5869a2192.png)
![2222](https://user-images.githubusercontent.com/56289048/99863562-ac16b900-2bd9-11eb-9edc-6ec8cad81ca8.png)
![3333](https://user-images.githubusercontent.com/56289048/99863563-ade07c80-2bd9-11eb-9653-48268246cbc8.png)

**Comment by glntlq** [comment]
蹲个解决方案

**Comment by Xeonpoint** [comment]
My problem was the same as yours.
II ran into this problem when I downloaded the ``openSUSE iso``.
url: ``https://mirrors.bfsu.edu.cn/opensuse/tumbleweed/iso/openSUSE-Tumbleweed-DVD-x86_64-Snapshot20201202-Media.iso``
I don't know how to do that.

**Comment by weiguozhao** [comment]
me, too

**Comment by zphj1987** [comment]
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

![Xnip2021-01-20_17-02-20](https://user-images.githubusercontent.com/2322061/105151956-8e19f600-5b41-11eb-8a8f-4ff13328d2f4.jpg)


@weiguozhao wei
@Xeonpoint X

需要自己填写User-agent 把上面的贴进去就可以了

**Comment by Xeonpoint** [comment]
> Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
> 
> ![Xnip2021-01-20_17-02-20](https://user-images.githubusercontent.com/2322061/105151956-8e19f600-5b41-11eb-8a8f-4ff13328d2f4.jpg)
> 
> 
> @weiguozhao wei
> @Xeonpoint X
> @glntlq
> 
> 需要自己填写User-agent 把上面的贴进去就可以了  
> 
> ![Xnip2021-01-20_17-06-14](https://user-images.githubusercontent.com/2322061/105152191-d3d6be80-5b41-11eb-869a-8ac1d4786e6d.jpg)
> 

Thank you for providing me with ideas to solve the problem.
I didn't expect that even downloading things like this would have user agent restrictions.

**Comment by Carrol888** [comment]
Thx
