### ISSUE TITLE
Can I custom the download limit speed?

### ISSUE THREAD

**Issue by unkn0wn95** [agalwood/Motrix#808]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
[
![Screenshot from 2020-11-22 15-52-35](https://user-images.githubusercontent.com/58463797/99898229-dd2ae280-2cda-11eb-9161-998f7d99dbaa.png)
](url)

**Comment by itsmeboy0** [comment]
Not just the download limit, but the upload limit speed as well!

**Comment by itsmeboy0** [comment]
@unkn0wn95 Why did you close it?

**Comment by unkn0wn95** [comment]
@itsmeboy0 owh I thought you tell me to custom/code it myself

**Comment by dtantono** [comment]
yeah qbitorrent allow us to set the numbers manually. motrix should have this as well

**Comment by nxjosephofficial** [comment]
Yes, this feature would be good. I think it's a need because these limits may not suitable for everyone.
