### ISSUE TITLE
Disable Title Bar and System Edge

### ISSUE THREAD

**Issue by alexwender1** [agalwood/Motrix#81]
**Describe the bug**
Do not allow the application to display the title bar and system borders.

**Screenshots**
![captura de tela_selecionar area_20190222105325](https://user-images.githubusercontent.com/45263160/53263253-99dfb200-36b7-11e9-9a84-c9b065ce0132.png)

**Environment (please complete the following information):**
 - OS & Version: Deepin 15.9.1
 - Motrix Version: 1.1.3 (AppImage)

**Additional context**
For some reason, the application can not disable the use of the bar and system edge.

**Comment by smallg0at** [comment]
This is the same issue as #54 I guess?

**Comment by agalwood** [comment]
Yes, it is a bug that has been fixed on the master branch. #54

**Comment by alexwender1** [comment]
That's right @smallg0at. Waiting for the next updates @agalwood.

**Comment by agalwood** [comment]
Released
https://github.com/agalwood/Motrix/releases/tag/v1.2.2
