### ISSUE TITLE
建议增加对 p 站的支持

### ISSUE THREAD

**Issue by deerainw** [agalwood/Motrix#810]
目前 p 站视频只能通过浏览器本身的下载功能来下载，三方下载工具全部报错

**Comment by wardseptember** [comment]
哪个p站？为什么这个国际化这么牛逼？程序员怎么会那么多语言？他们不是程序员？

**Comment by wdm1732418365** [comment]
> 目前 p 站视频只能通过浏览器本身的下载功能来下载，三方下载工具全部报错

用IDM
