### ISSUE TITLE
使用百度网盘插件下载提示“正在获取下载地址...”然后没有反应了

### ISSUE THREAD

**Issue by 52mzd** [agalwood/Motrix#82]
**Bug 描述**
使用百度网盘插件下载提示“正在获取下载地址...”然后没有反应了，MO是启动状态的，无法自动导出地址到MO中。

**运行环境**
 - 操作系统类型: macOS,
 - 具体版本 ：macOS 10.14.2, 
 - Motrix 版本 v1.1.3
 - Chrome版本 72.0.3626.119

**Comment by agalwood** [comment]
试下保存到自己的网盘再下载

**Comment by 52mzd** [comment]
必须保存到了自己网盘上啊，就是在自己网盘中操作的

**Comment by agalwood** [comment]
我的失误，上传了一个错误的扩展包，请重新下载安装 [BaiduExporter](https://motrix.app/release/BaiduExporter.zip)

**Comment by 52mzd** [comment]
果然ok了，谢谢，另外可以添加设置自动关联下载链接吗？默认磁力链打开都是迅雷。。。

**Comment by agalwood** [comment]
暂时不支持，可以先用 YAAW for Chrome 右键导出磁力链到 Motrix 下载
https://chrome.google.com/webstore/detail/yaaw-for-chrome/dennnbdlpgjgbcjfgaohdahloollfgoc

安装说明请看文档：
https://www.yuque.com/moapp/help/extensions#cquhno
