### ISSUE TITLE
Icon not present in AppImage

### ISSUE THREAD

**Issue by alexwender1** [agalwood/Motrix#83]
**Describe the bug**
The application icon is not displayed during execution. The system only displays a generic icon.

**Screenshots**
The yellow arrow points to the taskbar, where the application is running.

![captura de tela_20190223210306](https://user-images.githubusercontent.com/45263160/53293252-0e494c80-37af-11e9-8daa-fff6229759fd.png)

**Environment (please complete the following information):**
 - OS & Version: Deepin 15.9.1
 - Motrix Version: 1.1.3

**Comment by agalwood** [comment]
This deepin has been mentioned before the icon is displayed, but he said that it is normal after updating to 1.1.3. https://github.com/agalwood/Motrix/issues/15#issuecomment-463458577
So I don't know if it's a deepin or a Motrix problem : (

**Comment by alexwender1** [comment]
> This has not been mentioned before the icon is displayed run in deepin, but he said that it is ok after updating to 1.1.3. [#15 (comment)](https://github.com/agalwood/Motrix/issues/15#issuecomment-463458577)
> So I don't know if it's a deepin or a Motrix problem : (

I am referring to the AppImage version. This user mentioned the installable version (.deb).

I use other AppImage applications and all display their icon correctly.

**Comment by agalwood** [comment]
I just installed deepin 15.9.1 in VMware, and then installed Motrix v1.1.3 using AppImage. The dock icon is not displayed when I run it for the first time. Then I log out of the deepin os and run Motrix again. Its icon is displayed. It is.

**Comment by alexwender1** [comment]
I ask you to check the AppImage, because the system is not identficando the icon (surely it must be the way you configured it to display).

I use GIMP, Inskape, LibreOffice (all in the latest version) ... and display the corresponding icon correctly.

Note: I did not get the same results as you. Although I reinstalled the system a few days ago.

**Comment by agalwood** [comment]
> I ask you to check the AppImage, because the system is not identficando the icon (surely it must be the way you configured it to display).

I tested it according to your environment.
Deepin 15.9.1 + Motrix v1.1.3 AppImage. It is not displayed at the beginning, but I log out and re-login, and the icon is displayed.

I will try it in the next version according to this guide.
https://github.com/AppImage/AppImageKit/wiki/Bundling-Electron-apps

**Comment by alexwender1** [comment]
Thank you for your interest in verifying the problem.

**Comment by alexwender1** [comment]
Resolved in version 1.2.2. Thanks!
