### ISSUE TITLE
无法打开Motrix 显示 cannot read property 'showPage' of underfined

### ISSUE THREAD

**Issue by fengjunpeng** [agalwood/Motrix#84]
![image](https://user-images.githubusercontent.com/40300130/53293824-636c7900-3816-11e9-9a09-2a4f7d72b96d.png)
反复了几次都是这样

**Comment by agalwood** [comment]
对于你这种 issue，我没有那么多精力去猜你的运行环境，系统版本，应用版本，有没有换过其他安装包试过等等等
麻烦按照以下模版提，谢谢
https://github.com/agalwood/Motrix/issues/new?assignees=&labels=&template=bug_report_cn.md&title=请按以下格式填写反馈信息
