### ISSUE TITLE
连结任务中的「重新命名」，下载后的档名非预期正确

### ISSUE THREAD

**Issue by XokviqTzqKbs7V** [agalwood/Motrix#845]
**错误描述**
连结任务中的「重新命名」，下载后的档名非预期正确

**如何重现**
重现步骤，如：
1. 点击新建任务按钮
2. 黏贴链接 https://github.com/agalwood/Motrix/releases/download/v1.5.15/Motrix-1.5.15-win.zip
3. 重新命名 XXXXX (1080p).zip
4. 送出
5. 下载后的档名变成 XXXXX 1.zip

**预期的行为**
重新命名 XXXXX (1080p).zip → 下载后的档名应为 XXXXX (1080p).zip，而非 XXXXX 1.zip
请修正重新命名，下载后的档名正确性，谢谢！

**截图**
请添加屏幕截图以帮助解释你的问题：
https://i.imgur.com/jcoWj2w.jpeg

**运行环境**
 - 操作系统类型： Windows
 - 具体版本：Windows 7 X64
 - Motrix 版本： v1.5.15
 - 安装包类型：Motrix-Setup-1.5.15.exe

**更多信息**
补充有关该问题的其他信息。

**Comment by agalwood** [comment]
似乎 (1080p) 触发 https://github.com/agalwood/Motrix/issues/584#issuecomment-605855161 批量重命名规则 #341 了
