### ISSUE TITLE
希望增加批量删除功能

### ISSUE THREAD

**Issue by VincentCJ** [agalwood/Motrix#85]
希望增加多选及批量删除功能

**Comment by agalwood** [comment]
重复问题 https://github.com/agalwood/Motrix/issues/27
待开发 https://trello.com/b/qNUzA0bv/motrix

**Comment by agalwood** [comment]
已添加了鼠标拖拽选中任务批量删除功能，请更新 Motrix 到 v1.5.x 版本https://github.com/agalwood/Motrix/releases
