### ISSUE TITLE
百度网盘下载发生错误 #18，无法修改 chrome extension 代码

### ISSUE THREAD

**Issue by Xiaoven** [agalwood/Motrix#855]
**错误描述**
错误代码同 https://github.com/agalwood/Motrix/issues/540，我照着它的解决方法在 chrome 输入链接，但并没有打开代码编辑页面。

**如何重现**
重现步骤，如：
1. 打开安装了油猴的 chrome
2. 黏贴链接 chrome://extensions/?id=dhdgffkkebhmkfjojejmpbldmpobfkfo
4. 发现重定向回 chrome://extensions/ 页面

**预期的行为**
进入如 #540 所示的代码编辑页面

**运行环境**
 - 操作系统类型： MacOS
 - 具体版本：MacOS 10.15.7
 - Motrix 版本： v1.5.15
 - 安装包类型：dmg

**Comment by yeb666999** [comment]
ke yi Thanks.

**Comment by Lockik** [comment]
thanks a lot  栓q了

**Comment by Ah-yuan** [comment]
Thanks
