### ISSUE TITLE
是否可以推出一个arm版本（树莓派）

### ISSUE THREAD

**Issue by xiangdongping999** [agalwood/Motrix#856]
不知是否可以推出一个树莓派的arm版本。
这个软件我使用在 windows10 和 LinuxMint 上。
同样希望使用在 树莓派上。

以上，感谢！

**Comment by TheInterestingSoul** [comment]
这个是electron应用，electron又依赖node.js，但不管怎么说哪个环节都支持arm的吧，可以自行编译

**Comment by xiangdongping999** [comment]
哦，刚刚入门linux，不太懂编译，不过已经用aria2NG了，谢谢回复！～
