### ISSUE TITLE
下载文件失败终止问题

### ISSUE THREAD

**Issue by huaxinchan** [agalwood/Motrix#86]
下载百度云文件，有些文件下载中途会意外停止，需要重新打开软件才可以继续下载。希望可以添加文件意外终止后自动继续下载的功能

Version [1.1.3]

**Comment by agalwood** [comment]
收到，待开发 https://trello.com/b/qNUzA0bv/motrix

**Comment by T5eng** [comment]
有时候重新打开文件也不行，需要删掉原记录，新创建下载记录，从之前的下载文件断点续传

**Comment by agalwood** [comment]
Motrix v1.4.x 下载失败的任务支持重新下载，请更新到最新版本

![image](https://user-images.githubusercontent.com/1032175/60648515-a7c9ee80-9e72-11e9-8aa6-fc7300c9ecdc.png)

https://github.com/agalwood/Motrix/releases
