### ISSUE TITLE
无法https下载清华TUNA的文件

### ISSUE THREAD

**Issue by JohnLulzh2002** [agalwood/Motrix#871]
**错误描述**
无法https下载清华TUNA的文件

**如何重现**
重现步骤，如：
1. 新建链接任务，并试图下载以下几个文件：
https://mirrors.tuna.tsinghua.edu.cn/deepin-cd/20.1/deepin-desktop-community-1010-amd64.iso
https://mirrors.tuna.tsinghua.edu.cn/github-release/VSCodium/vscodium/LatestRelease/VSCodiumSetup-x64-1.53.2.exe
https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/33/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-33-1.2.iso
反复重试，均发生#22错误。并非测试环境网络问题，上述链接用BitComet可以正常下载。

**预期的行为**
正常下载

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： Windows 10 (x64)
 - Motrix 版本：1.5.15
 - 安装包类型：exe(Motrix-Setup-1.5.15.exe)

**更多信息**
同样的文件，[上海交大镜像](https://mirror.sjtu.edu.cn/fedora/linux/releases/33/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-33-1.2.iso)却能正常下载下载

**Comment by agalwood** [comment]
偏好设置里的 模拟用户代理（UA）改成 Chrome 的就可以了
