### ISSUE TITLE
能否支持改UA?以及如何自己编译最新版哈？

### ISSUE THREAD

**Issue by fredericky123** [agalwood/Motrix#876]
能否支持改UA?以及如何自己编译最新版哈？

由于正式更新比较慢，自己想尝鲜开发版，如何做到哇？

自定义UA是为了突破百度云的速度限制

**Comment by agalwood** [comment]
进阶设置——安全性——模拟用户代理（UA）支持手动输入 UA，保存就行了

**Comment by fredericky123** [comment]
Oh my god, 我发现我还曾经改过，这是脑子抽了，哈哈谢谢提醒
