### ISSUE TITLE
Motrix 启动后崩溃

### ISSUE THREAD

**Issue by JER-ry** [agalwood/Motrix#880]
**错误描述**
无法启动 Motrix

**如何重现**
重现步骤：
1. 点击图标启动 Motrix
2. 报错 (如图)
![图片](https://user-images.githubusercontent.com/30141096/111312763-95b9cf00-869a-11eb-8956-d5e984b11f2e.png)
3. 点击确定
4. 报错 (如图)
![图片](https://user-images.githubusercontent.com/30141096/111312860-ac602600-869a-11eb-915c-e7d770a4e6b9.png)
5. Motrix 终止运行

**预期的行为**
正常运行

**截图**
*报错数目会快速增长 (相同错误反复出现). 下图是启动后迅速截图的情形.*
![图片](https://user-images.githubusercontent.com/30141096/111313704-9ef76b80-869b-11eb-91b8-f9b58a239014.png)

**运行环境**
 - 操作系统类型： Windows 10
 - 具体版本：Windows 10 20H2
 - Motrix 版本： 1.5.15
 - 安装包类型：exe

**更多信息**
可能与此电脑上某些设置有关. 若通过以上信息无法判断, 可进一步联系我.

**Comment by JER-ry** [comment]
卸载后清除干净 AppData 再重装, 可以解决问题.

**Comment by SJ1848** [comment]
> 卸载后清除干净 AppData 再重装, 可以解决问题.

请问能具体说下怎么清理吗？我也遇到这个问题了。谢谢！

**Comment by JER-ry** [comment]
> > 卸载后清除干净 AppData 再重装, 可以解决问题.
> 
> 请问能具体说下怎么清理吗？我也遇到这个问题了。谢谢！

Motrix 的 AppData 位于 C:\Users\您的用户名\AppData\Roaming\Motrix（可能依您安装的位置而不同），删除此文件夹即可。
您可能也想看看 #1133。
