### ISSUE TITLE
对软件开发者开放的API，可进行批量任务处理(创建、暂停、删除)

### ISSUE THREAD

**Issue by iicey** [agalwood/Motrix#887]
**请描述一下你的新功能请求是否与已知问题有关？**
有200多个视频文件需要下载，但是只能一个一个的手动添加任务

**描述你想要的解决方案**
提供处理webAPI进行批量处理
例如：创建http://127.0.0.1:80/create?taskName=123&taskURL=http://movie.com/abc

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by uiYzzi** [comment]
直接调用aria2的rpc不就好了
