### ISSUE TITLE
提个题外的问题，关于github下载

### ISSUE THREAD

**Issue by goeway** [agalwood/Motrix#89]
在github里下载东西很上火，速度非常非常非常非常非常非常慢，速度时有时无，无论文件多大，一般以下载失败告终，因此在此提个无礼的请求，能否提供一个镜像以便下载呢

![2019-02-25_224304](https://user-images.githubusercontent.com/23276757/53352644-1dbac800-395e-11e9-9722-019c0e3abaab.png)

**Comment by Raistlin916** [comment]
放在 cdn 上还是挺贵的，免费软件耗不起，总不能放在百度网盘里吧 23333

**Comment by xysemies** [comment]
gitee.com 
和百度网盘分流

让大多数人能快速下载才是初衷啊

**Comment by Raistlin916** [comment]
我放了一个在 gitee 上，不过要登录是个问题

https://gitee.com/raistlin/Motrix/attach_files

**Comment by goeway** [comment]
> 放了一个在gitee上，不过要登录是个问题
> 
> https://gitee.com/raistlin/Motrix/attach_files

太感谢了，几秒钟就下回来了。。登录不是问题，我早已注册，原本就是想着用它来快速地下载github的东西而注册的，谁知注册后导入github的库后发现好像只能用来下载代码而不能用来下载软件（或许是我不懂操作吧，啰嗦了，不好意思）
