### ISSUE TITLE
应用启动失败: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by uselessbug** [agalwood/Motrix#895]
**错误描述**
应用启动失败: spawn ENAMETOOLONG

Error: Cannot read property 'child' of undefined

**如何重现**
重现步骤，如：
打开程序时弹出对话窗，后程序关闭

**预期的行为**
打开Motrix（orz

**截图**
![图片](https://user-images.githubusercontent.com/61285640/113464876-8d1b1400-9462-11eb-95a3-f6bc88abdaa0.png)
![图片](https://user-images.githubusercontent.com/61285640/113464880-986e3f80-9462-11eb-954e-451d8712d6f4.png)

**运行环境**
 - 操作系统类型：Windows
 - 具体版本：Windows 10
 - Motrix 版本： v1.5.15
 - 安装包类型：exe

**更多信息**
log
[main.log](https://github.com/agalwood/Motrix/files/6251739/main.log)
设置文件
[system.zip](https://github.com/agalwood/Motrix/files/6251752/system.zip)

**Comment by lqkx** [comment]
也遇到了一样的问题，在win7上，orz

**Comment by uselessbug** [comment]
> 
> 
> 也遇到了一样的问题，在win7上，orz

orz好像是设置文件太大了（我丢了很长一串代理白名单在里面因为）
