### ISSUE TITLE
kde下应用界面无法加载

### ISSUE THREAD

**Issue by dream-pioneer** [agalwood/Motrix#898]
**错误描述**
打开应用无法加载，卡在黑白屏界面

**如何重现**
打开应用

**截图**
![IMG_20210403_162245.jpg](https://user-images.githubusercontent.com/66502235/113472933-d71eec80-9498-11eb-9bdb-eec032b09f4b.jpg)

**运行环境**
 - 操作系统类型：Linux
 - 具体版本：Arch
 - Motrix 版本：1.5.15.r68.g0cd1ed1-1
 - 安装包类型：archlinuxcn源

**Comment by weearc** [comment]
@dream-pioneer 所以为什么不用aur里的release版本呢？archlinuxcn仓库的那个motrix-git是把整个node modules扔到/usr/lib里了，electron更新一次（或者产生一些变动）就会出现类似问题（这也是为什么我维护的版本没拆出electron，因为路由问题不能拆）。motrix-git为了减小体积是强行拆除的，出现这种状况很正常（当初也为了这个事情讨论了很久）

**Comment by dream-pioneer** [comment]
@weearc 谢谢，下载了release版本后可以正常使用了
