### ISSUE TITLE
建议发布到 Homebrew

### ISSUE THREAD

**Issue by Loyalsoldier** [agalwood/Motrix#90]
现在 Homebrew 中还搜索不到这个软件，建议发布到 Homebrew

**Comment by Mitscherlich** [comment]
我已经向 [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask) 提交了一个 pr  (Homebrew/homebrew-cask#59494)，合并之后应该就可以从 `brew` 下载安装了。希望作者 @agalwood  能维护这个 `cask`。

**Comment by agalwood** [comment]
@Mitscherlich 我也 fork 了，准备晚点提交 PR 的，结果你先提了哈: D，那我就不提了
要不你再更新一下，在 zap trash 里把 Motrix 的 Logs 和 Caches 也清一下吧～。～

```
'~/Library/Logs/Motrix',
'~/Library/Caches/net.agalwood.Motrix',
```

**Comment by Mitscherlich** [comment]
Ok，已经加了，感谢作者提供这么不错的工具，不知有没有办法支持ed2k？

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/14
