### ISSUE TITLE
能不能在任务栏上面显示加载进度？

### ISSUE THREAD

**Issue by StephenChips** [agalwood/Motrix#918]
**描述你想要的解决方案**
这个功能大多数下载器都有，像迅雷，FDM，希望你能提供。如果大家觉得OK，我也可以试着实现这功能。
就像这样：![就像这样](https://cloud.githubusercontent.com/assets/639601/5081682/16691fda-6f0e-11e4-9676-49b6418f1264.png)

**Comment by agalwood** [comment]
这个进度条目前用来显示自动更新应用时下载安装包的进度
