### ISSUE TITLE
欢迎回归，以及官网上的版本好久没更新了

### ISSUE THREAD

**Issue by fxzxmicah** [agalwood/Motrix#923]
还停留在1.5.15。
![image](https://user-images.githubusercontent.com/48860358/117306574-5c3f5c00-aeb2-11eb-8f0c-b5ef842afe78.png)
另外，`重新设计的 Motrix Scheme`意思是可以通过`Motrix://`启动Motrix并提交下载任务吗？

**Comment by agalwood** [comment]
官网一堆 npm 依赖要更新，还没发布

Motrix Scheme 目前还比较简陋，勉强能用吧
https://github.com/agalwood/Motrix/pull/716#issue-437359352

> // New Task
> motrix://new-task?uri=URL&out=NAME&dir=DIR

> // Add Task silently, no confirmation
> motrix://new-task?uri=URL&out=NAME&silent=true

> // Open Preference
> motrix://preferences

> // Open About
> motrix://about

**Comment by huanghaobaobao** [comment]
就差官方浏览器插件和资源嗅探了，期待ing

**Comment by yjvv1** [comment]
然而 1.6.8在win10下几分钟后貌似卡死，任务界面不变化，点等待中及已停止也无变化，再点结束任务一样，观察网络连接已断流，也试着下载成功过，但是过一会重现假死，退出再打开后，任务全没

**Comment by yjvv1** [comment]
> 转速下午npm特华特恩特
> 
> 莫特里克克斯计划不计其境， 专家专家
> [#716 （评论）](https://github.com/agalwood/Motrix/pull/716#issue-437359352)
> 
> > 新任务motrix://new 任务？
> 
> > 默默添加任务，没有确认motrix://new 任务？uri=URL+出=名称+沉默=真实
> 
> > 开放优先motrix://preferences
> 
> > 打开约motrix://about

然而 1.6.8在win10下几分钟后貌似卡死，任务界面不变化，点等待中及已停止也无变化，再点结束任务一样，观察网络连接已断流，也试着下载成功过，但是过一会重现假死，退出再打开后，任务全没

**Comment by agalwood** [comment]
@fxzxmicah 官网和自动更新版本已经更新

由于 Motrix v1.5.x 用的是 forever-monitor 的，升级到 v1.6.x 之后内置的下载引擎 aria2 的进程可能会启动失败，需要手动完全重启一次应用。
