### ISSUE TITLE
然而 1.6.8在win10下几分钟后貌似卡死，任务界面不变化，点等待中及已停止也无变化，再点结束任务一样，观察网络连接已断流，也试着下载成功过，但是过一会重现假死，退出再打开后，任务全没

### ISSUE THREAD

**Issue by yjvv1** [agalwood/Motrix#924]
**Before feedback**
Before you feedback, please search for the issues to see if there are similar problems that can solve your problem.

**Please delete the above and the contents of this line, then fill in the feedback form in the following format, Thanks.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & Version: [e.g. macOS, Windows, Linux]
 - Version: [e.g. macOS 10.14.2, Windows 10, Ubuntu 18.04]
 - Motrix Version: [e.g. v1.1.3, v1.1.0]
 - Installation package type: [e.g. dmg, AppImage]

**Additional context**

**Comment by yjvv1** [comment]
回退到1.5.15，以上情况没有了，但是得忍受内存占用4G以上，并虚拟内存涨至30G（任务多于6个，并文件大），，，1.6.8倒是没这个内存的问题了，但是不工作了就有点

**Comment by agalwood** [comment]
我在前几天开发过程中，现在 aria2  是用 NodeJS child_process 启动的，升级 Electron 到 v12.0.5 也出现了你描述的问题（macOS），下载下着下着就不动了，用系统进程管理器查看进程，aria2 进程还在但是 RPC 服务好像挂了。

回退到 v11.4.4 之后就没出现了，新版在 Windows 下的表现我还没有长时间测试过～。～

**Comment by jefcn** [comment]
我今天安装了新版也是出现了这个问题

**Comment by yjvv1** [comment]
最新进展，用1.5.15把这个1.6.8下载下来和浏览器直接下载来的对比了下，文件大小一样，但前者占用空间大了一点点 107,835,392 字节，用这个升级安装了一次，奇怪，正常了，占用内存很小，，，，aria2进程在打开程序界面时会消失，最小化到右下角又出现，到目前为止算是好了，这是什么鬼？

**Comment by yjvv1** [comment]
嗯~退出程序再进入，任务随机性的不见了，有时候有，有时候所有任务都没有，还得重新新建任务。。

**Comment by yjvv1** [comment]
> 我在前几天开发过程中，现在 aria2 是用 NodeJS child_process 启动的，升级 Electron 到 v12.0.5 也出现了你描述的问题（macOS），下载下着下着就不动了，用系统进程管理器查看进程，aria2 进程还在但是 RPC 服务好像挂了。
> 
> 回退到 v11.4.4 之后就没出现了，新版在 Windows 下的表现我还没有长时间测试过～。～

现在发现有两个aria2进程，结束占用小的那个会出现界面卡死，后面又启动了

**Comment by agalwood** [comment]
更新 Motrix 到 v1.6.9 试试
https://github.com/agalwood/Motrix/releases/tag/v1.6.9
