### ISSUE TITLE
新版本还是有spawn ENAMETOOLONG的问题啊

### ISSUE THREAD

**Issue by cddehsy** [agalwood/Motrix#930]
昨天安装的1.6.8没有问题，今天安装了1.6.9和1.6.10都有问题，用不了

![QQ截图20210508094551](https://user-images.githubusercontent.com/42635049/117521845-86903700-afe2-11eb-8934-27d4c61bd9c4.png)

**Comment by agalwood** [comment]
> Error: spawn ENAMETOOLONG

参数过长的问题可能 tracker 的地址过多了，你是不是勾选了多个 Tracker 服务器的源？

还有你的 Windows 是什么版本的？

**Comment by yjvv1** [comment]
重现，但是彻底删除后装1.6.10正常，是安装过程中卸载不干净？勾选了所有Track源的情况下，是不是只要勾选CDN的就可以

> > Error: spawn ENAMETOOLONG
> 
> 参数过长的问题可能 tracker 的地址过多了，你是不是勾选了多个 Tracker 服务器的源？
> 
> 还有你的 Windows 是什么版本的？

重现这个错误，但是彻底删除后再装1.6.10正常，勾选了所有Tracker源的情况下！是不是只要CDN的源就行，不用多？还加了这个
https://gitee.com/harvey520/www.yaozuopan.top/raw/master/blacklist.txt

**Comment by agalwood** [comment]
@yjvv1 加 blacklist 是反向操作呀（用了这个 blacklist 更没速度）。。。现在 tracker 黑名单功能只能手动修改 system.json

不要全选！不要全选！不要全选！

基本上配置两个 tracker 源就够用了 : |

ngosang/trackerslist 的
trackers_best.txt CDN
trackers_best_ip.txt CDN
或者
 XIU2/TrackersListCollection 的
best.txt CDN
http.txt CDN

**Comment by cddehsy** [comment]
真的吗，我勾选所有的了。

**Comment by cddehsy** [comment]
我删除了所有的tr，然后重装也不行。但是重置设置然后就OK了。

**Comment by sandboxdream** [comment]
> 我删除了所有的tr，然后重装也不行。但是重置设置然后就OK了。

请问怎么在无法启动应用的情况重置设置

**Comment by naamikiss** [comment]
1.卸载Motrix；
2.删除C:\Users\naamikiss\AppData\Roaming\目录下的Motrix文件夹；
3.重新安装；
问题解决了，起码我这样搞问题解决了。

**Comment by chuyueye** [comment]
> 1.卸载Motrix； 2.删除C:\Users\自己的账号名\AppData\Roaming\目录下的Motrix文件夹； 3.重新安装； 问题解决了，起码我这样搞问题解决了。 版本号：Version 1.6.11

赞

**Comment by xiaoyaoz1** [comment]
1.卸载Motrix；
2.删除C:\Users\自己的账号名\AppData\Roaming\目录下的Motrix文件夹；
3.重新安装；
问题解决了，起码我这样搞问题解决了。
版本号：Version 1.6.11   ---------------------------------------不用重装也可以，删除文件夹就行

**Comment by HuanLinOTO** [comment]
不用重装，报错后 electron window 还是会正常弹出的，直接去设置把 tracker 干掉一些即可
![image](https://github.com/agalwood/Motrix/assets/94176676/27cb0c96-7cbd-4194-917c-42e492fc0131)
