### ISSUE TITLE
检测版本不起作用了？

### ISSUE THREAD

**Issue by youngledo** [agalwood/Motrix#931]
我看tags都到v1.6.10，而官网上的版本还停留在v1.5.15。手动检测版本一直提示没有最新版本。

**Comment by S-T-eve** [comment]
客户端读的好像是官网的源，如果追更的话还是直接右上角点watch更好

**Comment by agalwood** [comment]
官网分发的是比较稳定的版本，还没更新版本号，在等等更多 GitHub 尝鲜用户的问题反馈

**Comment by agalwood** [comment]
@youngledo 官网和自动更新版本已经更新

由于 Motrix v1.5.x 用的是 forever-monitor 的，升级到 v1.6.x 之后内置的下载引擎 aria2 的进程可能会启动失败，需要手动完全重启一次应用。
