### ISSUE TITLE
建议增加一个Safari浏览器的插件，对Safari的下载即时监测及托管。

### ISSUE THREAD

**Issue by psspfizlk** [agalwood/Motrix#936]
**请描述一下你的新功能请求是否与已知问题有关？**
简明扼要地描述了问题所在。

**描述你想要的解决方案**
简明扼要地描述你想要的解决方案。

**描述你考虑过的替代方案**
简明扼要地描述你考虑过的任何替代解决方案或功能。

**更多信息**
补充有关该新功能的其他信息。

**Comment by agalwood** [comment]
Safari 浏览器扩展得上架 App Store，BT 下载工具上架不了 App Store : (

BTW：Motrix 提审 App Store 数次都被拒之后，这才有了这个开源项目

**Comment by xiao-baii** [comment]
有个问题，为什么迅雷可以...

**Comment by JOJOforshaun** [comment]
> Safari 浏览器扩展得上架 App Store，BT 下载工具上架不了 App Store : (
> 
> BTW：两年前 Motrix 提审 App Store 数次都被拒之后，这才有了这个开源项目

我的安全软件没有上架app store ，是官网版本，依然可以安装网页拦截扩展啊。应该有什么曲线救国的办法吧
