### ISSUE TITLE
更新了1.6.10，明明很多连接，但是速度一直上不去，1.5.15就能满速，请问这是什么原因？

### ISSUE THREAD

**Issue by kabuda2077** [agalwood/Motrix#938]
![image](https://user-images.githubusercontent.com/73030099/117761350-c90f7900-b259-11eb-9343-01833e705a5e.png)
![image](https://user-images.githubusercontent.com/73030099/117761387-d75d9500-b259-11eb-8a47-283b03f9f1b0.png)

**Comment by cddehsy** [comment]
这应该是种子本身的问题吧

**Comment by kabuda2077** [comment]
> 这应该是种子本身的问题吧

应该不是 ubuntu这个种子很多人的。后面重装了一下又能满速了。
