### ISSUE TITLE
百度云无法下载,一直出错

### ISSUE THREAD

**Issue by 673157660** [agalwood/Motrix#94]
**Before feedback**
Before you feedback, please search for the issues to see if there are similar problems that can solve your problem.

**Please delete the above and the contents of this line, then fill in the feedback form in the following format, Thanks.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS & Version: [e.g. macOS, Windows, Linux]
 - Version: [e.g. macOS 10.14.2, Windows 10, Ubuntu 18.04]
 - Motrix Version: [e.g. v1.1.3, v1.1.0]
 - Installation package type: [e.g. dmg, AppImage]

**Additional context**

**Comment by 673157660** [comment]
百度云无法下载文件 一直出错

**Comment by agalwood** [comment]
https://www.yuque.com/moapp/help/extensions

https://github.com/agalwood/Motrix/issues/new?assignees=&labels=&template=bug_report_cn.md
