### ISSUE TITLE
是否支持自定义协议?

### ISSUE THREAD

**Issue by sinyat** [agalwood/Motrix#949]
根据"协议"/"protocol"关键词未搜索到相关issues.

是否可支持自定义协议? 传递两个参数, 一个下载链接, 一个要重命名的文件名, 目前下载一个文件, 如果要重命名, 需要手动改, 这在比较多的文件需要被下载的时候很难受.

或者说, 有什么办法可以在自己的代码里, 调用motrix, 且自动下载和重命名?

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/pull/716#issue-437359352
https://github.com/agalwood/Motrix/blob/master/src/main/configs/protocol.js

**Comment by sinyat** [comment]
> [#716 (comment)](https://github.com/agalwood/Motrix/pull/716#issue-437359352)
> https://github.com/agalwood/Motrix/blob/master/src/main/configs/protocol.js

**Comment by BTMuli** [comment]
> [#716 (comment)](https://github.com/agalwood/Motrix/pull/716#issue-437359352) https://github.com/agalwood/Motrix/blob/master/src/main/configs/protocol.js

该部分的代码似乎没有涉及到 `type=torrent` 时 `torrent` 文件的参数接受，我试了 `torrent` `selectFile` 都不能很好的处理
![image](https://github.com/agalwood/Motrix/assets/72692909/88e7c481-880f-491f-aeca-6956f900c091)
