### ISSUE TITLE
设置代理服务器后无法启动 aria2

### ISSUE THREAD

**Issue by hr567** [agalwood/Motrix#950]
**错误描述**
设置代理服务器后无法启动 aria2

**如何重现**
启动Motrix，打开设置中使用代理服务器，填入代理服务器（socks5://127.0.0.1:1080），退出Motrix。
再次启动Motrix，Motrix界面正常显示，但引擎没有运行，此时之前的下载项目没有恢复，无法创建新的下载。
关闭代理服务器重启Motrix，Motrix运行正常。

**预期的行为**
重新启动Motrix后正常工作。

**运行环境**
 - 操作系统类型： Linux
 - 具体版本： Archlinux/20210517
 - Motrix 版本：aur/motrix-bin 1.6.10-1
 - 安装包类型：aur/motrix-bin 1.6.10-1

**Comment by agalwood** [comment]
代理不支持 socks5

**Comment by hr567** [comment]
谢谢，明白了。在运行中设置socks5代理下载功能正常工作了导致我误认为aria2支持socks代理。感谢您的回答。
