### ISSUE TITLE
Windows窗口上边框无法调整大小

### ISSUE THREAD

**Issue by shatyuka** [agalwood/Motrix#954]
**错误描述**
Windows窗口上边框无法调整大小

**截图**
![screenshot](https://user-images.githubusercontent.com/31368738/118656599-341cfa80-b7da-11eb-9973-1dabe36c1958.gif)

**运行环境**
 - 操作系统类型： Windows
 - 具体版本： Windows 10 20H2
 - Motrix 版本： v1.6.11

**更多信息**
看起来是`title-bar-dragger`的问题。是故意这样设计的吗，看相关代码是2年前的了。

**Comment by shatyuka** [comment]
`-webkit-app-region: drag;`会过滤掉鼠标事件

添加`margin: 5px 0 0 5px;`留5像素边界可以解决此问题。

**Comment by agalwood** [comment]
由于用了framsless，就自己实现了最小化、最大化、关闭按钮，所以加了 title-bar-dragger 用 -webkit-app-region: drag; 实现了窗口可以拖拽移动～。～

你发的这个问题不是故意设计的，看起来像没意识到的副作用

**Comment by shatyuka** [comment]
我也是上次更新才发现的，然后试了下v1.5发现也是这样。一直没人意识到挺离谱的

**Comment by agalwood** [comment]
可能没什么在窗体顶部那里调整窗体大小吧
