### ISSUE TITLE
希望添加种子或磁力任务时，在文件选择页显示种子的文件树结构

### ISSUE THREAD

**Issue by S-T-eve** [agalwood/Motrix#962]
![image](https://user-images.githubusercontent.com/53549980/119479921-b762c100-bd83-11eb-8f9d-ea7c3af79aab.png)
就是像迅雷或其他bt软件一样在要下载的文件选择时可以看到种子里已经分好的文件夹，然后按文件夹勾选来下载。开发者辛苦了

**Comment by agalwood** [comment]
支持不了，文件夹结构是 BitTorrent v2 的特性，aria2 目前不支持 https://github.com/aria2/aria2/issues/1685
Motrix 目前使用的种子解析库也不支持 v2，https://github.com/webtorrent/parse-torrent/issues/88

> https://blog.libtorrent.org/2020/09/bittorrent-v2/
