### ISSUE TITLE
关于aria2守护进程资源占用的问题

### ISSUE THREAD

**Issue by finalwhy** [agalwood/Motrix#963]
**Environment:**
 - OS & Version: Windows
 - Version: Windows 10 21H1
 - Motrix Version: v1.6.11
 - Installation package type: exe

**Describe the bug**
在Motrix后台运行时，即使没有下载任务，维持的aria2子进程依然会有稳定的10%CPU占用，根据v1.6.11的Release Note，这版是用child_process维护守护进程，然后我又去看了下代码 `Engine.js`（应该没错吧），是直接用`child_procese.spawn`起一个子进程跑aria2，
然后我就在node里也写了个类似的，直接用`spawn`跑 aria2 命令，配置文件用的是和本地 Motrix 一样的，代码如下：
```javascript
import { spawn } from 'child_process';

const aria2Instance = spawn(
  '[localpath]/aria2c.exe',
  ['--conf-path', '[localpath]\\aria2\\aria2.conf'],
  { shell: false, windowsHide: true }
);
```
结果是在没有进行下载任务时 aria2c 几乎没占用。
对此非常疑惑，希望和大家讨论一下，或者哪位大佬解惑一下
**Screenshots**
Motrix
![Taskmgr_1](https://user-images.githubusercontent.com/24859256/119603056-0d387700-be1f-11eb-945d-11b78b86ccd1.png)
自建的代码
![Taskmgr_2](https://user-images.githubusercontent.com/24859256/119603065-11fd2b00-be1f-11eb-8134-2dad0c3d9745.png)

**Comment by agalwood** [comment]
aria2 RPC + EngineClient Poll

**Comment by finalwhy** [comment]
@agalwood 抱歉打扰，这个issue我上午测得不仔细，导致资源占用不是因为Motrix，而是aria2浏览器插件我勾选了检测aria2状态，但一直是连接失败，我更新了浏览器和软件的rpc token后就好了。只可惜issue删不掉，我就直接关了

**Comment by agalwood** [comment]
欢迎做性能优化方面的测试研究🧐
