### ISSUE TITLE
应用启动失败: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by qingchuwudi** [agalwood/Motrix#981]
**错误描述**

win10 系统，安装Motrix新版本以后启动报错。安装路径更换为 `C:\Program Files`、 `D:\Program Files` 都不行。

**如何重现**

安装后直接启动就会报错。

**预期的行为**

**截图**
![image](https://user-images.githubusercontent.com/10055337/121325063-e06a8080-c943-11eb-8871-edde7ba98529.png)

**运行环境**
 - 操作系统类型： Windows 10
 - 具体版本： 2004
 - Motrix 版本： v1.6.11
 - 安装包类型：exe

**Comment by zeerdeer** [comment]
我也是这样

**Comment by qingchuwudi** [comment]
昨天下载绿色版本和1.5版本也报了同样的错，是最近系统更新以后出现的。

**Comment by yonassn** [comment]
我也是
