### ISSUE TITLE
应用启动失败: spawn ENAMETOOLONG 

### ISSUE THREAD

**Issue by LiMinghuaLiGan** [agalwood/Motrix#983]
**错误描述**
win10系统，安装Motrix新版本以后启动报错。安装路径D:\Program Files\Motrix。
**如何重现**
安装后每次直接启动就会出现。

**预期的行为**
截图
![image](https://user-images.githubusercontent.com/50763621/121474537-ca69c800-c9f6-11eb-863f-91029616a52a.png)

**运行环境**
操作系统类型： Windows 10
具体版本： 20H2
Motrix 版本： v1.6.11
安装包类型：exe
![image](https://user-images.githubusercontent.com/50763621/121474717-0c930980-c9f7-11eb-9c9d-eff449eefddd.png)

**Comment by xuangeyouneihan** [comment]
我21H1的也一样，同样是1.6.11最新版，只要C:\Users\Administrator\AppData\Roaming\Motrix目录下有dht.dat或dht6.dat就会有这个问题，并且由于电脑上一直运行着Motrix，问题一般发生在重启后。出现问题之后把这两个文件删了也没用，非得用Geek Unistaller卸载一遍（同时会删除残留）再重装才行。一通过种子下载文件就会生成dht.dat，然后就会出错。麻烦大佬修复一下谢谢！否则没法正常用种子下载文件了😂

**Comment by yonassn** [comment]
我也遇到了

**Comment by xuangeyouneihan** [comment]
@LiMinghuaLiGan 能设置一个bug/crash标签吗，谢谢

**Comment by BoxuanZng** [comment]
**运行环境**
操作系统类型： Windows 10 Pro
具体版本： 20H1
Motrix 版本： v1.6.11
安装包类型：exe
_**无问题**_

**Comment by BoxuanZng** [comment]
> 我21H1的也一样，同样是1.6.11最新版，只要C:\Users\Administrator\AppData\Roaming\Motrix目录下有dht.dat或dht6.dat就会有这个问题，并且由于电脑上一直运行着Motrix，问题一般发生在重启后。出现问题之后把这两个文件删了也没用，非得用Geek Unistaller卸载一遍（同时会删除残留）再重装才行。一通过种子下载文件就会生成dht.dat，然后就会出错。麻烦大佬修复一下谢谢！否则没法正常用种子下载文件了😂

IObit Uninstaller表示不屑😶

**Comment by LiMinghuaLiGan** [comment]
> @LiMinghuaLiGan 能设置一个bug/crash标签吗，谢谢

我好像加不了？没有权限

**Comment by xuangeyouneihan** [comment]
@agalwood 在吗？能看一下吗？谢谢！

**Comment by xuangeyouneihan** [comment]
> **运行环境**
> 操作系统类型： Windows 10 Pro
> 具体版本： 20H1
> Motrix 版本： v1.6.11
> 安装包类型：exe
> _**无问题**_

下载过BT吗，好像没下载过BT就没事

**Comment by naamikiss** [comment]
1.卸载Motrix；
2.删除C:\Users\naamikiss\AppData\Roaming\目录下的Motrix文件夹；
3.重新安装；
问题解决了，起码我这样搞问题解决了。
版本号：Version 1.6.11
