### ISSUE TITLE
文件内容目录信息

### ISSUE THREAD

**Issue by Jancat** [agalwood/Motrix#985]
**Is your feature request related to a problem? Please describe.**
 磁力文件内容希望能够切换按原目录展示（目前是打平成一级展示，可以提供手动切换视图的 icon），否则所有文件打平到一级，无法以目录为组勾选是否下载，而且丢失了目录信息

**Additional context**
![image](https://user-images.githubusercontent.com/11827786/121813146-471dd000-cc9d-11eb-8f35-9b1c869fbf05.png)

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/issues/962#issuecomment-847802079
