### ISSUE TITLE
应用启动失败: spawn ENAMETOOLONG 的解决办法

### ISSUE THREAD

**Issue by zeerdeer** [agalwood/Motrix#987]
删除 C:\Users\用户名\AppData\Roaming\Motrix ， 看到有人说是下载过BT的，没测试，反正删了就好了。试试吧:)

**Comment by zeerdeer** [comment]
> 删除 C:\Users\用户名\AppData\Roaming\Motrix ， 看到有人说是下载过BT的，没测试，反正删了就好了。试试吧:)

不要添加tracker

**Comment by qingchuwudi** [comment]
@zeerdeer 

能解决，多谢了。可是这操作治标不治本，后面肯定还会下载BT。

**Comment by zeerdeer** [comment]
> @zeerdeer
> 
> 能解决，多谢了。可是这操作治标不治本，后面肯定还会下载BT。

不要添加tracker就行了 默认就行

**Comment by rogerlee6411** [comment]
it works after remove C:\Users\用户名\AppData\Roaming\Motrix, 
thanks a lot.,

**Comment by KuChenX** [comment]
是由于你添加太多tracker导致的，你可以找到C:\Users\用户名\AppData\Roaming\Motrix目录下的**system.json**修改里面的**bt-tracker**，启动后在进阶设置里修改**tracker服务器**。
