### ISSUE TITLE
有個TORRENT/MAGNET會報#16錯誤

### ISSUE THREAD

**Issue by anipeg** [agalwood/Motrix#993]
**错误描述**
下載 magnet:?xt=urn:btih:J7I6GD7MZMPWXSGZKRW7GCOQI2JFPUFB
會發生#16 檔案無法開啟的錯誤
嘗試使用MAGNET Link或TORRENT檔案結果相同

**如何重现**
使用Motrix開啟magnet:?xt=urn:btih:J7I6GD7MZMPWXSGZKRW7GCOQI2JFPUFB

**运行环境**
Win10 - Motrix Version 1.6.11

**Comment by agalwood** [comment]
https://github.com/agalwood/Motrix/wiki/Error#16
If aria2 could not create new file or truncate existing file.

![image](https://user-images.githubusercontent.com/1032175/124388798-030b7180-dd17-11eb-9d1e-d0c53d0844f8.png)

**Comment by Akariln** [comment]
我用 aria2c 试了下，看起来是上游的问题。
I tried it with aria2c, and it seems to be an upstream problem.
